import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mkdirSync, chmodSync } from 'node:fs'
import { resolve } from 'node:path'
import { execFileSync } from 'node:child_process'
import { login, navigate, chooseOption } from './helpers'

async function capture(page: Page, name: string, fullPage = false) {
  if (!process.env.SOCIETY_CAPTURE_UI) return
  await page.evaluate(() => document.fonts.ready)
  if (fullPage) await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  const folder = resolve('../reports/local/account-administration-review'); mkdirSync(folder, { recursive: true, mode: 0o700 })
  const path = resolve(folder, name + '.png'); await page.screenshot({ path, fullPage, animations: 'disabled' }); chmodSync(path, 0o600)
}
async function manage(page: Page, name = 'Demo Owner A-101') {
  await navigate(page, 'Access & invitations'); await page.getByRole('button', { name: 'Manage access for ' + name, exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name, exact: true })).toBeVisible()
  await expect(page.getByRole('dialog').getByText('Opening this account…', { exact: true })).toHaveCount(0)
}
async function finish(page: Page, button: string) {
  await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('Verified fictional decision and appointment authority against the approved register.')
  await page.getByRole('dialog').getByRole('checkbox').check(); await page.getByRole('button', { name: button, exact: true }).click()
  await expect(page.getByRole('dialog').locator('.form-success')).toBeVisible(); await expect(page.getByRole('dialog').getByText('Updating this account…', { exact: true })).toHaveCount(0)
}
async function close(page: Page) { await page.getByRole('button', { name: 'Close account access', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0) }
async function post(page: Page, path: string, data: Record<string, unknown>, status = 200) {
  const me = await (await page.request.get('/api/auth/me')).json(); const response = await page.request.post(path, { headers: { Origin: new URL(page.url()).origin, 'X-CSRF-Token': me.csrf_token }, data }); expect(response.status(), await response.text()).toBe(status); return response.json()
}
function fixtureSQL(script: string) {
  const path = process.env.SOCIETY_BROWSER_DB; if (!path || !path.includes('society-browser-')) throw new Error('An isolated synthetic browser database is required.')
  execFileSync('python3', ['-c', 'import sqlite3,sys,time,json\ndb=sqlite3.connect(sys.argv[1]);db.execute("PRAGMA foreign_keys=ON")\n' + script + '\ndb.commit()', path])
}

test('current role expiry clears protected entry details and reloads only the resident financial scope', async ({ page, browser }) => {
  await login(page); await manage(page); await page.getByRole('button', { name: 'Add appointment', exact: true }).click(); await chooseOption(page, 'Appointment', 'Treasurer'); await finish(page, 'Save appointment'); await close(page)
  const date = new Intl.DateTimeFormat('en-CA', { year: 'numeric', month: '2-digit', day: '2-digit', timeZone: 'Asia/Kolkata' }).format(new Date())
  const description = 'QA Scope private entry outside the resident homes'
  const draft = await post(page, '/api/entries', { operation_key: crypto.randomUUID(), flat_id: 'demo-flat-A-103', kind: 'CHARGE', amount: '46.75', date, description, payer: '', method: '', reference: '' })
  await post(page, '/api/entries/' + draft.id + '/post', { operation_key: crypto.randomUUID(), confirmed: true, reason: '' })
  const context = await browser.newContext({ baseURL: new URL(page.url()).origin }); const resident = await context.newPage()
  try {
    await login(resident, 'Owner'); await navigate(resident, 'Entries'); await expect(resident.locator('.records-balance strong')).toHaveText('₹46.75'); await resident.getByRole('button', { name: 'Open ' + description + ', A-103', exact: true }).click(); await expect(resident.getByRole('dialog').locator('.record-facts')).toContainText(description)
    const before = await (await resident.request.get('/api/auth/me')).json(); expect(before.can_manage_records).toBe(true)
    // An unchanged current-session check keeps the open record intact.
    const unchanged = resident.waitForResponse(response => response.url().endsWith('/api/auth/me')); await resident.evaluate(() => window.dispatchEvent(new Event('session-recheck'))); expect((await unchanged).status()).toBe(200); await expect(resident.getByRole('dialog').locator('.record-facts')).toContainText(description); await capture(resident, 'current-scope-protected-detail')
    fixtureSQL("now=int(time.time());result=db.execute(\"UPDATE role_grants SET valid_from=?,valid_until=? WHERE user_id='demo-user-owner' AND role='TREASURER' AND revoked_at IS NULL\",(now-172800,now-1));assert result.rowcount==1")
    const rechecked = resident.waitForResponse(response => response.url().endsWith('/api/auth/me')); await resident.evaluate(() => window.dispatchEvent(new Event('session-recheck'))); const current = await (await rechecked).json(); expect(current.id).toBe(before.id); expect(current.scope_key).not.toBe(before.scope_key); expect(current.can_manage_records).toBe(false); expect(current.can_read_all_records).toBe(false); expect(current.can_read_records).toBe(true)
    await expect(resident.getByRole('dialog')).toHaveCount(0); await expect(resident.getByText(description, { exact: true })).toHaveCount(0); await expect(resident.locator('.records-balance strong')).toHaveText('₹0.00'); await expect(resident.getByRole('button', { name: 'Add an entry', exact: true })).toHaveCount(0); expect((await resident.request.get('/api/entries/' + draft.id)).status()).toBe(404); await capture(resident, 'current-scope-personal-entry-book', true)
    await resident.getByRole('combobox', { name: 'Filter records by home', exact: true }).click(); await expect(resident.getByRole('option')).toHaveCount(3); await expect(resident.getByRole('option', { name: 'Home A-103', exact: true })).toHaveCount(0); await capture(resident, 'current-scope-personal-home-menu'); await resident.keyboard.press('Escape')
  } finally { await context.close() }
})

test('account labels, self protection, activity and dialog focus match actual appointments', async ({ page }) => {
  await login(page); await navigate(page, 'Access & invitations')
  await expect(page.locator('.account-row').filter({ hasText: 'admin@demo.society' }).locator('.account-meta')).toContainText('Administrator · Treasurer')
  await capture(page, 'account-book-desktop', true); await manage(page, 'Demo Registry Officer')
  await expect(page.getByText('This is your account. Ask another administrator to change your access.', { exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: 'Add appointment', exact: true })).toHaveCount(0); await expect(page.getByRole('button', { name: 'Suspend account', exact: true })).toHaveCount(0)
  await expect(page.locator('.appointment-card')).toHaveCount(2); await capture(page, 'self-appointments')
  await page.getByRole('button', { name: /^Activity/ }).click(); await capture(page, 'self-activity'); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Manage access for Demo Registry Officer', exact: true })).toBeFocused()
})

test('actual bounded treasury appointment requires acknowledgement, factors and a separate explicit ending', async ({ page, browser }) => {
  await login(page); await manage(page, 'Demo Tenant A-103'); await expect(page.getByRole('heading', { name: 'No appointments yet.', exact: true })).toBeVisible(); await capture(page, 'no-appointments')
  await page.getByRole('button', { name: 'Add appointment', exact: true }).click(); await page.getByRole('combobox', { name: 'Appointment', exact: true }).click(); await expect(page.getByRole('option')).toHaveCount(4); await capture(page, 'appointment-menu-desktop'); await page.getByRole('option', { name: 'Treasurer', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Term (days)', exact: true }).fill('2'); await expect(page.getByRole('button', { name: 'Save appointment', exact: true })).toBeDisabled(); await capture(page, 'treasury-acknowledgement')
  await finish(page, 'Save appointment'); await expect(page.locator('.appointment-card').getByRole('heading', { name: 'Treasurer', exact: true })).toBeVisible(); await expect(page.locator('.form-success')).toBeFocused()
  const details = await (await page.request.get('/api/admin/accounts/demo-user-tenant')).json(); expect(details.grants[0].valid_until - details.grants[0].valid_from).toBe(172800); expect(details.version).toBe(2)
  await page.getByRole('button', { name: /^Activity/ }).click(); await expect(page.getByText('Appointment added', { exact: true })).toBeVisible(); await capture(page, 'appointment-activity'); await close(page); await expect(page.getByRole('button', { name: 'Manage access for Demo Tenant A-103', exact: true })).toBeFocused()
  const context = await browser.newContext({ baseURL: new URL(page.url()).origin }); const recipient = await context.newPage(); await login(recipient, 'Tenant'); await navigate(recipient, 'Entries'); await expect(recipient.getByRole('button', { name: 'Add an entry', exact: true })).toBeVisible(); expect((await recipient.request.get('/api/admin/accounts')).status()).toBe(403)
  await manage(page, 'Demo Tenant A-103'); await page.getByRole('button', { name: 'End Treasurer appointment', exact: true }).click(); await expect(page.getByRole('button', { name: 'End appointment', exact: true })).toBeDisabled(); await capture(page, 'end-appointment-confirmation'); await finish(page, 'End appointment'); await expect(page.locator('.appointment-revoked')).toHaveCount(1); expect((await recipient.request.get('/api/auth/me')).status()).toBe(401); await close(page); await context.close()
})

test('suspend and verified resume retain records and never revive an old session or appointment', async ({ page, browser }) => {
  await login(page); const base = new URL(page.url()).origin; const context = await browser.newContext({ baseURL: base }); const recipient = await context.newPage(); await login(recipient, 'Owner')
  await manage(page); await page.getByRole('button', { name: 'Suspend account', exact: true }).click(); await capture(page, 'suspension-confirmation'); await finish(page, 'Confirm suspension'); await expect(page.getByRole('dialog').locator('.account-state')).toHaveText('Suspended'); expect((await recipient.request.get('/api/auth/me')).status()).toBe(401); await capture(page, 'suspended-account')
  const recovery = await post(page, '/api/admin/accounts/demo-user-owner/link', { purpose: 'PASSWORD_RESET', identity_verified: true, note: 'Verified fictional identity for a recovery attempt' }, 400); expect(recovery.message).toContain('Resume this account')
  await page.getByRole('button', { name: 'Resume account', exact: true }).click(); await capture(page, 'resumption-confirmation'); await finish(page, 'Confirm resumption'); await expect(page.getByRole('dialog').locator('.account-state')).toHaveText('Active'); expect((await recipient.request.get('/api/auth/me')).status()).toBe(401); await capture(page, 'resumed-account')
  await close(page); await login(recipient, 'Owner'); await navigate(recipient, 'Your homes'); await expect(recipient.locator('.home-card')).toHaveCount(2); await context.close()
})

test('an actual auditor appointment opens financial reads without posting or administration', async ({ page, browser }) => {
  await login(page); await manage(page); await page.getByRole('button', { name: 'Add appointment', exact: true }).click(); await chooseOption(page, 'Appointment', 'Accountant / auditor'); await capture(page, 'auditor-powers'); await finish(page, 'Save appointment'); await close(page)
  const context = await browser.newContext({ baseURL: new URL(page.url()).origin }); const recipient = await context.newPage(); await login(recipient, 'Owner'); await navigate(recipient, 'Entries'); await expect(recipient.getByRole('button', { name: 'Add an entry', exact: true })).toHaveCount(0); await expect(recipient.getByRole('link', { name: 'Access & invitations', exact: true })).toHaveCount(0); await navigate(recipient, 'Your homes'); await expect(recipient.locator('.home-card')).toHaveCount(2)
  expect((await recipient.request.get('/api/admin/accounts/demo-user-admin')).status()).toBe(403); const me = await (await recipient.request.get('/api/auth/me')).json(); expect(me.can_read_all_records).toBe(true); expect(me.can_manage_records).toBe(false); expect(me.can_review_requests).toBe(false)
  await capture(recipient, 'auditor-personal-homes', true); await manage(page); await page.getByRole('button', { name: 'End Accountant / auditor appointment', exact: true }).click(); await finish(page, 'End appointment'); await close(page); await context.close()
})

test('source errors, delayed reads and failed busy saves remain recoverable without duplicate changes', async ({ page }) => {
  await login(page); const path = '**/api/admin/accounts/demo-user-owner/roles'; const readPath = /\/api\/admin\/accounts\/demo-user-owner(?:\?.*)?$/; await page.route(readPath, route => route.fulfill({ status: 503, contentType: 'application/json', body: '{}' })); await manage(page); await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible(); await capture(page, 'account-source-error'); await page.unroute(readPath); await page.getByRole('button', { name: 'Retry account', exact: true }).click(); await expect(page.getByRole('button', { name: 'Add appointment', exact: true })).toBeVisible(); await close(page)
  let releaseRead: () => void = () => {}; const waitRead = new Promise<void>(resolve => { releaseRead = resolve }); await page.route(readPath, async route => { await waitRead; await route.continue().catch(() => {}) }); await navigate(page, 'Access & invitations'); await page.getByRole('button', { name: 'Manage access for Demo Owner A-101', exact: true }).click(); await expect(page.getByText('Opening this account…', { exact: true })).toBeVisible(); await capture(page, 'account-source-pending'); await close(page); releaseRead(); await page.unroute(path)
  await manage(page); await page.getByRole('button', { name: 'Add appointment', exact: true }).click(); await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('Verified fictional appointment and authority for this retry.'); await page.getByRole('dialog').getByRole('checkbox').check()
  let release: () => void = () => {}; const waiting = new Promise<void>(resolve => { release = resolve }); let attempts = 0; await page.route(path, async route => { attempts++; await waiting; await route.fulfill({ status: 503, contentType: 'application/json', body: '{}' }) }); await page.getByRole('button', { name: 'Save appointment', exact: true }).click(); await expect(page.getByRole('button', { name: 'Saving…', exact: true })).toBeDisabled(); await expect(page.getByRole('textbox', { name: 'Reason', exact: true })).toBeDisabled(); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toBeVisible(); await capture(page, 'appointment-save-pending'); release(); await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible(); await expect(page.getByRole('dialog').getByRole('alert')).toBeFocused(); await capture(page, 'appointment-save-error'); expect(attempts).toBe(1)
  await page.unroute(path); await page.getByRole('button', { name: 'Save appointment', exact: true }).click(); await expect(page.locator('.form-success')).toBeVisible(); await page.getByRole('button', { name: 'End Committee appointment', exact: true }).click(); await finish(page, 'End appointment'); await close(page)
})

test('a competing administrator edit rejects stale confirmation and reloads current appointments', async ({ page, browser }) => {
  await login(page); await manage(page); await page.getByRole('button', { name: 'Add appointment', exact: true }).click()
  const context = await browser.newContext({ baseURL: new URL(page.url()).origin }); const second = await context.newPage(); await login(second); const current = await (await second.request.get('/api/admin/accounts/demo-user-owner')).json(); await post(second, '/api/admin/accounts/demo-user-owner/roles', { version: current.version, confirmed: true, reason: 'Verified a different fictional administrator decision first.', role: 'AUDITOR', term_days: 30 }, 201)
  await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('Verified fictional committee decision after the competing edit.'); await page.getByRole('dialog').getByRole('checkbox').check(); await page.getByRole('button', { name: 'Save appointment', exact: true }).click(); await expect(page.getByRole('button', { name: 'Reload account', exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: 'Save appointment', exact: true })).toBeDisabled(); await capture(page, 'stale-account-conflict')
  await page.getByRole('button', { name: 'Reload account', exact: true }).click(); await expect(page.getByRole('button', { name: 'End Accountant / auditor appointment', exact: true })).toBeVisible(); await capture(page, 'conflict-reloaded'); await page.getByRole('button', { name: 'End Accountant / auditor appointment', exact: true }).click(); await finish(page, 'End appointment'); await close(page); await context.close()
})

test('account cards, appointment menus, cancellation and actions fit all reviewed viewports', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' }); await login(page)
  for (const viewport of [{ width: 1440, height: 900 }, { width: 768, height: 1024 }, { width: 375, height: 812 }, { width: 320, height: 568 }, { width: 1440, height: 480 }]) {
    await page.setViewportSize(viewport); await navigate(page, 'Access & invitations'); await expect(page.locator('.account-list')).toHaveAttribute('aria-busy', 'false'); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await capture(page, 'account-book-' + viewport.width + '-' + viewport.height, true); await manage(page); await capture(page, 'appointments-' + viewport.width + '-' + viewport.height)
    await page.getByRole('button', { name: 'Add appointment', exact: true }).click(); await page.getByRole('combobox', { name: 'Appointment', exact: true }).focus(); await page.keyboard.press('Space'); await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 }); await expect(page.getByRole('option', { name: 'Committee', exact: true })).toBeFocused(); await capture(page, 'appointment-menu-' + viewport.width + '-' + viewport.height); await page.keyboard.press('ArrowDown'); await expect(page.getByRole('option', { name: 'Treasurer', exact: true })).toBeFocused(); await page.keyboard.press('Enter'); await expect(page.getByRole('combobox', { name: 'Appointment', exact: true })).toContainText('Treasurer'); await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('Verified fictional keyboard and layout verification.'); await page.getByRole('dialog').getByRole('checkbox').check(); await page.getByRole('button', { name: 'Save appointment', exact: true }).scrollIntoViewIfNeeded(); await expect(page.getByRole('button', { name: 'Save appointment', exact: true })).toBeInViewport({ ratio: 1 }); await capture(page, 'appointment-form-' + viewport.width + '-' + viewport.height)
    await page.getByRole('button', { name: 'Cancel', exact: true }).click(); await expect(page.getByRole('button', { name: 'Add appointment', exact: true })).toBeFocused(); await close(page); await expect(page.getByRole('button', { name: 'Manage access for Demo Owner A-101', exact: true })).toBeFocused(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
})

test('a suspended pending invitation needs a new verified handover after resumption', async ({ page, browser }) => {
  await login(page); await navigate(page, 'Access & invitations'); await page.getByRole('button', { name: 'Invite a person', exact: true }).click(); await page.getByLabel('Find a person').fill('Demo Owner C-101'); await chooseOption(page, 'Person in the registry', 'Demo Owner C-101'); await page.getByLabel('Email address', { exact: true }).fill('resumed@accounts.test'); await page.getByRole('checkbox').check(); await page.getByLabel('Verification note', { exact: true }).fill('Verified fictional current home relationship and personal email.'); await page.getByRole('button', { name: 'Create personal link', exact: true }).click(); const oldLink = await page.getByLabel('Personal link', { exact: true }).inputValue(); await page.getByRole('button', { name: 'I’ve finished the handover', exact: true }).click()
  await manage(page, 'Demo Owner C-101'); await expect(page.getByRole('dialog').locator('.account-state')).toHaveText('Invitation pending'); await page.getByRole('button', { name: 'Suspend account', exact: true }).click(); await finish(page, 'Confirm suspension'); await capture(page, 'suspended-invitation'); await page.getByRole('button', { name: 'Resume account', exact: true }).click(); await finish(page, 'Confirm resumption'); await expect(page.getByRole('dialog').locator('.account-state')).toHaveText('Invitation pending'); await close(page)
  const context = await browser.newContext({ baseURL: new URL(page.url()).origin }); const recipient = await context.newPage(); await recipient.goto(oldLink); await expect(recipient.getByRole('heading', { name: 'This link is unavailable.', exact: true })).toBeVisible(); await expect(recipient.getByRole('alert')).toContainText('This link has expired'); await capture(recipient, 'ended-invitation-link')
  const row = page.locator('.account-row').filter({ hasText: 'resumed@accounts.test' }); await row.getByRole('button', { name: 'New invitation link', exact: true }).click(); await page.getByRole('checkbox').check(); await page.getByLabel('Verification note', { exact: true }).fill('Verified resumed fictional identity and current relationship.'); await page.getByRole('button', { name: 'Create personal link', exact: true }).click(); const newLink = await page.getByLabel('Personal link', { exact: true }).inputValue(); expect(newLink).not.toBe(oldLink); await page.getByRole('button', { name: 'I’ve finished the handover', exact: true }).click(); await recipient.goto(newLink); await expect(recipient.getByRole('button', { name: 'Save my password', exact: true })).toBeVisible(); await capture(recipient, 'resumed-new-handover'); await context.close()
})

test('account and appointment activity pages expose bounded full counts and usable search states', async ({ page }) => {
  fixtureSQL(`now=int(time.time())\npassword=db.execute("SELECT password_hash FROM users WHERE id='demo-user-owner'").fetchone()[0]\nfor i in range(14):\n db.execute("INSERT INTO users(id,login,display_name,password_hash,status,created_at,verified_at) VALUES(?,?,?,?,?,?,?)",(f'qa-directory-{i:02d}',f'qa-{i:02d}@accounts.test',f'QA Directory {i:02d}',password,'ACTIVE',now+i,now))\nfor i in range(23):\n db.execute("INSERT INTO role_grants(id,user_id,role,valid_from,valid_until,granted_by) VALUES(?,'qa-directory-00','AUDITOR',?,?,'demo-user-admin')",(f'qa-expired-{i:02d}',now-5000-i,now-1))\n db.execute("INSERT INTO audit_events(actor_user_id,action,occurred_at,reason,before_json,after_json) VALUES('demo-user-admin','APPOINTMENT_GRANTED',?,'Historical fictional authorised appointment',?, '{}')",(now-i,json.dumps({'user_id':'qa-directory-00'})))`)
  await login(page); await navigate(page, 'Access & invitations'); await expect(page.getByRole('button', { name: 'Next account page', exact: true })).toBeEnabled(); await page.getByRole('button', { name: 'Next account page', exact: true }).click(); await expect(page.locator('.account-list')).toHaveAttribute('aria-busy', 'false'); await expect(page.locator('.account-row')).toHaveCount(7); await expect(page.locator('.pagination').first()).toContainText('Page 2 of 2'); await capture(page, 'account-page-two', true); await page.getByRole('button', { name: 'Previous account page', exact: true }).click(); await page.getByRole('searchbox', { name: 'Search accounts', exact: true }).fill('QA Directory 00'); await manage(page, 'QA Directory 00'); await expect(page.locator('.appointment-card')).toHaveCount(20); await expect(page.getByRole('dialog').locator('.pagination')).toContainText('23 appointments · Page 1 of 2'); await page.getByRole('button', { name: 'Next appointment page', exact: true }).click(); await expect(page.locator('.appointment-card')).toHaveCount(3); await capture(page, 'appointment-page-two'); await page.getByRole('button', { name: 'Previous appointment page', exact: true }).click(); await expect(page.locator('.appointment-card')).toHaveCount(20)
  await page.getByRole('button', { name: /^Activity/ }).click(); await expect(page.locator('.access-history li')).toHaveCount(20); await page.getByRole('button', { name: 'Next activity page', exact: true }).click(); await expect(page.locator('.access-history li')).toHaveCount(3); await capture(page, 'activity-page-two'); await page.getByRole('button', { name: 'Previous activity page', exact: true }).click(); await expect(page.locator('.access-history li')).toHaveCount(20); await close(page); await page.getByRole('searchbox', { name: 'Search accounts', exact: true }).fill('No such fictional identity'); await expect(page.getByRole('heading', { name: 'No accounts found.', exact: true })).toBeVisible(); await capture(page, 'account-search-empty', true); await page.getByRole('searchbox', { name: 'Search accounts', exact: true }).clear(); await expect(page.locator('.account-row')).toHaveCount(12)
})

test('expired fresh confirmation leads through real account security before another verified decision', async ({ page }) => {
  await login(page); await manage(page); await page.getByRole('button', { name: 'Add appointment', exact: true }).click(); fixtureSQL(`db.execute("UPDATE sessions SET reauthenticated_at=? WHERE user_id='demo-user-admin'",(int(time.time())-360,))`)
  await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('Verified fictional role change that still requires fresh identity.'); await page.getByRole('dialog').getByRole('checkbox').check(); await page.getByRole('button', { name: 'Save appointment', exact: true }).click(); await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Confirm your password'); await capture(page, 'fresh-identity-required')
  await page.getByRole('link', { name: 'Open Account security', exact: true }).click(); const confirmation = page.locator('.security-card').filter({ has: page.getByRole('heading', { name: 'Confirm it’s you.', exact: true }) }); await confirmation.getByLabel('Current password', { exact: true }).fill('Community-preview-2026!'); await confirmation.getByRole('button', { name: 'Use a preview code', exact: true }).click(); await confirmation.getByRole('button', { name: 'Confirm my identity', exact: true }).click(); await expect(confirmation.getByRole('status')).toBeVisible()
  await manage(page); await page.getByRole('button', { name: 'Add appointment', exact: true }).click(); await finish(page, 'Save appointment'); await page.getByRole('button', { name: 'End Committee appointment', exact: true }).click(); await finish(page, 'End appointment'); await close(page)
})
