import { expect } from '@playwright/test'
import type { Browser, Page } from '@playwright/test'
import { chmodSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { login, navigate, chooseOption } from './helpers'
import { ensureMaintenanceReviewer, financialHeaders } from './maintenance-fixtures'
import type { BudgetDetail, BudgetComparison, PaidExpenseDetail } from '../src/budgets'

export const planCheck='I reviewed these exact planning figures, dates, source and proposal.'
export const paidCheck='I reviewed this exact already-paid record, source and proposed effect.'
export const decisionCheck='I reviewed this exact proposal, source and decision’s effect.'
export const budgetPeriod=(month:number,year=2025)=>({start:year+'-'+String(month).padStart(2,'0')+'-01',end:new Date(Date.UTC(year,month,0)).toISOString().slice(0,10),paid:year+'-'+String(month).padStart(2,'0')+'-10'})
export async function budgetActors(page:Page,browser:Browser){await page.setViewportSize({width:1440,height:1000});await login(page);await ensureMaintenanceReviewer(page);const context=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await context.newPage();await login(reviewer,'Committee');return{reviewer,close:()=>context.close()}}
export async function budgetGet<T>(page:Page,path:string):Promise<T>{const response=await page.request.get(path);expect(response.status(),await response.text()).toBe(200);return await response.json() as T}
export async function budgetPost(page:Page,path:string,data:Record<string,unknown>){const response=await page.request.post(path,{headers:await financialHeaders(page),data:{...data,operation_key:crypto.randomUUID(),confirmed:true}});expect(response.status(),await response.text()).toBe(200);return await response.json() as {id:string}}
export async function apiBudget(page:Page,reviewer:Page,month:number,title:string,year=2025){const period=budgetPeriod(month,year),created=await budgetPost(page,'/api/budgets',{version:0,action:'PLAN',title,period_start:period.start,period_end:period.end,source_reference:'PRIVATE_BDG_SOURCE '+title,planned_collections:'2000.00',planned_expenses:'1250.25',reason:'PRIVATE_BDG supplied exact planning figures and original dates reviewed.'});await budgetPost(reviewer,'/api/budgets/'+created.id+'/decisions',{version:1,action:'APPROVED',reason:'PRIVATE_BDG separately reviewed the exact original plan.'});return created.id}
export async function apiPaid(page:Page,reviewer:Page,budget:string,month:number,payee:string,amount='32.51',confirmed=true,year=2025){const created=await budgetPost(page,'/api/paid-expenses',{version:0,action:'PAID',budget_id:budget,amount,paid_date:budgetPeriod(month,year).paid,payee,category:'Repairs',method:'CASH',reference:'BDG-VOUCHER-'+crypto.randomUUID(),source_note:'PRIVATE_BDG explicitly supplied external cash voucher.',reason:'PRIVATE_BDG deliberately record this supplied already-paid expense.'});if(confirmed)await budgetPost(reviewer,'/api/paid-expenses/'+created.id+'/decisions',{version:1,action:'APPROVED',reason:'PRIVATE_BDG independent review of the supplied paid record.'});return created.id}
export async function budgetEntry(page:Page,amount:string,date:string,kind='RECEIVED'){
 const received=kind==='RECEIVED',created=await page.request.post('/api/entries',{headers:await financialHeaders(page),data:{operation_key:crypto.randomUUID(),flat_id:'demo-flat-A-101',kind,amount,date,description:'PRIVATE_BDG supplied original '+kind,payer:received?'Fictional budget owner':'',method:received?'CASH':'',reference:'',source_note:'PRIVATE_BDG independently supplied source.'}});expect(created.status(),await created.text()).toBe(200);const id=(await created.json()).id as string;await budgetPost(page,'/api/entries/'+id+'/post',{reason:''});return id
}
export async function budgetDesk(page:Page){await navigate(page,'Statements');await page.getByRole('button',{name:'Budget & expenses',exact:true}).click();await expect(page.getByRole('heading',{name:'The operating plans.',exact:true})).toBeVisible()}
export async function openBudget(page:Page,id:string){await page.goto('/#statements?panel=budgets&budget='+encodeURIComponent(id));await page.reload();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('region',{name:'Current budget comparison',exact:true})).toBeVisible()}
export async function openPaid(page:Page,budget:string,id:string){await page.goto('/#statements?panel=budgets&budget='+encodeURIComponent(budget)+'&expense='+encodeURIComponent(id));await page.reload();await expect(page.getByRole('dialog').getByRole('heading',{name:'Every decision stays on record.',exact:true})).toBeVisible()}
export async function fillPlan(page:Page,month:number,title:string){const period=budgetPeriod(month);await page.getByRole('textbox',{name:'Plan title',exact:true}).fill(title);await page.getByLabel('Budget period starts',{exact:true}).fill(period.start);await page.getByLabel('Budget period ends',{exact:true}).fill(period.end);await page.getByRole('textbox',{name:'Planned collections',exact:true}).fill('2000.00');await page.getByRole('textbox',{name:'Planned expenses',exact:true}).fill('1250.25');await page.getByRole('textbox',{name:'Budget source reference',exact:true}).fill('PRIVATE_BDG committee supplied original plan reference');await page.getByRole('textbox',{name:'Proposal reason',exact:true}).fill('PRIVATE_BDG exact supplied plan, dates and independent review checked.')}
export async function fillPaid(page:Page,month:number,payee:string,amount:string,reference:string){await page.getByRole('textbox',{name:'Already-paid amount',exact:true}).fill(amount);await page.getByLabel('Expense paid date',{exact:true}).fill(budgetPeriod(month).paid);await page.getByRole('textbox',{name:'Expense payee',exact:true}).fill(payee);await page.getByRole('textbox',{name:'Expense payment reference',exact:true}).fill(reference);await page.getByRole('textbox',{name:'Expense source note',exact:true}).fill('PRIVATE_BDG supplied original external payment or cash-voucher source.');await page.getByRole('textbox',{name:'Proposal reason',exact:true}).fill('PRIVATE_BDG exact already-paid record and its proposed effect reviewed.')}
export async function submitBudgetPreview(page:Page,expense=false){await page.getByRole('checkbox',{name:expense?paidCheck:planCheck,exact:true}).check();const saved=page.waitForResponse(response=>new URL(response.url()).pathname===(expense?'/api/paid-expenses':'/api/budgets')&&response.request().method()==='POST');await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();return (await(await saved).json()).id as string}
export async function decideBudgetUI(page:Page,id:string,expense=false,parent='',action='APPROVED'){
 if(expense)await openPaid(page,parent,id);else await openBudget(page,id)
 await page.getByRole('button',{name:expense?'Review paid expense':'Review budget proposal',exact:true}).click();const current=await budgetGet<BudgetDetail|PaidExpenseDetail>(page,(expense?'/api/paid-expenses/':'/api/budgets/')+id),label=action==='DECLINED'?'Decline proposal':expense?'Confirm paid expense':current.snapshot.action==='CLOSE'?'Approve period closure':'Approve supplied plan'
 await expect(page.getByRole('combobox',{name:'Budget decision',exact:true})).toBeVisible();if(action==='DECLINED')await chooseOption(page,'Budget decision',label)
 await page.getByRole('textbox',{name:'Decision reason',exact:true}).fill('PRIVATE_BDG independently checked the exact supplied original and deliberate decision.');await page.getByRole('checkbox',{name:decisionCheck,exact:true}).check();const accepted=page.waitForResponse(response=>new URL(response.url()).pathname===(expense?'/api/paid-expenses/':'/api/budgets/')+id+'/decisions'&&response.request().method()==='POST');await page.getByRole('button',{name:label,exact:true}).click();expect((await accepted).status()).toBe(200);await expect(page.getByRole('button',{name:expense?'Close expense decision':'Close budget decision',exact:true})).toHaveCount(0)
}
export async function comparison(page:Page,id:string){return budgetGet<BudgetComparison>(page,'/api/budgets/'+id+'/comparison')}
export async function budgetCapture(page:Page,name:string){if(process.env.SOCIETY_CAPTURE_UI!=='1')return;await page.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().filter(animation=>Number.isFinite(Number(animation.effect?.getComputedTiming().endTime))).map(animation=>animation.finished.catch(()=>{})))});const root=resolve(process.env.SOCIETY_BUDGET_CAPTURE_ROOT??'../reports/local/budgets-ui');mkdirSync(root,{recursive:true,mode:0o700});const path=resolve(root,name+'.png');await page.screenshot({path,animations:'disabled'});chmodSync(path,0o600)}
export async function budgetWithin(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);for(const role of ['dialog','listbox'] as const){const target=page.getByRole(role);if(await target.count()){const box=await target.boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.y).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(page.viewportSize()!.width+1);expect(box!.y+box!.height).toBeLessThanOrEqual(page.viewportSize()!.height+1)}}for(const selector of await page.getByRole('combobox').all()){if(await selector.isVisible()){const box=await selector.boundingBox();expect(box!.height).toBeGreaterThanOrEqual(44)}}if(await page.getByRole('dialog').count()){await expect(page.getByRole('dialog').locator('.dialog-close')).toBeInViewport({ratio:1});const padding=await page.getByRole('dialog').locator('.dialog-scroll').evaluate(element=>Number.parseFloat(getComputedStyle(element).paddingLeft));expect(padding).toBeGreaterThanOrEqual(20)}}
