import { test, expect } from '@playwright/test'
import { login } from './helpers'
import type { Page } from '@playwright/test'
import type { BudgetDetail, PaidExpenseDetail, PaidExpensePage } from '../src/budgets'
import { messagePrivateFixture } from './messages-fixtures'
import { budgetActors, budgetDesk, budgetCapture, budgetWithin, fillPlan, fillPaid, submitBudgetPreview, decideBudgetUI, openBudget, openPaid, budgetGet, budgetPost, apiBudget, apiPaid, budgetEntry, comparison, planCheck, paidCheck } from './budgets-fixtures'

test.setTimeout(90000)
test('private budget desk empty loading error retry opened menus keyboard and denied scope render on five layouts',async({page,browser})=>{
 const actors=await budgetActors(page,browser)
 try{
  await budgetDesk(page);await expect(page.getByRole('heading',{name:'A considered plan starts here.',exact:true})).toBeVisible();await expect(page.locator('.budget-attention strong')).toHaveText(['0','0','0'])
  for(const [width,height] of [[1440,1000],[768,1000],[375,640],[320,640],[320,440]]){
   await page.setViewportSize({width,height});await page.getByRole('heading',{name:'The operating plans.',exact:true}).scrollIntoViewIfNeeded();await budgetCapture(page,'empty-desk-'+width+'-'+height);await budgetWithin(page)
   const countTops=await page.locator('.budget-attention strong').evaluateAll(elements=>elements.map(element=>element.getBoundingClientRect().top));expect(Math.max(...countTops)-Math.min(...countTops)).toBeLessThan(1)
   await page.getByRole('combobox',{name:'Filter budgets',exact:true}).click();await page.getByRole('option',{name:'Closed periods',exact:true}).hover();await budgetCapture(page,'period-menu-'+width+'-'+height);await budgetWithin(page);await page.keyboard.press('End');await expect(page.getByRole('option',{name:'No approved plan yet',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('combobox',{name:'Filter budgets',exact:true})).toContainText('No approved plan yet');await page.getByRole('button',{name:'Clear',exact:true}).click()
  }
  let release!:()=>void,ready!:()=>void;const held=new Promise<void>(resolve=>{release=resolve}),entered=new Promise<void>(resolve=>{ready=resolve})
  await page.route('**/api/budgets?**',async route=>{ready();await held;await route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporarily_unavailable"}'})});await page.reload();await entered;await expect(page.locator('.budget-attention strong')).toHaveText(['—','—','—']);await page.getByText('Opening the current operating plans…',{exact:true}).scrollIntoViewIfNeeded();await budgetCapture(page,'desk-loading-320-440');release();await expect(page.getByRole('heading',{name:'The budget desk could not be opened.',exact:true})).toBeVisible();await budgetCapture(page,'desk-error-320-440');await page.unroute('**/api/budgets?**');await page.getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByRole('heading',{name:'A considered plan starts here.',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Prepare a budget',exact:true}).click();await page.getByRole('textbox',{name:'Plan title',exact:true}).fill('PRIVATE_BDG abandoned human input');await page.getByRole('button',{name:'Preview supplied plan',exact:true}).click();await expect(page.getByRole('textbox',{name:'Budget source reference',exact:true})).toHaveValue('');await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Prepare a budget',exact:true})).toBeFocused()
  const context=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await context.newPage();try{await login(owner,'Owner');expect((await owner.request.get('/api/budgets')).status()).toBe(403);await owner.goto('/#statements?panel=budgets');await expect(owner.getByRole('heading',{name:'Shared with you',exact:true})).toBeVisible();await expect(owner.getByRole('navigation',{name:'Financial views',exact:true})).toHaveCount(0);await owner.setViewportSize({width:375,height:640});await budgetCapture(owner,'resident-budget-denied-375-640')}finally{await context.close()}
 }finally{await actors.close()}
})

async function submitRevision(page:Page,path:string,expense=false){await page.getByRole('checkbox',{name:expense?paidCheck:planCheck,exact:true}).check();const saved=page.waitForResponse(response=>new URL(response.url()).pathname===path&&response.request().method()==='POST');await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();expect((await saved).status()).toBe(200)}
async function paidProposal(page:Page,budget:string,month:number,payee:string,amount:string,reference:string){await openBudget(page,budget);await page.getByRole('button',{name:'Record a paid expense',exact:true}).click();await fillPaid(page,month,payee,amount,reference);await page.getByRole('combobox',{name:'Expense payment method',exact:true}).click();await page.getByRole('option',{name:'Bank transfer',exact:true}).hover();await budgetCapture(page,'paid-method-menu-'+month);await page.keyboard.press('Home');await expect(page.getByRole('option',{name:'Cash',exact:true})).toBeFocused();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Preview paid expense',exact:true}).click();return submitBudgetPreview(page,true)}

test('supplied plan preview separate approval and replacement retain exact accepted figures across four layouts',async({page,browser})=>{
 const a=await budgetActors(page,browser)
 try{await budgetDesk(page);await page.getByRole('button',{name:'Prepare a budget',exact:true}).click();await fillPlan(page,1,'January considered operating plan');await page.getByRole('button',{name:'Preview supplied plan',exact:true}).click();const preview=page.getByRole('region',{name:'Exact proposed plan',exact:true});await expect(preview.locator('.budget-original-money strong')).toHaveText(['₹2,000.00','₹1,250.25'])
 for(const [width,height] of [[1440,1000],[768,1000],[375,640],[320,440]]){await page.setViewportSize({width,height});await preview.locator('.budget-original-money').scrollIntoViewIfNeeded();await expect(preview.locator('.budget-original-money strong').first()).toBeInViewport();await budgetCapture(page,'plan-preview-'+width+'-'+height);await budgetWithin(page)}
 const id=await submitBudgetPreview(page);await expect(page.getByRole('button',{name:'Review budget proposal',exact:true})).toHaveCount(0);await expect(page.getByText('A separately approved plan opens this comparison.',{exact:true})).toBeVisible();await a.reviewer.setViewportSize({width:320,height:440});await openBudget(a.reviewer,id);await a.reviewer.getByRole('button',{name:'Review budget proposal',exact:true}).click();await a.reviewer.getByRole('combobox',{name:'Budget decision',exact:true}).click();await a.reviewer.getByRole('option',{name:'Decline proposal',exact:true}).hover();await budgetCapture(a.reviewer,'separate-plan-decision-menu-320-440');await budgetWithin(a.reviewer);await a.reviewer.keyboard.press('Home');await expect(a.reviewer.getByRole('option',{name:'Approve supplied plan',exact:true})).toBeFocused();await a.reviewer.keyboard.press('Enter');await a.reviewer.getByRole('textbox',{name:'Decision reason',exact:true}).fill('The independently supplied plan and precise amounts are reviewed.');await a.reviewer.getByRole('checkbox',{name:'I reviewed this exact proposal, source and decision’s effect.',exact:true}).check();const accepted=a.reviewer.waitForResponse(response=>new URL(response.url()).pathname==='/api/budgets/'+id+'/decisions'&&response.request().method()==='POST');await a.reviewer.getByRole('button',{name:'Approve supplied plan',exact:true}).click();expect((await accepted).status()).toBe(200);await expect(a.reviewer.getByRole('button',{name:'Close budget decision',exact:true})).toHaveCount(0)
 await openBudget(page,id);await page.getByRole('button',{name:'Revise plan',exact:true}).click();await expect(page.getByLabel('Budget period starts',{exact:true})).toBeDisabled();await expect(page.getByLabel('Budget period ends',{exact:true})).toBeDisabled();await page.getByRole('textbox',{name:'Plan title',exact:true}).fill('January revised supplied plan');await page.getByRole('textbox',{name:'Planned collections',exact:true}).fill('3000.00');await page.getByRole('textbox',{name:'Planned expenses',exact:true}).fill('0.00');await page.getByRole('textbox',{name:'Proposal reason',exact:true}).fill('Replace planning figures, preserving the accepted predecessor and period.');await page.getByRole('button',{name:'Preview supplied plan',exact:true}).click();await page.getByRole('region',{name:'Exact proposed plan',exact:true}).locator('.budget-original-money').scrollIntoViewIfNeeded();await expect(page.getByRole('region',{name:'Exact proposed plan',exact:true}).locator('.budget-original-money strong')).toHaveText(['₹3,000.00','₹0.00']);await budgetCapture(page,'replacement-zero-plan-320-440');await submitRevision(page,'/api/budgets/'+id+'/proposals');expect(await comparison(page,id)).toMatchObject({planned_collections_paise:200000,planned_expenses_paise:125025,plan_version:1});await decideBudgetUI(a.reviewer,id);await page.getByRole('button',{name:'Refresh comparison',exact:true}).click();await expect(page.getByRole('region',{name:'Current budget comparison',exact:true})).toContainText('Approved plan version 3');expect(await comparison(page,id)).toMatchObject({planned_collections_paise:300000,planned_expenses_paise:0,plan_version:3});await page.getByRole('region',{name:'Current budget comparison',exact:true}).locator('.budget-comparison-pair').scrollIntoViewIfNeeded();await budgetCapture(page,'approved-replacement-320-440')
 }finally{await a.close()}
})

test('received entries linked reversals and separately approved paid corrections give independently calculated exact period amounts',async({page,browser})=>{
 const a=await budgetActors(page,browser)
 try{const id=await apiBudget(page,a.reviewer,2,'February exact cash comparison'),first=await budgetEntry(page,'1000.00','2025-02-10'),second=await budgetEntry(page,'750.25','2025-02-10');await budgetPost(page,'/api/entries/'+second+'/reverse',{reason:'Independent correction of the original received entry.'});await budgetEntry(page,'200.00','2025-02-10','OPENING_CREDIT');await budgetEntry(page,'50.00','2025-02-10','CHARGE');await budgetEntry(page,'90.00','2023-02-10');const original=await budgetGet<Record<string,unknown>>(page,'/api/entries/'+first)
 const one=await paidProposal(page,id,2,'Fictional pump service','400.00','BDG-FEB-PUMP');expect(await comparison(page,id)).toMatchObject({recorded_expenses_paise:0,pending_expenses:1});await decideBudgetUI(a.reviewer,one,true,id);const two=await paidProposal(page,id,2,'Fictional lamp repair','32.51','BDG-FEB-LAMP');await decideBudgetUI(a.reviewer,two,true,id);expect(await comparison(page,id)).toMatchObject({original_collections_paise:175025,reversed_collections_paise:75025,collections_paise:100000,recorded_expenses_paise:43251,difference_paise:56749,expense_headroom_paise:81774})
 await openBudget(page,id);await page.getByText('See the collection basis',{exact:true}).click();for(const [width,height] of [[1440,1000],[768,1000],[375,640],[320,440]]){await page.setViewportSize({width,height});await page.locator('.budget-period-difference').scrollIntoViewIfNeeded();await expect(page.locator('.budget-period-difference strong')).toHaveText('₹567.49');await budgetCapture(page,'exact-comparison-'+width+'-'+height);await budgetWithin(page)}
 await openPaid(page,id,two);await page.getByRole('button',{name:'Prepare linked correction',exact:true}).click();await page.getByRole('textbox',{name:'Already-paid amount',exact:true}).fill('25.01');await page.getByRole('textbox',{name:'Proposal reason',exact:true}).fill('Correct the supplied voucher value while retaining its original snapshot.');await page.getByRole('button',{name:'Preview paid expense',exact:true}).click();await expect(page.getByRole('region',{name:'Current accepted effect',exact:true}).locator('.budget-expense-amount')).toHaveText('₹32.51');await expect(page.getByRole('region',{name:'Exact proposed paid record',exact:true}).locator('.budget-expense-amount')).toHaveText('₹25.01');await page.getByRole('region',{name:'Exact proposed paid record',exact:true}).scrollIntoViewIfNeeded();await budgetCapture(page,'linked-correction-preview-320-440');await submitRevision(page,'/api/paid-expenses/'+two+'/proposals',true);expect(await comparison(page,id)).toMatchObject({recorded_expenses_paise:43251,pending_expenses:1});await decideBudgetUI(a.reviewer,two,true,id);expect(await comparison(page,id)).toMatchObject({recorded_expenses_paise:42501,difference_paise:57499,expense_headroom_paise:82524});await page.reload();await page.getByText('Read retained paid snapshot',{exact:true}).last().click();await expect(page.getByRole('region',{name:'Retained version 1',exact:true}).locator('.budget-expense-amount')).toHaveText('₹32.51');await page.getByRole('region',{name:'Retained version 1',exact:true}).locator('.budget-expense-amount').scrollIntoViewIfNeeded();await budgetCapture(page,'retained-original-expense-320-440');const retained=await budgetGet<Record<string,unknown>>(page,'/api/entries/'+first);for(const key of ['id','amount_paise','receipt_number','posted_at','date','kind'])expect(retained[key]).toEqual(original[key])
 }finally{await a.close()}
})

test('closed periods preserve pending review original expense void restoration and globally reserved vouchers',async({page,browser})=>{
 const a=await budgetActors(page,browser)
 try{const id=await apiBudget(page,a.reviewer,3,'March closed retained period'),one=await apiPaid(page,a.reviewer,id,3,'Retained March original'),pending=await apiPaid(page,a.reviewer,id,3,'Prepared before closure','1.00',false),source=await budgetGet<PaidExpenseDetail>(page,'/api/paid-expenses/'+one);await openBudget(page,id);await page.getByRole('button',{name:'Prepare period closure',exact:true}).click();await page.getByRole('textbox',{name:'Proposal reason',exact:true}).fill('Close new intake while retaining originals and the already-prepared proposal.');await page.getByRole('button',{name:'Preview supplied plan',exact:true}).click();await budgetCapture(page,'closure-preview-1440-1000');await submitRevision(page,'/api/budgets/'+id+'/proposals');await decideBudgetUI(a.reviewer,id);await openBudget(page,id);await expect(page.getByRole('button',{name:'Record a paid expense',exact:true})).toHaveCount(0);await decideBudgetUI(a.reviewer,pending,true,id);expect(await comparison(page,id)).toMatchObject({recorded_expenses_paise:3351,expense_count:2})
 await openPaid(page,id,one);await page.getByRole('button',{name:'Remove this record’s effect',exact:true}).click();await page.getByRole('textbox',{name:'Proposal reason',exact:true}).fill('Remove the erroneous supplied record effect without changing its original.');await page.getByRole('button',{name:'Preview paid expense',exact:true}).click();await expect(page.getByRole('region',{name:'Proposed effect after approval',exact:true}).locator('.budget-expense-amount')).toHaveText('₹0.00');await page.setViewportSize({width:375,height:640});await page.getByRole('region',{name:'Proposed effect after approval',exact:true}).scrollIntoViewIfNeeded();await budgetCapture(page,'void-preview-375-640');await submitRevision(page,'/api/paid-expenses/'+one+'/proposals',true);expect(await comparison(page,id)).toMatchObject({recorded_expenses_paise:3351});await decideBudgetUI(a.reviewer,one,true,id);expect(await comparison(page,id)).toMatchObject({recorded_expenses_paise:100,difference_paise:-100});await openPaid(page,id,one);await expect(page.getByRole('button',{name:'Remove this record’s effect',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Prepare linked correction',exact:true}).click();await page.getByRole('textbox',{name:'Already-paid amount',exact:true}).fill('25.01');await page.getByRole('textbox',{name:'Proposal reason',exact:true}).fill('Restore the corrected supplied amount as a separately approved linked version.');await page.getByRole('button',{name:'Preview paid expense',exact:true}).click();await submitRevision(page,'/api/paid-expenses/'+one+'/proposals',true);await decideBudgetUI(a.reviewer,one,true,id);expect(await comparison(page,id)).toMatchObject({recorded_expenses_paise:2601,difference_paise:-2601});expect((await budgetGet<PaidExpenseDetail>(page,'/api/paid-expenses/'+one)).approved).toMatchObject({budget_version:1,previous_version:3,reference:source.snapshot.reference})
 const april=await apiBudget(page,a.reviewer,4,'April duplicate voucher protection');await openBudget(page,april);await page.getByRole('button',{name:'Record a paid expense',exact:true}).click();await fillPaid(page,4,'Duplicate voucher attempt','1.00',source.snapshot.reference);await page.getByRole('button',{name:'Preview paid expense',exact:true}).click();await page.getByRole('checkbox',{name:paidCheck,exact:true}).check();const rejected=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/paid-expenses'&&response.request().method()==='POST');await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();expect((await rejected).status()).toBe(409);await expect(page.getByRole('alert')).toContainText('already belongs');await budgetCapture(page,'duplicate-voucher-rejection-375-640');await expect(page.getByRole('button',{name:'Edit proposal',exact:true})).toBeEnabled();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Record a paid expense',exact:true})).toBeVisible();expect((await budgetGet<PaidExpensePage>(page,'/api/paid-expenses?budget_id='+april)).total).toBe(0)
 }finally{await a.close()}
})

test('unknown saves freeze dismissal and retry identical operations while stale revisions preserve human input for deliberate resubmission',async({page,browser})=>{
 const a=await budgetActors(page,browser);let release=()=>{}
 try{const id=await apiBudget(page,a.reviewer,5,'May guarded retries and stale proposal');await openBudget(page,id);await page.getByRole('button',{name:'Record a paid expense',exact:true}).click();await fillPaid(page,5,'Human retry payee','1.00','BDG-MAY-RETRY');await page.getByRole('button',{name:'Preview paid expense',exact:true}).click();await page.getByRole('checkbox',{name:paidCheck,exact:true}).check();let ready!:()=>void;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r}),bodies:unknown[]=[];await page.route('**/api/paid-expenses',async route=>{if(route.request().method()!=='POST'){await route.continue();return}bodies.push(route.request().postDataJSON());const response=await route.fetch();if(bodies.length===1){expect(response.status()).toBe(200);ready();await held;await route.abort('failed')}else await route.fulfill({response})});await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();await entered;await expect(page.getByRole('button',{name:'Saving…',exact:true})).toBeDisabled();expect(Number(await page.locator('.dialog-close').evaluate(element=>getComputedStyle(element).opacity))).toBeLessThan(1);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await page.setViewportSize({width:320,height:440});await page.getByRole('button',{name:'Saving…',exact:true}).scrollIntoViewIfNeeded();await budgetCapture(page,'pending-save-320-440');release();await expect(page.getByRole('button',{name:'Retry this proposal',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Edit proposal',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await budgetCapture(page,'unknown-save-retry-320-440');await page.getByRole('button',{name:'Retry this proposal',exact:true}).click();await expect(page.getByRole('heading',{name:'Every decision stays on record.',exact:true})).toBeVisible();expect(bodies).toHaveLength(2);expect(bodies[1]).toEqual(bodies[0]);await page.unroute('**/api/paid-expenses');const rows=await budgetGet<PaidExpensePage>(page,'/api/paid-expenses?budget_id='+id);expect(rows.total).toBe(1);const expense=rows.items[0].id
 await page.getByRole('button',{name:'Revise expense proposal',exact:true}).click();await page.getByRole('textbox',{name:'Already-paid amount',exact:true}).fill('3.00');await page.getByRole('textbox',{name:'Proposal reason',exact:true}).fill('Keep my deliberately supplied three rupee correction after a stale head.');const current=rows.items[0].snapshot;await budgetPost(page,'/api/paid-expenses/'+expense+'/proposals',{version:1,action:'PAID',budget_id:id,amount:'2.00',paid_date:current.paid_date,payee:'Competing supplied payee',category:current.category,method:current.method,reference:current.reference,source_note:current.source_note,reason:'A competing legitimate proposal makes the open human version stale.'});await page.getByRole('button',{name:'Preview paid expense',exact:true}).click();await page.getByRole('checkbox',{name:paidCheck,exact:true}).check();await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();await expect(page.getByRole('button',{name:'Reload current record',exact:true})).toBeVisible();await budgetCapture(page,'stale-expense-proposal-320-440');await page.getByRole('button',{name:'Reload current record',exact:true}).click();await expect(page.getByRole('textbox',{name:'Already-paid amount',exact:true})).toHaveValue('3.00');await expect(page.getByRole('textbox',{name:'Expense payee',exact:true})).toHaveValue('Human retry payee');await expect(page.getByRole('textbox',{name:'Proposal reason',exact:true})).toHaveValue('Keep my deliberately supplied three rupee correction after a stale head.');await page.getByRole('button',{name:'Preview paid expense',exact:true}).click();await expect(page.getByRole('checkbox',{name:paidCheck,exact:true})).not.toBeChecked();await submitRevision(page,'/api/paid-expenses/'+expense+'/proposals',true);expect((await budgetGet<PaidExpenseDetail>(page,'/api/paid-expenses/'+expense)).snapshot.amount_paise).toBe(300);expect(await comparison(page,id)).toMatchObject({recorded_expenses_paise:0,pending_expenses:1})
 }finally{release();await a.close()}
})

test('comparison and expense read errors recover independently and expired Treasury removes private forms despite broad committee ledger access',async({page,browser})=>{
 const a=await budgetActors(page,browser)
 try{const id=await apiBudget(page,a.reviewer,6,'June independent sources and permission expiry');await apiPaid(page,a.reviewer,id,6,'PRIVATE_BDG sensitive June payee');await page.route('**/api/budgets/'+id+'/comparison?**',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporarily_unavailable"}'}));await openBudget(page,id);await expect(page.getByRole('region',{name:'Accepted operating plan',exact:true})).toContainText('₹2,000.00');await expect(page.getByRole('region',{name:'Current budget comparison',exact:true})).toContainText('The comparison is unavailable.');await expect(page.locator('.budget-period-difference')).toHaveCount(0);await expect(page.getByRole('region',{name:'Budget decision history',exact:true})).toContainText('record version 1');await page.setViewportSize({width:320,height:440});await page.getByRole('button',{name:'Retry budget comparison',exact:true}).scrollIntoViewIfNeeded();await budgetCapture(page,'comparison-error-retained-plan-320-440');await page.unroute('**/api/budgets/'+id+'/comparison?**');await page.getByRole('button',{name:'Retry budget comparison',exact:true}).click();await expect(page.locator('.budget-period-difference strong')).toHaveText('-₹32.51')
 await page.route('**/api/paid-expenses?**',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporarily_unavailable"}'}));await page.reload();await expect(page.getByRole('heading',{name:'Paid records could not be opened.',exact:true})).toBeVisible();await expect(page.locator('.budget-period-difference strong')).toHaveText('-₹32.51');await page.getByRole('heading',{name:'Paid records could not be opened.',exact:true}).scrollIntoViewIfNeeded();await budgetCapture(page,'expense-read-error-320-440');await page.unroute('**/api/paid-expenses?**');await page.getByRole('region',{name:'Paid expense register',exact:true}).getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByRole('button',{name:'Open paid expense PRIVATE_BDG sensitive June payee',exact:true})).toBeVisible()
 await openBudget(a.reviewer,id);await a.reviewer.getByRole('button',{name:'Revise plan',exact:true}).click();await a.reviewer.getByRole('textbox',{name:'Plan title',exact:true}).fill('PRIVATE_BDG active text before expiry');messagePrivateFixture("db.execute(\"UPDATE role_grants SET valid_from=strftime('%s','now')-172800,valid_until=strftime('%s','now')-1 WHERE user_id='demo-user-committee' AND role='TREASURER' AND revoked_at IS NULL\")");expect((await a.reviewer.request.get('/api/budgets/'+id)).status()).toBe(403);await a.reviewer.reload();const me=await(await a.reviewer.request.get('/api/auth/me')).json();expect(me.can_read_all_records).toBe(true);expect(me.can_manage_records).toBe(false);await expect(a.reviewer.getByRole('navigation',{name:'Financial views',exact:true})).toHaveCount(0);await expect(a.reviewer.getByRole('dialog')).toHaveCount(0);await expect(a.reviewer.locator('body')).not.toContainText('PRIVATE_BDG sensitive June payee');await a.reviewer.setViewportSize({width:375,height:640});await budgetCapture(a.reviewer,'expired-treasury-private-view-375-640')
 }finally{messagePrivateFixture("db.execute(\"UPDATE role_grants SET valid_from=strftime('%s','now')-172800,valid_until=strftime('%s','now')+30*86400 WHERE user_id='demo-user-committee' AND role='TREASURER' AND revoked_at IS NULL\")");await a.close()}
})

test('register pages independent full counts retained filters and long histories remain usable on short phones',async({page,browser})=>{
 const a=await budgetActors(page,browser)
 try{const id=await apiBudget(page,a.reviewer,7,'July paged private expense register');for(let i=0;i<13;i++)await apiPaid(page,a.reviewer,id,7,'Paged synthetic payee '+String(i).padStart(2,'0'),'1.00',false);await openBudget(page,id);await expect(page.locator('.budget-expense-card')).toHaveCount(12);await expect(page.locator('.budget-expense-full-counts')).toContainText('13 proposals awaiting review');await page.getByRole('button',{name:'Next paid expenses page',exact:true}).click();await expect(page.locator('.budget-expense-card')).toHaveCount(1);await expect(page.getByRole('region',{name:'Paid expense register',exact:true})).toContainText('Page 2 of 2');await page.locator('.budget-expense-card').click();await page.getByRole('button',{name:'Return to budget period',exact:true}).click();await expect(page.getByRole('region',{name:'Paid expense register',exact:true})).toContainText('Page 2 of 2');await page.getByRole('textbox',{name:'Search paid expenses',exact:true}).fill('Paged synthetic payee 07');await expect(page.locator('.budget-expense-card')).toHaveCount(1);await expect(page.locator('.budget-expense-full-counts')).toContainText('13 proposals awaiting review');await page.locator('.budget-expense-card').click();await page.getByRole('button',{name:'Return to budget period',exact:true}).click();await expect(page.getByRole('textbox',{name:'Search paid expenses',exact:true})).toHaveValue('Paged synthetic payee 07');await page.setViewportSize({width:320,height:440});await page.locator('.budget-expense-card').scrollIntoViewIfNeeded();await budgetCapture(page,'expense-filter-preserved-320-440');await page.getByRole('button',{name:'Close budget details',exact:true}).click()
 const ids:string[]=[];for(let i=0;i<13;i++){const created=await budgetPost(page,'/api/budgets',{version:0,action:'PLAN',title:'Paged supplied plan '+String(i).padStart(2,'0'),period_start:'2024-10-'+String(i+1).padStart(2,'0'),period_end:'2024-10-'+String(i+1).padStart(2,'0'),source_reference:'PRIVATE_BDG page source',planned_collections:'0.00',planned_expenses:'0.00',reason:'Independent retained original for page and status checks.'});ids.push(created.id)}await page.reload();await page.getByRole('textbox',{name:'Search budgets',exact:true}).fill('Paged supplied plan');await expect(page.locator('.budget-card')).toHaveCount(12);await page.getByRole('button',{name:'Next budgets page',exact:true}).click();await expect(page.locator('.budget-card')).toHaveCount(1);await expect(page.locator('.budget-attention strong').nth(1)).toHaveText('13');await page.locator('.budget-card').scrollIntoViewIfNeeded();await budgetCapture(page,'budget-page-two-320-440')
 const retained=ids[0];for(let version=1;version<25;version++)await budgetPost(page,'/api/budgets/'+retained+'/proposals',{version,action:'PLAN',title:'Paged supplied plan history '+version,period_start:'2024-10-01',period_end:'2024-10-01',source_reference:'PRIVATE_BDG retained original reference',planned_collections:'0.00',planned_expenses:'0.00',reason:'Retain deliberate supplied plan history version '+version+' for inspection.'});await openBudget(page,retained);await page.getByRole('button',{name:'Next budget history page',exact:true}).click();await page.getByRole('button',{name:'Next budget history page',exact:true}).click();await expect(page.getByRole('region',{name:'Budget decision history',exact:true}).locator('article')).toHaveCount(1);await expect(page.getByRole('region',{name:'Budget decision history',exact:true})).toContainText('record version 1');await page.getByRole('region',{name:'Budget decision history',exact:true}).locator('article').scrollIntoViewIfNeeded();await budgetCapture(page,'original-budget-history-page-three-320-440');await budgetWithin(page);expect((await budgetGet<BudgetDetail>(page,'/api/budgets/'+retained+'?event_page=3')).events[0].version).toBe(1)
 }finally{await a.close()}
})
