import { test, expect } from '@playwright/test'
import { chooseOption } from './helpers'
import { financialHeaders } from './maintenance-fixtures'
import { messagePrivateFixture } from './messages-fixtures'
import type { ChecklistDetail, ChecklistPage } from '../src/checklists'
import { checklistActors, checklistGet, checklistPost, checklistDesk, openChecklist, apiChecklist, apiChecklistAction, apiChecklistChecks, readyChecklist, fillChecklist, submitChecklistUI, finishChecklistAction, checkDetailUI, checklistCapture, checklistWithin, proposalCheck, actionCheck } from './checklists-fixtures'

test.setTimeout(120000)
test('checklist desk empty loading error retry menus keyboard and denied scopes render on five layouts',async({page,browser})=>{
 const a=await checklistActors(page,browser)
 try{await checklistDesk(page);await expect(page.getByRole('heading',{name:'A thoughtful handover starts here.',exact:true})).toBeVisible();await expect(page.locator('.checklist-attention strong')).toHaveText(['0','0','0'])
 for(const [width,height] of [[1440,1000],[768,1000],[375,640],[320,640],[320,440]]){await page.setViewportSize({width,height});await page.getByRole('heading',{name:'The checklist desk.',exact:true}).scrollIntoViewIfNeeded();await checklistCapture(page,'empty-desk-'+width+'-'+height);await checklistWithin(page);const tops=await page.locator('.checklist-attention strong').evaluateAll(els=>els.map(e=>e.getBoundingClientRect().top));expect(Math.max(...tops)-Math.min(...tops)).toBeLessThan(1);await page.getByRole('combobox',{name:'Filter checklists',exact:true}).click();await page.getByRole('option',{name:'Completed outcomes',exact:true}).hover();await checklistCapture(page,'filter-menu-'+width+'-'+height);await checklistWithin(page);await page.keyboard.press('Home');await expect(page.getByRole('option',{name:'All checklist records',exact:true})).toBeFocused();await page.keyboard.press('End');await expect(page.getByRole('option',{name:'Closed without completion',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('combobox',{name:'Filter checklists',exact:true})).toContainText('Closed without completion');await page.getByRole('button',{name:'Clear',exact:true}).click()}
 let ready!:()=>void,release!:()=>void;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r});await page.route('**/api/move-checklists?**',async route=>{ready();await held;await route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporarily_unavailable"}'})});await page.reload();await entered;await expect(page.locator('.checklist-attention strong')).toHaveText(['—','—','—']);await page.getByText('Opening the current checklist desk…',{exact:true}).scrollIntoViewIfNeeded();await checklistCapture(page,'desk-loading-320-440');release();await expect(page.getByRole('heading',{name:'The checklist desk could not be opened.',exact:true})).toBeVisible();await checklistCapture(page,'desk-error-320-440');await page.unroute('**/api/move-checklists?**');await page.getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByRole('heading',{name:'A thoughtful handover starts here.',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Prepare a checklist',exact:true}).click();await page.getByRole('button',{name:'Preview checklist proposal',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Prepare a checklist',exact:true})).toBeFocused()
 expect((await a.owner.request.get('/api/move-checklists/options?home=demo-flat-A-103')).status()).toBe(404);expect((await a.owner.request.post('/api/move-checklists',{headers:await financialHeaders(a.owner),data:{operation_key:crypto.randomUUID(),version:0,flat_id:'demo-flat-A-103',resident_id:'demo-tenant-A-103',kind:'MOVE_IN',effective_date:'2026-10-15',note:'Forged different household supplied request.',reason:'Cross-household proposal must be denied.',confirmed:true}})).status()).toBe(403)
 }finally{await a.close()}
})

test('resident proposal five actual checks optional explanation and different administrator completion preserve original sources',async({page,browser})=>{
 const a=await checklistActors(page,browser)
 try{await checklistDesk(a.owner);await a.owner.getByRole('button',{name:'Prepare a checklist',exact:true}).click();await a.owner.setViewportSize({width:375,height:640});await fillChecklist(a.owner,'PRIVATE_CHK resident supplied contact handover request.');await checklistCapture(a.owner,'resident-exact-preview-375-640');await checklistWithin(a.owner);const id=await submitChecklistUI(a.owner);expect((await checklistGet<ChecklistDetail>(a.owner,'/api/move-checklists/'+id)).version).toBe(1);await expect(a.owner.getByRole('button',{name:/^Review Identity/})).toHaveCount(0)
 await openChecklist(page,id);await expect(page.getByRole('button',{name:'Prepare separate review',exact:true})).toBeDisabled();const registry=page.waitForEvent('popup');await page.getByRole('link',{name:'Open registry record',exact:true}).click();const home=await registry;await expect(home.getByRole('dialog')).toContainText('A-101');await home.close();const contact=page.waitForEvent('popup');await page.getByRole('link',{name:'Open contact preferences',exact:true}).click();const profile=await contact;await expect(profile.getByRole('dialog')).toContainText('Demo Owner A-101');await profile.close()
 for(const kind of ['IDENTITY','REGISTRY','CONTACT','DOCUMENTS','HANDOVER']){await checkDetailUI(page,id,kind);if(kind!=='HANDOVER')await expect(page.getByRole('button',{name:'Prepare separate review',exact:true})).toBeDisabled()}
 await page.setViewportSize({width:320,height:440});await page.getByRole('region',{name:'Checklist checks',exact:true}).scrollIntoViewIfNeeded();await checklistCapture(page,'five-current-checks-320-440');await checklistWithin(page);await page.getByRole('button',{name:'Prepare separate review',exact:true}).click();await finishChecklistAction(page,id,'Submit for separate review');await expect(page.getByRole('button',{name:'Review checklist proposal',exact:true})).toHaveCount(0)
 await openChecklist(a.reviewer,id);await a.reviewer.getByRole('button',{name:'Review checklist proposal',exact:true}).click();await a.reviewer.setViewportSize({width:375,height:640});await a.reviewer.getByRole('combobox',{name:'Checklist decision',exact:true}).click();await expect(a.reviewer.getByRole('option',{name:'Complete review',exact:true})).toBeVisible();await checklistCapture(a.reviewer,'separate-decision-menu-375-640');await checklistWithin(a.reviewer);await a.reviewer.keyboard.press('Escape');await finishChecklistAction(a.reviewer,id,'Complete review');const done=await checklistGet<ChecklistDetail>(a.owner,'/api/move-checklists/'+id);expect(done).toMatchObject({version:8,phase:'COMPLETED',pending:false,approved:{version:8},checked:3,not_applicable:2,event_total:8});expect(done.events.at(-1)?.snapshot.note).toBe('PRIVATE_CHK resident supplied contact handover request.');await openChecklist(a.owner,id);await checklistCapture(a.owner,'completed-own-outcome-375-640');expect((await checklistGet<{version:number}>(page,'/api/flats/demo-flat-A-101')).version).toBe(1);expect((await checklistGet<{version:number}>(a.owner,'/api/contacts/me')).version).toBe(0);const money=await checklistGet<{total:number}>(page,'/api/entries');expect(money.total).toBe(0)
 }finally{await a.close()}
})

test('information request revision fresh checks withdrawal and linked correction retain the completed predecessor',async({page,browser})=>{
 const a=await checklistActors(page,browser)
 try{const id=await apiChecklist(a.owner,'PRIVATE_CHK information and linked correction original.');await readyChecklist(page,id);await openChecklist(a.reviewer,id);await a.reviewer.getByRole('button',{name:'Review checklist proposal',exact:true}).click();await chooseOption(a.reviewer,'Checklist decision','Ask for information');await finishChecklistAction(a.reviewer,id,'Ask for information');await openChecklist(a.owner,id);await a.owner.getByRole('button',{name:'Revise request',exact:true}).click();await a.owner.getByRole('textbox',{name:'Checklist explanation',exact:true}).fill('PRIVATE_CHK clarified the actual supplied handover detail.');await a.owner.getByRole('textbox',{name:'Checklist proposal reason',exact:true}).fill('PRIVATE_CHK provide the requested original supporting explanation.');await a.owner.getByRole('button',{name:'Preview checklist proposal',exact:true}).click();await a.owner.getByRole('checkbox',{name:proposalCheck,exact:true}).check();await a.owner.getByRole('button',{name:'Submit for checks',exact:true}).click();await expect(a.owner.getByRole('region',{name:'Checklist checks',exact:true})).toBeVisible();expect((await checklistGet<ChecklistDetail>(page,'/api/move-checklists/'+id)).snapshot.checks.every(x=>x.state==='INCOMPLETE')).toBe(true);await readyChecklist(page,id);await apiChecklistAction(a.reviewer,id,'APPROVED');const approved=await checklistGet<ChecklistDetail>(a.owner,'/api/move-checklists/'+id)
 await openChecklist(a.owner,id);await a.owner.getByRole('button',{name:'Prepare linked correction',exact:true}).click();await a.owner.getByRole('textbox',{name:'Checklist explanation',exact:true}).fill('PRIVATE_CHK correction to the supplied handover note.');await a.owner.getByRole('textbox',{name:'Checklist proposal reason',exact:true}).fill('PRIVATE_CHK correct the supplied note while retaining the completed predecessor.');await a.owner.getByRole('button',{name:'Preview checklist proposal',exact:true}).click();await a.owner.getByRole('checkbox',{name:proposalCheck,exact:true}).check();await a.owner.getByRole('button',{name:'Submit for checks',exact:true}).click();await expect(a.owner.getByRole('region',{name:'Completed outcome on record',exact:true})).toBeVisible();await a.owner.setViewportSize({width:320,height:440});await a.owner.getByRole('region',{name:'Completed outcome on record',exact:true}).scrollIntoViewIfNeeded();await checklistCapture(a.owner,'accepted-predecessor-pending-correction-320-440');await a.owner.getByRole('button',{name:'Withdraw proposal',exact:true}).click();await finishChecklistAction(a.owner,id,'Withdraw proposal');const withdrawn=await checklistGet<ChecklistDetail>(a.owner,'/api/move-checklists/'+id);expect(withdrawn.approved).toEqual(approved.approved);expect(withdrawn.pending).toBe(false);expect(withdrawn.phase).toBe('CANCELLED');expect(withdrawn.state).toBe('COMPLETED');await expect(a.owner.getByRole('region',{name:'Completed outcome on record',exact:true})).toContainText('clarified the actual supplied handover detail.')
 }finally{await a.close()}
})

test('changed contact and registry context keeps supplied notes and blocks completion until all checks are current',async({page,browser})=>{
 const a=await checklistActors(page,browser)
 try{const id=await apiChecklist(a.owner,'PRIVATE_CHK preserved source notes for current review.');await readyChecklist(page,id);const old=await checklistGet<ChecklistDetail>(page,'/api/move-checklists/'+id),profile=await checklistGet<{version:number}>(a.owner,'/api/contacts/me');await checklistPost(a.owner,'/api/contacts/me/register',{version:profile.version,phone:'+919000000902',email:'checklist-context@example.test',preferred_channel:'EMAIL',community_whatsapp:false,community_email:true,finance_whatsapp:false,finance_email:false,consent_source:'PRIVATE_CHK supplied actual profile choice for separate contact verification.',reason:'PRIVATE_CHK changed registered profile invalidates the previous checklist context.'});await openChecklist(a.reviewer,id);await expect(a.reviewer.getByRole('heading',{name:'The context has moved on.',exact:true})).toBeVisible();await a.reviewer.getByRole('button',{name:'Review checklist proposal',exact:true}).click();await expect(a.reviewer.getByRole('combobox',{name:'Checklist decision',exact:true})).toContainText('Decline proposal');await a.reviewer.getByRole('combobox',{name:'Checklist decision',exact:true}).click();await expect(a.reviewer.getByRole('option',{name:'Complete review',exact:true})).toHaveCount(0);await a.reviewer.keyboard.press('Escape');await a.reviewer.getByRole('button',{name:'Back to checklist',exact:true}).click();await a.reviewer.setViewportSize({width:320,height:440});await a.reviewer.getByRole('heading',{name:'The context has moved on.',exact:true}).scrollIntoViewIfNeeded();await checklistCapture(a.reviewer,'changed-context-requires-current-checks-320-440');await checklistWithin(a.reviewer)
 await openChecklist(page,id);await page.getByRole('button',{name:'Return to checks',exact:true}).click();await finishChecklistAction(page,id,'Return to checks');await checkDetailUI(page,id,'CONTACT');await expect(page.getByRole('button',{name:'Prepare separate review',exact:true})).toBeDisabled();let d=await checklistGet<ChecklistDetail>(page,'/api/move-checklists/'+id);expect(d.stale_checks).toBe(4);expect(d.snapshot.checks.find(x=>x.kind==='IDENTITY')?.reference).toBe(old.snapshot.checks.find(x=>x.kind==='IDENTITY')?.reference)
 await apiChecklistChecks(page,id);await apiChecklistAction(page,id,'READY');messagePrivateFixture("db.execute(\"UPDATE flats SET version=version+1 WHERE id='demo-flat-A-101'\")");await openChecklist(a.reviewer,id);await a.reviewer.getByRole('button',{name:'Review checklist proposal',exact:true}).click();await a.reviewer.getByRole('combobox',{name:'Checklist decision',exact:true}).click();await expect(a.reviewer.getByRole('option',{name:'Complete review',exact:true})).toHaveCount(0);await a.reviewer.keyboard.press('Escape');await apiChecklistAction(page,id,'RETURN');await readyChecklist(page,id);await apiChecklistAction(a.reviewer,id,'APPROVED');d=await checklistGet<ChecklistDetail>(a.owner,'/api/move-checklists/'+id);expect(d.snapshot.note).toBe(old.snapshot.note);expect(d.phase).toBe('COMPLETED');expect(d.source.contact_state).toBe('PENDING');expect(d.source.registry_version).toBe(2)
 await page.route('**/api/move-checklists/'+id+'?**',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporarily_unavailable"}'}));await page.goto('/#homes?panel=checklists&checklist='+id);await page.reload();await expect(page.getByRole('heading',{name:'This checklist could not be opened.',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'The checklist is unavailable.',exact:true})).toBeVisible();await checklistCapture(page,'detail-read-error-desktop');await page.unroute('**/api/move-checklists/'+id+'?**');await page.getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByRole('region',{name:'Completed outcome on record',exact:true})).toBeVisible()
 }finally{await a.close()}
})

test('interrupted create check and completion freeze exact payload and retry once while stale reload retains human input',async({page,browser})=>{
 const a=await checklistActors(page,browser)
 try{await checklistDesk(a.owner);await a.owner.getByRole('button',{name:'Prepare a checklist',exact:true}).click();await fillChecklist(a.owner,'PRIVATE_CHK interrupted original supplied request.');await a.owner.getByRole('checkbox',{name:proposalCheck,exact:true}).check();let id=''
 for(const mode of ['create','check','approve']){const actor=mode==='create'?a.owner:mode==='check'?page:a.reviewer;if(mode==='check'){await openChecklist(page,id);await page.getByRole('button',{name:'Review Identity & supplied source',exact:true}).click();await page.getByRole('textbox',{name:'Checklist check reference',exact:true}).fill('PRIVATE_CHK exact retained original identity reference.')}if(mode==='approve'){await readyChecklist(page,id);await openChecklist(a.reviewer,id);await a.reviewer.getByRole('button',{name:'Review checklist proposal',exact:true}).click()}
 if(mode!=='create'){await actor.getByRole('textbox',{name:'Checklist action reason',exact:true}).fill('PRIVATE_CHK exact supplied action for interrupted response retry.');await actor.getByRole('checkbox',{name:actionCheck,exact:true}).check()}
 const path=mode==='create'?'/api/move-checklists':'/api/move-checklists/'+id+'/actions',label=mode==='create'?'Submit for checks':mode==='check'?'Record this check':'Complete review',bodies:string[]=[];let ready!:()=>void,release!:()=>void;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r});await actor.route('**'+path,async route=>{if(route.request().method()!=='POST'){await route.continue();return}bodies.push(route.request().postData()!);if(bodies.length>1){await route.continue();return}const response=await route.fetch();expect(response.status()).toBe(200);if(mode==='create')id=(await response.json()).id;ready();await held;await route.fulfill({status:503,contentType:'application/json',body:'{"error":"response_interrupted"}'})});await actor.getByRole('button',{name:label,exact:true}).click();await entered;await expect(actor.getByRole('button',{name:mode==='create'?'Close checklist proposal':'Close checklist action',exact:true})).toBeDisabled();await actor.keyboard.press('Escape');await expect(actor.getByRole('dialog')).toBeVisible();release();await expect(actor.getByRole('button',{name:mode==='create'?'Retry this proposal':'Retry this action',exact:true})).toBeVisible();await actor.setViewportSize({width:320,height:440});await actor.getByRole('alert').scrollIntoViewIfNeeded();await checklistCapture(actor,'unknown-'+mode+'-exact-retry-320-440');await checklistWithin(actor);await actor.getByRole('button',{name:mode==='create'?'Retry this proposal':'Retry this action',exact:true}).click();await expect(actor.getByRole('region',{name:'Checklist checks',exact:true})).toBeVisible();expect(bodies).toHaveLength(2);expect(bodies[1]).toBe(bodies[0]);await actor.unroute('**'+path)}
 let d=await checklistGet<ChecklistDetail>(a.owner,'/api/move-checklists/'+id);expect(d.phase).toBe('COMPLETED');expect(d.event_total).toBe(9);expect((await checklistGet<ChecklistPage>(a.owner,'/api/move-checklists?q=PRIVATE_CHK%20interrupted%20original')).total).toBe(1)
 const stale=await apiChecklist(a.owner,'PRIVATE_CHK separate stale editable proposal.');await openChecklist(page,stale);await page.getByRole('button',{name:'Review Identity & supplied source',exact:true}).click();await page.getByRole('textbox',{name:'Checklist check reference',exact:true}).fill('PRIVATE_CHK human evidence retained after version conflict.');await page.getByRole('textbox',{name:'Checklist action reason',exact:true}).fill('PRIVATE_CHK human reason retained after version conflict.');await page.getByRole('checkbox',{name:actionCheck,exact:true}).check();await apiChecklistAction(a.reviewer,stale,'CHECK',{check_kind:'REGISTRY',check_state:'CHECKED',reference:'PRIVATE_CHK a different real current registry check.'});await page.getByRole('button',{name:'Record this check',exact:true}).click();await expect(page.getByRole('button',{name:'Reload current record',exact:true})).toBeVisible();await page.getByRole('button',{name:'Reload current record',exact:true}).click();await expect(page.getByRole('checkbox',{name:actionCheck,exact:true})).not.toBeChecked();await expect(page.getByRole('textbox',{name:'Checklist check reference',exact:true})).toHaveValue('PRIVATE_CHK human evidence retained after version conflict.');await finishChecklistAction(page,stale,'Record this check');d=await checklistGet<ChecklistDetail>(page,'/api/move-checklists/'+stale);expect(d.version).toBe(3)
 }finally{await a.close()}
})

test('ended residents retain only own submitted outcome and withdrawal while expired registry staff lose private views',async({page,browser})=>{
 const a=await checklistActors(page,browser)
 try{const own=await apiChecklist(a.owner,'PRIVATE_CHK own pending retained after move.'),other=await apiChecklist(a.reviewer,'PRIVATE_CHK unrelated private household','demo-flat-A-103','demo-tenant-A-103');await openChecklist(a.owner,own);await a.owner.getByRole('button',{name:'Revise request',exact:true}).click();await a.owner.getByRole('textbox',{name:'Checklist explanation',exact:true}).fill('PRIVATE_CHK old active form before relationship ended.');messagePrivateFixture("r=db.execute(\"UPDATE flat_memberships SET end_date='2026-01-01' WHERE resident_id='demo-owner-A-101'\");assert r.rowcount==2");await a.owner.reload();await expect(a.owner.getByRole('textbox',{name:'Checklist explanation',exact:true})).toHaveCount(0);await expect(a.owner.getByRole('link',{name:'Open registry record',exact:true})).toHaveCount(0);await expect(a.owner.getByRole('link',{name:'Open contact preferences',exact:true})).toHaveCount(0);await expect(a.owner.getByRole('button',{name:'Revise request',exact:true})).toHaveCount(0);expect((await a.owner.request.get('/api/move-checklists/'+other)).status()).toBe(404);await a.owner.setViewportSize({width:375,height:640});await a.owner.getByText('Your submitted outcome stays here. Current household details and new household actions are unavailable.',{exact:true}).scrollIntoViewIfNeeded();await checklistCapture(a.owner,'ended-relationship-limited-own-history-375-640');await a.owner.getByRole('button',{name:'Withdraw proposal',exact:true}).click();await finishChecklistAction(a.owner,own,'Withdraw proposal');expect((await checklistGet<ChecklistDetail>(a.owner,'/api/move-checklists/'+own)).phase).toBe('CANCELLED');await a.owner.getByRole('button',{name:'Close checklist details',exact:true}).click();await expect(a.owner.getByRole('button',{name:'Prepare a checklist',exact:true})).toHaveCount(0)
 await openChecklist(a.reviewer,other);await a.reviewer.getByRole('button',{name:'Review Identity & supplied source',exact:true}).click();await a.reviewer.getByRole('textbox',{name:'Checklist check reference',exact:true}).fill('PRIVATE_CHK private staff input before appointment expiry.');messagePrivateFixture("db.execute(\"UPDATE role_grants SET valid_from=strftime('%s','now')-172800,valid_until=strftime('%s','now')-1 WHERE user_id='demo-user-committee' AND role='ADMINISTRATOR' AND revoked_at IS NULL\")");await a.reviewer.reload();await expect(a.reviewer.getByRole('button',{name:'Move & contact reviews',exact:true})).toHaveCount(0);await expect(a.reviewer.getByRole('dialog')).toHaveCount(0);await expect(a.reviewer.locator('body')).not.toContainText('PRIVATE_CHK unrelated private household');expect((await a.reviewer.request.get('/api/move-checklists/'+other)).status()).toBe(403);const me=await checklistGet<{can_read_all_records:boolean;can_read_checklists:boolean}>(a.reviewer,'/api/auth/me');expect(me.can_read_all_records).toBe(true);expect(me.can_read_checklists).toBe(false);await a.reviewer.setViewportSize({width:375,height:640});await checklistCapture(a.reviewer,'expired-registry-private-view-375-640')
 }finally{messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=NULL WHERE resident_id='demo-owner-A-101'\");db.execute(\"UPDATE role_grants SET valid_from=strftime('%s','now')-172800,valid_until=strftime('%s','now')+30*86400 WHERE user_id='demo-user-committee' AND role='ADMINISTRATOR' AND revoked_at IS NULL\")");await a.close()}
})

test('scoped register paging full counts filters original history and internal scrolling remain usable on short phones',async({page,browser})=>{
 const a=await checklistActors(page,browser)
 try{const ids:string[]=[];for(let i=0;i<13;i++)ids.push(await apiChecklist(a.owner,'PRIVATE_CHK paged supplied request '+String(i).padStart(2,'0')));await checklistDesk(a.owner);await a.owner.getByRole('textbox',{name:'Search checklists',exact:true}).fill('PRIVATE_CHK paged supplied request');await expect(a.owner.locator('.checklist-card')).toHaveCount(12);const full=await checklistGet<ChecklistPage>(a.owner,'/api/move-checklists');await a.owner.getByRole('button',{name:'Next checklists page',exact:true}).click();await expect(a.owner.locator('.checklist-card')).toHaveCount(1);await expect(a.owner.locator('.checklist-attention strong').nth(0)).toHaveText(String(full.counts.checking));await a.owner.setViewportSize({width:320,height:440});await a.owner.locator('.checklist-card').scrollIntoViewIfNeeded();await checklistCapture(a.owner,'scoped-page-two-320-440');await a.owner.locator('.checklist-card').click();await a.owner.getByRole('button',{name:'Close checklist details',exact:true}).click();await expect(a.owner.getByRole('textbox',{name:'Search checklists',exact:true})).toHaveValue('PRIVATE_CHK paged supplied request');await expect(a.owner.locator('.checklist-card')).toHaveCount(1)
 const retained=ids[0];for(let i=1;i<25;i++)await apiChecklistAction(a.owner,retained,'REVISE',{effective_date:'2026-10-15',note:'PRIVATE_CHK paged supplied request retained history '+i});await openChecklist(a.owner,retained);await a.owner.getByRole('button',{name:'Next checklist history page',exact:true}).click();await a.owner.getByRole('button',{name:'Next checklist history page',exact:true}).click();const history=a.owner.getByRole('region',{name:'Checklist history',exact:true});await expect(history.locator('article')).toHaveCount(1);await expect(history).toContainText('record version 1');await history.getByText('Read retained checklist',{exact:true}).click();await history.getByRole('region',{name:'Retained checklist version 1',exact:true}).scrollIntoViewIfNeeded();await checklistCapture(a.owner,'original-history-page-three-320-440');await checklistWithin(a.owner);expect((await checklistGet<ChecklistDetail>(a.owner,'/api/move-checklists/'+retained+'?event_page=3')).events[0].snapshot.note).toBe('PRIVATE_CHK paged supplied request 00');await a.owner.keyboard.press('Escape');await expect(a.owner.getByRole('dialog')).toHaveCount(0)
 await checklistDesk(page);await page.getByRole('button',{name:'Prepare a checklist',exact:true}).click();await page.setViewportSize({width:320,height:440});await page.getByRole('combobox',{name:'Checklist review type',exact:true}).click();await page.getByRole('option',{name:'Move-out review',exact:true}).hover();await checklistCapture(page,'staff-proposal-type-menu-320-440');await checklistWithin(page);await page.keyboard.press('Escape');await chooseOption(page,'Checklist home','A-101');await page.getByRole('combobox',{name:'Checklist person',exact:true}).click();await checklistCapture(page,'staff-current-person-menu-320-440');await checklistWithin(page);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Close checklist proposal',exact:true}).click();await expect(page.getByRole('button',{name:'Prepare a checklist',exact:true})).toBeFocused()
 }finally{await a.close()}
})
