import { expect } from '@playwright/test'
import type { Browser, Page } from '@playwright/test'
import { chmodSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { login, chooseOption } from './helpers'
import { financialHeaders } from './maintenance-fixtures'
import type { ChecklistDetail } from '../src/checklists'
import { checkLabels } from '../src/checklists'

export const proposalCheck='I reviewed this exact home, person, date and checklist proposal.'
export const actionCheck='I reviewed this exact checklist, current context and deliberate action.'
export async function checklistGet<T>(page:Page,path:string):Promise<T>{const r=await page.request.get(path);expect(r.status(),await r.text()).toBe(200);return r.json()}
export async function checklistPost(page:Page,path:string,data:Record<string,unknown>){const r=await page.request.post(path,{headers:await financialHeaders(page),data:{...data,operation_key:crypto.randomUUID(),confirmed:true}});expect(r.status(),await r.text()).toBe(200);return r.json() as Promise<{id:string}>}
export async function checklistActors(page:Page,browser:Browser){
 await page.setViewportSize({width:1440,height:1000});await login(page)
 const account=await checklistGet<{version:number;grants:{role:string;state:string}[]}>(page,'/api/admin/accounts/demo-user-committee')
 if(!account.grants.some(x=>x.role==='ADMINISTRATOR'&&x.state==='ACTIVE')){const r=await page.request.post('/api/admin/accounts/demo-user-committee/roles',{headers:await financialHeaders(page),data:{version:account.version,confirmed:true,reason:'Fictional separate registry reviewer for isolated checklist evaluations.',role:'ADMINISTRATOR',term_days:30}});expect(r.status(),await r.text()).toBe(201)}
 const contexts=await Promise.all([0,1,2].map(()=>browser.newContext({baseURL:new URL(page.url()).origin}))),reviewer=await contexts[0].newPage(),owner=await contexts[1].newPage(),tenant=await contexts[2].newPage()
 await login(reviewer,'Committee');await login(owner,'Owner');await login(tenant,'Tenant')
 return{reviewer,owner,tenant,close:async()=>{await Promise.all(contexts.map(context=>context.close()))}}
}
export async function checklistDesk(page:Page){await page.goto('/#homes?panel=checklists');await page.reload();await expect(page.getByRole('heading',{name:/The checklist desk\.|Your requests, thoughtfully kept\./})).toBeVisible()}
export async function openChecklist(page:Page,id:string){await page.goto('/#homes?panel=checklists&checklist='+encodeURIComponent(id));await page.reload();await expect(page.getByRole('region',{name:'Checklist checks',exact:true})).toBeVisible()}
export async function apiChecklist(page:Page,note:string,home='demo-flat-A-101',person='demo-owner-A-101',kind='MOVE_IN'){return(await checklistPost(page,'/api/move-checklists',{version:0,flat_id:home,resident_id:person,kind,effective_date:'2026-10-15',note,reason:'PRIVATE_CHK deliberate supplied request for careful registry review.'})).id}
export async function apiChecklistAction(page:Page,id:string,action:string,fields:Record<string,unknown>={}){const d=await checklistGet<ChecklistDetail>(page,'/api/move-checklists/'+id);return checklistPost(page,'/api/move-checklists/'+id+'/actions',{version:d.version,action,reason:'PRIVATE_CHK deliberately reviewed this exact current action.',...(['CHECK','READY','APPROVED'].includes(action)?{source_key:d.source.key}:{}),...fields})}
export async function apiChecklistChecks(page:Page,id:string){for(const kind of Object.keys(checkLabels))await apiChecklistAction(page,id,'CHECK',{check_kind:kind,check_state:['DOCUMENTS','HANDOVER'].includes(kind)?'NOT_APPLICABLE':'CHECKED',reference:'PRIVATE_CHK supplied '+kind+' evidence or explained absence.'})}
export async function readyChecklist(page:Page,id:string){await apiChecklistChecks(page,id);await apiChecklistAction(page,id,'READY')}
export async function fillChecklist(page:Page,note:string,staff=false){await chooseOption(page,'Checklist review type','Contact review');await chooseOption(page,'Checklist home','A-101');if(staff)await chooseOption(page,'Checklist person','Demo Owner A-101');else await expect(page.locator('.checklist-own-person')).toContainText('Demo Owner A-101');await page.getByLabel('Checklist supplied date',{exact:true}).fill('2026-10-15');await page.getByRole('textbox',{name:'Checklist explanation',exact:true}).fill(note);await page.getByRole('textbox',{name:'Checklist proposal reason',exact:true}).fill('PRIVATE_CHK supplied exact date and details for separate review.');await page.getByRole('button',{name:'Preview checklist proposal',exact:true}).click();await expect(page.getByRole('region',{name:'Exact proposed checklist',exact:true})).toContainText(note)}
export async function submitChecklistUI(page:Page){await page.getByRole('checkbox',{name:proposalCheck,exact:true}).check();const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/move-checklists'&&r.request().method()==='POST');await page.getByRole('button',{name:'Submit for checks',exact:true}).click();const r=await response;expect(r.status(),await r.text()).toBe(200);const id=(await r.json()).id as string;await expect(page.getByRole('region',{name:'Checklist checks',exact:true})).toBeVisible();return id}
export async function finishChecklistAction(page:Page,id:string,label:string,reason='PRIVATE_CHK independently checked the exact current context and proposed effect.'){await page.getByRole('textbox',{name:'Checklist action reason',exact:true}).fill(reason);await page.getByRole('checkbox',{name:actionCheck,exact:true}).check();const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/move-checklists/'+id+'/actions'&&r.request().method()==='POST');await page.getByRole('button',{name:label,exact:true}).click();expect((await response).status()).toBe(200);await expect(page.getByRole('button',{name:'Close checklist action',exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'Checklist checks',exact:true})).toBeVisible()}
export async function checkDetailUI(page:Page,id:string,kind:string){await page.getByRole('button',{name:'Review '+checkLabels[kind],exact:true}).click();await expect(page.getByRole('textbox',{name:'Checklist check reference',exact:true})).toBeVisible();if(['DOCUMENTS','HANDOVER'].includes(kind))await chooseOption(page,'Checklist check outcome','Not applicable, with an explanation');await page.getByRole('textbox',{name:'Checklist check reference',exact:true}).fill('PRIVATE_CHK supplied '+kind+' evidence or reviewed explained absence.');await finishChecklistAction(page,id,'Record this check')}
export async function checklistCapture(page:Page,name:string){if(process.env.SOCIETY_CAPTURE_UI!=='1')return;await page.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().filter(a=>Number.isFinite(Number(a.effect?.getComputedTiming().endTime))).map(a=>a.finished.catch(()=>{})))});const root=resolve(process.env.SOCIETY_CHECKLIST_CAPTURE_ROOT??'../reports/local/checklists-ui');mkdirSync(root,{recursive:true,mode:0o700});const path=resolve(root,name+'.png');await page.screenshot({path,animations:'disabled'});chmodSync(path,0o600)}
export async function checklistWithin(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);for(const role of ['dialog','listbox'] as const){const loc=page.getByRole(role);if(await loc.count()){const b=await loc.boundingBox();expect(b!.x).toBeGreaterThanOrEqual(0);expect(b!.y).toBeGreaterThanOrEqual(0);expect(b!.x+b!.width).toBeLessThanOrEqual(page.viewportSize()!.width+1);expect(b!.y+b!.height).toBeLessThanOrEqual(page.viewportSize()!.height+1)}}for(const combo of await page.getByRole('combobox').all())if(await combo.isVisible())expect((await combo.boundingBox())!.height).toBeGreaterThanOrEqual(44);for(const confirmation of await page.locator('.checklist-dialog .confirmation').all())if(await confirmation.isVisible()){const geometry=await confirmation.evaluate(e=>{const box=e.querySelector('input')!.getBoundingClientRect(),node=Array.from(e.childNodes).find(n=>n.nodeType===Node.TEXT_NODE&&n.textContent?.trim())!,range=document.createRange();range.selectNodeContents(node);const text=range.getClientRects()[0];return{gap:text.left-box.right,top:Math.abs(text.top-box.top)}});expect(geometry.gap).toBeGreaterThanOrEqual(6);expect(geometry.top).toBeLessThanOrEqual(8)}if(await page.getByRole('dialog').count()){await expect(page.locator('dialog .dialog-close')).toBeInViewport({ratio:1});expect(await page.locator('dialog .dialog-scroll').evaluate(e=>parseFloat(getComputedStyle(e).paddingLeft))).toBeGreaterThanOrEqual(20)}}
