import { test,expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { chmodSync,mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { chooseOption,login,navigate } from './helpers'
import { ensureMaintenanceReviewer,financialHeaders } from './maintenance-fixtures'
import { apiFund,apiFundAction,apiFundReport,apiFundVerify } from './collections-fixtures'
import { careDate } from './upkeep-fixtures'
import { plainPDF } from './document-fixtures'
import { execFileSync } from 'node:child_process'

async function capture(page:Page,name:string){
 if(!process.env.SOCIETY_CAPTURE_UI)return
 await page.evaluate(()=>document.fonts.ready)
 await page.evaluate(async()=>{await Promise.allSettled(document.getAnimations().filter(animation=>animation.effect?.getComputedTiming().iterations!==Infinity).map(animation=>animation.finished))})
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))))
 const modal=await page.getByRole('dialog').count()>0,y=await page.evaluate(()=>window.scrollY)
 if(modal){await expect(page.getByRole('dialog').locator('.dialog-close')).toBeInViewport({ratio:1});await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}))}
 const folder=resolve('../reports/local/collections-review');mkdirSync(folder,{recursive:true,mode:0o700});const path=resolve(folder,name+'.png')
 try{await page.screenshot({path,animations:'allow'});chmodSync(path,0o600)}finally{if(modal)await page.evaluate(y=>window.scrollTo({top:y,behavior:'instant'}),y)}
}
async function within(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);if(await page.getByRole('dialog').count())expect(await page.getByRole('dialog').evaluate(element=>element.scrollWidth<=element.clientWidth)).toBe(true)}
async function fillFund(page:Page,title:string){
 await page.getByRole('button',{name:'Prepare a fund',exact:true}).click();await page.getByRole('textbox',{name:'Fund title',exact:true}).fill(title);await page.getByRole('textbox',{name:'Purpose to share with participants',exact:true}).fill('Fictional shared water services and a garden fund for our community.');await page.getByLabel('Supplied due date',{exact:true}).fill(careDate(5));await page.getByRole('textbox',{name:'Private source / approval reference',exact:true}).fill('PRIVATE supplied garden resolution');await page.getByRole('textbox',{name:'Private supporting note (optional)',exact:true}).fill('PRIVATE internal source note');await chooseOption(page,'Fund participating home 1','Home A-101');await page.getByRole('textbox',{name:'Amount for home 1',exact:true}).fill('1000.00');await page.getByRole('button',{name:'Add a participating home',exact:true}).click();await chooseOption(page,'Fund participating home 2','Home A-102');await page.getByRole('textbox',{name:'Amount for home 2',exact:true}).fill('500.25')
}
async function fundAction(page:Page,label:string){await chooseOption(page,'Fund action',label);await page.getByRole('textbox',{name:'Reason for the fund action',exact:true}).fill('PRIVATE independently checked the supplied resolution and amounts');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:label,exact:true}).click();if(['Decline proposal','Withdraw proposal'].includes(label))await expect(page.getByRole('combobox',{name:'Fund action',exact:true})).toHaveCount(0);else await expect(page.getByRole('combobox',{name:'Fund action',exact:true})).toContainText('Choose an action')}
async function verifyUI(page:Page,identity:string,amount:string){
 await chooseOption(page,'Payment report action','Verify payment');await page.getByRole('textbox',{name:'Private verification source',exact:true}).fill('PRIVATE fictional bank source');await page.getByRole('textbox',{name:'Private payment identity',exact:true}).fill(identity);await page.getByRole('textbox',{name:'Amount to allocate to this fund',exact:true}).fill(amount);await page.getByRole('textbox',{name:'Decision reason',exact:true}).fill('Checked original fictional statement and external payment identity');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Verify received payment',exact:true}).click();await expect(page.getByRole('dialog').getByText('Verified',{exact:true})).toBeVisible()
}

test('fund menus preparation frozen review and keyboard dismissal stay aligned at four widths',async({page})=>{
 test.setTimeout(60000);await login(page);await navigate(page,'Collections')
 for(const width of [1440,768,375,320]){
  await page.setViewportSize({width,height:900});await expect(page.getByRole('button',{name:'Prepare a fund',exact:true})).toBeEnabled();await within(page);await capture(page,'funds-empty-'+width)
  const state=page.getByRole('combobox',{name:'Filter funds by state',exact:true});await state.click();await page.getByRole('option',{name:'Closed',exact:true}).hover();await capture(page,'fund-state-menu-'+width);await page.keyboard.press('Escape');await expect(state).toBeFocused();await state.click();await expect(page.getByRole('option',{name:'All funds',exact:true})).toBeFocused();await page.keyboard.press('End');await expect(page.getByRole('option',{name:'Withdrawn',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(state).toContainText('Withdrawn');await page.getByRole('button',{name:'Clear',exact:true}).click()
  await fillFund(page,'A shared garden '+width);await page.getByRole('combobox',{name:'Contribution type',exact:true}).click();await page.getByRole('option',{name:'Voluntary contributions',exact:true}).hover();await capture(page,'contribution-type-menu-'+width);await page.keyboard.press('Escape');await chooseOption(page,'Contribution type','Voluntary contributions');await expect(page.getByRole('textbox',{name:'Amount for home 1',exact:true})).toHaveCount(0);await chooseOption(page,'Contribution type','Fixed supplied amounts');await expect(page.getByRole('textbox',{name:'Amount for home 1',exact:true})).toHaveValue('1000.00');await page.getByRole('button',{name:'Review this fund',exact:true}).click();await expect(page.getByRole('heading',{name:'A shared garden '+width,exact:true})).toBeFocused();await expect(page.getByRole('dialog').locator('.maintenance-form-total strong')).toHaveText('₹1,500.25');await within(page);await capture(page,'fund-proposal-review-'+width);await page.getByRole('button',{name:'Edit the proposal',exact:true}).click();await expect(page.getByRole('textbox',{name:'Fund title',exact:true})).toHaveValue('A shared garden '+width);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Prepare a fund',exact:true})).toBeFocused()
 }
 const tabs=page.getByRole('tab',{name:'Funds',exact:true});await tabs.focus();await page.keyboard.press('ArrowRight');await expect(page.getByRole('tab',{name:'Payment reports',exact:true})).toBeFocused();await expect(page.getByRole('tab',{name:'Payment reports',exact:true})).toHaveAttribute('aria-selected','true');await page.keyboard.press('End');await expect(page.getByRole('tab',{name:'Exemptions',exact:true})).toBeFocused();await page.keyboard.press('Home');await expect(tabs).toBeFocused()
})

test('partial and excess payments keep same-home credit while voluntary assignment and corrections preserve original receipts',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page);const context=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await context.newPage();await login(reviewer,'Committee');const ownerContext=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await ownerContext.newPage();await login(owner,'Owner');const id=await apiFund(page,'Partial excess fund '+Date.now());await apiFundAction(reviewer,id,'PUBLISHED');const first=await apiFundReport(owner,id,'400.00','PART-'+id);const original=await apiFundVerify(page,first,'PART-'+id,'400.00');const second=await apiFundReport(owner,id,'1200.00','EXCESS-'+id);await page.goto('/#collections?report='+second);await verifyUI(page,'EXCESS-'+id,'600.00');const excess=await(await page.request.get('/api/payment-reports/'+second)).json();let fund=await(await page.request.get('/api/collections/'+id)).json();expect(fund.outstanding_paise).toBe(50025);expect(fund.lines.map((line:{status:string})=>line.status)).toEqual(['PAID','UNPAID']);expect((await(await page.request.get('/api/statements/demo-flat-A-101')).json()).credits.find((entry:{id:string})=>entry.id===excess.entry_id).remaining_paise).toBe(60000)
 const voluntary=await apiFund(page,'Voluntary shared purpose '+Date.now(),{contribution_type:'VOLUNTARY',target:'2000.00',lines:[{flat_id:'demo-flat-A-101',amount:''},{flat_id:'demo-flat-A-102',amount:''}]});await apiFundAction(reviewer,voluntary,'PUBLISHED');await page.goto('/#collections?campaign='+voluntary);await page.getByRole('dialog').locator('.fund-line').filter({hasText:'Home A-101'}).getByRole('button',{name:'Use confirmed receipt credit',exact:true}).click();await chooseOption(page,'Voluntary contribution receipt',excess.receipt+' · available ₹600.00');await page.getByRole('textbox',{name:'Amount for this voluntary fund',exact:true}).fill('500.00');await page.getByRole('textbox',{name:'Purpose assignment reason',exact:true}).fill('PRIVATE supplied purpose assigned from this confirmed receipt');await page.getByRole('button',{name:'Review purpose assignment',exact:true}).click();await page.setViewportSize({width:320,height:900});await within(page);await capture(page,'voluntary-credit-review-320');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Confirm purpose assignment',exact:true}).click();await expect(page.getByRole('tab',{name:'Voluntary history',exact:true})).toHaveAttribute('aria-selected','true');const contribution=page.getByRole('button',{name:'Open voluntary assignment A-101 '+(await(await page.request.get('/api/collections/'+voluntary)).json()).title,exact:true});await expect(contribution).toBeVisible();expect((await(await page.request.get('/api/collections/'+voluntary)).json()).voluntary_paise).toBe(50000);expect((await(await page.request.get('/api/collections/'+voluntary)).json()).outstanding_paise).toBe(0);await contribution.click();await capture(page,'voluntary-assignment-details-320');await page.getByRole('button',{name:'Correct purpose assignment',exact:true}).click();await page.getByRole('textbox',{name:'Purpose correction reason',exact:true}).fill('Corrected fictional purpose assignment while retaining the original payment');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Confirm purpose correction',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect((await(await page.request.get('/api/collections/'+voluntary)).json()).voluntary_paise).toBe(0);await contribution.click();await expect(page.getByRole('dialog').getByText('Assignment corrected',{exact:true})).toBeVisible();await capture(page,'corrected-voluntary-history-320');await page.getByRole('button',{name:'Close contribution details',exact:true}).click()
 await page.goto('/#entries?entry='+original.entry_id);await page.getByRole('button',{name:'Correct this entry',exact:true}).click();await page.getByRole('textbox',{name:'Reason for reversal',exact:true}).fill('Supplied fictional original receipt correction');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Confirm reversal',exact:true}).click();await expect(page.getByRole('dialog').getByText('Reversed · original preserved',{exact:true})).toBeVisible();fund=await(await page.request.get('/api/collections/'+id)).json();expect(fund.outstanding_paise).toBe(90025);expect((await(await page.request.get('/api/payment-reports/'+first)).json()).receipt).toBe(original.receipt);expect((await(await page.request.get('/api/payment-reports/'+first)).json()).current_state).toBe('CORRECTED');await capture(page,'reversed-original-receipt-320');await context.close();await ownerContext.close()
})

test('partial and full exemption proposals require another reviewer and release old charge links without rewriting receipts',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page);const context=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await context.newPage();await login(reviewer,'Committee');const ownerContext=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await ownerContext.newPage();await login(owner,'Owner');const id=await apiFund(page,'Separate exemptions '+Date.now());await apiFundAction(reviewer,id,'PUBLISHED');const report=await apiFundReport(owner,id,'400.00','WAIVER-'+id),receipt=await apiFundVerify(page,report,'WAIVER-'+id,'400.00')
 for(const [amount,expected]of[['300.00',120025],['700.00',50025]] as const){await page.goto('/#collections?campaign='+id);await page.getByRole('dialog').locator('.fund-line').filter({hasText:'Home A-101'}).getByRole('button',{name:'Propose an exemption',exact:true}).click();await page.getByRole('textbox',{name:'Supplied exemption amount',exact:true}).fill(amount);await page.getByRole('textbox',{name:'Private exemption approval reference',exact:true}).fill('PRIVATE supplied exception resolution');await page.getByRole('textbox',{name:'Private exemption reason',exact:true}).fill('PRIVATE reviewed supplied exception for this fictional home');await page.getByRole('button',{name:'Review exemption proposal',exact:true}).click();await page.setViewportSize({width:320,height:900});await within(page);await capture(page,'exemption-proposal-'+amount);await page.getByRole('dialog').getByRole('checkbox').check();const save=page.waitForResponse(response=>response.url().endsWith('/api/fund-waivers')&&response.request().method()==='POST');await page.getByRole('button',{name:'Submit exemption for separate review',exact:true}).click();const waiver=(await(await save).json()).id;await page.getByRole('combobox',{name:'Exemption action',exact:true}).click();await expect(page.getByRole('option',{name:'Approve supplied exemption',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');expect((await owner.request.get('/api/fund-waivers/'+waiver)).status()).toBe(403);await reviewer.goto('/#collections?waiver='+waiver);await chooseOption(reviewer,'Exemption action','Approve supplied exemption');await reviewer.getByRole('textbox',{name:'Exemption decision reason',exact:true}).fill('Independently reviewed the supplied exception and current charge');await reviewer.getByRole('dialog').getByRole('checkbox').check();await capture(reviewer,'exemption-separate-review-'+amount);await reviewer.getByRole('button',{name:'Approve supplied exemption',exact:true}).click();await expect(reviewer.getByRole('dialog').getByText('Approved',{exact:true})).toBeVisible();expect((await(await page.request.get('/api/collections/'+id)).json()).outstanding_paise).toBe(expected);expect((await(await page.request.get('/api/payment-reports/'+report)).json()).receipt).toBe(receipt.receipt)}
 const fund=await(await page.request.get('/api/collections/'+id)).json();expect(fund.lines[0].status).toBe('EXEMPT');expect(fund.waived_paise).toBe(100000);expect(fund.allocated_paise).toBe(0);const statement=await(await page.request.get('/api/statements/demo-flat-A-101')).json();expect(statement.credits.find((entry:{id:string})=>entry.id===receipt.entry_id).remaining_paise).toBe(40000);await page.getByRole('button',{name:'Close exemption details',exact:true}).click();await page.getByRole('tab',{name:'Exemptions',exact:true}).click();await within(page);await capture(page,'exemption-history-320');await context.close();await ownerContext.close()
})

test('own evidence upload restores the payment form and remains pending while information requests can be revised or withdrawn',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page);const reviewContext=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await reviewContext.newPage();await login(reviewer,'Committee');const id=await apiFund(page,'Evidence and revision '+Date.now());await apiFundAction(reviewer,id,'PUBLISHED');const context=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await context.newPage();await login(owner,'Owner');await owner.goto('/#collections?campaign='+id);await owner.getByRole('dialog').locator('.fund-line').filter({hasText:'Home A-101'}).getByRole('button',{name:'Report money already paid',exact:true}).click();await owner.getByRole('textbox',{name:'Already-paid amount',exact:true}).fill('25.00');await owner.getByRole('textbox',{name:'External payment reference',exact:true}).fill('EVIDENCE-'+id);await owner.getByRole('button',{name:'Attach payment evidence',exact:true}).click();await expect(owner.getByRole('combobox',{name:'Document category',exact:true})).toHaveCount(0);await owner.getByLabel('Document file',{exact:true}).setInputFiles({name:'fictional-payment.pdf',mimeType:'application/pdf',buffer:plainPDF()});await owner.getByRole('button',{name:'Upload for review',exact:true}).click();await expect(owner.getByRole('textbox',{name:'Already-paid amount',exact:true})).toHaveValue('25.00');await expect(owner.getByRole('button',{name:'Review payment report',exact:true})).toBeEnabled();await owner.setViewportSize({width:375,height:900});await within(owner);await capture(owner,'validated-report-evidence-375');await owner.getByRole('button',{name:'Review payment report',exact:true}).click();await owner.getByRole('dialog').getByRole('checkbox').check();const saved=owner.waitForResponse(response=>response.url().endsWith('/api/payment-reports')&&response.request().method()==='POST');await owner.getByRole('button',{name:'Send payment report',exact:true}).click();const report=(await(await saved).json()).id;await expect(owner.getByRole('link',{name:'Download payment evidence',exact:true})).toBeVisible();const item=await(await owner.request.get('/api/payment-reports/'+report)).json();const original=await page.request.get('/api/payment-reports/'+report+'/evidence');expect(original.status()).toBe(200);expect(original.headers()['cache-control']).toBe('no-store');expect(original.headers()['content-disposition']).toContain('attachment');expect(await original.body()).toEqual(plainPDF());expect((await(await owner.request.get('/api/documents/'+item.evidence_id)).json()).review_state).toBe('PENDING')
 await page.goto('/#collections?report='+report);await chooseOption(page,'Payment report action','Ask for more information');await page.getByRole('textbox',{name:'Decision reason',exact:true}).fill('Please supply the original fictional source line and payment date');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Ask for more information',exact:true}).click();await expect(page.getByRole('dialog').getByText('More information needed',{exact:true})).toBeVisible();await owner.goto('/#collections?report='+report);await owner.getByRole('button',{name:'Refresh report',exact:true}).click();await owner.getByRole('button',{name:'Revise this report',exact:true}).click();await owner.getByRole('textbox',{name:'Supporting comment (optional)',exact:true}).fill('Original fictional source line supplied for separate verification');await owner.getByRole('button',{name:'Review payment report',exact:true}).click();await owner.getByRole('dialog').getByRole('checkbox').check();await owner.getByRole('button',{name:'Send revised payment report',exact:true}).click();await expect(owner.getByRole('dialog').getByText('Awaiting verification',{exact:true})).toBeVisible();await chooseOption(owner,'Payment report action','Withdraw my report');await owner.getByRole('textbox',{name:'Decision reason',exact:true}).fill('Withdrawn this fictional unconfirmed report with no receipt issued');await owner.getByRole('dialog').getByRole('checkbox').check();await owner.getByRole('button',{name:'Withdraw my report',exact:true}).click();await expect(owner.getByRole('dialog').getByText('Withdrawn',{exact:true})).toBeVisible();expect((await(await owner.request.get('/api/payment-reports/'+report)).json()).receipt).toBe('');for(const viewport of [{width:1440,height:900},{width:768,height:1024},{width:375,height:900},{width:320,height:900}]){await owner.setViewportSize(viewport);await owner.locator('.fund-report-tools').scrollIntoViewIfNeeded();await within(owner);const refresh=await owner.getByRole('button',{name:'Refresh report',exact:true}).boundingBox(),download=await owner.getByRole('link',{name:'Download payment evidence',exact:true}).boundingBox();expect(refresh).not.toBeNull();expect(download).not.toBeNull();expect(Math.max(download!.x-refresh!.x-refresh!.width,download!.y-refresh!.y-refresh!.height)).toBeGreaterThanOrEqual(12);await capture(owner,'withdrawn-own-report-'+viewport.width);}await context.close();await reviewContext.close()
})

test('lost fund submission retries one frozen identity and a stale fund action reloads current state before reopening',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page);await navigate(page,'Collections');const title='Retry collection '+Date.now();await fillFund(page,title);await page.getByRole('button',{name:'Review this fund',exact:true}).click();await page.getByRole('dialog').getByRole('checkbox').check();let release!:()=>void,calls=0;const keys:string[]=[];await page.route('**/api/collections',async route=>{if(route.request().method()!=='POST'){await route.continue();return}keys.push(route.request().postDataJSON().operation_key);calls++;if(calls===1){await new Promise<void>(resolve=>{release=resolve});await route.fetch();await route.abort('failed')}else await route.continue()});await page.getByRole('button',{name:'Submit fund for separate review',exact:true}).click();await expect(page.getByRole('button',{name:'Close fund preparation',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await expect.poll(()=>typeof release).toBe('function');await capture(page,'fund-submission-pending');release();await expect(page.getByRole('button',{name:'Retry fund submission',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Edit the proposal',exact:true})).toBeDisabled();await capture(page,'fund-submission-lost-response');await page.getByRole('button',{name:'Retry fund submission',exact:true}).click();await expect(page.getByRole('combobox',{name:'Fund action',exact:true})).toBeVisible();expect(keys.length).toBe(2);expect(keys[0]).toBe(keys[1]);await page.unroute('**/api/collections');const matches=await(await page.request.get('/api/collections?q='+encodeURIComponent(title))).json();expect(matches.total).toBe(1);const id=matches.items[0].id
 const context=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await context.newPage();await login(reviewer,'Committee');await apiFundAction(reviewer,id,'PUBLISHED');await page.goto('/#collections?campaign='+id);await page.getByRole('button',{name:'Refresh fund',exact:true}).click();await chooseOption(page,'Fund action','Close new reports');await page.getByRole('textbox',{name:'Reason for the fund action',exact:true}).fill('Fictional close prepared before the concurrent reviewed close');await page.getByRole('dialog').getByRole('checkbox').check();await apiFundAction(reviewer,id,'CLOSED');await page.getByRole('button',{name:'Close new reports',exact:true}).click();await expect(page.getByRole('alert')).toContainText('changed');await capture(page,'fund-action-stale');await page.getByRole('button',{name:'Reload current record',exact:true}).click();await expect(page.getByRole('dialog').getByText('Closed',{exact:true})).toBeVisible();await fundAction(page,'Reopen new reports');await expect(page.getByRole('dialog').getByText('Open',{exact:true})).toBeVisible();await context.close()
})

test('current financial home removal closes the queried report without exposing another reporter while denied workspaces remain useful',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page);const reviewContext=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await reviewContext.newPage();await login(reviewer,'Committee');const id=await apiFund(page,'Current home privacy '+Date.now());await apiFundAction(reviewer,id,'PUBLISHED');const other=await apiFundReport(reviewer,id,'19.00','OTHER-'+id);const context=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await context.newPage();await login(owner,'Owner');expect((await owner.request.get('/api/payment-reports/'+other)).status()).toBe(404);const own=await apiFundReport(owner,id,'19.00','OWN-'+id);await owner.goto('/#collections?report='+own);await expect(owner.getByRole('dialog').getByText('Awaiting verification',{exact:true})).toBeVisible();const path=process.env.SOCIETY_BROWSER_DB;if(!path||!path.includes('society-browser-'))throw new Error('Disposable collection database required');const scope=(removed:boolean)=>execFileSync('python3',['-c',"import sqlite3,sys;db=sqlite3.connect(sys.argv[1]);db.execute(\"UPDATE flat_memberships SET can_view_finances=? WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101'\",(int(sys.argv[2]),));db.commit()",path,removed?'0':'1'])
 try{scope(true);await owner.evaluate(()=>window.dispatchEvent(new Event('session-recheck')));await expect(owner.getByRole('dialog')).toHaveCount(0);expect((await owner.request.get('/api/payment-reports/'+own)).status()).toBe(404);expect((await(await owner.request.get('/api/collections/'+id)).json()).participants).toBe(1);await owner.setViewportSize({width:320,height:900});await capture(owner,'current-home-report-cleared-320')}finally{scope(false)}
 await context.close();const tenantContext=await browser.newContext({baseURL:new URL(page.url()).origin}),tenant=await tenantContext.newPage();await login(tenant,'Tenant');await expect(tenant.getByRole('link',{name:'Collections',exact:true})).toHaveCount(0);await tenant.goto('/#collections');await expect(tenant.getByRole('heading',{name:'Collections needs financial access.',exact:true})).toBeVisible();await capture(tenant,'financial-access-denied');await tenantContext.close();await reviewContext.close()
})

test('verification choice errors retry locally and a lost confirmation locks fields and returns the one original receipt',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page);const context=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await context.newPage();await login(reviewer,'Committee');const id=await apiFund(page,'Verification recovery '+Date.now());await apiFundAction(reviewer,id,'PUBLISHED');const report=await apiFundReport(reviewer,id,'33.25','LOST-'+id);await page.route('**/api/payment-reports/'+report+'/options',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await page.goto('/#collections?report='+report);await chooseOption(page,'Payment report action','Verify payment');await expect(page.getByRole('dialog').getByRole('button',{name:'Try again',exact:true})).toBeVisible();await capture(page,'verification-choices-error');await page.unroute('**/api/payment-reports/'+report+'/options');await page.getByRole('dialog').getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByRole('textbox',{name:'Private verification source',exact:true})).toBeVisible();await page.getByRole('textbox',{name:'Private verification source',exact:true}).fill('PRIVATE fictional verified statement');await page.getByRole('textbox',{name:'Private payment identity',exact:true}).fill('LOST-'+id);await page.getByRole('textbox',{name:'Amount to allocate to this fund',exact:true}).fill('33.25');await page.getByRole('textbox',{name:'Decision reason',exact:true}).fill('Independently checked this external source before one receipt');await page.getByRole('dialog').getByRole('checkbox').check()
 let release!:()=>void,calls=0;const keys:string[]=[];await page.route('**/api/payment-reports/'+report+'/actions',async route=>{keys.push(route.request().postDataJSON().operation_key);calls++;if(calls===1){await new Promise<void>(resolve=>{release=resolve});await route.fetch();await route.abort('failed')}else await route.continue()});await page.getByRole('button',{name:'Verify received payment',exact:true}).click();await expect(page.getByRole('button',{name:'Close payment report details',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await expect.poll(()=>typeof release).toBe('function');await capture(page,'verification-pending');release();await expect(page.getByRole('button',{name:'Retry report decision',exact:true})).toBeEnabled();await expect(page.getByRole('textbox',{name:'Private payment identity',exact:true})).toBeDisabled();await capture(page,'verification-lost-response');await page.getByRole('button',{name:'Retry report decision',exact:true}).click();await expect(page.getByRole('dialog').getByText('Verified',{exact:true})).toBeVisible();expect(keys.length).toBe(2);expect(keys[0]).toBe(keys[1]);const result=await(await page.request.get('/api/payment-reports/'+report)).json();expect(result.event_total).toBe(2);expect(result.receipt).not.toBe('');expect((await(await page.request.get('/api/collections/'+id)).json()).outstanding_paise).toBe(146700);const denied=await page.request.post('/api/fund-contributions',{headers:await financialHeaders(page),data:{operation_key:crypto.randomUUID(),campaign_id:id,flat_id:'demo-flat-A-102',source_id:result.entry_id,amount:'1.00',reason:'Fictional forbidden cross-home credit assignment',confirmed:true}});expect(denied.status()).not.toBe(200);await context.close()
})

test('fund report and activity pages are bounded and preserve the prepared human decision through history navigation',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page);const context=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await context.newPage();await login(reviewer,'Committee');const prefix='Paged fund '+Date.now(),ids:string[]=[];for(let i=0;i<13;i++)ids.push(await apiFund(page,prefix+' '+String(i).padStart(2,'0')));await navigate(page,'Collections');await page.getByRole('searchbox',{name:'Search funds',exact:true}).fill(prefix);await expect(page.locator('.fund-grid > button')).toHaveCount(12);await page.getByRole('button',{name:'Next funds page',exact:true}).click();await expect(page.locator('.fund-grid > button')).toHaveCount(1);await capture(page,'fund-second-page');await page.getByRole('button',{name:'Previous funds page',exact:true}).click();await expect(page.locator('.fund-grid > button')).toHaveCount(12)
 await apiFundAction(reviewer,ids[0],'PUBLISHED');for(let i=0;i<21;i++)await apiFundAction(page,ids[0],i%2?'REOPEN':'CLOSED');await page.goto('/#collections?campaign='+ids[0]);await expect(page.getByRole('region',{name:'Fund activity',exact:true}).getByRole('listitem')).toHaveCount(20);await chooseOption(page,'Fund action','Reopen new reports');await page.getByRole('textbox',{name:'Reason for the fund action',exact:true}).fill('PRIVATE human reason preserved through bounded history pages');await page.getByRole('button',{name:'Next fund activity page',exact:true}).click();await expect(page.getByRole('region',{name:'Fund activity',exact:true}).getByRole('listitem')).toHaveCount(3);await expect(page.getByRole('textbox',{name:'Reason for the fund action',exact:true})).toHaveValue('PRIVATE human reason preserved through bounded history pages');await page.setViewportSize({width:320,height:900});await within(page);await capture(page,'fund-history-second-page-320');await page.getByRole('button',{name:'Close fund details',exact:true}).click();await apiFundAction(page,ids[0],'REOPEN');for(let i=0;i<13;i++)await apiFundReport(reviewer,ids[0],'5.00','PAGE-'+i+'-'+ids[0]);await page.getByRole('tab',{name:'Payment reports',exact:true}).click();await page.getByRole('searchbox',{name:'Search payment reports',exact:true}).fill(prefix+' 00');await expect(page.locator('.fund-report-list > button')).toHaveCount(12);await page.getByRole('button',{name:'Next payment reports page',exact:true}).click();await expect(page.locator('.fund-report-list > button')).toHaveCount(1);await capture(page,'payment-reports-second-page-320');await context.close()
})

test('a separately published supplied fund supports own reported money verification original receipt and duplicates',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page);const context=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await context.newPage();await login(reviewer,'Committee');const ownerContext=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await ownerContext.newPage();await login(owner,'Owner');const title='Water reserve '+Date.now();await navigate(page,'Collections');await fillFund(page,title);await page.getByRole('button',{name:'Review this fund',exact:true}).click();await page.getByRole('dialog').getByRole('checkbox').check();const submitted=page.waitForResponse(response=>response.url().endsWith('/api/collections')&&response.request().method()==='POST');await page.getByRole('button',{name:'Submit fund for separate review',exact:true}).click();const id=(await(await submitted).json()).id
 await expect(page.getByRole('dialog').getByText('A different treasury reviewer must publish your proposal.',{exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Fund action',exact:true}).click();await expect(page.getByRole('option',{name:'Publish fund',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');expect((await owner.request.get('/api/collections/'+id)).status()).toBe(404)
 await reviewer.goto('/#collections?campaign='+id);await fundAction(reviewer,'Publish fund');const fund=await(await page.request.get('/api/collections/'+id)).json();expect(fund.outstanding_paise).toBe(150025);expect(fund.overdue_paise).toBe(0);expect(fund.lines.map((line:{status:string})=>line.status)).toEqual(['UNPAID','UNPAID']);await capture(reviewer,'published-fixed-fund')
 await owner.goto('/#collections?campaign='+id);await expect(owner.getByRole('dialog').getByText('PRIVATE supplied garden resolution',{exact:true})).toHaveCount(0);await owner.getByRole('dialog').locator('.fund-line').filter({hasText:'Home A-101'}).getByRole('button',{name:'Report money already paid',exact:true}).click();await owner.getByRole('textbox',{name:'Already-paid amount',exact:true}).fill('400.00');await owner.getByLabel('Payment date',{exact:true}).fill('2026-01-01');await chooseOption(owner,'Reported payment method','Bank transfer');await owner.getByRole('textbox',{name:'External payment reference',exact:true}).fill('FUND-CORE-'+id);await owner.getByRole('textbox',{name:'Supporting comment (optional)',exact:true}).fill('PRIVATE reported external transfer detail');await owner.getByRole('button',{name:'Review payment report',exact:true}).click();await capture(owner,'own-payment-report-review');await owner.getByRole('dialog').getByRole('checkbox').check();const reportSaved=owner.waitForResponse(response=>response.url().endsWith('/api/payment-reports')&&response.request().method()==='POST');await owner.getByRole('button',{name:'Send payment report',exact:true}).click();const report=(await(await reportSaved).json()).id;await expect(owner.getByRole('dialog').getByText('Awaiting verification',{exact:true})).toBeVisible();expect((await(await page.request.get('/api/collections/'+id)).json()).outstanding_paise).toBe(150025);expect((await(await owner.request.get('/api/payment-reports/'+report)).json()).receipt).toBe('')
 await page.goto('/#collections?report='+report);await verifyUI(page,'BANK-CORE-'+id,'400.00');const original=await(await page.request.get('/api/payment-reports/'+report)).json();expect(original.state).toBe('CONFIRMED');expect(original.receipt).not.toBe('');expect((await(await page.request.get('/api/collections/'+id)).json()).outstanding_paise).toBe(110025);await capture(page,'verified-original-receipt');await page.getByRole('link',{name:'Open original receipt',exact:true}).click();await expect(page.getByRole('dialog').getByText(original.receipt,{exact:true})).toBeVisible();await page.getByRole('button',{name:'Close entry details',exact:true}).click()
 const duplicate=await apiFundReport(owner,id,'400.00','FUND-CORE-'+id);await page.goto('/#collections?report='+duplicate);await chooseOption(page,'Payment report action','Verify payment');await expect(page.getByRole('textbox',{name:'Private verification source',exact:true})).toHaveValue('PRIVATE fictional bank source');await expect(page.getByRole('textbox',{name:'Private payment identity',exact:true})).toHaveValue('BANK-CORE-'+id);await expect(page.getByRole('textbox',{name:'Private payment identity',exact:true})).toHaveAttribute('readonly','');await page.getByRole('textbox',{name:'Decision reason',exact:true}).fill('Checked this second report against the original verified source');await page.getByRole('dialog').getByRole('checkbox').check();await capture(page,'duplicate-payment-verification');await page.getByRole('button',{name:'Verify received payment',exact:true}).click();await expect(page.getByRole('dialog').getByText('Already recorded',{exact:true})).toBeVisible();const repeated=await(await page.request.get('/api/payment-reports/'+duplicate)).json();expect(repeated.entry_id).toBe(original.entry_id);expect(repeated.receipt).toBe(original.receipt);expect((await(await page.request.get('/api/collections/'+id)).json()).outstanding_paise).toBe(110025);await capture(page,'duplicate-links-original')
 await context.close();await ownerContext.close()
})

test('an existing manual receipt loads after a delay and verification choices remain usable at four widths without another receipt',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page)
 const context=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await context.newPage();await login(reviewer,'Committee')
 const id=await apiFund(page,'Existing original receipt '+Date.now());await apiFundAction(reviewer,id,'PUBLISHED')
 const reference='MANUAL-'+id,headers=await financialHeaders(page)
 const created=await page.request.post('/api/entries',{headers,data:{operation_key:crypto.randomUUID(),flat_id:'demo-flat-A-101',kind:'RECEIVED',amount:'22.00',date:'2026-01-01',description:'Manually recorded fictional payment before its resident report',payer:'Fictional payer',method:'BANK_TRANSFER',reference}});expect(created.status()).toBe(200)
 const entry=(await created.json()).id;expect((await page.request.post('/api/entries/'+entry+'/post',{headers,data:{operation_key:crypto.randomUUID(),confirmed:true,reason:''}})).status()).toBe(200)
 const original=await(await page.request.get('/api/entries/'+entry)).json(),report=await apiFundReport(reviewer,id,'22.00',reference)
 let release!:()=>void;const waiting=new Promise<void>(resolve=>{release=resolve})
 await page.route('**/api/payment-reports/'+report+'/options',async route=>{await waiting;await route.continue()})
 await page.goto('/#collections?report='+report);await chooseOption(page,'Payment report action','Verify payment');await expect(page.getByRole('button',{name:'Verify received payment',exact:true})).toBeDisabled();await capture(page,'manual-receipt-options-pending');release()
 await expect(page.getByRole('combobox',{name:'Receipt handling',exact:true})).toContainText('Existing receipt')
 await expect(page.getByRole('combobox',{name:'Compatible original receipt',exact:true})).toContainText(original.receipt_number)
 await page.getByRole('textbox',{name:'Decision reason',exact:true}).fill('Preserve this original manual receipt after checking the external source')
 for(const width of [1440,768,375,320]){
  await page.setViewportSize({width,height:900});const menu=page.getByRole('combobox',{name:'Receipt handling',exact:true});expect(await menu.evaluate(element=>{const label=element.querySelector('span');return !!label&&label.scrollWidth<=label.clientWidth})).toBe(true);await menu.click();await expect(page.getByRole('option',{name:'Existing receipt',exact:true})).toHaveAttribute('aria-selected','true');await page.getByRole('option',{name:'New receipt',exact:true}).hover();await expect(page.getByRole('listbox')).toBeInViewport({ratio:1});await within(page);await capture(page,'manual-receipt-handling-menu-'+width);await page.keyboard.press('Escape');await expect(menu).toBeFocused();await expect(page.getByRole('textbox',{name:'Decision reason',exact:true})).toHaveValue('Preserve this original manual receipt after checking the external source')
  await chooseOption(page,'Receipt handling','New receipt');await expect(page.getByRole('combobox',{name:'Compatible original receipt',exact:true})).toHaveCount(0);await chooseOption(page,'Receipt handling','Existing receipt')
 }
 await page.getByRole('textbox',{name:'Private verification source',exact:true}).fill('Fictional original cashbook review');await page.getByRole('textbox',{name:'Private payment identity',exact:true}).fill('MANUAL-IDENTITY-'+id);await page.getByRole('textbox',{name:'Amount to allocate to this fund',exact:true}).fill('0.00');await page.getByRole('dialog').getByRole('checkbox').check();await capture(page,'manual-receipt-zero-allocation-review-320');await page.getByRole('button',{name:'Verify received payment',exact:true}).click();await expect(page.getByRole('dialog').getByText('Verified',{exact:true})).toBeVisible()
 const result=await(await page.request.get('/api/payment-reports/'+report)).json();expect(result.entry_id).toBe(entry);expect(result.receipt).toBe(original.receipt_number);expect((await(await page.request.get('/api/collections/'+id)).json()).outstanding_paise).toBe(150025);expect((await(await page.request.get('/api/statements/demo-flat-A-101')).json()).credits.find((item:{id:string})=>item.id===entry).remaining_paise).toBe(2200);await capture(page,'manual-receipt-linked-zero-allocation-320');await context.close()
})

test('bulk participating homes preview supplied amounts and a separately published voluntary proposal records purpose without debt',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page);await navigate(page,'Collections');await page.getByRole('button',{name:'Prepare a fund',exact:true}).click();await page.getByRole('button',{name:'Include all homes',exact:true}).click();await expect(page.locator('.maintenance-participant')).toHaveCount(118);await page.getByRole('textbox',{name:'Supplied amount for selected homes',exact:true}).fill('2.01');await page.getByRole('button',{name:'Apply supplied amount',exact:true}).click();await expect(page.locator('.maintenance-form-total strong')).toHaveText('₹237.18');await page.getByRole('button',{name:'Remove fund home 118',exact:true}).click();await expect(page.locator('.maintenance-participant')).toHaveCount(117);await expect(page.locator('.maintenance-form-total strong')).toHaveText('₹235.17');await page.setViewportSize({width:375,height:900});await within(page);await capture(page,'bulk-fund-preparation-375');await page.getByRole('button',{name:'Close fund preparation',exact:true}).click()
 const title='Voluntary community fund '+Date.now();await fillFund(page,title);await chooseOption(page,'Contribution type','Voluntary contributions');await page.getByRole('textbox',{name:'Optional collection target',exact:true}).fill('2000.00');await page.getByRole('button',{name:'Review this fund',exact:true}).click();await expect(page.locator('.maintenance-form-total strong')).toHaveText('No charge');await capture(page,'voluntary-fund-proposal-375');await page.getByRole('dialog').getByRole('checkbox').check();const saved=page.waitForResponse(response=>response.url().endsWith('/api/collections')&&response.request().method()==='POST');await page.getByRole('button',{name:'Submit fund for separate review',exact:true}).click();const id=(await(await saved).json()).id
 const context=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await context.newPage();await login(reviewer,'Committee');await reviewer.goto('/#collections?campaign='+id);await fundAction(reviewer,'Publish fund');const report=await apiFundReport(reviewer,id,'25.00','VOLUNTARY-'+id);await page.goto('/#collections?report='+report);await chooseOption(page,'Payment report action','Verify payment');await page.getByRole('textbox',{name:'Private verification source',exact:true}).fill('Fictional supplied bank statement');await page.getByRole('textbox',{name:'Private payment identity',exact:true}).fill('VOLUNTARY-IDENTITY-'+id);await page.getByRole('textbox',{name:'Amount to assign to this voluntary purpose',exact:true}).fill('20.00');await page.getByRole('textbox',{name:'Decision reason',exact:true}).fill('Verified twenty five paid and twenty explicitly assigned to this purpose');await page.getByRole('dialog').getByRole('checkbox').check();await capture(page,'voluntary-verification-review-375');await page.getByRole('button',{name:'Verify received payment',exact:true}).click();await expect(page.getByRole('dialog').getByText('Verified',{exact:true})).toBeVisible()
 const payment=await(await page.request.get('/api/payment-reports/'+report)).json(),fund=await(await page.request.get('/api/collections/'+id)).json();expect(fund.requested_paise).toBe(0);expect(fund.outstanding_paise).toBe(0);expect(fund.overdue_paise).toBe(0);expect(fund.voluntary_paise).toBe(2000);expect(fund.target_paise).toBe(200000);expect(fund.lines.every((line:{entry_id:string})=>line.entry_id==='')).toBe(true);expect((await(await page.request.get('/api/statements/demo-flat-A-101')).json()).credits.find((credit:{id:string})=>credit.id===payment.entry_id).remaining_paise).toBe(500);await page.getByRole('button',{name:'Close payment report details',exact:true}).click();await page.getByRole('tab',{name:'Funds',exact:true}).click();await page.getByRole('searchbox',{name:'Search funds',exact:true}).fill(title);await expect(page.locator('.fund-card-progress-label')).toHaveText('Target ₹2,000.00');await page.getByRole('button',{name:'Open fund '+title,exact:true}).scrollIntoViewIfNeeded();await capture(page,'voluntary-confirmed-card-375');await context.close()
})

test('declined and withdrawn proposals never post while rejected reports can be revised and verified after reports close',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page);const context=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await context.newPage();await login(reviewer,'Committee')
 const declined=await apiFund(page,'Declined supplied proposal '+Date.now());await reviewer.goto('/#collections?campaign='+declined);await fundAction(reviewer,'Decline proposal');expect((await(await page.request.get('/api/collections/'+declined)).json()).lines.every((line:{entry_id:string})=>line.entry_id==='')).toBe(true)
 const withdrawn=await apiFund(page,'Withdrawn supplied proposal '+Date.now());await page.goto('/#collections?campaign='+withdrawn);await fundAction(page,'Withdraw proposal');expect((await(await page.request.get('/api/collections/'+withdrawn)).json()).lines.every((line:{entry_id:string})=>line.entry_id==='')).toBe(true);await capture(page,'withdrawn-fund-proposal')
 const id=await apiFund(page,'Closed fund existing report '+Date.now());await apiFundAction(reviewer,id,'PUBLISHED');const ownerContext=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await ownerContext.newPage();await login(owner,'Owner');const report=await apiFundReport(owner,id,'10.00','REJECTED-'+id);await page.goto('/#collections?report='+report);await chooseOption(page,'Payment report action','Decline verification');await page.getByRole('textbox',{name:'Decision reason',exact:true}).fill('The fictional external statement needs a corrected supporting comment');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Decline verification',exact:true}).click();await expect(page.getByRole('dialog').getByText('Not verified',{exact:true})).toBeVisible();expect((await(await page.request.get('/api/payment-reports/'+report)).json()).receipt).toBe('');expect((await(await page.request.get('/api/collections/'+id)).json()).outstanding_paise).toBe(150025)
 await reviewer.goto('/#collections?campaign='+id);await fundAction(reviewer,'Close new reports');await owner.goto('/#collections?campaign='+id);await expect(owner.getByRole('button',{name:'Report money already paid',exact:true})).toHaveCount(0);await capture(owner,'closed-fund-resident')
 await owner.goto('/#collections?report='+report);await owner.getByRole('button',{name:'Revise this report',exact:true}).click();await owner.getByRole('textbox',{name:'Supporting comment (optional)',exact:true}).fill('Corrected fictional supporting comment with the externally checked payment');await owner.getByRole('button',{name:'Review payment report',exact:true}).click();await owner.getByRole('dialog').getByRole('checkbox').check();await owner.getByRole('button',{name:'Send revised payment report',exact:true}).click();await expect(owner.getByRole('dialog').getByText('Awaiting verification',{exact:true})).toBeVisible();await capture(owner,'rejected-report-revised-after-close');await page.goto('/#collections?report='+report);await page.reload();await verifyUI(page,'REVISED-CLOSED-'+id,'10.00');expect((await(await page.request.get('/api/payment-reports/'+report)).json()).version).toBe(4);expect((await(await page.request.get('/api/collections/'+id)).json()).outstanding_paise).toBe(149025);await capture(page,'existing-report-verified-after-close');await context.close();await ownerContext.close()
})
