import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { chmodSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { login, navigate, chooseOption } from './helpers'
import { ensureMaintenanceReviewer } from './maintenance-fixtures'
import { apiFund, apiFundAction, apiFundReport, apiFundVerify } from './collections-fixtures'

async function capture(page:Page,name:string){
 if(!process.env.SOCIETY_CAPTURE_UI)return
 await page.evaluate(()=>document.fonts.ready);const folder=resolve('../reports/local/collections-review');mkdirSync(folder,{recursive:true,mode:0o700});const path=resolve(folder,name+'.png');await page.screenshot({path,fullPage:!(await page.getByRole('dialog').count()),animations:'disabled'});chmodSync(path,0o600)
}
async function overview(page:Page){if(await page.getByRole('dialog').count()){await expect(page.getByRole('dialog').locator('.dialog-close')).toBeEnabled();await page.getByRole('dialog').locator('.dialog-close').click()}await navigate(page,'Overview');await expect(page.getByRole('button',{name:'Refresh overview',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Refresh overview',exact:true}).click();await expect(page.getByRole('button',{name:'Refresh overview',exact:true})).toBeEnabled()}

test('current fund decisions and own requested information open exact overview records while unavailable totals stay unknown and retry locally',async({page,browser})=>{
 test.setTimeout(60000);await login(page);await ensureMaintenanceReviewer(page)
 const context=await browser.newContext({baseURL:new URL(page.url()).origin}),reviewer=await context.newPage();await login(reviewer,'Committee')
 const title='Overview water reserve '+Date.now(),id=await apiFund(reviewer,title);await overview(page);await expect(page.getByRole('link',{name:'Review a fund proposal: '+title,exact:true})).toBeVisible();await page.getByRole('link',{name:'Review a fund proposal: '+title,exact:true}).click();expect(new URL(page.url()).hash).toBe('#collections?campaign='+id);await expect(page.getByRole('dialog').getByRole('heading',{name:title,exact:true})).toBeVisible();await capture(page,'overview-exact-fund-proposal');await page.getByRole('button',{name:'Close fund details',exact:true}).click()
 await apiFundAction(page,id,'PUBLISHED');const ownerContext=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await ownerContext.newPage();await login(owner,'Owner');const report=await apiFundReport(owner,id,'400.00','OVERVIEW-'+id);await overview(page)
 const panel=page.getByRole('region',{name:'Collections, in view.',exact:true});await expect(panel.locator('.overview-maintenance-amounts strong')).toHaveText(['₹0.00','₹1,500.25','1']);await page.getByRole('link',{name:'Verify a reported payment: '+title,exact:true}).click();expect(new URL(page.url()).hash).toBe('#collections?report='+report);await chooseOption(page,'Payment report action','Ask for more information');await page.getByRole('textbox',{name:'Decision reason',exact:true}).fill('Please supply a corrected external reference before verification');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Ask for more information',exact:true}).click();await overview(owner);await owner.getByRole('link',{name:'Update your payment report: '+title,exact:true}).click();expect(new URL(owner.url()).hash).toBe('#collections?report='+report);await expect(owner.getByRole('button',{name:'Revise this report',exact:true})).toBeVisible();await capture(owner,'overview-exact-own-clarification')
 await owner.getByRole('button',{name:'Revise this report',exact:true}).click();await owner.getByRole('textbox',{name:'External payment reference',exact:true}).fill('OVERVIEW-CORRECTED-'+id);await owner.getByRole('button',{name:'Review payment report',exact:true}).click();await owner.getByRole('dialog').getByRole('checkbox').check();await owner.getByRole('button',{name:'Send revised payment report',exact:true}).click();await expect(owner.getByRole('dialog').getByText('Awaiting verification',{exact:true})).toBeVisible();await apiFundVerify(page,report,'OVERVIEW-VERIFIED-'+id,'400.00');await overview(page);await expect(panel.locator('.overview-maintenance-amounts strong')).toHaveText(['₹400.00','₹1,100.25','0'])
 for(const width of [1440,768,375,320]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const funds=await panel.boundingBox(),care=await page.getByRole('region',{name:'Everyday care, in view.',exact:true}).boundingBox();expect(care!.y-(funds!.y+funds!.height)).toBeGreaterThanOrEqual(16);await capture(page,'collections-overview-'+width)}
 await page.route('**/api/overview/collections',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await page.getByRole('button',{name:'Refresh overview',exact:true}).click();await expect(panel.locator('.overview-maintenance-amounts strong')).toHaveText(['—','—','—']);await expect(page.getByRole('alert').getByText('Collections unavailable',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Maintenance, in view.',exact:true}).locator('.overview-maintenance-amounts strong')).toHaveText(['₹0.00','₹0.00','0']);await capture(page,'collections-overview-source-error-320');await page.unroute('**/api/overview/collections');await page.getByRole('button',{name:'Retry collections',exact:true}).click();await expect(panel.locator('.overview-maintenance-amounts strong')).toHaveText(['₹400.00','₹1,100.25','0'])
 await page.route('**/api/collections?*',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await navigate(page,'Collections');await expect(page.locator('.fund-metrics strong')).toHaveText(['—','—','—','—']);await expect(page.getByRole('heading',{name:'Collections unavailable.',exact:true})).toBeVisible();await capture(page,'collections-list-and-totals-error-320');await page.unroute('**/api/collections?*');await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('button',{name:'Retry totals',exact:true}).click();await expect(page.getByRole('button',{name:'Open fund '+title,exact:true})).toBeVisible();await expect(page.locator('.fund-metrics strong')).toHaveText(['₹400.00','₹1,100.25','₹1,100.25','0'])
 await page.route('**/api/collections/'+id+'?*',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await page.getByRole('button',{name:'Open fund '+title,exact:true}).click();await expect(page.getByRole('heading',{name:'Fund unavailable.',exact:true})).toBeVisible();await expect(page.getByRole('dialog').getByText('PRIVATE supplied society resolution',{exact:true})).toHaveCount(0);await capture(page,'collection-detail-error-320');await page.unroute('**/api/collections/'+id+'?*');await page.getByRole('dialog').getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByRole('dialog').getByRole('heading',{name:title,exact:true})).toBeVisible();await capture(page,'collection-detail-recovered-320');await context.close();await ownerContext.close()
})
