import { expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { financialHeaders } from './maintenance-fixtures'
import { communityLocal } from '../src/community'

export async function communityPost(page:Page,path:string,data:Record<string,unknown>){const r=await page.request.post(path,{headers:await financialHeaders(page),data:{operation_key:crypto.randomUUID(),confirmed:true,...data}});expect(r.status(),await r.text()).toBe(200);return r.json()}
export async function communityDetail(page:Page,id:string,desk=true){const r=await page.request.get('/api/community/'+id+'?desk='+desk);expect(r.status(),await r.text()).toBe(200);return r.json()}
export async function communityProposal(page:Page,title:string,kind='CONTACT',scope='ALL',homeIDs:string[]=[]){const options=await(await page.request.get('/api/community/options')).json();const now=Math.floor(Date.now()/1000);return (await communityPost(page,'/api/community',{kind,action:'PUBLISH',title,body:'Supplied fictional service details deliberately shared with the exact current audience.',service:'WATER',scope,home_ids:homeIDs,area_key:options.area_key,...(kind==='CONTACT'?{phone:'+919000000101',availability:'Weekdays 09:00–17:00, supplied availability',attestation:'PRIVATE_COMMUNITY independently supplied directory permission'}:{start_at:now-3600,estimated_end:now-60}),reason:'PRIVATE_COMMUNITY supplied the exact service information and area'})).id as string}
export async function communityApprove(page:Page,id:string){const x=await communityDetail(page,id);await communityPost(page,'/api/community/'+id+'/decisions',{version:x.version,action:'APPROVED',reason:'PRIVATE_COMMUNITY independently checked the original wording and exact area'})}
export async function openCommunity(page:Page,id:string,desk=true){const target='/#community?service='+id+(desk?'&desk=true':'');if(new URL(target,page.url()).href===page.url())await page.reload();else await page.goto(target);await expect(page.getByRole('dialog').locator('.community-state').first()).toBeVisible()}
export async function communityCapture(page:Page,name:string){if(process.env.SOCIETY_CAPTURE_UI!=='1')return;await page.evaluate(async()=>{await document.fonts.ready;const animations=document.getAnimations().filter(a=>Number.isFinite(Number(a.effect?.getComputedTiming().endTime)));await Promise.all(animations.map(a=>a.finished.catch(()=>{})))});const folder=resolve('../reports/local/community-services-ui');mkdirSync(folder,{recursive:true,mode:0o700});await page.screenshot({path:resolve(folder,name+'.png'),fullPage:false})}
export async function communityWithin(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);const dialog=page.getByRole('dialog');if(await dialog.count()){const b=await dialog.boundingBox();expect(b!.x).toBeGreaterThanOrEqual(0);expect(b!.x+b!.width).toBeLessThanOrEqual(page.viewportSize()!.width+1);expect(b!.height).toBeLessThanOrEqual(page.viewportSize()!.height+1)}if(await page.getByRole('listbox').count()){const b=await page.getByRole('listbox').boundingBox();expect(b!.x).toBeGreaterThanOrEqual(0);expect(b!.x+b!.width).toBeLessThanOrEqual(page.viewportSize()!.width+1);expect(b!.y+b!.height).toBeLessThanOrEqual(page.viewportSize()!.height+1)}}
export const communityNowLocal=()=>communityLocal(Math.floor(Date.now()/1000))
