import { test,expect } from '@playwright/test'
import { chooseOption,login,navigate } from './helpers'
import { messageActors,messagePrivateFixture } from './messages-fixtures'
import { communityApprove,communityCapture,communityDetail,communityNowLocal,communityPost,communityProposal,communityWithin,openCommunity } from './community-fixtures'
import { communityLocal } from '../src/community'

test.setTimeout(90000)
test('service publication opens actual menus at all layouts prepares an exact contact and needs a separate reviewer',async({page,browser})=>{
 const actors=await messageActors(page,browser),ownerContext=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await ownerContext.newPage()
 try{
  await navigate(page,'Community');await expect(page.getByRole('heading',{name:'Good to know. Good to share.'})).toBeVisible();await page.getByRole('link',{name:'Publication desk',exact:true}).click();await expect(page.getByRole('heading',{name:'The publication desk.'})).toBeVisible();await communityCapture(page,'desk-empty-1440');await page.getByRole('button',{name:'Prepare an update',exact:true}).click()
  for(const [width,height] of [[1440,1000],[768,1024],[375,640],[320,640],[320,440]]){await page.setViewportSize({width,height});for(const [name,selected] of [['Update type','Service interruption'],['Service','Water'],['Area to publish','All current homes']]){const menu=page.getByRole('combobox',{name,exact:true});await menu.scrollIntoViewIfNeeded();await menu.click();const option=page.getByRole('option',{name:selected,exact:true});await expect(option).toHaveAttribute('aria-selected','true');await option.hover();await communityCapture(page,`menu-${name.replaceAll(' ','-')}-${width}-${height}`);await communityWithin(page);await page.keyboard.press('Escape');await expect(page.getByRole('listbox')).toHaveCount(0);await expect(menu).toBeFocused()}}
  await chooseOption(page,'Update type','Help contact');await chooseOption(page,'Service','Other services');await page.getByLabel('Update title',{exact:true}).fill('COMMUNITY UI supplied caretaker contact');await page.getByLabel('Information to publish',{exact:true}).fill('Contact the fictional caretaker during the supplied hours for common-area help.');await page.getByLabel('Supplied telephone number',{exact:true}).fill('javascript:broken');await page.getByLabel('Supplied availability',{exact:true}).fill('Weekdays 09:00–17:00, as supplied');await page.getByLabel('Contact permission / authority reference',{exact:true}).fill('PRIVATE_COMMUNITY supplied permission from the fictional contact');await chooseOption(page,'Area to publish','One wing');await page.getByRole('combobox',{name:'Publication wing',exact:true}).click();await page.getByRole('option',{name:'Wing B',exact:true}).hover();await communityCapture(page,'wing-menu-320-440');await page.keyboard.press('End');await expect(page.getByRole('option',{name:'Wing C',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('combobox',{name:'Publication wing',exact:true})).toHaveText('Wing C');await chooseOption(page,'Area to publish','Selected homes');await page.getByRole('checkbox',{name:'A-101',exact:true}).check();await page.getByLabel('Private proposal reason',{exact:true}).fill('PRIVATE_COMMUNITY checked these supplied directory details and current home.');await page.getByRole('button',{name:'Review exact proposal',exact:true}).click();await expect(page.getByRole('alert')).toContainText('international phone number');await communityCapture(page,'phone-validation-320-440');await page.getByLabel('Supplied telephone number',{exact:true}).fill('+91 (90000) 00101');await page.getByRole('button',{name:'Review exact proposal',exact:true}).click();await expect(page.getByRole('region',{name:'Exact proposed service update'})).toContainText('+919000000101');await page.getByRole('region',{name:'Exact proposed service update'}).scrollIntoViewIfNeeded();await communityCapture(page,'exact-contact-review-320-440');await page.getByRole('checkbox',{name:'I checked these exact details, contact authority, times and homes for separate review.',exact:true}).check();await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();await expect(page.getByRole('dialog').locator('.community-state').first()).toHaveText('Awaiting separate review');await expect(page.getByRole('button',{name:'Review proposal',exact:true})).toHaveCount(0);const id=new URLSearchParams(page.url().split('?')[1]).get('service')!;expect((await communityDetail(page,id)).snapshot.homes).toEqual([{id:'demo-flat-A-101',label:'A-101'}])
  await openCommunity(actors.reviewer,id);await actors.reviewer.setViewportSize({width:320,height:440});await actors.reviewer.getByRole('button',{name:'Review proposal',exact:true}).click();await actors.reviewer.getByRole('combobox',{name:'Publication decision',exact:true}).click();await expect(actors.reviewer.getByRole('option',{name:'Approve this exact proposal',exact:true})).toHaveAttribute('aria-selected','true');await actors.reviewer.getByRole('option',{name:'Decline this proposal',exact:true}).hover();await communityCapture(actors.reviewer,'decision-menu-320-440');await actors.reviewer.keyboard.press('Escape');await actors.reviewer.getByLabel('Decision reason',{exact:true}).fill('PRIVATE_COMMUNITY separately checked supplied consent, contact and frozen area.');await actors.reviewer.getByRole('checkbox',{name:'I reviewed the exact wording, contact authority, times, homes and this decision.',exact:true}).check();await actors.reviewer.getByRole('button',{name:'Approve this exact proposal',exact:true}).scrollIntoViewIfNeeded();await communityCapture(actors.reviewer,'decision-actions-320-440');await actors.reviewer.getByRole('button',{name:'Approve this exact proposal',exact:true}).click();await expect(actors.reviewer.getByRole('dialog').locator('.community-state').first()).toHaveText('Published contact')
  await login(owner,'Owner');await openCommunity(owner,id,false);await owner.setViewportSize({width:320,height:440});const call=owner.getByRole('link',{name:'Call this contact',exact:true});await expect(call).toHaveAttribute('href','tel:+919000000101');await expect(owner.getByText('PRIVATE_COMMUNITY',{exact:false})).toHaveCount(0);await call.evaluate(element=>element.addEventListener('click',event=>{event.preventDefault();element.setAttribute('data-call-intercepted','true')},{once:true}));await call.scrollIntoViewIfNeeded();await communityCapture(owner,'approved-contact-call-320-440');await call.click();await expect(call).toHaveAttribute('data-call-intercepted','true');await communityWithin(owner);await owner.keyboard.press('Escape');await expect(owner.getByRole('dialog')).toHaveCount(0)
 }finally{await actors.close();await ownerContext.close()}
})

test('approved interruptions reach current Overview attention and require an exact separately approved restoration',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage()
 try{
  const id=await communityProposal(page,'COMMUNITY UI water estimate needs an update','INTERRUPTION');await communityApprove(actors.reviewer,id);const original=await communityDetail(page,id,false),options=await(await page.request.get('/api/community/options')).json(),now=Math.floor(Date.now()/1000)
  const future=(await communityPost(page,'/api/community',{kind:'INTERRUPTION',action:'PUBLISH',title:'COMMUNITY UI planned power maintenance',body:'This separately supplied planned interruption has not started yet.',service:'POWER',scope:'WING',building_code:'A',area_key:options.area_key,start_at:now+3600,estimated_end:0,reason:'PRIVATE_COMMUNITY supplied future timing and exact wing'})).id;await communityApprove(actors.reviewer,future)
  await login(owner,'Owner');await owner.goto('/#overview');await expect(owner.getByRole('button',{name:'Refresh overview',exact:true})).toBeEnabled();const source=owner.getByRole('region',{name:'Services, in view.'});await expect(source).toContainText('Current interruptions');const before=await(await owner.request.get('/api/overview/community')).json();expect(before.counts).toMatchObject({active:1,update_needed:1});expect(before.items).toHaveLength(1);const link=owner.getByRole('link',{name:'Interruption estimate needs an update: COMMUNITY UI water estimate needs an update',exact:true});await link.scrollIntoViewIfNeeded();await communityCapture(owner,'overview-active-interruption-1440');await link.click();await expect(owner.getByRole('dialog').locator('.community-state').first()).toHaveText('Estimate passed · update needed')
  await openCommunity(page,id);await page.setViewportSize({width:320,height:440});await page.getByRole('button',{name:'Propose restoration',exact:true}).click();await page.getByLabel('Supplied restoration time · IST',{exact:true}).fill(communityNowLocal());await page.getByLabel('Public restoration update',{exact:true}).fill('The fictional operator confirms the water service was restored at this supplied time.');await page.getByLabel('Private proposal reason',{exact:true}).fill('PRIVATE_COMMUNITY independently supplied actual restoration time.');await page.getByRole('button',{name:'Review exact proposal',exact:true}).click();await page.getByRole('region',{name:'Exact proposed service update'}).scrollIntoViewIfNeeded();await communityCapture(page,'restoration-review-320-440');await page.getByRole('checkbox',{name:'I checked these exact details, contact authority, times and homes for separate review.',exact:true}).check();await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();expect(await communityDetail(owner,id,false)).toEqual(original)
  await openCommunity(actors.reviewer,id);await actors.reviewer.getByRole('button',{name:'Review proposal',exact:true}).click();await actors.reviewer.getByLabel('Decision reason',{exact:true}).fill('PRIVATE_COMMUNITY checked the supplied restoration and approved original scope.');await actors.reviewer.getByRole('checkbox',{name:'I reviewed the exact wording, contact authority, times, homes and this decision.',exact:true}).check();await actors.reviewer.getByRole('button',{name:'Approve this exact proposal',exact:true}).click();await expect(actors.reviewer.getByRole('dialog').locator('.community-state').first()).toHaveText('Service restored');await openCommunity(owner,id,false);await owner.setViewportSize({width:375,height:640});await communityCapture(owner,'approved-restoration-375');const restored=await communityDetail(owner,id,false);expect(restored.snapshot.start_at).toBe(original.snapshot.start_at);expect(restored.snapshot.estimated_end).toBe(original.snapshot.estimated_end);expect(restored.snapshot.resolved_at).toBeGreaterThan(original.snapshot.start_at)
  await owner.getByRole('button',{name:'Close service update',exact:true}).click();await navigate(owner,'Overview');await expect(owner.getByRole('button',{name:'Refresh overview',exact:true})).toBeEnabled();expect((await(await owner.request.get('/api/overview/community')).json()).counts.active).toBe(0);await expect(owner.getByRole('link',{name:'Interruption estimate needs an update: COMMUNITY UI water estimate needs an update',exact:true})).toHaveCount(0);await communityCapture(owner,'overview-restored-375');await openCommunity(owner,future,false);await expect(owner.getByRole('dialog').locator('.community-state').first()).toHaveText('Planned interruption');await communityCapture(owner,'planned-interruption-375')
 }finally{await actors.close();await oc.close()}
})
test('held proposals lock dismissal and lost decision responses retry the exact accepted operation once',async({page,browser})=>{
 const actors=await messageActors(page,browser);let release=()=>{}
 try{
  await navigate(page,'Community');await page.getByRole('link',{name:'Publication desk',exact:true}).click();await page.getByRole('button',{name:'Prepare an update',exact:true}).click();await page.getByLabel('Update title',{exact:true}).fill('COMMUNITY UI held lift interruption');await chooseOption(page,'Service','Lift');await page.getByLabel('Information to publish',{exact:true}).fill('The fictional lift is being inspected and this exact update awaits review.');await page.getByLabel('Supplied start time · IST',{exact:true}).fill(communityLocal(Math.floor(Date.now()/1000)-600));await page.getByLabel('Private proposal reason',{exact:true}).fill('PRIVATE_COMMUNITY supplied the fictional lift interruption and time.');await page.getByRole('button',{name:'Review exact proposal',exact:true}).click();await page.getByRole('checkbox',{name:'I checked these exact details, contact authority, times and homes for separate review.',exact:true}).check()
  const held=new Promise<void>(r=>{release=r});let ready!:()=>void;const captured=new Promise<void>(r=>{ready=r});await page.route('**/api/community',async route=>{if(route.request().method()!=='POST'){await route.continue();return}const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();await captured;await page.setViewportSize({width:320,height:440});await expect(page.getByRole('button',{name:'Close service proposal',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Saving proposal…',exact:true}).scrollIntoViewIfNeeded();await communityCapture(page,'held-proposal-320-440');release();await page.unroute('**/api/community');await expect(page.getByRole('dialog').locator('.community-state').first()).toHaveText('Awaiting separate review');const id=new URLSearchParams(page.url().split('?')[1]).get('service')!
  await openCommunity(actors.reviewer,id);await actors.reviewer.setViewportSize({width:320,height:440});await actors.reviewer.getByRole('button',{name:'Review proposal',exact:true}).click();await actors.reviewer.getByLabel('Decision reason',{exact:true}).fill('PRIVATE_COMMUNITY checked this exact retained lift proposal.');await actors.reviewer.getByRole('checkbox',{name:'I reviewed the exact wording, contact authority, times, homes and this decision.',exact:true}).check();const bodies:string[]=[];let lost=true;await actors.reviewer.route('**/api/community/'+id+'/decisions',async route=>{bodies.push(route.request().postData()!);const response=await route.fetch();if(lost){lost=false;await route.abort('failed')}else await route.fulfill({response})});await actors.reviewer.getByRole('button',{name:'Approve this exact proposal',exact:true}).click();await expect(actors.reviewer.getByRole('button',{name:'Retry this decision',exact:true})).toBeEnabled();await expect(actors.reviewer.getByRole('button',{name:'Close service update',exact:true})).toBeDisabled();await communityCapture(actors.reviewer,'lost-decision-response-320-440');await actors.reviewer.getByRole('button',{name:'Retry this decision',exact:true}).click();await expect(actors.reviewer.getByRole('dialog').locator('.community-state').first()).toHaveText('Service interrupted');expect(bodies).toHaveLength(2);expect(bodies[0]).toBe(bodies[1]);const saved=await communityDetail(actors.reviewer,id);expect(saved.version).toBe(2);expect(saved.event_total).toBe(2);messagePrivateFixture("assert db.execute('SELECT COUNT(*) FROM entries').fetchone()[0]==0;assert db.execute('SELECT COUNT(*) FROM receipts').fetchone()[0]==0")
 }finally{release();await actors.close()}
})
test('service list options and independent Overview sources show real loading error empty and retry states',async({page})=>{
 await login(page);await navigate(page,'Community');let release=()=>{};let ready!:()=>void;const held=new Promise<void>(r=>{release=r}),captured=new Promise<void>(r=>{ready=r});let first=true
 try{
  await page.route('**/api/community?**',async route=>{if(first){first=false;ready();await held;await route.fulfill({status:503,json:{error:'unavailable'}})}else await route.continue()});await page.getByRole('link',{name:'Services & help',exact:true}).click();await captured;await page.setViewportSize({width:320,height:440});await expect(page.getByText('Loading current service updates',{exact:true})).toBeAttached();await communityCapture(page,'service-list-loading-320-440');release();await expect(page.getByRole('alert')).toContainText('Service updates unavailable');await page.getByRole('alert').scrollIntoViewIfNeeded();await communityCapture(page,'service-list-error-320-440');await page.getByRole('button',{name:'Retry service updates',exact:true}).click();await expect(page.getByRole('button',{name:'Open service update: COMMUNITY UI supplied caretaker contact',exact:true})).toBeVisible();await page.unroute('**/api/community?**');await page.getByLabel('Search service updates',{exact:true}).fill('a deliberately unmatched synthetic search');await expect(page.getByRole('heading',{name:'No matching updates.'})).toBeVisible();await communityCapture(page,'service-list-filtered-empty-320-440');await page.getByRole('button',{name:'Clear update filters',exact:true}).click()
  let failed=true;await page.route('**/api/community/options',async route=>{if(failed){failed=false;await route.fulfill({status:503,json:{error:'unavailable'}})}else await route.continue()});await page.getByRole('button',{name:'Prepare an update',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();await communityCapture(page,'area-options-error-320-440');await page.getByRole('dialog').getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByLabel('Update title',{exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await page.unroute('**/api/community/options')
  let overviewFailed=true;await page.route('**/api/overview/community',async route=>{if(overviewFailed)await route.fulfill({status:503,json:{error:'unavailable'}});else await route.continue()});await navigate(page,'Overview');await expect(page.getByRole('button',{name:'Refresh overview',exact:true})).toBeEnabled();await expect(page.getByRole('region',{name:'Needs attention'})).toContainText('Partial view');await expect(page.getByRole('region',{name:'Money, accounted for.'})).toContainText('₹0.00');const source=page.getByRole('region',{name:'Services, in view.'});await expect(source).toContainText('Service updates unavailable');await source.scrollIntoViewIfNeeded();await communityCapture(page,'overview-service-error-320-440');overviewFailed=false;await source.getByRole('button',{name:'Retry service updates',exact:true}).click();await expect(source.getByRole('alert')).toHaveCount(0);await expect(page.getByRole('button',{name:'Refresh overview',exact:true})).toBeEnabled();await page.unroute('**/api/overview/community')
 }finally{release()}
})
test('stale replacement reload preserves the human draft while the approved predecessor stays unchanged',async({page,browser})=>{
 const actors=await messageActors(page,browser)
 try{
  const id=await communityProposal(page,'COMMUNITY UI exact predecessor');await communityApprove(actors.reviewer,id);const original=await communityDetail(page,id,false);await openCommunity(page,id);await page.getByRole('button',{name:'Prepare a replacement',exact:true}).click();await page.getByLabel('Update title',{exact:true}).fill('COMMUNITY UI keep this human draft');await page.getByLabel('Private proposal reason',{exact:true}).fill('PRIVATE_COMMUNITY human change retained across a current-version reload.');await page.getByRole('button',{name:'Review exact proposal',exact:true}).click();await page.getByRole('checkbox',{name:'I checked these exact details, contact authority, times and homes for separate review.',exact:true}).check()
  const options=await(await page.request.get('/api/community/options')).json();await communityPost(page,'/api/community/'+id+'/proposals',{version:2,kind:'CONTACT',action:'PUBLISH',title:'PRIVATE_COMMUNITY competing pending text',body:'This competing private proposal must not replace the approved original yet.',service:'WATER',phone:'+919000000202',availability:'Supplied weekday hours',attestation:'PRIVATE_COMMUNITY deliberately supplied publication permission',scope:'ALL',area_key:options.area_key,reason:'PRIVATE_COMMUNITY separately prepared the competing version.'});await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();await expect(page.getByRole('button',{name:'Reload current record',exact:true})).toBeVisible();await page.setViewportSize({width:320,height:440});await page.getByRole('alert').scrollIntoViewIfNeeded();await communityCapture(page,'stale-replacement-320-440');expect(await communityDetail(page,id,false)).toEqual(original);await page.getByRole('button',{name:'Reload current record',exact:true}).click();await expect(page.getByLabel('Update title',{exact:true})).toHaveValue('COMMUNITY UI keep this human draft');await expect(page.getByRole('textbox',{name:'Private proposal reason',exact:true})).toHaveValue('PRIVATE_COMMUNITY human change retained across a current-version reload.');await communityCapture(page,'draft-preserved-after-reload-320-440');await page.getByRole('button',{name:'Review exact proposal',exact:true}).click();await expect(page.getByRole('checkbox',{name:'I checked these exact details, contact authority, times and homes for separate review.',exact:true})).not.toBeChecked();await page.getByRole('checkbox',{name:'I checked these exact details, contact authority, times and homes for separate review.',exact:true}).check();await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();const x=await communityDetail(page,id);expect(x.version).toBe(4);expect(x.snapshot.title).toBe('COMMUNITY UI keep this human draft');expect(x.events[1].snapshot.title).toBe('PRIVATE_COMMUNITY competing pending text');expect(await communityDetail(page,id,false)).toEqual(original)
 }finally{await actors.close()}
})
test('actual service filters pagination retained-history menus and dismissal remain usable across layouts',async({page,browser})=>{
 const actors=await messageActors(page,browser);let last=''
 try{
  for(let i=0;i<13;i++){last=await communityProposal(page,'COMMUNITY PAGING help '+i);await communityApprove(actors.reviewer,last)}await navigate(page,'Community');await page.getByRole('link',{name:'Services & help',exact:true}).click();await page.getByLabel('Search service updates',{exact:true}).fill('COMMUNITY PAGING');await expect(page.locator('.registry-toolbar').getByRole('status')).toContainText('13 updates');expect(await page.locator('.community-card').count()).toBe(12)
  for(const [width,height] of [[1440,1000],[768,1024],[375,640],[320,640],[320,440]]){await page.setViewportSize({width,height});const type=page.getByRole('combobox',{name:'Filter service update type',exact:true});await type.scrollIntoViewIfNeeded();await type.click();await page.getByRole('option',{name:'Help contacts',exact:true}).hover();await communityCapture(page,`filter-type-${width}-${height}`);await communityWithin(page);await page.keyboard.press('Escape');await expect(type).toBeFocused()}
  await chooseOption(page,'Filter service update status','Published contact');await page.getByRole('button',{name:'Next service updates page',exact:true}).click();await expect(page.locator('.community-card')).toHaveCount(1);await communityCapture(page,'service-page-two-320-440');await page.getByRole('button',{name:'Previous service updates page',exact:true}).click();await expect(page.locator('.community-card')).toHaveCount(12)
  for(let i=0;i<11;i++){const x=await communityDetail(page,last),options=await(await page.request.get('/api/community/options')).json();await communityPost(page,'/api/community/'+last+'/proposals',{version:x.version,kind:'CONTACT',action:'PUBLISH',title:'COMMUNITY PAGING retained revision '+i,body:'This exact replacement contact is retained for an independent separate review.',service:'OTHER',phone:'+919000000101',availability:'Supplied office hours',attestation:'PRIVATE_COMMUNITY deliberately supplied contact publication permission',scope:'ALL',area_key:options.area_key,reason:'PRIVATE_COMMUNITY prepare linked contact revision '+i});await communityApprove(actors.reviewer,last)}await openCommunity(page,last);await page.getByRole('button',{name:'Next community history page',exact:true}).click();const history=page.getByRole('region',{name:'Community publication history'});await expect(history.locator('ol > li')).toHaveCount(4);await history.locator('ol > li > details > summary').last().click();const original=history.locator('ol > li').last();await expect(original).toContainText('COMMUNITY PAGING help 12');await original.locator('.community-area > summary').click();await expect(original.locator('.community-area > div > span')).toHaveCount(118);await original.scrollIntoViewIfNeeded();await communityCapture(page,'retained-original-history-320-440');await communityWithin(page);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('link',{name:'Publication desk',exact:true})).toBeVisible()
 }finally{await actors.close()}
})
test('decline cancellation withdrawal and current-home denial preserve originals without exposing private history',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage(),tc=await browser.newContext({baseURL:new URL(page.url()).origin}),tenant=await tc.newPage()
 try{
  const id=await communityProposal(page,'COMMUNITY UI withdrawn directory','CONTACT','HOMES',['demo-flat-A-101']);await communityApprove(actors.reviewer,id);const original=await communityDetail(page,id,false);await openCommunity(page,id);await page.getByRole('button',{name:'Propose withdrawal',exact:true}).click();await page.getByLabel('Private proposal reason',{exact:true}).fill('PRIVATE_COMMUNITY supplied directory withdrawal for separate review.');await page.getByRole('button',{name:'Review exact proposal',exact:true}).click();await page.getByRole('checkbox',{name:'I checked these exact details, contact authority, times and homes for separate review.',exact:true}).check();await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();await openCommunity(actors.reviewer,id);await actors.reviewer.getByRole('button',{name:'Review proposal',exact:true}).click();await chooseOption(actors.reviewer,'Publication decision','Decline this proposal');await actors.reviewer.getByLabel('Decision reason',{exact:true}).fill('PRIVATE_COMMUNITY declined the proposed withdrawal; original remains current.');await actors.reviewer.getByRole('checkbox',{name:'I reviewed the exact wording, contact authority, times, homes and this decision.',exact:true}).check();await actors.reviewer.getByRole('button',{name:'Decline this proposal',exact:true}).click();expect(await communityDetail(page,id,false)).toEqual(original)
  await openCommunity(page,id);await page.getByRole('button',{name:'Propose withdrawal',exact:true}).click();await page.getByLabel('Private proposal reason',{exact:true}).fill('PRIVATE_COMMUNITY supplied a replacement withdrawal pending own cancellation.');await page.getByRole('button',{name:'Review exact proposal',exact:true}).click();await page.getByRole('checkbox',{name:'I checked these exact details, contact authority, times and homes for separate review.',exact:true}).check();await page.getByRole('button',{name:'Submit for separate review',exact:true}).click();await page.getByRole('button',{name:'Cancel your proposal',exact:true}).click();await page.getByLabel('Decision reason',{exact:true}).fill('PRIVATE_COMMUNITY deliberately cancelled only the pending proposal.');await page.getByRole('checkbox',{name:'I reviewed the exact wording, contact authority, times, homes and this decision.',exact:true}).check();await page.getByRole('button',{name:'Cancel pending proposal',exact:true}).click();expect(await communityDetail(page,id,false)).toEqual(original)
  await login(owner,'Owner');await login(tenant,'Tenant');await openCommunity(owner,id,false);await expect(owner.getByRole('button',{name:'Propose withdrawal',exact:true})).toHaveCount(0);expect((await tenant.request.get('/api/community/'+id)).status()).toBe(403);await tenant.goto('/#community?service='+id);await expect(tenant.getByRole('dialog').getByRole('alert')).toBeVisible();await tenant.setViewportSize({width:320,height:440});await communityCapture(tenant,'cross-home-service-denied-320-440');messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=date('now') WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101' AND end_date IS NULL\")");await owner.reload();await expect(owner.getByRole('dialog').getByRole('alert')).toBeVisible();await owner.setViewportSize({width:320,height:440});await communityCapture(owner,'ended-home-service-denied-320-440');await expect(owner.getByRole('link',{name:'Call this contact',exact:true})).toHaveCount(0)
  const x=await communityDetail(page,id);await communityPost(page,'/api/community/'+id+'/proposals',{version:x.version,action:'WITHDRAW',reason:'PRIVATE_COMMUNITY separate withdrawal preserves original and all decisions.'});await communityApprove(actors.reviewer,id);expect((await page.request.get('/api/community/'+id)).status()).toBe(404);const retained=await communityDetail(page,id);expect(retained.state).toBe('WITHDRAWN');expect(retained.snapshot.resolved_at).toBe(0);expect(retained.events.at(-1).snapshot.phone).toBe('+919000000101')
 }finally{messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=NULL WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101'\")");await actors.close();await oc.close();await tc.close()}
})
