import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mkdirSync, chmodSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { createHash } from 'node:crypto'
import { login, navigate, chooseOption } from './helpers'
import { plainPDF } from './document-fixtures'

async function capture(page: Page, name: string) { if (!process.env.SOCIETY_CAPTURE_UI) return; await page.evaluate(() => document.fonts.ready); const dir = resolve('../reports/local/documents-review'); mkdirSync(dir, { recursive: true, mode: 0o700 }); const path = resolve(dir, name + '.png'); await page.screenshot({ path, animations: 'disabled' }); chmodSync(path, 0o600) }
async function library(page: Page) { await navigate(page, 'Documents'); await expect(page.getByRole('heading', { name: 'Your document library' })).toBeVisible() }
async function startUpload(page: Page, title: string, name = 'fictional-record.pdf', bytes = plainPDF()) { await library(page); await page.getByRole('button', { name: 'Add a document', exact: true }).click(); await page.getByLabel('Document file', { exact: true }).setInputFiles({ name, mimeType: 'application/pdf', buffer: bytes }); await page.getByRole('textbox', { name: 'Title', exact: true }).fill(title) }
async function savedUpload(page: Page, button = 'Upload for review') { const response = page.waitForResponse(response => /\/api\/documents\/[^/]+\/content$/.test(response.url()) && response.request().method() === 'POST'); await page.getByRole('button', { name: button, exact: true }).click(); const result = await response; expect(result.status()).toBe(200); const id = (await result.json()).id as string; await expect(page.getByRole('button', { name: 'Download original', exact: true })).toBeEnabled(); return id }
async function close(page: Page) { await page.getByRole('button', { name: 'Close document details', exact: true }).click() }
async function switchTo(page: Page, account: string) { if (await page.getByRole('button', { name: 'Close document details', exact: true }).count()) await close(page); await page.getByRole('button', { name: 'Sign out', exact: true }).click(); await login(page, account) }
async function open(page: Page, title: string) { await library(page); await page.getByRole('searchbox', { name: 'Search documents' }).fill(title); await page.getByRole('button', { name: 'Open document ' + title, exact: true }).click(); await expect(page.getByRole('dialog').getByRole('heading', { name: title, exact: true })).toBeVisible() }
async function decide(page: Page, decision: string, message = 'The fictional content and its audience have been checked separately') { await chooseOption(page, 'Document decision', decision); await page.getByRole('textbox', { name: 'Document decision reason' }).fill(message); await page.getByRole('checkbox', { name: 'I have checked this version, its audience and my decision.' }).check(); const response = page.waitForResponse(response => /\/api\/documents\/[^/]+\/actions$/.test(response.url()) && response.request().method() === 'POST'); await page.getByRole('button', { name: 'Save document decision', exact: true }).click(); expect((await response).status()).toBe(200) }
async function download(page: Page, filename: string, expected = plainPDF()) { const result = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download original', exact: true }).click(); const file = await result; expect(file.suggestedFilename()).toBe(filename); expect(readFileSync((await file.path())!)).toEqual(expected) }
async function fixture(page: Page, title: string, overrides: Record<string, unknown> = {}) { const bytes = plainPDF(); const me = await (await page.request.get('/api/auth/me')).json(); const headers = { Origin: new URL(page.url()).origin, 'X-CSRF-Token': me.csrf_token }; const result = await page.request.post('/api/documents', { headers, data: { operation_key: crypto.randomUUID(), title, filename: 'fixture.pdf', size_bytes: bytes.length, sha256: createHash('sha256').update(bytes).digest('hex'), category: 'RESIDENT_DOCUMENT', visibility: 'RESIDENT_SPECIFIC', flat_id: '', subject_resident_id: '', expiry_date: '', replaces_document_id: '', version: 0, ...overrides } }); expect(result.status()).toBe(200); const id = (await result.json()).id as string; expect((await page.request.post('/api/documents/' + id + '/content', { headers: { ...headers, 'Content-Type': 'application/octet-stream' }, data: bytes })).status()).toBe(200); return id }

test('a resident uploads a private original and a separate reviewer approves through visible controls', async ({ page }) => {
 await login(page, 'Owner'); await library(page); await expect(page.getByRole('heading', { name: 'A place for the papers that matter.' })).toBeVisible(); await page.locator('.records-empty').scrollIntoViewIfNeeded(); await capture(page, 'library-empty'); await startUpload(page, 'PAPERS A private resident record', 'निवासी-record.pdf'); const id = await savedUpload(page)
 await expect(page.getByText('A different authorized person must review the file', { exact: false })).toBeVisible(); await capture(page, 'resident-file-ready-for-review')
 await page.getByRole('combobox', { name: 'Document decision' }).click(); await expect(page.getByRole('option', { name: 'Approve this version', exact: true })).toHaveCount(0); await page.keyboard.press('Escape')
 await switchTo(page, 'Tenant'); expect((await page.request.get('/api/documents/' + id)).status()).toBe(404); await library(page); await page.getByRole('searchbox', { name: 'Search documents' }).fill('PAPERS A private resident record'); await expect(page.getByRole('status')).toHaveText('0 documents found')
 await switchTo(page, 'Registry officer'); await open(page, 'PAPERS A private resident record'); await download(page, 'निवासी-record.pdf'); await decide(page, 'Approve this version'); await expect(page.getByRole('dialog').locator('.review-state')).toHaveText('Approved'); await capture(page, 'reviewer-approved-private-record')
 await switchTo(page, 'Owner'); await page.goto('/#documents?file=' + id); await expect(page.getByRole('button', { name: 'Download original', exact: true })).toBeEnabled(); await download(page, 'निवासी-record.pdf')
 const item = await (await page.request.get('/api/documents/' + id)).json(); expect(item.revision).toBe(1); expect(item.events.some((event: { action: string }) => event.action === 'APPROVED')).toBe(true)
})

test('a shared replacement preserves the approved original until separately approved and archival removes fresh links', async ({ page }) => {
 await login(page, 'Owner'); await startUpload(page, 'PAPERS Original garden circular'); await chooseOption(page, 'Document category', 'Circular'); await chooseOption(page, 'Document audience', 'Current society residents'); const original = await savedUpload(page)
 await switchTo(page, 'Registry officer'); await open(page, 'PAPERS Original garden circular'); await decide(page, 'Approve this version')
 await switchTo(page, 'Owner'); await open(page, 'PAPERS Original garden circular'); await page.getByRole('button', { name: 'Add a new version', exact: true }).click(); await page.getByLabel('Document file', { exact: true }).setInputFiles({ name: 'revised-circular.pdf', mimeType: 'application/pdf', buffer: plainPDF() }); await page.getByRole('textbox', { name: 'Title', exact: true }).fill('PAPERS Revised garden circular'); const replacement = await savedUpload(page, 'Upload replacement'); await capture(page, 'resident-pending-replacement')
 await switchTo(page, 'Tenant'); await open(page, 'PAPERS Original garden circular'); await expect(page.getByRole('region', { name: 'Document versions' }).locator('li')).toHaveCount(1); await expect(page.getByText('PAPERS Revised garden circular')).toHaveCount(0); await expect(page.getByRole('region', { name: 'Private document review history' })).toHaveCount(0); await download(page, 'fictional-record.pdf')
 await switchTo(page, 'Registry officer'); await open(page, 'PAPERS Revised garden circular'); await decide(page, 'Approve this version'); await capture(page, 'reviewer-approved-replacement')
 await switchTo(page, 'Tenant'); await open(page, 'PAPERS Revised garden circular'); await expect(page.getByRole('region', { name: 'Document versions' }).locator('li')).toHaveCount(2); await download(page, 'revised-circular.pdf'); expect((await page.request.get('/api/documents/' + original + '/download')).status()).toBe(200)
 await switchTo(page, 'Registry officer'); await open(page, 'PAPERS Revised garden circular'); await decide(page, 'Archive this collection'); await expect(page.getByRole('dialog').locator('.review-state')).toHaveText('Archived')
 await switchTo(page, 'Tenant'); for (const id of [original, replacement]) expect((await page.request.get('/api/documents/' + id + '/download')).status()).toBe(404)
})

test('resident payment evidence follows explicit financial scope and never posts money or a receipt', async ({ page }) => {
 await login(page, 'Owner'); await startUpload(page, 'PAPERS Fictional paid-entry evidence'); await chooseOption(page, 'Document category', 'Payment evidence'); await chooseOption(page, 'Document home', 'Home A-101'); const id = await savedUpload(page)
 await expect(page.getByRole('dialog').getByText('Current home members · Home A-101')).toBeVisible()
 await switchTo(page, 'Committee'); await open(page, 'PAPERS Fictional paid-entry evidence'); await decide(page, 'Approve this version')
 const entries = await (await page.request.get('/api/entries')).json(); expect(entries.total).toBe(0); expect(entries.balance_paise).toBe(0)
 await switchTo(page, 'Tenant'); expect((await page.request.get('/api/documents/' + id)).status()).toBe(404); await startUpload(page, 'PAPERS Tenant personal record'); await page.getByRole('combobox', { name: 'Document category', exact: true }).click(); await expect(page.getByRole('option', { name: 'Payment evidence', exact: true })).toHaveCount(0); await page.keyboard.press('Escape')
})

test('document forms, required fields, opened menus and keyboard selection fit desktop tablet and small phones', async ({ page }) => {
 await page.emulateMedia({ reducedMotion: 'reduce' }); await login(page, 'Owner')
 for (const viewport of [{ width: 1440, height: 900 }, { width: 768, height: 1024 }, { width: 375, height: 812 }, { width: 320, height: 568 }]) {
  await page.setViewportSize(viewport); await library(page); await expect(page.getByRole('combobox', { name: 'Filter document state' })).toBeVisible(); if (viewport.width >= 768) expect(await page.getByRole('combobox', { name: 'Filter document state' }).evaluate(el => { const label = el.querySelector('span')!; const style = getComputedStyle(label); return label.getBoundingClientRect().height <= parseFloat(style.lineHeight) + 1 })).toBe(true); await capture(page, `library-${viewport.width}-page`)
  for (const label of ['Filter document category', 'Filter document state']) { await page.getByRole('combobox', { name: label }).click(); await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 }); await capture(page, `library-${viewport.width}-${label.replaceAll(' ', '-').toLowerCase()}`); await page.keyboard.press('Escape') }
  await startUpload(page, 'PAPERS Long upload filename and title ' + viewport.width, 'fictional-long-original-filename-for-document-layout.pdf')
  await page.getByRole('combobox', { name: 'Document category', exact: true }).click(); await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 }); await capture(page, `library-${viewport.width}-category-menu`); await page.keyboard.press('Home'); await page.keyboard.press('Enter')
  await page.getByRole('combobox', { name: 'Document audience' }).click(); await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 }); await capture(page, `library-${viewport.width}-audience-menu`); await page.getByRole('option', { name: 'Current home members', exact: true }).click()
  await page.getByRole('button', { name: 'Upload for review', exact: true }).click(); await expect(page.getByRole('combobox', { name: 'Document home' })).toBeFocused(); await page.keyboard.press('Enter'); await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 }); await capture(page, `library-${viewport.width}-home-menu`); await page.keyboard.press('End'); await page.keyboard.press('Enter')
  expect(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.keyboard.press('Escape'); await expect(page.getByRole('button', { name: 'Add a document', exact: true })).toBeFocused()
 }
})

test('lost reservation and original-upload responses preserve one upload identity and busy dialogs stay open', async ({ page }) => {
 await login(page, 'Owner'); await startUpload(page, 'PAPERS Retried reservation identity'); const keys: string[] = []
 await page.route('**/api/documents', async route => { if (route.request().method() !== 'POST') return route.continue(); keys.push(route.request().postDataJSON().operation_key); await route.fetch(); await route.abort() })
 await page.getByRole('button', { name: 'Upload for review', exact: true }).click(); await expect(page.getByRole('alert')).toBeInViewport({ ratio: 1 }); await expect(page.getByRole('button', { name: 'Close document upload' })).toBeInViewport({ ratio: 1 }); await capture(page, 'library-lost-reservation-response')
 await page.unroute('**/api/documents'); page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/api/documents')) keys.push(request.postDataJSON().operation_key) }); await savedUpload(page, 'Retry this upload'); expect(keys).toHaveLength(2); expect(keys[0]).toBe(keys[1]); await close(page)
 await startUpload(page, 'PAPERS Retried original bytes'); const ids: string[] = []; let release!: () => void; const held = new Promise<void>(resolve => { release = resolve })
 await page.route('**/api/documents/*/content', async route => { ids.push(route.request().url()); await route.fetch(); await held; await route.abort() }); await page.getByRole('button', { name: 'Upload for review', exact: true }).click(); await expect(page.getByRole('button', { name: 'Uploading the original…' })).toBeDisabled(); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toBeVisible(); release(); await expect(page.getByRole('alert')).toBeVisible(); await page.unroute('**/api/documents/*/content')
 page.on('request', request => { if (request.method() === 'POST' && /\/api\/documents\/[^/]+\/content$/.test(request.url())) ids.push(request.url()) }); await savedUpload(page, 'Retry this upload'); expect(ids).toHaveLength(2); expect(ids[0]).toBe(ids[1]); await close(page); await page.getByRole('searchbox', { name: 'Search documents' }).fill('PAPERS Retried original bytes'); await expect(page.getByRole('status')).toHaveText('1 documents found')
})

test('invalid file content cannot be downloaded and declined or withdrawn originals retain history', async ({ page }) => {
 await login(page, 'Owner'); await startUpload(page, 'PAPERS Unsupported active PDF', 'active.pdf', plainPDF(true)); const response = page.waitForResponse(response => /\/content$/.test(response.url())); await page.getByRole('button', { name: 'Upload for review', exact: true }).click(); const id = (await (await response).json()).id as string
 await expect(page.getByRole('dialog').locator('.review-state')).toHaveText('File needs attention'); await expect(page.getByRole('button', { name: 'Download original', exact: true })).toHaveCount(0); await expect(page.getByRole('alert')).toContainText('unsupported active content'); await capture(page, 'library-rejected-active-pdf'); expect((await page.request.get('/api/documents/' + id + '/download')).status()).toBe(409)
 await decide(page, 'Withdraw this upload', 'The rejected active PDF is withdrawn and retained for review'); await expect(page.getByRole('dialog').locator('.review-state')).toHaveText('Withdrawn')
 await close(page); await startUpload(page, 'PAPERS Declined draft'); await savedUpload(page); await switchTo(page, 'Registry officer'); await open(page, 'PAPERS Declined draft'); await decide(page, 'Decline this version', 'The fictional source does not match the intended record'); await expect(page.getByRole('dialog').locator('.review-state')).toHaveText('Declined'); await capture(page, 'library-declined-record')
})

test('phone list and download failures recover and stale decisions cannot overwrite a reviewer', async ({ page }) => {
 await page.setViewportSize({ width: 320, height: 568 }); await login(page, 'Owner'); const id = await fixture(page, 'PAPERS A stale approval')
 await page.route('**/api/documents?**', route => route.fulfill({ status: 503, json: { error: 'unavailable' } })); await library(page); await expect(page.getByRole('alert')).toBeInViewport({ ratio: 1 }); await capture(page, 'library-phone-list-error'); await page.unroute('**/api/documents?**'); await page.getByRole('button', { name: 'Try again', exact: true }).click()
 await switchTo(page, 'Registry officer'); let releaseDetails!: () => void; const heldDetails = new Promise<void>(resolve => { releaseDetails = resolve }); const detailPattern = '**/api/documents/' + id + '?**'
 await page.route(detailPattern, async route => { await heldDetails; await route.fulfill({ status: 503, json: { error: 'unavailable' } }) }); await library(page); await page.getByRole('searchbox', { name: 'Search documents' }).fill('PAPERS A stale approval'); await page.getByRole('button', { name: 'Open document PAPERS A stale approval', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Opening the record…', exact: true })).toBeVisible(); await capture(page, 'library-phone-detail-loading'); releaseDetails(); await expect(page.getByRole('alert')).toBeVisible(); await expect(page.getByRole('heading', { name: 'Document unavailable', exact: true })).toBeVisible(); await capture(page, 'library-phone-detail-error'); await page.unroute(detailPattern); await page.getByRole('button', { name: 'Reload document', exact: true }).click(); await expect(page.getByRole('button', { name: 'Download original', exact: true })).toBeEnabled(); await chooseOption(page, 'Document decision', 'Approve this version'); await page.getByRole('textbox', { name: 'Document decision reason' }).fill('An old visible review tries to approve after another action'); await page.getByRole('checkbox', { name: 'I have checked this version, its audience and my decision.' }).check()
 const me = await (await page.request.get('/api/auth/me')).json(); const item = await (await page.request.get('/api/documents/' + id)).json(); expect((await page.request.post('/api/documents/' + id + '/actions', { headers: { Origin: new URL(page.url()).origin, 'X-CSRF-Token': me.csrf_token }, data: { operation_key: crypto.randomUUID(), version: item.version, action: 'DECLINED', reason: 'A completed reviewer decision wins before the stale browser action', confirmed: true } })).status()).toBe(200)
 await page.getByRole('button', { name: 'Save document decision', exact: true }).click(); await expect(page.getByRole('alert')).toBeInViewport({ ratio: 1 }); await expect(page.getByRole('button', { name: 'Close document details' })).toBeInViewport({ ratio: 1 }); expect(await page.getByRole('dialog').evaluate(el => el.scrollTop)).toBe(0); await capture(page, 'library-phone-stale-decision'); await page.getByRole('button', { name: 'Reload latest document', exact: true }).click(); await expect(page.getByRole('dialog').locator('.review-state')).toHaveText('Declined')
 await page.route('**/api/documents/*/download', route => route.fulfill({ status: 503, json: { error: 'unavailable' } })); await page.getByRole('button', { name: 'Download original', exact: true }).click(); await expect(page.getByRole('alert')).toBeInViewport({ ratio: 1 }); await capture(page, 'library-phone-download-error'); await page.unroute('**/api/documents/*/download'); await download(page, 'fixture.pdf')
})

test('document search pagination visits every authorised fixture and clamps after a filter changes', async ({ page }) => {
 await login(page, 'Owner'); for (let i = 0; i < 14; i++) await fixture(page, 'PAPERS PAGE Fixture ' + i)
 await library(page); await page.getByRole('searchbox', { name: 'Search documents' }).fill('PAPERS PAGE Fixture'); await expect(page.getByRole('status')).toHaveText('14 documents found'); const names = new Set<string>()
 for (const index of [1, 2]) { if (index === 2) { const response = page.waitForResponse(response => response.url().includes('/api/documents?') && response.url().includes('page=2')); await page.getByRole('button', { name: 'Next documents page' }).click(); await response }; const buttons = page.getByRole('button', { name: /^Open document PAPERS PAGE Fixture/ }); for (let i = 0; i < await buttons.count(); i++) names.add((await buttons.nth(i).getAttribute('aria-label'))!) }
 expect(names.size).toBe(14); await page.getByRole('searchbox', { name: 'Search documents' }).fill('PAPERS PAGE Fixture 13'); await expect(page.getByText('Page 1 of 1')).toBeVisible()
})

test('staff person expiry and decision controls work in a short phone dialog with keyboard and focus return', async ({ page }) => {
 await login(page, 'Registry officer'); await page.setViewportSize({ width: 320, height: 568 }); await startUpload(page, 'PAPERS Contract for a named person'); await chooseOption(page, 'Document category', 'Contract'); await chooseOption(page, 'Document audience', 'Named person & reviewers'); await page.getByRole('textbox', { name: 'Find document subject' }).fill('Demo Owner A-101')
 await page.getByRole('combobox', { name: 'Document subject' }).click(); await expect(page.getByRole('option', { name: 'Demo Owner A-101', exact: true })).toBeVisible(); await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 }); await capture(page, 'library-phone-subject-menu'); await page.getByRole('option', { name: 'Demo Owner A-101', exact: true }).click(); await page.getByLabel('Document expiry date').fill('2027-10-04'); await savedUpload(page)
 await switchTo(page, 'Committee'); await open(page, 'PAPERS Contract for a named person'); await expect(page.getByRole('button', { name: 'Download original', exact: true })).toBeEnabled(); await page.getByRole('combobox', { name: 'Document decision' }).click(); await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 }); await capture(page, 'library-phone-decision-menu'); await page.getByRole('option', { name: 'Approve this version', exact: true }).click(); await decide(page, 'Approve this version'); await capture(page, 'library-phone-approved-named-person')
})

test('the real file picker resumes an unfinished upload and refuses changed original bytes', async ({ page }) => {
 await page.setViewportSize({ width: 375, height: 812 }); await login(page, 'Owner'); await library(page); await page.getByRole('button', { name: 'Add a document', exact: true }).click()
 const picker = page.waitForEvent('filechooser'); await page.locator('.document-upload-target').click(); await (await picker).setFiles({ name: 'unfinished-original.pdf', mimeType: 'application/pdf', buffer: plainPDF() }); await page.getByRole('textbox', { name: 'Title', exact: true }).fill('PAPERS An unfinished original')
 await page.route('**/api/documents/*/content', route => route.fulfill({ status: 503, json: { error: 'unavailable' } })); await page.getByRole('button', { name: 'Upload for review', exact: true }).click(); await expect(page.getByRole('alert')).toBeInViewport({ ratio: 1 }); await page.unroute('**/api/documents/*/content'); await page.getByRole('button', { name: 'Close document upload' }).click()
 await open(page, 'PAPERS An unfinished original'); await expect(page.getByRole('dialog').locator('.review-state')).toHaveText('Upload unfinished'); await capture(page, 'library-phone-upload-unfinished'); await page.getByRole('button', { name: 'Finish this upload', exact: true }).click()
 await expect(page.getByRole('textbox', { name: 'Title', exact: true })).toBeDisabled(); await page.getByLabel('Document file', { exact: true }).setInputFiles({ name: 'changed.pdf', mimeType: 'application/pdf', buffer: plainPDF(true) }); await page.getByRole('button', { name: 'Finish upload', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('same size and content'); await expect(page.getByRole('button', { name: 'Close document upload' })).toBeInViewport({ ratio: 1 }); await capture(page, 'library-phone-resume-checksum-error')
 await page.getByLabel('Document file', { exact: true }).setInputFiles({ name: 'unfinished-original.pdf', mimeType: 'application/pdf', buffer: plainPDF() }); await savedUpload(page, 'Finish upload'); await download(page, 'unfinished-original.pdf'); await capture(page, 'library-phone-resumed-original')
})

test('a lost approval response retries the same decision without a second event and blocks dismissal while pending', async ({ page }) => {
 await login(page, 'Owner'); await startUpload(page, 'PAPERS One retry-safe approval'); const id = await savedUpload(page); await switchTo(page, 'Registry officer'); await open(page, 'PAPERS One retry-safe approval'); await chooseOption(page, 'Document decision', 'Approve this version'); await page.getByRole('textbox', { name: 'Document decision reason' }).fill('This independent review remains the same if its response is lost'); await page.getByRole('checkbox', { name: 'I have checked this version, its audience and my decision.' }).check()
 const keys: string[] = []; let release!: () => void; const held = new Promise<void>(resolve => { release = resolve })
 await page.route('**/api/documents/*/actions', async route => { keys.push(route.request().postDataJSON().operation_key); await route.fetch(); await held; await route.abort() }); await page.getByRole('button', { name: 'Save document decision', exact: true }).click(); await expect(page.getByRole('button', { name: 'Saving the decision…', exact: true })).toBeDisabled(); await expect(page.getByRole('button', { name: 'Download original', exact: true })).toBeDisabled(); await expect(page.getByRole('button', { name: 'Close document details' })).toBeDisabled(); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toBeVisible(); await capture(page, 'library-approval-pending'); release()
 await expect(page.getByRole('alert')).toBeInViewport({ ratio: 1 }); await capture(page, 'library-lost-approval-response'); await page.unroute('**/api/documents/*/actions'); page.on('request', request => { if (request.method() === 'POST' && /\/api\/documents\/[^/]+\/actions$/.test(request.url())) keys.push(request.postDataJSON().operation_key) }); await page.getByRole('button', { name: 'Retry this decision', exact: true }).click(); await expect(page.getByRole('dialog').locator('.review-state')).toHaveText('Approved')
 expect(keys).toHaveLength(2); expect(keys[0]).toBe(keys[1]); const item = await (await page.request.get('/api/documents/' + id)).json(); expect(item.revision).toBe(1); expect(item.events.filter((event: { action: string }) => event.action === 'APPROVED')).toHaveLength(1); await capture(page, 'library-approval-retry-complete')
})

test('version history visits fourteen approved originals while a pending replacement remains private', async ({ page, browser }) => {
 await login(page, 'Owner'); const context = await browser.newContext(); const reviewer = await context.newPage()
 try {
  await login(reviewer, 'Registry officer'); const me = await (await reviewer.request.get('/api/auth/me')).json(); const headers = { Origin: new URL(page.url()).origin, 'X-CSRF-Token': me.csrf_token }; let current = ''; let version = 0
  for (let revision = 1; revision <= 14; revision++) {
   current = await fixture(page, 'PAPERS VERSION Circular ' + revision, { category: 'CIRCULAR', visibility: 'ALL_AUTHORIZED_RESIDENTS', replaces_document_id: current, version })
   await expect.poll(async () => (await (await reviewer.request.get('/api/documents/' + current)).json()).validation_status).toBe('AVAILABLE'); const record = await (await reviewer.request.get('/api/documents/' + current)).json(); expect((await reviewer.request.post('/api/documents/' + current + '/actions', { headers, data: { operation_key: crypto.randomUUID(), version: record.version, action: 'APPROVED', reason: 'The fictional version and its resident audience are checked independently', confirmed: true } })).status()).toBe(200); version = (await (await page.request.get('/api/documents/' + current)).json()).version
  }
  const pending = await fixture(page, 'PAPERS VERSION Hidden pending version', { category: 'CIRCULAR', visibility: 'ALL_AUTHORIZED_RESIDENTS', replaces_document_id: current, version }); await switchTo(page, 'Tenant'); await page.setViewportSize({ width: 375, height: 812 }); await page.goto('/#documents?file=' + current); const section = page.getByRole('region', { name: 'Document versions' }); await expect(section.locator('li')).toHaveCount(12); await expect(page.getByText('14 permitted versions')).toBeVisible(); await expect(page.getByRole('region', { name: 'Private document review history' })).toHaveCount(0)
  const seen = new Set(await section.locator('li strong').allTextContents()); await page.getByRole('button', { name: 'Older document versions' }).click(); await expect(section.locator('li')).toHaveCount(2); for (const title of await section.locator('li strong').allTextContents()) seen.add(title); expect(seen.size).toBe(14); expect([...seen].some(title => title.includes('Hidden pending'))).toBe(false); await capture(page, 'library-phone-history-second-page'); await page.getByRole('button', { name: 'Newer document versions' }).click(); await expect(section.locator('li')).toHaveCount(12); await capture(page, 'library-phone-history-first-page'); expect((await page.request.get('/api/documents/' + pending)).status()).toBe(404)
 } finally { await context.close() }
})
