import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mkdirSync, chmodSync } from 'node:fs'
import { resolve } from 'node:path'
import { login, navigate, chooseFilter } from './helpers'

async function capture(page: Page, name: string) {
  if (!process.env.SOCIETY_CAPTURE_UI) return
  await page.evaluate(() => document.fonts.ready)
  const folder = resolve('../reports/local/interaction-review')
  mkdirSync(folder, { recursive: true, mode: 0o700 })
  const path = resolve(folder, name + '.png')
  await page.screenshot({ path })
  chmodSync(path, 0o600)
}

test('filter menus align, distinguish selection from hover, and close without changing the selection', async ({ page }) => {
  await page.setViewportSize({ width: 2048, height: 1119 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await login(page)
  await navigate(page, 'Homes & people')
  await chooseFilter(page, 'Filter by wing', 'B')
  await chooseFilter(page, 'Filter by occupancy', 'RENTED')
  await expect(page.getByRole('status')).toHaveText('12 homes found')
  const boxes = await page.locator('.search-control, .filter-select').evaluateAll(elements => elements.map(el => {
    const { y, height } = el.getBoundingClientRect()
    const style = getComputedStyle(el)
    return { y, height, border: style.borderWidth, radius: style.borderRadius }
  }))
  expect(new Set(boxes.map(box => box.y)).size).toBe(1)
  expect(boxes.every(box => box.height === 48 && box.border === '1px' && box.radius === '9px')).toBe(true)
  await capture(page, 'filters-desktop-aligned')
  const wing = page.getByRole('combobox', { name: 'Filter by wing', exact: true })
  await wing.click()
  await expect(page.getByRole('listbox')).toBeVisible()
  await expect(page.getByRole('option', { name: 'Wing B', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('option', { name: 'Wing B', exact: true }).locator('.filter-check')).toBeVisible()
  await page.getByRole('option', { name: 'Wing C', exact: true }).hover()
  await expect(page.getByRole('option', { name: 'Wing C', exact: true })).toHaveAttribute('data-highlighted', '')
  await expect(page.getByRole('option', { name: 'Wing C', exact: true })).toHaveAttribute('aria-selected', 'false')
  await capture(page, 'filters-desktop-wing-menu-hover')
  await page.keyboard.press('Escape')
  await expect(wing).toBeFocused()
  await expect(wing).toHaveText('Wing B')
  await wing.click()
  await expect(page.getByRole('option', { name: 'Wing B', exact: true })).toBeFocused()
  await page.mouse.click(350, 100)
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(wing).toHaveText('Wing B')
  await chooseFilter(page, 'Filter by wing', 'C')
  await expect(page.getByRole('status')).toHaveText('11 homes found')
  await expect(page.getByRole('button', { name: 'Explore Wing C, 38 homes', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const occupancy = page.getByRole('combobox', { name: 'Filter by occupancy', exact: true })
  await occupancy.click()
  await page.getByRole('option', { name: 'Owner occupied', exact: true }).hover()
  await capture(page, 'filters-desktop-occupancy-menu')
  await page.getByRole('option', { name: 'Vacant', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('3 homes found')
})

test('filters support keyboard opening, arrows, typeahead, commit and cancellation', async ({ page }) => {
  await login(page)
  await navigate(page, 'Homes & people')
  const wing = page.getByRole('combobox', { name: 'Filter by wing', exact: true })
  await wing.focus()
  await page.keyboard.press('Space')
  await expect(page.getByRole('listbox')).toBeVisible()
  await expect(page.getByRole('option', { name: 'All wings', exact: true })).toBeFocused()
  await page.keyboard.press('End')
  await expect(page.getByRole('option', { name: 'Wing C', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(wing).toHaveText('Wing C')
  await expect(wing).toBeFocused()
  await expect(page.getByRole('status')).toHaveText('38 homes found')
  await page.keyboard.press('ArrowUp')
  await expect(page.getByRole('option', { name: 'Wing C', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowUp')
  await expect(page.getByRole('option', { name: 'Wing B', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(wing).toHaveText('Wing B')
  await expect(page.getByRole('status')).toHaveText('40 homes found')
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('option', { name: 'Wing B', exact: true })).toBeFocused()
  await page.keyboard.press('Home')
  await expect(page.getByRole('option', { name: 'All wings', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(wing).toBeFocused()
  await expect(wing).toHaveText('Wing B')
  const occupancy = page.getByRole('combobox', { name: 'Filter by occupancy', exact: true })
  await occupancy.focus()
  await expect(occupancy).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('option', { name: 'All occupancy', exact: true })).toBeFocused()
  await page.keyboard.type('rent')
  await expect(page.getByRole('option', { name: 'Rented', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(occupancy).toHaveText('Rented')
  await expect(page.getByRole('status')).toHaveText('12 homes found')
  await page.getByRole('button', { name: 'Clear', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('118 homes found')
  await expect(wing).toHaveText('All wings')
  await expect(occupancy).toHaveText('All occupancy')
  await expect(page.getByRole('button', { name: 'Clear', exact: true })).toBeDisabled()
})

test('open dropdowns fit tablets and small phones, including near the bottom of the viewport', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await login(page)
  await navigate(page, 'Homes & people')
  for (const viewport of [{ width: 1280, height: 720 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 375, height: 812 }, { width: 320, height: 568 }]) {
    await page.setViewportSize(viewport)
    for (const [name, suffix] of [['Filter by wing', 'wing'], ['Filter by occupancy', 'occupancy']]) {
      const control = page.getByRole('combobox', { name, exact: true })
      await control.scrollIntoViewIfNeeded()
      await control.evaluate(el => el.scrollIntoView({ block: 'end', behavior: 'instant' }))
      await control.click()
      await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 })
      const bounds = await page.getByRole('listbox').boundingBox()
      expect(bounds!.x).toBeGreaterThanOrEqual(0)
      expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await capture(page, `filters-${viewport.width}x${viewport.height}-${suffix}-open`)
      await page.keyboard.press('Escape')
      await expect(control).toBeFocused()
    }
  }
})
