import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mkdirSync, chmodSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { resolve } from 'node:path'
import { login, chooseOption } from './helpers'
import { messagePrivateFixture } from './messages-fixtures'
import { financialHeaders } from './maintenance-fixtures'
import { exportCheck, exactExportSources, openExport, previewExport, createExportUI, downloadedCSV, exportEntry, apiExport, exportDates } from './finance-exports-fixtures'
import { apiFund, apiFundAction } from './collections-fixtures'
import { statementActors } from './statements-fixtures'

test.setTimeout(90000)
async function capture(page: Page, name: string) {
  if (!process.env.SOCIETY_CAPTURE_UI) return
  await page.evaluate(() => document.fonts.ready); await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  const root = resolve(process.env.SOCIETY_EXPORT_CAPTURE_ROOT ?? '../reports/local/finance-exports-review'); mkdirSync(root, { recursive: true, mode: 0o700 }); const file = resolve(root, name + '.png'); await page.screenshot({ path: file, animations: 'disabled' }); chmodSync(file, 0o600)
}
async function within(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); const dialog = page.getByRole('dialog'); await expect(dialog.locator('.dialog-close')).toBeInViewport({ ratio: 1 }); expect(await dialog.evaluate(e => e.scrollWidth <= e.clientWidth)).toBe(true) }

test('export menus keyboard empty sources loading errors retries and short dialog controls render at every width', async ({ page }) => {
  await login(page)
  for (const width of [1440, 768, 375, 320]) {
    await page.setViewportSize({ width, height: width <= 375 ? 640 : 1000 }); await openExport(page)
    await page.getByRole('combobox', { name: 'Financial export report', exact: true }).click(); await expect(page.getByRole('option', { name: 'Confirmed ledger', exact: true })).toHaveAttribute('aria-selected', 'true'); await page.getByRole('option', { name: 'Fund reconciliation', exact: true }).hover(); await capture(page, 'report-menu-' + width)
    await page.keyboard.press('End'); await expect(page.getByRole('option', { name: 'Fund reconciliation', exact: true })).toBeFocused(); await page.keyboard.press('Enter')
    await page.getByRole('combobox', { name: 'Financial export scope', exact: true }).click(); await expect(page.getByRole('option', { name: 'Whole society · Treasury access', exact: true })).toHaveAttribute('aria-selected', 'true'); await page.getByRole('option', { name: 'One permitted home', exact: true }).hover(); await capture(page, 'scope-menu-' + width); await page.keyboard.press('End'); await page.keyboard.press('Enter')
    await chooseOption(page, 'Financial export home', 'Home A-101'); await previewExport(page); await expect(page.getByRole('region', { name: 'Financial export preview' })).toContainText('1 financial home · 0 selected sources · 1 output row'); await expect(page.getByRole('button', { name: 'Create reviewed snapshot', exact: true })).toBeDisabled(); await page.getByRole('region', { name: 'Financial export preview' }).scrollIntoViewIfNeeded(); await capture(page, 'empty-preview-' + width); await within(page)
    await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Export records', exact: true })).toBeFocused()
  }
  await page.route('**/api/finance-exports/choices', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"temporarily_unavailable"}' })); await page.getByRole('button', { name: 'Export records', exact: true }).click(); await expect(page.getByRole('button', { name: 'Retry export access', exact: true })).toBeVisible(); await capture(page, 'choices-error-320'); await page.unroute('**/api/finance-exports/choices'); await page.getByRole('button', { name: 'Retry export access', exact: true }).click(); await expect(page.getByRole('combobox', { name: 'Financial export report', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Saved snapshots', exact: true }).click(); await expect(page.getByRole('heading', { name: 'A clear copy starts here.', exact: true })).toBeVisible(); await capture(page, 'empty-saved-320'); await page.getByRole('button', { name: 'Prepare an export', exact: true }).click()
  await page.route('**/api/finance-exports/preview', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"temporarily_unavailable"}' })); await page.getByRole('button', { name: 'Preview export', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('workspace could not be reached'); await capture(page, 'preview-error-320'); await page.unroute('**/api/finance-exports/preview'); await previewExport(page)
  await page.setViewportSize({ width: 320, height: 440 }); await page.getByRole('checkbox', { name: exportCheck, exact: true }).scrollIntoViewIfNeeded(); await capture(page, 'short-phone-preview-actions'); await within(page); await expect(page.getByRole('heading', { name: 'Your records, ready to keep.', exact: true })).toBeVisible(); await page.evaluate(() => document.fonts.ready); expect(await page.evaluate(() => { const heading = document.querySelector('#export-title')!, close = document.querySelector('.finance-export-dialog .dialog-close')!.getBoundingClientRect(), walker = document.createTreeWalker(heading, NodeFilter.SHOW_TEXT); let node; const boxes: DOMRect[] = []; while ((node = walker.nextNode())) { const range = document.createRange(); range.selectNodeContents(node); boxes.push(...range.getClientRects()); } return boxes.filter(box => box.width > 1 && box.top < close.bottom && box.bottom > close.top).every(box => box.right <= close.left - 6); })).toBe(true); await page.getByRole('checkbox', { name: exportCheck, exact: true }).check(); await page.getByRole('button', { name: 'Create reviewed snapshot', exact: true }).scrollIntoViewIfNeeded(); await page.keyboard.press('Tab'); await expect(page.getByRole('button', { name: 'Create reviewed snapshot', exact: true })).toBeFocused(); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0)
  let release!: () => void, captured!: () => void; const held = new Promise<void>(r => { release = r }), reached = new Promise<void>(r => { captured = r }); await page.route('**/api/finance-exports/choices', async route => { captured(); await held; await route.continue().catch(() => {}) }); await page.getByRole('button', { name: 'Export records', exact: true }).click(); await reached; await expect(page.getByRole('dialog').getByRole('status')).toContainText('Opening your permitted export choices'); await capture(page, 'choices-loading-320-short'); release(); await page.unroute('**/api/finance-exports/choices'); await expect(page.getByRole('combobox', { name: 'Financial export report', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Close financial export', exact: true }).click()
})

test('all four human report workflows preserve exact paise originals links and reopen a verified downloadable snapshot', async ({ page, browser }) => {
  const a = await exactExportSources(page, browser)
  try {
    for (const [workspace, report, rows] of [['Entries', 'LEDGER', 13], ['Receipts', 'RECEIPTS', 4], ['Maintenance', 'MAINTENANCE', 4], ['Collections', 'FUNDS', 5]] as const) {
      await openExport(a.owner, workspace); await previewExport(a.owner); const preview = a.owner.getByRole('region', { name: 'Financial export preview' }); await expect(preview).toContainText(rows + ' output rows'); await expect(preview).toContainText('₹32.20'); await expect(preview).toContainText('₹340.00'); if (report === 'FUNDS') await expect(preview).toContainText('₹372.19'); if (report === 'RECEIPTS') await expect(preview).toContainText('₹501.01')
      await a.owner.setViewportSize({ width: report === 'FUNDS' ? 320 : report === 'RECEIPTS' ? 375 : report === 'MAINTENANCE' ? 768 : 1440, height: report === 'FUNDS' ? 440 : 1000 }); await preview.scrollIntoViewIfNeeded(); await capture(a.owner, 'exact-' + report.toLowerCase() + '-preview'); await within(a.owner)
      const snapshot = await createExportUI(a.owner); expect(snapshot).toMatchObject({ report, rows, authority: 'PERSONAL', summary: { current_net_paise: '3220', current_received_paise: '50000', available_received_paise: '34000', opening_credit_paise: '10000' } }); await capture(a.owner, 'ready-' + report.toLowerCase())
      const download = await downloadedCSV(a.owner); expect(download.filename).toBe(`society-${report.toLowerCase()}-2026-01-01-2026-01-31.csv`); expect(createHash('sha256').update(download.bytes).digest('hex')).toBe(snapshot.sha256); expect(download.bytes.length).toBe(snapshot.bytes); expect(download.bytes.toString()).toContain('SCOPE'); expect(download.bytes.toString()).not.toContain('PRIVATE'); if (report === 'RECEIPTS') { expect(download.bytes.toString()).toContain('ENTRY_REVERSAL'); expect(download.bytes.toString()).toContain('1.01') }
      await expect(a.owner.getByRole('dialog').getByRole('status')).toContainText('verified CSV download was started'); await a.owner.keyboard.press('Escape')
    }
    await openExport(a.owner); await a.owner.getByRole('tab', { name: 'Saved snapshots', exact: true }).click(); await expect(a.owner.locator('.export-history-row')).toHaveCount(4); await capture(a.owner, 'saved-history-320-short'); await a.owner.getByRole('button', { name: 'Open saved Original receipt register Your financial homes', exact: true }).click(); const file = await downloadedCSV(a.owner); expect(file.bytes.toString()).toContain('501.01'); await a.owner.getByRole('button', { name: 'Prepare a new export', exact: true }).click(); await expect(a.owner.getByRole('combobox', { name: 'Financial export report', exact: true })).toBeVisible(); await a.owner.keyboard.press('Escape')
  } finally { await a.close() }
})

test('lost create responses keep one operation pending controls lock and download errors cannot become success', async ({ page }) => {
  await login(page); await exportEntry(page, 'RECEIVED', '432.19'); await openExport(page); await previewExport(page); await page.getByRole('checkbox', { name: exportCheck, exact: true }).check()
  let release!: () => void, reached!: () => void; const held = new Promise<void>(r => { release = r }), captured = new Promise<void>(r => { reached = r }); const operations: string[] = []
  await page.route('**/api/finance-exports', async route => { if (route.request().method() !== 'POST') return route.continue(); operations.push(route.request().postDataJSON().operation_key); await route.fetch(); reached(); await held; await route.abort('connectionreset') })
  const creating = page.getByRole('button', { name: 'Create reviewed snapshot', exact: true }); await creating.click(); await captured
  await expect(page.getByRole('button', { name: 'Close financial export', exact: true })).toBeDisabled(); await expect(page.getByRole('combobox', { name: 'Financial export report', exact: true })).toBeDisabled(); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(1); await capture(page, 'create-pending-1440'); release(); await expect(page.getByRole('button', { name: 'Retry this snapshot', exact: true })).toBeVisible(); await capture(page, 'create-lost-response-1440'); await page.unroute('**/api/finance-exports')
  page.on('request', request => { if (new URL(request.url()).pathname === '/api/finance-exports' && request.method() === 'POST') operations.push(request.postDataJSON().operation_key) }); await page.getByRole('button', { name: 'Retry this snapshot', exact: true }).click(); await expect(page.getByRole('button', { name: 'Download reviewed CSV', exact: true })).toBeVisible(); expect(operations).toHaveLength(2); expect(operations[0]).toBe(operations[1]); expect((await (await page.request.get('/api/finance-exports')).json()).total).toBe(1)
  const downloads: string[] = []; page.on('download', download => downloads.push(download.suggestedFilename())); await page.route('**/api/finance-exports/*/download', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"temporarily_unavailable"}' })); await page.getByRole('button', { name: 'Download reviewed CSV', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('could not be downloaded'); await expect(page.getByText('The verified CSV download was started.', { exact: false })).toHaveCount(0); expect(downloads).toEqual([]); await capture(page, 'download-error-1440'); await page.unroute('**/api/finance-exports/*/download')
  await page.route('**/api/finance-exports/*/download', async route => { const response = await route.fetch(); await route.fulfill({ response, body: Buffer.from('wrong bytes') }) }); await page.getByRole('button', { name: 'Download reviewed CSV', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('did not match the reviewed snapshot'); expect(downloads).toEqual([]); await capture(page, 'download-checksum-error-1440'); await page.unroute('**/api/finance-exports/*/download'); await downloadedCSV(page); expect(downloads).toHaveLength(1)
})

test('stale previews and current denied actor home and treasury scope do not replay older exports', async ({ page, browser }) => {
  await login(page); const beforeCount = (await (await page.request.get('/api/finance-exports')).json()).total; await exportEntry(page, 'RECEIVED', '0.01', 'demo-flat-B-101'); await openExport(page); await chooseOption(page, 'Financial export scope', 'One permitted home'); await chooseOption(page, 'Financial export home', 'Home B-101'); await previewExport(page); await page.getByRole('checkbox', { name: exportCheck, exact: true }).check(); await exportEntry(page, 'RECEIVED', '0.10', 'demo-flat-B-101'); await page.getByRole('button', { name: 'Create reviewed snapshot', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('records or selected homes changed'); await capture(page, 'stale-preview-1440'); await expect(page.getByRole('region', { name: 'Financial export preview' })).toHaveCount(0); expect((await (await page.request.get('/api/finance-exports')).json()).total).toBe(beforeCount); await page.getByRole('button', { name: 'Preview export', exact: true }).click(); await expect(page.getByRole('region', { name: 'Financial export preview' })).toContainText('₹0.11'); await page.keyboard.press('Escape')
  const ownerContext = await browser.newContext({ baseURL: new URL(page.url()).origin }), owner = await ownerContext.newPage(), tenantContext = await browser.newContext({ baseURL: new URL(page.url()).origin }), tenant = await tenantContext.newPage()
  try {
    await login(owner, 'Owner'); await openExport(owner); await owner.getByRole('combobox', { name: 'Financial export scope', exact: true }).click(); await expect(owner.getByRole('option', { name: 'Whole society · Treasury access', exact: true })).toHaveCount(0); await owner.keyboard.press('Escape'); await previewExport(owner); const snapshot = await createExportUI(owner)
    messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=date('now') WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101' AND end_date IS NULL\")"); const response = await owner.request.get('/api/finance-exports/' + snapshot.id + '/download'); expect(response.status()).toBe(403); await owner.getByRole('button', { name: 'Download reviewed CSV', exact: true }).click(); await expect(owner.getByRole('dialog')).toHaveCount(0); expect((await (await owner.request.get('/api/finance-exports')).json()).total).toBe(0)
    await login(tenant, 'Tenant'); await tenant.goto('/#entries'); await expect(tenant.getByRole('button', { name: 'Export records', exact: true })).toHaveCount(0); expect((await tenant.request.get('/api/finance-exports/choices')).status()).toBe(403); const guess = await owner.request.post('/api/finance-exports/preview', { headers: await financialHeaders(owner), data: { report: 'LEDGER', scope: 'HOME', home_id: 'demo-flat-B-101', fund_id: '', from: '2026-01-01', to: '2026-01-31' } }); expect(guess.status()).toBe(403)
    const privileged = await apiExport(page, 'LEDGER', 'SOCIETY'); messagePrivateFixture("db.execute(\"UPDATE role_grants SET revoked_at=strftime('%s','now') WHERE user_id='demo-user-admin' AND role='TREASURER' AND revoked_at IS NULL\")"); expect((await page.request.get('/api/finance-exports/' + privileged.id + '/download')).status()).toBe(403); await page.reload(); await expect(page.getByRole('button', { name: 'Export records', exact: true })).toHaveCount(0)
  } finally { messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=NULL WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101'\");db.execute(\"UPDATE role_grants SET revoked_at=NULL WHERE user_id='demo-user-admin' AND role='TREASURER'\")"); await ownerContext.close(); await tenantContext.close() }
})

test('specific fund selection large credit preview and saved pagination exercise their real controls and recover from loading errors', async ({ page, browser }) => {
  const actors = await statementActors(page, browser)
  try {
    const fund = await apiFund(page, 'Specific water fund for export review', { lines: [{ flat_id: 'demo-flat-C-101', amount: '0.01' }] })
    await apiFundAction(actors.reviewer, fund, 'PUBLISHED')
    const other = await apiFund(page, 'Specific garden fund for export review', { lines: [{ flat_id: 'demo-flat-C-101', amount: '0.02' }] })
    await apiFundAction(actors.reviewer, other, 'PUBLISHED')
    await exportEntry(page, 'RECEIVED', '10000000.00', 'demo-flat-C-101')
    await page.setViewportSize({ width: 320, height: 640 }); await openExport(page, 'Collections')
    await chooseOption(page, 'Financial export scope', 'One permitted home'); await chooseOption(page, 'Financial export home', 'Home C-101')
    await page.getByRole('combobox', { name: 'Financial export fund', exact: true }).click()
    await expect(page.getByRole('option', { name: 'All published funds in the range', exact: true })).toHaveAttribute('aria-selected', 'true')
    await page.getByRole('option', { name: 'Specific water fund for export review', exact: true }).hover(); await capture(page, 'specific-fund-menu-320')
    await page.getByRole('option', { name: 'Specific water fund for export review', exact: true }).click()
    await page.getByRole('combobox', { name: 'Financial export fund', exact: true }).click(); await expect(page.getByRole('option', { name: 'Specific water fund for export review', exact: true })).toHaveAttribute('aria-selected', 'true'); await page.keyboard.press('Escape')
    await exportDates(page)
    let release!: () => void, reached!: () => void
    const held = new Promise<void>(r => { release = r }), captured = new Promise<void>(r => { reached = r })
    await page.route('**/api/finance-exports/preview', async route => { const response = await route.fetch(); reached(); await held; await route.fulfill({ response }).catch(() => {}) })
    await page.getByRole('button', { name: 'Preview export', exact: true }).click(); await captured
    await expect(page.getByRole('button', { name: 'Close financial export', exact: true })).toBeDisabled(); await expect(page.getByRole('combobox', { name: 'Financial export fund', exact: true })).toBeDisabled(); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(1); await capture(page, 'preview-pending-320')
    release(); await expect(page.getByRole('region', { name: 'Financial export preview' })).toBeVisible(); await page.unroute('**/api/finance-exports/preview')
    const preview = page.getByRole('region', { name: 'Financial export preview' })
    await expect(preview).toContainText('1 selected source · 2 output rows'); await expect(preview).toContainText('₹0.01'); await expect(preview).toContainText('−₹99,99,999.97'); await expect(preview).toContainText('₹1,00,00,000.00'); await preview.scrollIntoViewIfNeeded(); await within(page); await capture(page, 'large-credit-specific-fund-preview-320')
    await page.keyboard.press('Escape')
    const before = (await (await page.request.get('/api/finance-exports')).json()).total as number
    for (let i = 0; i < 13; i++) await apiExport(page, 'LEDGER', 'SOCIETY')
    await openExport(page)
    await page.route('**/api/finance-exports?page=1', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"temporarily_unavailable"}' }))
    await page.getByRole('tab', { name: 'New export', exact: true }).focus(); await page.keyboard.press('ArrowRight'); await expect(page.getByRole('tab', { name: 'Saved snapshots', exact: true })).toHaveAttribute('aria-selected', 'true'); await expect(page.getByRole('button', { name: 'Retry saved snapshots', exact: true })).toBeVisible(); await capture(page, 'saved-history-error-320'); await page.unroute('**/api/finance-exports?page=1')
    let releaseHistory!: () => void, reachedHistory!: () => void
    const heldHistory = new Promise<void>(r => { releaseHistory = r }), capturedHistory = new Promise<void>(r => { reachedHistory = r })
    await page.route('**/api/finance-exports?page=1', async route => { reachedHistory(); await heldHistory; await route.continue().catch(() => {}) })
    await page.getByRole('button', { name: 'Retry saved snapshots', exact: true }).click(); await capturedHistory; await expect(page.getByRole('dialog').getByRole('status')).toContainText('Opening your saved snapshots'); await capture(page, 'saved-history-loading-320'); releaseHistory(); await expect(page.locator('.export-history-row')).toHaveCount(12); await page.unroute('**/api/finance-exports?page=1')
    await page.getByRole('button', { name: 'Next export snapshots page', exact: true }).click(); await expect(page.locator('.export-history-row')).toHaveCount(before + 13 - 12); await expect(page.getByRole('button', { name: 'Next export snapshots page', exact: true })).toBeDisabled(); await within(page); await capture(page, 'saved-history-second-page-320')
    await page.getByRole('button', { name: 'Previous export snapshots page', exact: true }).click(); await expect(page.locator('.export-history-row')).toHaveCount(12)
    await page.setViewportSize({ width: 1440, height: 1000 }); await page.mouse.click(5, 5); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Export records', exact: true })).toBeFocused()
  } finally { await actors.close() }
})
