import { test, expect } from '@playwright/test'
import type { Page, Browser } from '@playwright/test'
import { mkdirSync, chmodSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { login, navigate, chooseOption } from './helpers'
import { ensureMaintenanceReviewer, financialHeaders } from './maintenance-fixtures'
import { apiFine, apiFineSource, apiFineAction, apiIssuedFine, apiFineReport, apiFineVerify, fineGet, finePost } from './fines-fixtures'
import { careDate } from './upkeep-fixtures'
import { apiIncidentAction } from './incidents-fixtures'
import { plainPDF } from './document-fixtures'

test.setTimeout(90000)

async function capture(page: Page, name: string) {
  if (!process.env.SOCIETY_CAPTURE_UI) return
  await page.evaluate(() => document.fonts.ready)
  const folder = resolve(process.env.SOCIETY_FINE_CAPTURE_ROOT ?? '../reports/local/fines-review')
  mkdirSync(folder, { recursive: true, mode: 0o700 })
  const path = resolve(folder, name + '.png')
  await page.screenshot({ path, animations: 'disabled' }); chmodSync(path, 0o600)
}
async function within(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  if (await page.getByRole('dialog').count()) {
    await expect(page.getByRole('dialog').locator('.dialog-close')).toBeInViewport({ ratio: 1 })
    const separation = await page.getByRole('dialog').evaluate(dialog => {
      const close = dialog.querySelector('.dialog-close')!.getBoundingClientRect()
      return dialog.querySelector('.dialog-scroll')!.getBoundingClientRect().top - close.bottom
    })
    expect(separation).toBeGreaterThanOrEqual(8)
    if (await page.getByRole('dialog').evaluate(dialog => dialog.classList.contains('fine-dialog'))) {
      expect(await page.getByRole('dialog').evaluate(dialog => {
        const close = dialog.querySelector('.dialog-close')!.getBoundingClientRect()
        const bounds = dialog.getBoundingClientRect()
        const target = document.elementFromPoint(bounds.left + 24, close.top + close.height / 2)
        return target === dialog || !!target?.closest('.dialog-close')
      })).toBe(true)
    }
  }
}
async function actors(page: Page, browser: Browser) {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await login(page); await ensureMaintenanceReviewer(page)
  const reviewerContext = await browser.newContext({ baseURL: new URL(page.url()).origin })
  const ownerContext = await browser.newContext({ baseURL: new URL(page.url()).origin })
  const reviewer = await reviewerContext.newPage(), owner = await ownerContext.newPage()
  await reviewer.setViewportSize({ width: 1440, height: 1000 })
  await owner.setViewportSize({ width: 1440, height: 1000 })
  await login(reviewer, 'Committee'); await login(owner, 'Owner')
  return { reviewer, owner, close: async () => { await reviewerContext.close(); await ownerContext.close() } }
}
async function openFine(page: Page, id: string) {
  await page.goto('/#fines?fine=' + id)
  await expect(page.getByRole('dialog').locator('.fine-balance strong')).toBeVisible()
}
async function fineDecision(page: Page, label: string) {
  await chooseOption(page, 'Fine decision', label)
  await page.getByRole('textbox', { name: 'Decision reason', exact: true }).fill('PRIVATE deliberate review of the current supplied source and financial effect.')
  if (label === 'Resolve the current responses') {
    await page.getByLabel('Resolution of current source and responses', { exact: true }).fill('The supplied household response has been considered before this separate charge.')
    await page.getByLabel('Early issuance authority / response decision', { exact: true }).fill('Supplied fictional policy permits a separately considered early decision.')
  }
  await page.getByRole('checkbox', { name: 'I reviewed the current home, amount, supplied authority, responses and this decision’s effect.', exact: true }).check()
  await page.getByRole('button', { name: label, exact: true }).click()
}

test('fine menus tabs empty loading and retry states stay aligned and keyboard usable at four widths', async ({ page }) => {
  await login(page)
  for (const width of [1440, 768, 375, 320]) {
    await page.setViewportSize({ width, height: width <= 375 ? 640 : 1000 })
    await navigate(page, 'Fines & appeals')
    await expect(page.getByRole('heading', { name: 'A considered decision. Every step, together.' })).toBeVisible()
    await page.getByRole('tab', { name: 'Fines', exact: true }).click()
    await page.getByRole('combobox', { name: 'Filter fines by state', exact: true }).click()
    const selected = page.getByRole('option', { name: 'All permitted fines', exact: true })
    await expect(selected).toHaveAttribute('aria-selected', 'true')
    await page.getByRole('option', { name: 'Issued', exact: true }).hover()
    await capture(page, 'empty-open-filter-' + width)
    await page.keyboard.press('End'); await page.keyboard.press('Enter')
    await expect(page.getByRole('combobox', { name: 'Filter fines by state', exact: true })).toBeFocused()
    await page.getByRole('button', { name: 'Clear', exact: true }).click()
    for (const label of ['Household notices', 'Paid reports', 'Appeals', 'Corrections', 'Fines']) {
      await page.getByRole('tab', { name: label, exact: true }).click()
      await expect(page.getByRole('tabpanel').getByRole('heading', { name: 'A clear space, for now.' })).toBeVisible()
    }
    await page.getByRole('tab', { name: 'Fines', exact: true }).focus()
    await page.keyboard.press('ArrowRight')
    await expect(page.getByRole('tab', { name: 'Household notices', exact: true })).toBeFocused()
    await expect(page.getByRole('tab', { name: 'Household notices', exact: true })).toHaveAttribute('aria-selected', 'true')
    await within(page); await capture(page, 'empty-household-' + width)
  }
  await page.route('**/api/fines?*', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{}' }))
  await page.getByRole('tab', { name: 'Fines', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'This workspace is unavailable.', exact: true })).toBeVisible()
  await capture(page, 'list-local-error-320')
  await page.unroute('**/api/fines?*'); await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByRole('tabpanel').getByRole('heading', { name: 'A clear space, for now.' })).toBeVisible()
})

test('a real proposal notice household response and reviewed issuance preserve one exact charge through a lost response', async ({ page, browser }) => {
  const { reviewer, owner, close } = await actors(page, browser)
  const title = 'FINE Supplied corridor amount'
  await apiFineSource(page, reviewer, owner, title)
  await navigate(page, 'Fines & appeals')
  await page.getByRole('button', { name: 'Prepare a fine', exact: true }).click()
  await page.getByRole('combobox', { name: 'Substantiated incident', exact: true }).click()
  await page.getByRole('option').filter({ hasText: title + ' supplied policy' }).click()
  await page.getByLabel('Fine title', { exact: true }).fill(title)
  await page.getByLabel('Supplied amount in rupees', { exact: true }).fill('250.25')
  await page.getByLabel('Amount / authority reference', { exact: true }).fill('Supplied fictional separate authority F-01')
  await page.getByLabel('Household response date', { exact: true }).fill(careDate(3))
  await page.getByLabel('Supplied due date', { exact: true }).fill(careDate(7))
  await page.getByLabel('Household notice wording', { exact: true }).fill('A fictional fine of Rs250.25 is proposed for your household account. Please respond.')
  await page.getByLabel('Private proposal reason', { exact: true }).fill('PRIVATE source and exact amount supplied separately for treasury review.')
  await page.getByRole('button', { name: 'Review proposal', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Review this proposal.', exact: true })).toBeFocused()
  await within(page); await capture(page, 'proposal-review-1440')
  await page.getByRole('dialog').getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Submit fine for review', exact: true }).click()
  await expect(page).toHaveURL(/#fines\?fine=[^?&]+$/)
  await expect(page.getByRole('dialog').getByRole('heading', { name: title, exact: true, level: 2 })).toBeVisible()
  const id = new URLSearchParams(page.url().split('?')[1]).get('fine')!
  expect((await (await page.request.get('/api/entries')).json()).total).toBe(0)
  await expect(page.getByRole('combobox', { name: 'Fine decision', exact: true })).toBeVisible()
  await openFine(reviewer, id); await fineDecision(reviewer, 'Approve household notice')
  await expect(reviewer.getByRole('dialog').getByText('Household notice approved', { exact: true })).toBeVisible()
  const fine = await fineGet(page, id)
  expect((await (await page.request.get('/api/entries')).json()).total).toBe(0)
  await owner.setViewportSize({ width: 375, height: 640 })
  await owner.goto('/#fines?notice=' + fine.notice_id)
  await expect(owner.getByRole('dialog').getByRole('heading', { name: title, exact: true, level: 2 })).toBeVisible()
  await expect(owner.getByRole('dialog')).not.toContainText('PRIVATE')
  await owner.getByLabel('Your response', { exact: true }).fill('My fictional household account was supplied before this considered decision.')
  await owner.getByRole('dialog').getByRole('checkbox').check()
  await within(owner); await capture(owner, 'household-response-375')
  await owner.getByRole('button', { name: 'Send household response', exact: true }).click()
  await expect(owner.getByRole('dialog').getByText('My fictional household account was supplied before this considered decision.', { exact: true })).toBeVisible()
  await reviewer.getByRole('button', { name: 'Refresh fine', exact: true }).click()
  await fineDecision(reviewer, 'Resolve the current responses')
  await expect(reviewer.getByText('This review matches the current source and retained responses.', { exact: true })).toBeVisible()
  let attempts = 0; const bodies: string[] = []
  await reviewer.route('**/api/fines/' + id + '/actions', async route => {
    if (route.request().postDataJSON().action !== 'ISSUE') return route.continue()
    bodies.push(route.request().postData()!); attempts++
    const response = await route.fetch()
    if (attempts === 1) await route.abort('failed'); else await route.fulfill({ response })
  })
  await fineDecision(reviewer, 'Issue reviewed charge')
  await expect(reviewer.getByRole('button', { name: 'Retry this decision', exact: true })).toBeEnabled()
  await expect(reviewer.getByRole('combobox', { name: 'Fine decision', exact: true })).toBeDisabled()
  await expect(reviewer.getByRole('button', { name: 'Close fine details', exact: true })).toBeDisabled()
  await reviewer.keyboard.press('Escape'); await expect(reviewer.getByRole('dialog')).toBeVisible()
  await capture(reviewer, 'issuance-uncertain-lock-1440')
  await reviewer.getByRole('button', { name: 'Retry this decision', exact: true }).click()
  await expect(reviewer.getByRole('dialog').locator('.fine-balance strong')).toHaveText('₹250.25')
  expect(bodies).toHaveLength(2); expect(bodies[0]).toBe(bodies[1])
  const entries = await (await page.request.get('/api/entries')).json()
  expect(entries.total).toBe(1); expect(entries.items[0].amount_paise).toBe(25025)
  expect(entries.items[0].fine_id).toBe(id)
  expect((await (await page.request.get('/api/entries?receipts=true')).json()).items.filter((x: { receipt_id: string }) => x.receipt_id)).toHaveLength(0)
  for (const width of [768, 375, 320]) {
    await reviewer.setViewportSize({ width, height: width === 320 ? 480 : 700 })
    await within(reviewer); await capture(reviewer, 'issued-private-detail-' + width)
  }
  await reviewer.keyboard.press('Escape'); await expect(reviewer.getByRole('dialog')).toHaveCount(0)
  await close()
})

test('already-paid claim and independent review create one original receipt with an explicit allocation', async ({ page, browser }) => {
  const { reviewer, owner, close } = await actors(page, browser)
  const id = await apiIssuedFine(page, reviewer, owner, 'FINE Paid claim for supplied amount')
  await openFine(owner, id)
  await owner.getByRole('button', { name: 'Report money already paid', exact: true }).click()
  await owner.getByLabel('Already-paid amount', { exact: true }).fill('100.00')
  await owner.getByLabel('Payment date', { exact: true }).fill(careDate(0))
  await owner.getByLabel('Payer name', { exact: true }).fill('PRIVATE fictional paid household')
  await chooseOption(owner, 'Fine reported payment method', 'UPI')
  await owner.getByLabel('External payment reference', { exact: true }).fill('FINE-SUPPLIED-PAID-100')
  const originalEvidence = plainPDF()
  await owner.getByRole('button', { name: 'Upload evidence', exact: true }).click()
  await owner.getByLabel('Document file', { exact: true }).setInputFiles({ name: 'fictional-fine-payment.pdf', mimeType: 'application/pdf', buffer: originalEvidence })
  await owner.getByRole('textbox', { name: 'Title', exact: true }).fill('FINE A private supplied payment original')
  await capture(owner, 'fine-evidence-upload-1440')
  await owner.getByRole('button', { name: 'Upload for review', exact: true }).click()
  await expect(owner.getByText('Validated private original', { exact: true })).toBeVisible()
  await expect(owner.getByLabel('Already-paid amount', { exact: true })).toHaveValue('100.00')
  await expect(owner.getByLabel('External payment reference', { exact: true })).toHaveValue('FINE-SUPPLIED-PAID-100')
  await owner.getByRole('combobox', { name: 'Fine payment evidence', exact: true }).click()
  await expect(owner.getByRole('option').filter({ hasText: 'fictional-fine-payment.pdf' })).toHaveAttribute('aria-selected', 'true')
  await capture(owner, 'fine-evidence-retained-selection-1440')
  await owner.keyboard.press('Escape')
  await owner.getByRole('button', { name: 'Review fine payment report', exact: true }).click()
  await owner.getByRole('dialog').getByRole('checkbox').check()
  await capture(owner, 'paid-claim-preview-1440')
  await owner.getByRole('button', { name: 'Send fine payment report', exact: true }).click()
  await expect(owner.getByRole('heading', { name: 'Home A-101', exact: true })).toBeVisible()
  const report = new URLSearchParams(owner.url().split('?')[1]).get('report')!
  expect((await fineGet(page, id)).outstanding_paise).toBe(25025)
  await reviewer.goto('/#fines?report=' + report)
  await expect(reviewer.getByRole('heading', { name: 'Home A-101', exact: true })).toBeVisible()
  await chooseOption(reviewer, 'Fine payment review decision', 'Verify received fine payment')
  await reviewer.getByLabel('Private verification source', { exact: true }).fill('PRIVATE supplied original bank source')
  await reviewer.getByLabel('Private external payment identity', { exact: true }).fill('PRIVATE external row one')
  await reviewer.getByLabel('Explicit amount to allocate to this fine', { exact: true }).fill('100.00')
  await reviewer.getByLabel('Payment decision reason', { exact: true }).fill('PRIVATE confirmed external money and deliberate allocation are separately checked.')
  await reviewer.getByRole('dialog').getByRole('checkbox').check()
  await capture(reviewer, 'paid-verification-preview-1440')
  await reviewer.getByRole('button', { name: 'Verify received fine payment', exact: true }).click()
  await expect(reviewer.getByRole('dialog').getByText('The independently verified payment keeps its original receipt.', { exact: true })).toBeVisible()
  const paid = await (await page.request.get('/api/fine-reports/' + report)).json()
  expect(paid.receipt).toBeTruthy()
  expect(paid.evidence_id).toBeTruthy()
  const evidenceDownload = owner.waitForEvent('download')
  await owner.getByRole('link', { name: 'Download supplied evidence', exact: true }).click()
  expect(readFileSync((await (await evidenceDownload).path())!)).toEqual(originalEvidence)
  const current = await fineGet(page, id)
  expect(current.allocated_paise).toBe(10000); expect(current.outstanding_paise).toBe(15025)
  await owner.getByRole('button', { name: 'Refresh payment report', exact: true }).click()
  await expect(owner.getByRole('dialog').getByText('The independently verified payment keeps its original receipt.', { exact: true })).toBeVisible()
  await expect(owner.getByRole('dialog')).not.toContainText('PRIVATE supplied original bank source')
  await owner.setViewportSize({ width: 320, height: 480 }); await within(owner); await capture(owner, 'original-fine-receipt-320')
  await owner.getByRole('link', { name: 'Open original receipt', exact: true }).click()
  await expect(owner).toHaveURL(new RegExp('#receipts\\?entry=' + paid.entry_id + '$'))
  await expect(owner.getByRole('dialog').locator('.record-facts').first()).toContainText(paid.receipt)
  await expect(owner.getByRole('dialog').getByRole('button', { name: 'Download PDF', exact: true })).toBeEnabled({ timeout: 10000 })
  await within(owner); await capture(owner, 'original-receipt-download-320')
  const receiptDownload = owner.waitForEvent('download')
  await owner.getByRole('button', { name: 'Download PDF', exact: true }).click()
  const receipt = await receiptDownload
  expect(receipt.suggestedFilename()).toBe(paid.receipt + '.pdf')
  const receiptBytes = readFileSync((await receipt.path())!)
  expect(receiptBytes.subarray(0, 5).toString()).toBe('%PDF-')
  const originalResponse = await owner.request.get('/api/receipts/' + paid.receipt_id + '/download')
  expect(originalResponse.status()).toBe(200)
  expect(createHash('sha256').update(receiptBytes).digest('hex')).toBe(createHash('sha256').update(await originalResponse.body()).digest('hex'))
  expect((await fineGet(page, id)).outstanding_paise).toBe(15025)
  await close()
})

test('a nonfinancial household submits an appeal while an independent reviewer deliberately pauses and resolves collection', async ({ page, browser }) => {
  const { reviewer, owner, close } = await actors(page, browser)
  const id = await apiIssuedFine(page, reviewer, owner, 'FINE Tenant appeal and explicit pause', 'demo-flat-A-103')
  const fine = await fineGet(page, id)
  const context = await browser.newContext({ baseURL: new URL(page.url()).origin }), tenant = await context.newPage()
  await login(tenant, 'Tenant'); await tenant.setViewportSize({ width: 320, height: 480 })
  await tenant.goto('/#fines?notice=' + fine.notice_id)
  await expect(tenant.getByRole('button', { name: 'Submit your appeal', exact: true })).toBeVisible()
  await expect(tenant.getByRole('button', { name: 'Open current financial position', exact: true })).toHaveCount(0)
  await expect(tenant.getByRole('tab', { name: 'Fines', exact: true })).toHaveCount(0)
  await tenant.getByRole('button', { name: 'Submit your appeal', exact: true }).click()
  await tenant.getByLabel('Your appeal', { exact: true }).fill('My fictional household requests a considered review of the supplied amount.')
  await tenant.getByRole('button', { name: 'Review fine appeal', exact: true }).click()
  await tenant.getByRole('dialog').getByRole('checkbox').check()
  await within(tenant); await capture(tenant, 'nonfinancial-appeal-preview-320')
  await tenant.getByRole('button', { name: 'Edit appeal', exact: true }).click()
  await tenant.getByRole('button', { name: 'Review fine appeal', exact: true }).click()
  await expect(tenant.getByRole('dialog').getByRole('checkbox')).not.toBeChecked()
  await tenant.getByRole('dialog').getByRole('checkbox').check()
  await tenant.getByRole('button', { name: 'Submit fine appeal', exact: true }).click()
  await expect(tenant).toHaveURL(/#fines\?appeal=[^?&]+$/)
  const appeal = new URLSearchParams(tenant.url().split('?')[1]).get('appeal')!
  await reviewer.goto('/#fines?appeal=' + appeal)
  await chooseOption(reviewer, 'Fine appeal decision', 'Record an explicit collection pause')
  await reviewer.getByLabel('Supplied appeal / pause authority', { exact: true }).fill('Supplied fictional separate pause reference P-01')
  await reviewer.getByLabel('Explicit pause until', { exact: true }).fill(careDate(4))
  await reviewer.getByLabel('Appeal decision reason', { exact: true }).fill('Consider the supplied household account while preserving the exact existing charge.')
  await reviewer.getByRole('dialog').getByRole('checkbox').check()
  await reviewer.setViewportSize({ width: 375, height: 640 })
  await within(reviewer); await capture(reviewer, 'explicit-pause-preview-375')
  await reviewer.getByRole('button', { name: 'Record an explicit collection pause', exact: true }).click()
  await expect(reviewer.getByRole('dialog').locator('.fine-detail-tools .fund-state')).toHaveText('Collection paused')
  let current = await fineGet(page, id)
  expect(current.active_paise).toBe(25025); expect(current.outstanding_paise).toBe(25025); expect(current.pause_until).toBe(careDate(4))
  await chooseOption(reviewer, 'Fine appeal decision', 'Resolve this appeal')
  await reviewer.getByLabel('Supplied appeal / pause authority', { exact: true }).fill('Supplied fictional resolution reference P-02')
  await reviewer.getByLabel('Appeal decision reason', { exact: true }).fill('The supplied household account is deliberately resolved without changing the charge.')
  await reviewer.getByRole('dialog').getByRole('checkbox').check()
  await reviewer.getByRole('button', { name: 'Resolve this appeal', exact: true }).click()
  await expect(reviewer.getByRole('dialog').locator('.fine-detail-tools .fund-state')).toHaveText('Resolved')
  current = await fineGet(page, id); expect(current.active_paise).toBe(25025); expect(current.pause_until).toBeFalsy()
  await tenant.getByRole('button', { name: 'Refresh appeal', exact: true }).click()
  await expect(tenant.getByRole('dialog').locator('.fine-detail-tools .fund-state')).toHaveText('Resolved')
  await expect(tenant.getByRole('combobox', { name: 'Fine appeal decision', exact: true })).toHaveCount(0)
  await within(tenant); await capture(tenant, 'nonfinancial-resolved-appeal-320')
  await context.close(); await close()
})

test('a supplied partial correction needs another reviewer preserves the original receipt and releases credit without reallocating it', async ({ page, browser }) => {
  const { reviewer, owner, close } = await actors(page, browser)
  const id = await apiIssuedFine(page, reviewer, owner, 'FINE Retained partial correction')
  const report = await apiFineReport(owner, id), paid = await apiFineVerify(reviewer, report)
  await openFine(page, id)
  await page.getByRole('button', { name: 'Prepare a linked correction', exact: true }).click()
  await page.getByLabel('Supplied waiver amount', { exact: true }).fill('75.25')
  await page.getByLabel('Supplied correction authority', { exact: true }).fill('Supplied fictional independent correction C-01')
  await page.getByLabel('Private correction reason', { exact: true }).fill('PRIVATE supplied reduction against the current retained fine charge.')
  await page.getByRole('button', { name: 'Review fine correction', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('₹175.00')
  await expect(page.getByRole('dialog')).toContainText('₹100.00')
  await page.getByRole('dialog').getByRole('checkbox').check()
  await capture(page, 'partial-correction-preview-1440')
  await page.getByRole('button', { name: 'Submit fine correction for review', exact: true }).click()
  await expect(page).toHaveURL(/#fines\?correction=[^?&]+$/)
  const correction = new URLSearchParams(page.url().split('?')[1]).get('correction')!
  await expect(page.getByRole('combobox', { name: 'Fine correction decision', exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: 'Fine correction decision', exact: true }).click()
  await expect(page.getByRole('option', { name: 'Approve linked fine correction', exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await reviewer.goto('/#fines?correction=' + correction)
  await chooseOption(reviewer, 'Fine correction decision', 'Approve linked fine correction')
  await reviewer.getByLabel('Correction decision reason', { exact: true }).fill('PRIVATE independent reviewer checks the live charge and released original credit.')
  await reviewer.getByRole('dialog').getByRole('checkbox').check()
  for (const width of [768, 375, 320]) {
    await reviewer.setViewportSize({ width, height: width === 320 ? 480 : 700 })
    await reviewer.getByRole('button', { name: 'Approve linked fine correction', exact: true }).scrollIntoViewIfNeeded()
    await within(reviewer); await capture(reviewer, 'correction-approval-preview-' + width)
  }
  await reviewer.getByRole('button', { name: 'Approve linked fine correction', exact: true }).click()
  await expect(reviewer.getByRole('dialog').getByText('Approved', { exact: true })).toBeVisible()
  const current = await fineGet(page, id)
  expect(current.active_paise).toBe(17500); expect(current.allocated_paise).toBe(0); expect(current.outstanding_paise).toBe(17500)
  const afterPaid = await (await page.request.get('/api/fine-reports/' + report)).json()
  expect(afterPaid.receipt).toBe(paid.receipt); expect(afterPaid.entry_id).toBe(paid.entry_id)
  await openFine(owner, id); await owner.getByRole('button', { name: 'Home statement & credit', exact: true }).click()
  await expect(owner.getByRole('dialog')).toContainText('₹175.00')
  await expect(owner.getByRole('dialog')).toContainText('₹100.00')
  await capture(owner, 'released-original-credit-statement-1440')
  const entries = await (await page.request.get('/api/entries?home=demo-flat-A-101')).json()
  expect(entries.items.filter((x: { id: string }) => x.id === current.original_entry_id)).toHaveLength(1)
  await close()
})

test('new household responses invalidate a prepared resolution and require a fresh ordinary review while private notes remain private', async ({ page, browser }) => {
  const { reviewer, owner, close } = await actors(page, browser)
  const title = 'FINE Response race requiring renewed review'
  const source = await apiFineSource(page, reviewer, owner, title)
  const id = await apiFine(page, source, title)
  await apiFineAction(reviewer, id, 'NOTIFY'); await apiFineAction(reviewer, id, 'RESOLVE')
  const fine = await fineGet(page, id)
  await openFine(reviewer, id)
  await chooseOption(reviewer, 'Fine decision', 'Issue reviewed charge')
  const reason = 'PRIVATE retained reason written against the earlier reviewed response context.'
  await reviewer.getByLabel('Decision reason', { exact: true }).fill(reason)
  await reviewer.getByRole('dialog').getByRole('checkbox').check()
  await finePost(owner, '/api/fine-notices/' + fine.notice_id + '/responses', { version: 1, body: 'A newer private household response requires a fresh deliberate resolution.' })
  await reviewer.getByRole('button', { name: 'Issue reviewed charge', exact: true }).click()
  await expect(reviewer.getByRole('dialog').getByRole('alert')).toBeVisible()
  await expect(reviewer.getByRole('button', { name: 'Reload current record', exact: true })).toBeEnabled()
  await capture(reviewer, 'stale-resolution-blocked-1440')
  await reviewer.getByRole('button', { name: 'Reload current record', exact: true }).click()
  await chooseOption(reviewer, 'Fine decision', 'Resolve the current responses')
  await expect(reviewer.getByRole('textbox', { name: 'Decision reason', exact: true })).toHaveValue(reason)
  await expect(reviewer.getByRole('dialog').getByRole('checkbox')).not.toBeChecked()
  await expect(reviewer.getByRole('dialog')).toContainText('A fresh review is required before issuance.')
  await expect(reviewer.getByRole('combobox', { name: 'Fine decision', exact: true })).toBeEnabled()
  const unchanged = await fineGet(page, id)
  expect(unchanged.original_entry_id).toBeFalsy(); expect(unchanged.state).toBe('NOTIFIED')
  await fineDecision(reviewer, 'Resolve the current responses'); await fineDecision(reviewer, 'Issue reviewed charge')
  expect((await fineGet(page, id)).active_paise).toBe(25025)
  await openFine(owner, id); await expect(owner.getByRole('dialog')).not.toContainText('PRIVATE')
  await capture(owner, 'resident-issued-projection-1440')
  await close()
})

test('ending a tagged home denies retained notices and appeals while a changed financial flag retains household participation', async ({ page, browser }) => {
  const { reviewer, owner, close } = await actors(page, browser)
  const id = await apiIssuedFine(page, reviewer, owner, 'FINE Current-home access boundaries')
  const fine = await fineGet(page, id), path = process.env.SOCIETY_BROWSER_DB
  if (!path || !path.includes('society-browser-')) throw new Error('A disposable financial-scope fixture is required.')
  const change = (financial: number, ended: string | null) => execFileSync('python3', ['-c', "import sqlite3,sys;db=sqlite3.connect(sys.argv[1]);r=db.execute(\"UPDATE flat_memberships SET can_view_finances=?,end_date=? WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101'\",(int(sys.argv[2]),None if sys.argv[3]=='none' else sys.argv[3]));assert r.rowcount==1;db.commit()", path, String(financial), ended ?? 'none'])
  try {
    change(0, null); await owner.goto('/#fines?notice=' + fine.notice_id)
    await expect(owner.getByLabel('Your response', { exact: true })).toBeVisible()
    await expect(owner.getByRole('button', { name: 'Open current financial position', exact: true })).toHaveCount(0)
    expect((await owner.request.get('/api/fines/' + id)).status()).toBe(404)
    const result = await owner.request.post('/api/fine-notices/' + fine.notice_id + '/responses', { headers: await financialHeaders(owner), data: { operation_key: crypto.randomUUID(), version: 1, body: 'Current household participation remains permitted without financial access.', confirmed: true } })
    expect(result.status()).toBe(200)
    change(0, careDate(0)); await owner.reload()
    await expect(owner.getByRole('dialog').getByRole('heading', { name: 'Notice unavailable', exact: true })).toBeVisible()
    await expect(owner.getByRole('dialog').getByRole('alert')).toBeVisible()
    await capture(owner, 'ended-home-denied-notice-1440')
    expect((await owner.request.get('/api/fine-notices/' + fine.notice_id)).status()).toBe(404)
  } finally { change(1, null); await close() }
})

test('withdrawal retained replacement and independent decline cancel only the notice while preserving every unissued preparation', async ({ page, browser }) => {
  const { reviewer, owner, close } = await actors(page, browser)
  const title = 'FINE Retained withdrawn preparation'
  const source = await apiFineSource(page, reviewer, owner, title), first = await apiFine(page, source, title)
  await openFine(page, first); await fineDecision(page, 'Withdraw proposal')
  await expect(page.getByRole('dialog').locator('.fine-detail-tools .fund-state')).toHaveText('Withdrawn')
  await page.getByRole('button', { name: 'Prepare a retained replacement', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Substantiated incident', exact: true })).toHaveCount(0)
  await page.getByLabel('Fine title', { exact: true }).fill('FINE Retained declined replacement')
  await page.getByLabel('Supplied amount in rupees', { exact: true }).fill('100.25')
  await page.getByRole('textbox', { name: 'Household notice wording', exact: true }).fill('A fictional fine of Rs100.25 is proposed for your household account. Please respond.')
  await page.getByLabel('Household response date', { exact: true }).fill(careDate(3))
  await page.getByLabel('Supplied due date', { exact: true }).fill(careDate(7))
  await page.getByLabel('Private proposal reason', { exact: true }).fill('A supplied replacement remains linked to the withdrawn preparation.')
  await page.getByRole('button', { name: 'Review proposal', exact: true }).click()
  await page.getByRole('dialog').getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Submit fine for review', exact: true }).click()
  await expect(page).toHaveURL(/#fines\?fine=[^?&]+$/)
  await expect.poll(() => new URLSearchParams(page.url().split('?')[1]).get('fine')).not.toBe(first)
  const second = new URLSearchParams(page.url().split('?')[1]).get('fine')!
  expect(second).not.toBe(first)
  const fine = await fineGet(page, second); expect(fine.replaces_id).toBe(first); expect(fine.amount_paise).toBe(10025)
  await openFine(reviewer, second); await fineDecision(reviewer, 'Approve household notice')
  await expect(reviewer.getByRole('dialog').locator('.fine-detail-tools .fund-state')).toHaveText('Household notice approved')
  await fineDecision(reviewer, 'Decline proposal')
  await expect(reviewer.getByRole('dialog').locator('.fine-detail-tools .fund-state')).toHaveText('Declined')
  const declined = await fineGet(page, second)
  await owner.goto('/#fines?notice=' + declined.notice_id)
  await expect(owner.getByRole('dialog')).toContainText('This retained notice was cancelled. Responses are closed.')
  await expect(owner.getByRole('textbox', { name: 'Your response', exact: true })).toHaveCount(0)
  await expect(owner.getByRole('dialog')).not.toContainText('PRIVATE')
  await owner.setViewportSize({ width: 375, height: 640 }); await within(owner); await capture(owner, 'retained-cancelled-household-notice-375')
  expect((await fineGet(page, first)).original_entry_id).toBeFalsy()
  expect(declined.original_entry_id).toBeFalsy(); expect(declined.state).toBe('DECLINED')
  await close()
})

test('payment clarification revision and duplicate linking use the original money without a second receipt or allocation', async ({ page, browser }) => {
  const { reviewer, owner, close } = await actors(page, browser)
  const id = await apiIssuedFine(page, reviewer, owner, 'FINE Clarified paid claim and original duplicate')
  const report = await apiFineReport(owner, id)
  await reviewer.goto('/#fines?report=' + report)
  await chooseOption(reviewer, 'Fine payment review decision', 'Ask for more information')
  await reviewer.getByRole('textbox', { name: 'Payment decision reason', exact: true }).fill('PRIVATE a supplied original payment detail needs deliberate clarification.')
  await reviewer.getByRole('dialog').getByRole('checkbox').check()
  await reviewer.getByRole('button', { name: 'Ask for more information', exact: true }).click()
  await expect(reviewer.getByRole('dialog')).toContainText('More information needed')
  await owner.goto('/#fines?report=' + report)
  await owner.getByRole('button', { name: 'Revise this fine payment report', exact: true }).click()
  await owner.getByRole('textbox', { name: 'Supporting comment (optional)', exact: true }).fill('The household supplied its original external payment clarification.')
  await owner.getByRole('button', { name: 'Review fine payment report', exact: true }).click()
  await owner.getByRole('dialog').getByRole('checkbox').check()
  await owner.getByRole('button', { name: 'Send revised fine payment report', exact: true }).click()
  await expect(owner.getByRole('dialog')).toContainText('Awaiting verification')
  const paid = await apiFineVerify(reviewer, report)
  const duplicate = await apiFineReport(owner, id, { reference: paid.reference, payer: paid.payer, method: paid.method, payment_date: paid.payment_date })
  await reviewer.goto('/#fines?report=' + duplicate)
  await chooseOption(reviewer, 'Fine payment review decision', 'Verify received fine payment')
  await chooseOption(reviewer, 'Fine original receipt handling', 'Link a compatible original receipt')
  await reviewer.getByRole('combobox', { name: 'Compatible fine payment receipt', exact: true }).click()
  await reviewer.getByRole('option').filter({ hasText: paid.receipt }).click()
  await reviewer.getByRole('textbox', { name: 'Explicit amount to allocate to this fine', exact: true }).fill('0.00')
  await reviewer.getByRole('textbox', { name: 'Payment decision reason', exact: true }).fill('PRIVATE this is a duplicate report of the already retained original money.')
  await reviewer.getByRole('dialog').getByRole('checkbox').check()
  await reviewer.setViewportSize({ width: 375, height: 640 }); await within(reviewer); await capture(reviewer, 'duplicate-original-receipt-preview-375')
  await reviewer.getByRole('button', { name: 'Verify received fine payment', exact: true }).click()
  await expect(reviewer.getByRole('dialog')).toContainText('Original receipt linked')
  const result = await (await page.request.get('/api/fine-reports/' + duplicate)).json()
  expect(result.state).toBe('DUPLICATE'); expect(result.receipt).toBe(paid.receipt); expect(result.entry_id).toBe(paid.entry_id)
  const current = await fineGet(page, id)
  expect(current.active_paise).toBe(25025); expect(current.allocated_paise).toBe(10000); expect(current.outstanding_paise).toBe(15025)
  await close()
})

test('a full live-charge reversal requires an independent decision and retains paid money as available credit', async ({ page, browser }) => {
  const { reviewer, owner, close } = await actors(page, browser)
  const id = await apiIssuedFine(page, reviewer, owner, 'FINE Full considered correction')
  const report = await apiFineReport(owner, id), paid = await apiFineVerify(reviewer, report)
  await openFine(page, id); await page.getByRole('button', { name: 'Prepare a linked correction', exact: true }).click()
  await chooseOption(page, 'Fine correction type', 'Remove the full live charge')
  await page.getByRole('textbox', { name: 'Supplied correction authority', exact: true }).fill('Supplied fictional full reversal source C-02')
  await page.getByRole('textbox', { name: 'Private correction reason', exact: true }).fill('PRIVATE the supplied full removal preserves the paid money and original receipt.')
  await page.getByRole('button', { name: 'Review fine correction', exact: true }).click()
  await page.getByRole('dialog').getByRole('checkbox').check()
  await capture(page, 'full-reversal-preview-1440')
  await page.getByRole('button', { name: 'Submit fine correction for review', exact: true }).click()
  await expect(page).toHaveURL(/#fines\?correction=[^?&]+$/)
  const correction = new URLSearchParams(page.url().split('?')[1]).get('correction')!
  await reviewer.goto('/#fines?correction=' + correction)
  await chooseOption(reviewer, 'Fine correction decision', 'Approve linked fine correction')
  await reviewer.getByRole('textbox', { name: 'Correction decision reason', exact: true }).fill('PRIVATE independently reviewed full removal with the original received money retained.')
  await reviewer.getByRole('dialog').getByRole('checkbox').check()
  await reviewer.getByRole('button', { name: 'Approve linked fine correction', exact: true }).click()
  await expect(reviewer.getByRole('dialog')).toContainText('Approved')
  const current = await fineGet(page, id)
  expect(current.state).toBe('WAIVED'); expect(current.active_paise).toBe(0); expect(current.outstanding_paise).toBe(0)
  expect(current.current_entry_id).toBeFalsy(); expect(current.waived_paise).toBe(25025)
  const original = await (await page.request.get('/api/fine-reports/' + report)).json()
  expect(original.receipt).toBe(paid.receipt); expect(original.entry_id).toBe(paid.entry_id)
  await openFine(owner, id); await expect(owner.getByRole('dialog').locator('.fine-balance strong')).toHaveText('₹0.00')
  await capture(owner, 'fully-waived-resident-original-1440')
  await close()
})

test('paging source responses invalidates the attestation when an operational household reply changes the reviewed context', async ({ page, browser }) => {
  const { reviewer, owner, close } = await actors(page, browser)
  const title = 'FINE Bounded operational response context'
  const incident = await apiFineSource(page, reviewer, owner, title)
  const sourceNotice = await apiIncidentAction(reviewer, incident, 'ISSUE_NOTICE', { title: 'Supplied source response notice', body: 'Please provide the fictional shared-access household account.', response_by: careDate(3) })
  const notice = await (await owner.request.get('/api/incident-notices/' + sourceNotice.notice_id)).json()
  const reply = async (body: string) => finePost(owner, '/api/incident-notices/' + sourceNotice.notice_id + '/responses', { version: notice.version, body })
  for (let i = 0; i < 22; i++) await reply('PRIVATE separately retained fictional operational response ' + i)
  const id = await apiFine(page, incident, title)
  await apiFineAction(reviewer, id, 'NOTIFY'); await apiFineAction(reviewer, id, 'RESOLVE')
  await openFine(reviewer, id)
  await chooseOption(reviewer, 'Fine decision', 'Issue reviewed charge')
  await reviewer.getByRole('textbox', { name: 'Decision reason', exact: true }).fill('PRIVATE earlier reviewed operational context must be reconsidered if it changes.')
  await reviewer.getByRole('dialog').getByRole('checkbox').check()
  await reply('PRIVATE later operational household response invalidates the earlier financial review.')
  await reviewer.getByRole('button', { name: 'Next source responses page', exact: true }).click()
  await expect(reviewer.getByRole('region', { name: 'Supplied incident decision', exact: true }).getByRole('alert')).toContainText('The source has changed.')
  await expect(reviewer.getByRole('dialog').getByRole('checkbox')).not.toBeChecked()
  await expect(reviewer.getByRole('dialog').getByRole('checkbox')).toBeDisabled()
  await expect(reviewer.getByRole('button', { name: 'Issue reviewed charge', exact: true })).toBeDisabled()
  await reviewer.setViewportSize({ width: 375, height: 640 })
  await reviewer.getByRole('region', { name: 'Supplied incident decision', exact: true }).getByRole('alert').scrollIntoViewIfNeeded()
  await within(reviewer); await capture(reviewer, 'bounded-source-change-blocked-375')
  await reviewer.getByRole('button', { name: 'Previous source responses page', exact: true }).click()
  await expect(reviewer.getByRole('dialog').getByRole('checkbox')).toBeDisabled()
  await reviewer.getByRole('button', { name: 'Reload current context', exact: true }).click()
  await expect(reviewer.getByRole('dialog')).toContainText('A fresh review is required before issuance.')
  const current = await fineGet(page, id); expect(current.response_total).toBe(23); expect(current.original_entry_id).toBeFalsy()
  await chooseOption(reviewer, 'Fine decision', 'Resolve the current responses')
  await expect(reviewer.getByRole('dialog').getByRole('checkbox')).not.toBeChecked()
  await expect(reviewer.getByRole('dialog').getByRole('checkbox')).toBeEnabled()
  await close()
})
