import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mkdirSync, chmodSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { login, navigate, completePreviewMFA, chooseFilter, chooseOption } from './helpers'

const password = 'Community-preview-2026!'
const verifiedLabel = 'I verified this person’s identity, email and home relationship.'

async function capture(page: Page, name: string) {
  if (!process.env.SOCIETY_CAPTURE_UI) return
  await page.evaluate(() => document.fonts.ready)
  const folder = resolve('../reports/local/interaction-review')
  mkdirSync(folder, { recursive: true, mode: 0o700 })
  const path = resolve(folder, name + '.png')
  await page.screenshot({ path })
  chmodSync(path, 0o600)
}
async function signIn(page: Page, email: string, value: string) {
  await page.getByLabel('Email address', { exact: true }).fill(email)
  await page.getByLabel('Password', { exact: true }).fill(value)
  const response = page.waitForResponse(response => response.url().endsWith('/api/auth/login'))
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  expect((await response).status()).toBe(200)
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toHaveCount(0)
  await completePreviewMFA(page)
  await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeVisible()
}
async function prepareInvitation(page: Page, name: string, email: string, role = 'RESIDENT') {
  await page.getByRole('button', { name: 'Invite a person', exact: true }).click()
  await page.getByLabel('Find a person').fill(name)
  await chooseOption(page, 'Person in the registry', name)
  await page.getByLabel('Email address', { exact: true }).fill(email)
  await chooseOption(page, 'Access', role)
  if (role !== 'RESIDENT') await page.getByLabel('Access term (days)').fill('30')
  await page.getByRole('checkbox', { name: verifiedLabel }).check()
  await page.getByLabel('Verification note').fill('Fictional identity verified for isolated interaction QA.')
}
async function issueLink(page: Page) {
  await page.getByRole('button', { name: 'Create personal link', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Their door is open.' })).toBeVisible()
  return page.getByLabel('Personal link', { exact: true }).inputValue()
}

test('login controls, validation, help and busy feedback work', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Show password', exact: true }).click()
  await expect(page.getByLabel('Password', { exact: true })).toHaveAttribute('type', 'text')
  await page.getByRole('button', { name: 'Hide password', exact: true }).click()
  await expect(page.getByLabel('Password', { exact: true })).toHaveAttribute('type', 'password')
  const help = page.getByRole('button', { name: 'Need access or forgot your password?' })
  await help.click()
  await expect(help).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('.help-note')).toBeVisible()
  await help.click()
  await expect(page.locator('.help-note')).toHaveCount(0)
  for (const [label, email] of [['Committee', 'committee'], ['Owner', 'owner'], ['Tenant', 'tenant'], ['Registry officer', 'admin']]) {
    await page.getByRole('button', { name: new RegExp('^' + label) }).click()
    await expect(page.getByLabel('Email address')).toHaveValue(email + '@demo.society')
    await expect(page.getByLabel('Password', { exact: true })).toHaveValue(password)
  }
  await page.getByLabel('Email address').fill('not-an-email')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  expect(await page.getByLabel('Email address').evaluate((el: HTMLInputElement) => el.validity.typeMismatch)).toBe(true)
  await page.getByLabel('Email address').fill('admin@demo.society')
  await page.getByLabel('Password', { exact: true }).fill('An incorrect fictional password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('didn’t match')
  await capture(page, 'login-error')
  await page.getByRole('button', { name: /^Registry officer/ }).click()
  let release = () => {}
  const pending = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/auth/login', async route => { await pending; await route.continue() })
  try {
    await page.getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Opening your workspace…', exact: true })).toBeDisabled()
    await expect(page.getByRole('button', { name: /^Owner/ })).toBeDisabled()
  } finally { release() }
  await expect(page.getByRole('button', { name: 'Verify and continue', exact: true })).toBeVisible()
  await completePreviewMFA(page)
})

test('shell links, About, backdrop, focus, history and committee access work', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await login(page)
  await expect(page.getByRole('link', { name: 'Documents', exact: true })).toHaveAttribute('href', '#documents')
  await expect(page.getByRole('link', { name: 'Community', exact: true })).toHaveAttribute('href', '#community')
  await expect(page.getByRole('link', { name: 'Requests & approvals', exact: true })).toHaveAttribute('href', '#reviews')
  await page.locator('.workspace-profile').click()
  await expect(page.getByRole('heading', { name: 'A little less admin. A lot more living.' })).toBeVisible()
  await page.getByRole('button', { name: 'Make yourself at home', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.workspace-profile')).toBeFocused()
  await page.getByRole('button', { name: 'About this preview', exact: true }).click()
  await capture(page, 'about-desktop')
  for (let i = 0; i < 4; i++) {
    await page.keyboard.press('Tab')
    expect(await page.getByRole('dialog').evaluate(el => el.contains(document.activeElement))).toBe(true)
  }
  await page.mouse.click(4, 4)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'About this preview', exact: true })).toBeFocused()
  await navigate(page, 'Homes & people')
  await expect(page.getByRole('status')).toHaveText('118 homes found')
  await page.getByRole('link', { name: 'Society OS overview', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your community, a little closer.' })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Every home has a story.', exact: true })).toBeVisible()
  await page.goForward()
  await expect(page.getByRole('heading', { name: 'Your community, a little closer.' })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await login(page, 'Committee')
  await navigate(page, 'Homes & people')
  await page.getByRole('button', { name: 'View home A-103', exact: true }).click()
  await expect(page.getByText('Demo Former Tenant A-103', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Manage home', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Close details', exact: true }).click()
  await navigate(page, 'Account security')
  await expect(page.getByRole('heading', { name: 'Account security.' })).toBeVisible()
  expect((await page.request.get('/api/admin/accounts')).status()).toBe(403)
})

test('overview routes, every filter and all 118 home cards work across ten pages', async ({ page }) => {
  test.setTimeout(120000)
  await login(page)
  for (const [wing, count] of [['A', 40], ['B', 40], ['C', 38]] as const) {
    await page.getByRole('button', { name: `Explore Wing ${wing}, ${count} homes`, exact: true }).click()
    await expect(page.getByRole('status')).toHaveText(`${count} homes found`)
    await navigate(page, 'Overview')
  }
  await page.getByRole('link', { name: 'See all homes', exact: true }).click()
  await expect.soft(page.getByRole('status')).toHaveText('118 homes found')
  await chooseFilter(page, 'Filter by wing', '')
  for (const [wing, count] of [['A', 40], ['B', 40], ['C', 38]] as const) {
    const card = page.getByRole('button', { name: `Explore Wing ${wing}, ${count} homes`, exact: true })
    await card.click()
    await expect(card).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByRole('status')).toHaveText(`${count} homes found`)
    await card.click()
    await expect(card).toHaveAttribute('aria-pressed', 'false')
    await expect(page.getByRole('status')).toHaveText('118 homes found')
  }
  for (const [occupancy, count] of [['OWNER_OCCUPIED', 74], ['RENTED', 35], ['VACANT', 9]] as const) {
    await chooseFilter(page, 'Filter by occupancy', occupancy)
    await expect(page.getByRole('status')).toHaveText(`${count} homes found`)
  }
  await chooseFilter(page, 'Filter by wing', 'C')
  await page.getByRole('button', { name: 'Clear', exact: true }).click()
  await expect(page.getByLabel('Filter by wing')).toHaveText('All wings')
  await expect(page.getByLabel('Filter by occupancy')).toHaveText('All occupancy')
  await expect(page.getByRole('status')).toHaveText('118 homes found')
  const visited = new Set<string>()
  await expect(page.getByRole('button', { name: 'Previous page', exact: true })).toBeDisabled()
  for (let number = 1; number <= 10; number++) {
    await expect(page.getByText(`Page ${number} of 10`, { exact: true })).toBeVisible()
    const cards = page.locator('.home-card')
    const count = await cards.count()
    for (let index = 0; index < count; index++) {
      const card = cards.nth(index)
      const label = (await card.getAttribute('aria-label'))!
      visited.add(label)
      await card.click()
      await expect(page.getByRole('heading', { name: 'Home ' + label.split('-').at(-1), exact: true })).toBeVisible()
      await page.getByRole('button', { name: 'Close details', exact: true }).click()
      await expect(card).toBeFocused()
    }
    if (number < 10) await page.getByRole('button', { name: 'Next page', exact: true }).click()
  }
  expect(visited.size).toBe(118)
  await expect(page.getByRole('button', { name: 'Next page', exact: true })).toBeDisabled()
  await capture(page, 'registry-last-page')
  await page.getByRole('button', { name: 'Previous page', exact: true }).click()
  await expect(page.getByText('Page 9 of 10', { exact: true })).toBeVisible()
})

test('home loading retries, new people, primary contact, all relationships and history retry work', async ({ page }) => {
  await login(page)
  await navigate(page, 'Homes & people')
  await page.getByLabel('Search homes or people').fill('C-101')
  await expect(page.getByRole('status')).toHaveText('1 homes found')
  const endpoint = '**/api/flats/demo-flat-C-101'
  await page.route(endpoint, route => route.fulfill({ status: 503, body: '{}' }))
  await page.getByRole('button', { name: 'View home C-101', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Home unavailable' })).toBeVisible()
  await page.unroute(endpoint)
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Home 101' })).toBeVisible()
  for (const relationship of ['OWNER', 'FAMILY', 'AUTHORIZED_OCCUPANT']) {
    await page.getByRole('button', { name: 'Manage home', exact: true }).click()
    await page.getByRole('button', { name: 'Add person', exact: true }).click()
    const name = `Interaction QA ${relationship}`
    await page.getByLabel('Full name').fill(name)
    await chooseOption(page, 'Relationship', relationship)
    await page.getByLabel('Start date').fill('2025-01-01')
    await page.getByLabel('Reason for this change').fill('Testing a fictional new relationship')
    await page.getByRole('checkbox', { name: 'Make this person the primary contact' }).check()
    await expect(page.getByText('This replaces the current primary contact for this home.')).toBeVisible()
    await page.getByRole('button', { name: 'Add person to home', exact: true }).click()
    await expect(page.getByText('Person added to this home. The relationship is recorded in history.')).toBeVisible()
    await page.getByRole('button', { name: 'People', exact: true }).click()
    const member = page.locator('.member-row').filter({ hasText: name })
    await expect(member).toContainText('Primary contact')
    await page.getByRole('button', { name: 'Manage home', exact: true }).click()
    await page.getByRole('button', { name: 'End relationship', exact: true }).click()
    await chooseOption(page, 'Relationship to end', name + ' · ' + ({ OWNER: 'Owner', FAMILY: 'Family member', AUTHORIZED_OCCUPANT: 'Authorized occupant' }[relationship]))
    await page.getByLabel('Reason for this change').fill('Ending the fictional test relationship')
    await page.getByRole('button', { name: 'End this relationship', exact: true }).click()
    await expect(page.getByText('Relationship ended. The original record is preserved in history.')).toBeVisible()
  }
  await page.route('**/api/flats/demo-flat-C-101/activity', route => route.fulfill({ status: 503, body: '{}' }))
  await page.getByRole('button', { name: 'History', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.unroute('**/api/flats/demo-flat-C-101/activity')
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.locator('.history-list li')).toHaveCount(6)
  await capture(page, 'home-history-retry')
})

test('invitation handover, clipboard, all access choices, pending reissue and account pagination work', async ({ page, browser }) => {
  test.setTimeout(120000)
  await login(page)
  await navigate(page, 'Access & invitations')
  await expect(page.locator('.account-row')).not.toHaveCount(0)
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'], { origin: new URL(page.url()).origin })
  const numbers = ['201', '202', '203', '204', '301', '302', '303', '304', '401', '402', '403', '404', '501']
  let original = ''
  for (let index = 0; index < numbers.length; index++) {
    const role = ['RESIDENT', 'COMMITTEE', 'ADMINISTRATOR'][index % 3]
    await prepareInvitation(page, 'Demo Owner C-' + numbers[index], `interaction-${index}@browser.test`, role)
    const url = await issueLink(page)
    if (index === 0) {
      original = url
      await page.getByLabel('Personal link', { exact: true }).click()
      expect(await page.getByLabel('Personal link').evaluate((el: HTMLInputElement) => el.selectionEnd! - el.selectionStart!)).toBe(url.length)
      await page.getByRole('button', { name: 'Copy personal link', exact: true }).click()
      await expect(page.getByRole('button', { name: 'Link copied', exact: true })).toBeVisible()
      expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(url)
      await capture(page, 'invitation-copied')
    }
    if (index === 1) {
      await page.evaluate(() => { Object.defineProperty(navigator.clipboard, 'writeText', { configurable: true, value: () => Promise.reject(new Error('Simulated clipboard denial')) }) })
      await page.getByRole('button', { name: 'Copy personal link', exact: true }).click()
      await expect(page.getByRole('alert')).toContainText('Select and copy the link above.')
      await capture(page, 'invitation-clipboard-fallback')
    }
    await page.getByRole('button', { name: 'I’ve finished the handover', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Invite a person', exact: true })).toBeFocused()
  }
  await expect(page.getByRole('button', { name: 'Previous account page', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Next account page', exact: true }).click()
  await expect(page.getByText(/accounts · Page 2 of 2/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Next account page', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Previous account page', exact: true }).click()
  await page.getByRole('searchbox', { name: 'Search accounts', exact: true }).fill('interaction-0@browser.test')
  await expect(page.locator('.account-row')).toHaveCount(1)
  await page.getByRole('button', { name: 'New invitation link', exact: true }).click()
  await page.getByRole('checkbox', { name: verifiedLabel }).check()
  await page.getByLabel('Verification note').fill('Reverified fictional identity to replace an invitation.')
  await issueLink(page)
  const recipientContext = await browser.newContext()
  try {
    const recipient = await recipientContext.newPage()
    await recipient.goto(original)
    await expect(recipient.getByRole('alert')).toContainText('expired or has already been used')
    await recipient.getByRole('button', { name: 'Return to sign in', exact: true }).click()
    await expect(recipient.getByRole('heading', { name: 'Welcome back.' })).toBeVisible()
  } finally { await recipientContext.close() }
})

test('account and people lookup errors recover and invitation errors offer the right route', async ({ page }) => {
  await login(page)
  await page.route('**/api/admin/accounts?**', route => route.fulfill({ status: 503, body: '{}' }))
  await navigate(page, 'Access & invitations')
  await expect(page.getByRole('alert')).toBeVisible()
  await capture(page, 'accounts-unavailable')
  await page.unroute('**/api/admin/accounts?**')
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.locator('.account-row')).not.toHaveCount(0)
  await page.getByRole('searchbox', { name: 'Search accounts', exact: true }).fill('No such account')
  await expect(page.getByRole('heading', { name: 'No accounts found.' })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search accounts', exact: true }).fill('')
  await page.route('**/api/people?**', route => route.fulfill({ status: 503, body: '{}' }))
  await page.getByRole('button', { name: 'Invite a person', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.unroute('**/api/people?**')
  await page.getByLabel('Find a person').fill('Demo Owner C-601')
  await expect.soft(page.getByRole('alert')).toHaveCount(0)
  await chooseOption(page, 'Person in the registry', 'Demo Owner C-601')
  await page.getByLabel('Email address', { exact: true }).fill('an-error@browser.test')
  await page.getByRole('checkbox', { name: verifiedLabel }).check()
  await page.getByLabel('Verification note').fill('Fictional identity verified for failure-state QA.')
  await page.route('**/api/admin/invitations', route => route.fulfill({ status: 400, contentType: 'application/json', body: '{"message":"A fictional validation error."}' }))
  await page.getByRole('button', { name: 'Create personal link', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('fictional validation error')
  await expect(page.getByRole('link', { name: 'Open Account security', exact: true })).toHaveCount(0)
  await page.unroute('**/api/admin/invitations')
  await page.route('**/api/admin/invitations', route => route.fulfill({ status: 403, contentType: 'application/json', body: '{"error":"reauthentication_required"}' }))
  await page.getByRole('button', { name: 'Create personal link', exact: true }).click()
  await page.getByRole('link', { name: 'Open Account security', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Account security.' })).toBeVisible()
})

test('optional authenticator, setup retry, codes, reauthentication and password changes work on phone', async ({ page }) => {
  test.setTimeout(90000)
  await page.setViewportSize({ width: 375, height: 812 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await login(page, 'Owner')
  await navigate(page, 'Account security')
  await page.getByRole('button', { name: 'Set up authenticator', exact: true }).click()
  await page.getByRole('button', { name: 'Back to account security', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Account security.' })).toBeVisible()
  await page.route('**/api/auth/mfa/setup', route => route.fulfill({ status: 503, body: '{}' }))
  await page.getByRole('button', { name: 'Set up authenticator', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Verify and continue', exact: true })).toBeDisabled()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.unroute('**/api/auth/mfa/setup')
  await page.getByRole('button', { name: 'Restart setup', exact: true }).click()
  const setup = page.getByText('Enter a setup key instead', { exact: true })
  await setup.click()
  await expect(page.locator('.setup-key')).toBeVisible()
  await setup.click()
  await expect(page.locator('.setup-key')).toBeHidden()
  await page.getByRole('button', { name: 'Use a preview code', exact: true }).click()
  await page.getByRole('button', { name: 'Verify and continue', exact: true }).click()
  await expect(page.locator('.recovery-grid code')).toHaveCount(10)
  const codes = await page.locator('.recovery-grid code').allTextContents()
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download codes', exact: true }).click()
  const download = await downloadEvent
  const contents = readFileSync((await download.path())!, 'utf8')
  for (const code of codes) expect(contents).toContain(code)
  await capture(page, 'optional-mfa-codes-phone')
  await page.getByRole('checkbox', { name: 'I have saved my recovery codes privately.' }).check()
  await page.getByRole('button', { name: 'Return to account security', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Account security.' })).toBeVisible()
  await page.getByRole('button', { name: 'Use a recovery code', exact: true }).click()
  await page.getByLabel('Recovery code', { exact: true }).fill(codes[0])
  await page.getByLabel('Current password', { exact: true }).first().fill(password)
  await page.getByRole('button', { name: 'Confirm my identity', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Identity confirmed.')
  await page.getByRole('button', { name: 'Use my authenticator app', exact: true }).click()
  await page.getByRole('button', { name: 'Use a preview code', exact: true }).click()
  await page.getByLabel('Current password', { exact: true }).first().fill(password)
  await page.getByRole('button', { name: 'Confirm my identity', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Identity confirmed.')
  const next = 'Temporary fictional password, then restored!'
  await page.getByLabel('Current password', { exact: true }).last().fill(password)
  await page.getByLabel('New password', { exact: true }).fill(next)
  await page.getByLabel('Confirm new password', { exact: true }).fill('A deliberately different phrase!')
  await page.getByRole('button', { name: 'Save new password', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('new passwords do not match')
  await expect.soft(page.getByRole('alert')).toBeInViewport()
  await capture(page, 'password-mismatch-phone')
  await page.getByLabel('Confirm new password', { exact: true }).fill(next)
  await page.getByRole('button', { name: 'Save new password', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible()
  await signIn(page, 'owner@demo.society', next)
  await navigate(page, 'Account security')
  await page.getByLabel('Current password', { exact: true }).last().fill(next)
  await page.getByLabel('New password', { exact: true }).fill(password)
  await page.getByLabel('Confirm new password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Save new password', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible()
  await signIn(page, 'owner@demo.society', password)
})
