import { test, expect } from '@playwright/test'
import { login, completePreviewMFA, chooseOption, navigate } from './helpers'

test('officer updates occupancy, adds an existing person, ends the relationship and sees history', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: 'Open homes & people', exact: true }).click()
  await page.getByRole('button', { name: 'View home A-101', exact: true }).click()
  await page.getByRole('button', { name: 'Manage home', exact: true }).click()
  await chooseOption(page, 'Occupancy', 'VACANT')
  await page.getByLabel('Reason for this change').fill('Fictional occupant moved out')
  await page.getByRole('button', { name: 'Save occupancy', exact: true }).click()
  await expect(page.getByText('Occupancy updated. The change is recorded in history.')).toBeVisible()
  await page.getByRole('button', { name: 'History', exact: true }).click()
  await expect(page.getByText('Owner occupied → Vacant', { exact: true })).toBeVisible()
  await expect(page.getByText('Fictional occupant moved out', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Manage home', exact: true }).click()
  await chooseOption(page, 'Occupancy', 'OWNER_OCCUPIED')
  await page.getByLabel('Reason for this change').fill('Restoring the fictional home status')
  await page.getByRole('button', { name: 'Save occupancy', exact: true }).click()
  await expect(page.getByText('Occupancy updated. The change is recorded in history.')).toBeVisible()
  await page.getByRole('button', { name: 'Add person', exact: true }).click()
  await chooseOption(page, 'Person record', 'existing')
  await page.getByLabel('Find a person').fill('Demo Tenant A-103')
  await chooseOption(page, 'Existing person', 'Demo Tenant A-103')
  await chooseOption(page, 'Relationship', 'TENANT')
  await page.getByLabel('Start date').fill('2022-01-01')
  await page.getByLabel('Reason for this change').fill('Fictional second home relationship')
  await page.getByRole('button', { name: 'Add person to home', exact: true }).click()
  await expect(page.getByText('Person added to this home. The relationship is recorded in history.')).toBeVisible()
  await page.getByRole('button', { name: 'People', exact: true }).click()
  await expect(page.getByText('Demo Tenant A-103', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Manage home', exact: true }).click()
  await page.getByRole('button', { name: 'End relationship', exact: true }).click()
  await chooseOption(page, 'Relationship to end', 'Demo Tenant A-103 · Tenant')
  await page.getByLabel('Reason for this change').fill('Fictional second home tenancy ended')
  await page.getByRole('button', { name: 'End this relationship', exact: true }).click()
  await expect(page.getByText('Relationship ended. The original record is preserved in history.')).toBeVisible()
  await page.getByRole('button', { name: 'History', exact: true }).click()
  await expect(page.getByText('Fictional second home tenancy ended', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await navigate(page, 'Homes & people')
  await expect(page.locator('.stat-item').filter({ hasText: 'Owners' }).locator('strong')).toHaveText('118')
  await expect(page.locator('.stat-item').filter({ hasText: 'Tenants' }).locator('strong')).toHaveText('35')
})

test('account switching clears the officer workspace and scopes owner and tenant homes', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible()
  await expect(page.locator('.wing-card')).toHaveCount(0)
  await login(page, 'Owner')
  await expect(page.getByRole('heading', { name: 'Good things, in order.' })).toBeVisible()
  await navigate(page, 'Your homes')
  await expect(page.getByRole('status')).toHaveText('2 homes found')
  await expect(page.getByRole('button', { name: 'View home A-101', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'View home A-102', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Overview', exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: 'View home A-101', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Manage home', exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  const forbidden = await page.request.get('/api/flats/demo-flat-B-101')
  expect(forbidden.status()).toBe(404)
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await login(page, 'Tenant')
  await navigate(page, 'Your homes')
  await expect(page.getByRole('status')).toHaveText('1 homes found')
  await page.getByRole('button', { name: 'View home A-103', exact: true }).click()
  await expect(page.getByText('Demo Former Tenant A-103', { exact: true })).toHaveCount(0)
})

test('phone login and management form fit, and a stale save offers reload', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Use a preview code', exact: true })).toBeVisible()
  await completePreviewMFA(page)
  await page.getByRole('link', { name: 'Open homes & people', exact: true }).click()
  await page.getByRole('button', { name: 'View home A-101', exact: true }).click()
  await page.getByRole('button', { name: 'Manage home', exact: true }).click()
  await chooseOption(page, 'Occupancy', 'VACANT')
  await page.getByLabel('Reason for this change').fill('Stale browser edit example')
  await page.route('**/api/flats/demo-flat-A-101', route => route.request().method() === 'PATCH' ? route.fulfill({ status: 409, contentType: 'application/json', body: '{"error":"record_changed"}' }) : route.continue())
  await page.getByRole('button', { name: 'Save occupancy', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Someone has updated this home')
  await page.getByRole('button', { name: 'Reload home', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  const modalFits = await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth)
  expect(modalFits).toBe(true)
})
