import { test, expect } from '@playwright/test'
import { login, navigate, chooseOption } from './helpers'
import { messageActors, messagePrivateFixture } from './messages-fixtures'
import { communityLocal } from '../src/community'
import { meetingAckConfirmation, meetingApprove, meetingCapture, meetingDecisionConfirmation, meetingDetail, meetingPost, meetingProposal, meetingProposalConfirmation, meetingRequestAcknowledgement, meetingWithin, openMeeting } from './meetings-fixtures'

test.setTimeout(120000)
test('actual preparation separate approval and personal acknowledgement retain an exact selected-home version',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage()
 try{
  await navigate(page,'Community');await page.getByRole('link',{name:'Meetings & minutes',exact:true}).click();await expect(page.getByRole('heading',{name:'Room for the next conversation.',exact:true})).toBeVisible();await meetingCapture(page,'empty-meetings-1440')
  await page.getByRole('button',{name:'Prepare a meeting',exact:true}).click();await page.getByLabel('Meeting title',{exact:true}).fill('MEETING UI a thoughtful community conversation');await page.getByLabel('Supplied meeting agenda',{exact:true}).fill('Discuss the supplied maintenance updates, service visits and community questions.');await page.getByLabel('Meeting location',{exact:true}).fill('Fictional community garden');await page.getByLabel('Scheduled start · IST',{exact:true}).fill(communityLocal(Math.floor(Date.now()/1000)+3600));await page.getByLabel('Scheduled end · IST',{exact:true}).fill(communityLocal(Math.floor(Date.now()/1000)+7200));await chooseOption(page,'Meeting publication area','One wing');await chooseOption(page,'Meeting publication wing','Wing A');await expect(page.getByText('40 homes in this reviewed area.',{exact:false})).toBeVisible();await chooseOption(page,'Meeting publication area','Selected homes');await page.getByRole('checkbox',{name:'A-101',exact:true}).check();await page.getByRole('checkbox',{name:'A-202',exact:true}).check();await page.getByRole('checkbox',{name:meetingRequestAcknowledgement,exact:true}).check();await page.getByLabel('Supplied acknowledgement deadline · IST',{exact:true}).fill(communityLocal(Math.floor(Date.now()/1000)+86400));await page.getByLabel('Private meeting proposal reason',{exact:true}).fill('PRIVATE_MEETING supplied this exact agenda and selected homes for separate review.');await meetingCapture(page,'selected-home-preparation-1440')
  await page.getByRole('button',{name:'Review exact meeting proposal',exact:true}).click();await page.getByRole('checkbox',{name:meetingProposalConfirmation,exact:true}).check();await meetingCapture(page,'exact-proposal-preview-1440');await page.getByRole('button',{name:'Submit meeting for separate review',exact:true}).click();await expect(page.getByRole('dialog').locator('.community-state').first()).toHaveText('Awaiting separate review');const id=new URLSearchParams(page.url().split('?')[1]).get('meeting')!;await expect(page.getByRole('button',{name:'Review meeting proposal',exact:true})).toHaveCount(0);await meetingCapture(page,'private-pending-agenda-1440')
  await openMeeting(actors.reviewer,id);await actors.reviewer.getByRole('button',{name:'Review meeting proposal',exact:true}).click();await actors.reviewer.getByLabel('Meeting decision reason',{exact:true}).fill('PRIVATE_MEETING independently checked the selected homes, times and acknowledgement.');await actors.reviewer.getByRole('checkbox',{name:meetingDecisionConfirmation,exact:true}).check();await actors.reviewer.setViewportSize({width:768,height:1024});await meetingCapture(actors.reviewer,'separate-approval-768');await actors.reviewer.getByRole('button',{name:'Approve this exact meeting proposal',exact:true}).click();await expect(actors.reviewer.getByRole('dialog').locator('.community-state').first()).toHaveText('Upcoming meeting')
  await login(owner,'Owner');await openMeeting(owner,id,false);await owner.setViewportSize({width:375,height:640});await expect(owner.getByRole('button',{name:'Review meeting proposal',exact:true})).toHaveCount(0);await expect(owner.getByRole('region',{name:'Meeting publication history'})).toHaveCount(0);await meetingCapture(owner,'published-agenda-375');await owner.getByRole('button',{name:'Acknowledge this version',exact:true}).click();await owner.getByRole('checkbox',{name:meetingAckConfirmation,exact:true}).check();await meetingCapture(owner,'personal-confirmation-375');await owner.getByRole('button',{name:'Record my acknowledgement',exact:true}).click();await expect(owner.getByText('You acknowledged version 1 on',{exact:false})).toBeVisible();await meetingCapture(owner,'personal-acknowledged-375')
  const x=await meetingDetail(owner,id,false);expect(x.version).toBe(1);expect(x.snapshot.homes.map((h:{label:string})=>h.label)).toEqual(['A-101','A-202']);expect(x.acknowledgement.acknowledged).toBe(true);for(const secret of ['PRIVATE_MEETING','submitted_by','reason','events','resident_id'])expect(JSON.stringify(x)).not.toContain(secret)
  await openMeeting(page,id);await page.getByRole('button',{name:'View personal responses',exact:true}).click();await expect(page.locator('.meeting-response-counts strong')).toHaveText(['1','1','0','1']);await meetingCapture(page,'private-response-counts-1440');messagePrivateFixture("assert db.execute('SELECT COUNT(*) FROM meeting_acknowledgements').fetchone()[0]==1;assert db.execute('SELECT COUNT(*) FROM entries').fetchone()[0]==0;assert db.execute('SELECT COUNT(*) FROM receipts').fetchone()[0]==0")
 }finally{await actors.close();await oc.close()}
})

test('supplied minutes retain the original schedule and require a fresh personal acknowledgement of their version',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage()
 try{
  const now=Math.floor(Date.now()/1000),id=await meetingProposal(page,'MEETING UI supplied minutes',{start_at:now-7200,end_at:now-3600});await meetingApprove(actors.reviewer,id);await login(owner,'Owner');let original=await meetingDetail(owner,id,false);expect(original.state).toBe('PAST');expect(original.snapshot.held_at).toBe(0);expect(original.snapshot.minutes).toBeUndefined();await meetingPost(owner,'/api/meetings/'+id+'/acknowledgements',{version:original.version,fingerprint:original.acknowledgement.fingerprint});original=await meetingDetail(owner,id,false)
  await openMeeting(page,id);await page.getByRole('button',{name:'Prepare meeting minutes',exact:true}).click();await page.getByLabel('Supplied meeting-held time · IST',{exact:true}).fill(communityLocal(now-5400));await page.getByLabel('Supplied minutes',{exact:true}).fill('The supplied minutes record the maintenance discussion and a later service visit. Any financial action uses its own review.');await page.getByRole('checkbox',{name:meetingRequestAcknowledgement,exact:true}).check();await page.getByLabel('Private meeting proposal reason',{exact:true}).fill('PRIVATE_MEETING supplied the held time and original minutes for separate review.');await page.setViewportSize({width:768,height:1024});await page.getByRole('textbox',{name:'Supplied minutes',exact:true}).scrollIntoViewIfNeeded();await meetingCapture(page,'minutes-preparation-768');await page.getByRole('button',{name:'Review exact meeting proposal',exact:true}).click();await page.getByRole('checkbox',{name:meetingProposalConfirmation,exact:true}).check();await page.getByRole('button',{name:'Submit meeting for separate review',exact:true}).click();expect(await meetingDetail(owner,id,false)).toEqual(original)
  await openMeeting(actors.reviewer,id);await actors.reviewer.setViewportSize({width:320,height:440});await actors.reviewer.getByRole('button',{name:'Review meeting proposal',exact:true}).click();await actors.reviewer.getByLabel('Meeting decision reason',{exact:true}).fill('PRIVATE_MEETING separately checked the exact supplied minutes and retained agenda.');await actors.reviewer.getByRole('checkbox',{name:meetingDecisionConfirmation,exact:true}).check();await actors.reviewer.getByRole('button',{name:'Approve this exact meeting proposal',exact:true}).scrollIntoViewIfNeeded();await meetingWithin(actors.reviewer);await meetingCapture(actors.reviewer,'minutes-approval-320-440');await actors.reviewer.getByRole('button',{name:'Approve this exact meeting proposal',exact:true}).click()
  await openMeeting(owner,id,false);await owner.setViewportSize({width:320,height:640});await expect(owner.getByRole('dialog').locator('.community-state').first()).toHaveText('Minutes published');await expect(owner.getByRole('button',{name:'Acknowledge this version',exact:true})).toBeVisible();await owner.getByRole('region',{name:'Approved meeting record',exact:true}).locator('.community-restoration > strong').scrollIntoViewIfNeeded();await meetingCapture(owner,'published-minutes-320');const current=await meetingDetail(owner,id,false);expect(current.version).toBe(3);expect(current.snapshot.start_at).toBe(original.snapshot.start_at);expect(current.snapshot.end_at).toBe(original.snapshot.end_at);expect(current.snapshot.homes).toEqual(original.snapshot.homes);expect(current.acknowledgement.acknowledged).toBe(false);expect(current.acknowledgement.fingerprint).not.toBe(original.acknowledgement.fingerprint)
  await owner.getByRole('button',{name:'Acknowledge this version',exact:true}).click();await owner.getByRole('checkbox',{name:meetingAckConfirmation,exact:true}).check();await owner.getByRole('button',{name:'Record my acknowledgement',exact:true}).click();await expect(owner.getByText('You acknowledged version 3 on',{exact:false})).toBeVisible();await openMeeting(page,id);await page.getByRole('button',{name:'View personal responses',exact:true}).click();await expect(page.locator('.meeting-response-counts strong')).toHaveText(['2','1','1','2']);await page.setViewportSize({width:320,height:440});await page.getByRole('heading',{name:'Retained personal originals',exact:true}).scrollIntoViewIfNeeded();await meetingCapture(page,'retained-personal-originals-320-440')
 }finally{await actors.close();await oc.close()}
})

test('stale revisions preserve the human draft and stale personal confirmation requires reading the new publication',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage()
 try{
  const id=await meetingProposal(page,'MEETING UI exact approved predecessor',{scope:'HOMES',home_ids:['demo-flat-A-101']});await meetingApprove(actors.reviewer,id);await login(owner,'Owner');const original=await meetingDetail(owner,id,false);await openMeeting(owner,id,false);await owner.getByRole('button',{name:'Acknowledge this version',exact:true}).click();await owner.getByRole('checkbox',{name:meetingAckConfirmation,exact:true}).check()
  await openMeeting(page,id);await page.getByRole('button',{name:'Prepare a revised agenda',exact:true}).click();await page.getByLabel('Meeting title',{exact:true}).fill('MEETING UI keep my human revised title');await page.getByLabel('Private meeting proposal reason',{exact:true}).fill('PRIVATE_MEETING human reason survives a required current-version reload.');await page.getByRole('button',{name:'Review exact meeting proposal',exact:true}).click();await page.getByRole('checkbox',{name:meetingProposalConfirmation,exact:true}).check();const options=await(await page.request.get('/api/meetings/options')).json();await meetingPost(page,'/api/meetings/'+id+'/proposals',{version:2,action:'AGENDA',title:'PRIVATE_MEETING competing pending title',body:'This supplied competing proposal stays private until separately approved.',location:'Fictional alternate room',scope:'HOMES',home_ids:['demo-flat-A-101'],area_key:options.area_key,start_at:original.snapshot.start_at,end_at:original.snapshot.end_at,ack_required:true,reason:'PRIVATE_MEETING separately supplied competing agenda revision'});await page.getByRole('button',{name:'Submit meeting for separate review',exact:true}).click();await expect(page.getByRole('button',{name:'Reload current record',exact:true})).toBeVisible();await expect(page.getByRole('alert')).toContainText('This record has changed');await expect(page.getByRole('alert')).not.toContainText('home');expect(await meetingDetail(owner,id,false)).toEqual(original);await page.setViewportSize({width:320,height:440});await page.getByRole('alert').scrollIntoViewIfNeeded();await meetingCapture(page,'stale-agenda-conflict-320-440');await page.getByRole('button',{name:'Reload current record',exact:true}).click();await expect(page.getByLabel('Meeting title',{exact:true})).toHaveValue('MEETING UI keep my human revised title');await expect(page.getByRole('textbox',{name:'Private meeting proposal reason',exact:true})).toHaveValue('PRIVATE_MEETING human reason survives a required current-version reload.');await meetingCapture(page,'human-draft-preserved-320-440');await page.getByRole('button',{name:'Review exact meeting proposal',exact:true}).click();await expect(page.getByRole('checkbox',{name:meetingProposalConfirmation,exact:true})).not.toBeChecked();await page.getByRole('checkbox',{name:meetingProposalConfirmation,exact:true}).check();await page.getByRole('button',{name:'Submit meeting for separate review',exact:true}).click();expect((await meetingDetail(page,id)).version).toBe(4);expect(await meetingDetail(owner,id,false)).toEqual(original);await meetingApprove(actors.reviewer,id)
  await owner.getByRole('button',{name:'Record my acknowledgement',exact:true}).click();await expect(owner.getByRole('button',{name:'Reload current record',exact:true})).toBeVisible();await expect(owner.getByRole('alert')).toContainText('This record has changed');await expect(owner.getByRole('alert')).not.toContainText('home');await owner.setViewportSize({width:320,height:440});await owner.getByRole('alert').scrollIntoViewIfNeeded();await meetingCapture(owner,'superseded-acknowledgement-320-440');await owner.getByRole('button',{name:'Reload current record',exact:true}).click();await expect(owner.getByRole('checkbox',{name:meetingAckConfirmation,exact:true})).not.toBeChecked();await expect(owner.getByRole('heading',{name:'MEETING UI keep my human revised title',exact:true}).first()).toBeVisible();await expect(owner.getByRole('button',{name:'Record my acknowledgement',exact:true})).toBeDisabled();await owner.getByRole('checkbox',{name:meetingAckConfirmation,exact:true}).check();await owner.getByRole('button',{name:'Record my acknowledgement',exact:true}).click();await expect(owner.getByText('You acknowledged version 4 on',{exact:false})).toBeVisible();const retained=await meetingDetail(page,id);expect(retained.events[2].snapshot.title).toBe('PRIVATE_MEETING competing pending title');expect((await meetingDetail(owner,id,false)).acknowledgement.acknowledged).toBe(true)
 }finally{await actors.close();await oc.close()}
})

test('held meeting writes lock dismissal and an uncertain acknowledgement retries one exact durable action',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage();let release=()=>{}
 try{
  await navigate(page,'Community');await page.getByRole('link',{name:'Meetings & minutes',exact:true}).click();await page.getByRole('button',{name:'Prepare a meeting',exact:true}).click();await page.getByLabel('Meeting title',{exact:true}).fill('MEETING UI held proposal and exact retry');await page.getByLabel('Supplied meeting agenda',{exact:true}).fill('The supplied agenda remains immutable while the operator waits for a confirmed response.');await page.getByLabel('Meeting location',{exact:true}).fill('Fictional shared room');await page.getByRole('checkbox',{name:meetingRequestAcknowledgement,exact:true}).check();await page.getByLabel('Private meeting proposal reason',{exact:true}).fill('PRIVATE_MEETING deliberately prepared this exact held meeting proposal.');await page.getByRole('button',{name:'Review exact meeting proposal',exact:true}).click();await page.getByRole('checkbox',{name:meetingProposalConfirmation,exact:true}).check()
  let ready!:()=>void;const held=new Promise<void>(r=>{release=r}),captured=new Promise<void>(r=>{ready=r});await page.route('**/api/meetings',async route=>{if(route.request().method()!=='POST'){await route.continue();return}const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});await page.getByRole('button',{name:'Submit meeting for separate review',exact:true}).click();await captured;await page.setViewportSize({width:320,height:440});await expect(page.getByRole('button',{name:'Close meeting proposal',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Saving meeting proposal…',exact:true}).scrollIntoViewIfNeeded();await meetingCapture(page,'held-proposal-320-440');release();await page.unroute('**/api/meetings');await expect(page.getByRole('dialog').locator('.community-state').first()).toHaveText('Awaiting separate review');const id=new URLSearchParams(page.url().split('?')[1]).get('meeting')!;await meetingApprove(actors.reviewer,id)
  await login(owner,'Owner');await openMeeting(owner,id,false);await owner.setViewportSize({width:320,height:440});await owner.getByRole('button',{name:'Acknowledge this version',exact:true}).click();await owner.getByRole('checkbox',{name:meetingAckConfirmation,exact:true}).check();const bodies:string[]=[];let lost=true;await owner.route('**/api/meetings/'+id+'/acknowledgements',async route=>{bodies.push(route.request().postData()!);const response=await route.fetch();if(lost){lost=false;await route.abort('failed')}else await route.fulfill({response})});await owner.getByRole('button',{name:'Record my acknowledgement',exact:true}).click();await expect(owner.getByRole('button',{name:'Retry this acknowledgement',exact:true})).toBeEnabled();await expect(owner.getByRole('button',{name:'Close meeting',exact:true})).toBeDisabled();await expect(owner.getByRole('checkbox',{name:meetingAckConfirmation,exact:true})).toBeDisabled();await owner.getByRole('alert').scrollIntoViewIfNeeded();await meetingCapture(owner,'uncertain-acknowledgement-320-440');await owner.keyboard.press('Escape');await expect(owner.getByRole('dialog')).toBeVisible();await owner.getByRole('button',{name:'Retry this acknowledgement',exact:true}).click();await expect(owner.getByText('You acknowledged version 1 on',{exact:false})).toBeVisible();expect(bodies).toHaveLength(2);expect(bodies[0]).toBe(bodies[1]);messagePrivateFixture("assert db.execute('SELECT COUNT(*) FROM meeting_acknowledgements WHERE resource_id=?',("+JSON.stringify(id)+",)).fetchone()[0]==1");await meetingCapture(owner,'exact-acknowledgement-retry-320-440')
 }finally{release();await actors.close();await oc.close()}
})

test('meeting list options detail private responses and Overview have usable loading error empty and retry states',async({page,browser})=>{
 const actors=await messageActors(page,browser);let release=()=>{}
 try{
  const id=await meetingProposal(page,'MEETING UI independently retryable record');await meetingApprove(actors.reviewer,id);await navigate(page,'Community');let ready!:()=>void;const held=new Promise<void>(r=>{release=r}),captured=new Promise<void>(r=>{ready=r});let first=true
  await page.route('**/api/meetings?**',async route=>{if(first){first=false;ready();await held;await route.fulfill({status:503,json:{error:'unavailable'}})}else await route.continue()});await page.getByRole('link',{name:'Meetings & minutes',exact:true}).click();await captured;await page.setViewportSize({width:320,height:440});await expect(page.getByText('Loading current meetings',{exact:true})).toBeAttached();await meetingCapture(page,'list-loading-320-440');release();await expect(page.getByRole('alert')).toContainText('Meetings unavailable.');await page.getByRole('alert').scrollIntoViewIfNeeded();await meetingCapture(page,'list-error-320-440');await page.getByRole('button',{name:'Retry meetings',exact:true}).click();await expect(page.getByRole('button',{name:'Open meeting: MEETING UI independently retryable record',exact:true})).toBeVisible();await page.unroute('**/api/meetings?**');await page.getByLabel('Search meetings',{exact:true}).fill('deliberately unmatched fictional meeting query');await expect(page.getByRole('heading',{name:'No matching meetings.',exact:true})).toBeVisible();await meetingCapture(page,'filtered-empty-320-440');await page.getByRole('button',{name:'Clear meeting filters',exact:true}).click()
  let optionsFailed=true;await page.route('**/api/meetings/options',async route=>{if(optionsFailed){optionsFailed=false;await route.fulfill({status:503,json:{error:'unavailable'}})}else await route.continue()});await page.getByRole('button',{name:'Prepare a meeting',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();await meetingCapture(page,'area-options-error-320-440');await page.getByRole('dialog').getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByLabel('Meeting title',{exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await page.unroute('**/api/meetings/options')
  let detailFailed=true;await page.route('**/api/meetings/'+id+'?**',async route=>{if(detailFailed){detailFailed=false;await route.fulfill({status:503,json:{error:'unavailable'}})}else await route.continue()});await page.goto('/#community?meeting='+id+'&desk=true');await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();await meetingCapture(page,'detail-error-320-440');await page.getByRole('dialog').getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByRole('button',{name:'View personal responses',exact:true})).toBeVisible();await page.unroute('**/api/meetings/'+id+'?**')
  let responsesFailed=true;await page.route('**/api/meetings/'+id+'/responses?**',async route=>{if(responsesFailed){responsesFailed=false;await route.fulfill({status:503,json:{error:'unavailable'}})}else await route.continue()});await page.getByRole('button',{name:'View personal responses',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();await meetingCapture(page,'private-responses-error-320-440');await page.getByRole('dialog').getByRole('button',{name:'Try again',exact:true}).click();await expect(page.locator('.meeting-response-counts strong')).toHaveText(['2','0','2','0']);await meetingCapture(page,'private-current-responses-320-440');await page.keyboard.press('Escape');await page.unroute('**/api/meetings/'+id+'/responses?**')
  let overviewFailed=true;await page.route('**/api/overview/meetings',async route=>{if(overviewFailed)await route.fulfill({status:503,json:{error:'unavailable'}});else await route.continue()});await navigate(page,'Overview');await expect(page.getByRole('button',{name:'Refresh overview',exact:true})).toBeEnabled();await expect(page.getByRole('region',{name:'Needs attention',exact:true})).toContainText('Partial view');const source=page.getByRole('region',{name:'Meetings, in view.',exact:true});await expect(source.locator('.overview-maintenance-amounts strong')).toHaveText(['—','—','—']);await expect(page.getByRole('region',{name:'Money, accounted for.',exact:true})).toContainText('₹0.00');await source.scrollIntoViewIfNeeded();await meetingCapture(page,'overview-independent-error-320-440');overviewFailed=false;await source.getByRole('button',{name:'Retry meetings',exact:true}).click();await expect(source.getByRole('alert')).toHaveCount(0);expect(Number(await source.locator('.overview-maintenance-amounts strong').first().textContent())).toBeGreaterThanOrEqual(1);await page.unroute('**/api/overview/meetings')
 }finally{release();await actors.close()}
})

test('actual meeting menus selection focus keyboard history pagination scrolling and dismissal work across layouts',async({page,browser})=>{
 const actors=await messageActors(page,browser);let last=''
 try{
  for(let i=0;i<13;i++){last=await meetingProposal(page,'MEETING PAGING supplied agenda '+i,{ack_required:false,ack_deadline:0});await meetingApprove(actors.reviewer,last)}await navigate(page,'Community');await page.getByRole('link',{name:'Meetings & minutes',exact:true}).click();await page.getByLabel('Search meetings',{exact:true}).fill('MEETING PAGING');await expect(page.locator('.registry-toolbar').getByRole('status')).toHaveText('13 meetings');await expect(page.locator('.meeting-card')).toHaveCount(12)
  for(const [width,height] of [[1440,1000],[768,1024],[375,640],[320,640],[320,440]]){
   await page.setViewportSize({width,height});const filter=page.getByRole('combobox',{name:'Filter meeting status',exact:true});await filter.scrollIntoViewIfNeeded();await filter.click();await page.getByRole('option',{name:'Upcoming meeting',exact:true}).hover();await meetingCapture(page,`filter-open-${width}-${height}`);await meetingWithin(page);await page.keyboard.press('Escape');await expect(filter).toBeFocused();await filter.press('ArrowDown');await expect(page.getByRole('listbox')).toBeVisible();await page.keyboard.press('Home');await expect(page.getByRole('option',{name:'All meeting statuses',exact:true})).toBeFocused();await page.keyboard.press('ArrowDown');await expect(page.getByRole('option',{name:'Upcoming meeting',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(filter).toContainText('Upcoming meeting');await meetingCapture(page,`filter-selected-${width}-${height}`)
  }
  await page.getByRole('button',{name:'Next meetings page',exact:true}).click();await expect(page.locator('.meeting-card')).toHaveCount(1);await meetingCapture(page,'meeting-page-two-320-440');await page.getByRole('button',{name:'Previous meetings page',exact:true}).click();await expect(page.locator('.meeting-card')).toHaveCount(12)
  await page.getByRole('button',{name:'Prepare a meeting',exact:true}).click()
  for(const [width,height] of [[1440,1000],[768,1024],[375,640],[320,640],[320,440]]){
   await page.setViewportSize({width,height});const area=page.getByRole('combobox',{name:'Meeting publication area',exact:true});await area.click();await page.getByRole('option',{name:'One wing',exact:true}).hover();await meetingCapture(page,`area-menu-${width}-${height}`);await meetingWithin(page);await page.keyboard.press('Escape');await expect(area).toBeFocused();await expect(page.getByRole('dialog')).toBeVisible();await chooseOption(page,'Meeting publication area','One wing');const wing=page.getByRole('combobox',{name:'Meeting publication wing',exact:true});await wing.click();await page.getByRole('option',{name:'Wing B',exact:true}).hover();await meetingCapture(page,`wing-menu-${width}-${height}`);await meetingWithin(page);await page.keyboard.press('End');await expect(page.getByRole('option',{name:'Wing C',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(wing).toContainText('Wing C');await expect(page.getByText('38 homes in this reviewed area.',{exact:false})).toBeVisible();await chooseOption(page,'Meeting publication area','All current homes')
   const heading=await page.getByRole('dialog').locator('.dialog-heading h2').boundingBox(),close=await page.getByRole('button',{name:'Close meeting proposal',exact:true}).boundingBox();expect(heading!.x+heading!.width).toBeLessThanOrEqual(close!.x);await page.getByLabel('Private meeting proposal reason',{exact:true}).scrollIntoViewIfNeeded();await page.getByRole('button',{name:'Review exact meeting proposal',exact:true}).scrollIntoViewIfNeeded();await expect(page.getByRole('button',{name:'Close meeting proposal',exact:true})).toBeVisible();expect(await page.getByRole('dialog').locator('.dialog-scroll').evaluate(el=>el.scrollTop>0&&el.scrollHeight>el.clientHeight)).toBe(true);await meetingCapture(page,`proposal-scroll-${width}-${height}`)
  }
  await page.getByRole('button',{name:'Review exact meeting proposal',exact:true}).focus();await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Close meeting proposal',exact:true})).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(page.getByRole('button',{name:'Review exact meeting proposal',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Prepare a meeting',exact:true})).toBeFocused()
  for(let i=0;i<11;i++){const x=await meetingDetail(page,last),options=await(await page.request.get('/api/meetings/options')).json();await meetingPost(page,'/api/meetings/'+last+'/proposals',{version:x.version,action:'AGENDA',title:'MEETING PAGING retained revision '+i,body:'The exact revised supplied agenda remains retained with its independent publication decision.',location:'Fictional community room',scope:'ALL',area_key:options.area_key,start_at:x.snapshot.start_at,end_at:x.snapshot.end_at,reason:'PRIVATE_MEETING prepare the exact linked agenda revision'});await meetingApprove(actors.reviewer,last)}await openMeeting(page,last);await page.getByRole('button',{name:'Next meeting history page',exact:true}).click();const history=page.getByRole('region',{name:'Meeting publication history',exact:true});await expect(history.locator('ol > li')).toHaveCount(4);const original=history.locator('ol > li').last();await original.locator('details > summary').first().click();await expect(original).toContainText('MEETING PAGING supplied agenda 12');await original.locator('.community-area > summary').click();await expect(original.locator('.community-area > div > span')).toHaveCount(118);await original.scrollIntoViewIfNeeded();await meetingWithin(page);await meetingCapture(page,'retained-original-history-320-440');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)
 }finally{await actors.close()}
})

test('decline own proposal cancellation public cancellation withdrawal and current-home denial retain the original',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage(),tc=await browser.newContext({baseURL:new URL(page.url()).origin}),tenant=await tc.newPage()
 try{
  const id=await meetingProposal(page,'MEETING UI deliberately cancelled meeting',{scope:'HOMES',home_ids:['demo-flat-A-101']});await meetingApprove(actors.reviewer,id);await login(owner,'Owner');await login(tenant,'Tenant');const original=await meetingDetail(owner,id,false);await meetingPost(owner,'/api/meetings/'+id+'/acknowledgements',{version:1,fingerprint:original.acknowledgement.fingerprint});const acknowledged=await meetingDetail(owner,id,false)
  const cancellation=async(reason:string)=>{await openMeeting(page,id);await page.getByRole('button',{name:'Propose meeting cancellation',exact:true}).click();await page.getByLabel('Public cancellation update',{exact:true}).fill('The society supplied an explicit cancellation of this fictional meeting.');await page.getByLabel('Private meeting proposal reason',{exact:true}).fill(reason);await page.getByRole('button',{name:'Review exact meeting proposal',exact:true}).click();await page.getByRole('checkbox',{name:meetingProposalConfirmation,exact:true}).check();await page.getByRole('button',{name:'Submit meeting for separate review',exact:true}).click();await expect(page.getByRole('dialog').locator('.community-state').first()).toHaveText('Awaiting separate review')}
  await cancellation('PRIVATE_MEETING first supplied cancellation awaiting a separate review.');await openMeeting(actors.reviewer,id);await actors.reviewer.setViewportSize({width:320,height:440});await actors.reviewer.getByRole('button',{name:'Review meeting proposal',exact:true}).click();await actors.reviewer.getByRole('combobox',{name:'Meeting publication decision',exact:true}).click();await actors.reviewer.getByRole('option',{name:'Decline this meeting proposal',exact:true}).hover();await meetingCapture(actors.reviewer,'decision-menu-320-440');await meetingWithin(actors.reviewer);await actors.reviewer.getByRole('option',{name:'Decline this meeting proposal',exact:true}).click();await actors.reviewer.getByLabel('Meeting decision reason',{exact:true}).fill('PRIVATE_MEETING declined this cancellation; the original agenda stays published.');await actors.reviewer.getByRole('checkbox',{name:meetingDecisionConfirmation,exact:true}).check();await actors.reviewer.getByRole('button',{name:'Decline this meeting proposal',exact:true}).click();expect(await meetingDetail(owner,id,false)).toEqual(acknowledged)
  await cancellation('PRIVATE_MEETING a later supplied cancellation to be cancelled by its own preparer.');await page.getByRole('button',{name:'Cancel your meeting proposal',exact:true}).click();await page.getByLabel('Meeting decision reason',{exact:true}).fill('PRIVATE_MEETING deliberately cancel only my pending proposal.');await page.getByRole('checkbox',{name:meetingDecisionConfirmation,exact:true}).check();await page.getByRole('button',{name:'Cancel pending meeting proposal',exact:true}).click();expect(await meetingDetail(owner,id,false)).toEqual(acknowledged)
  await cancellation('PRIVATE_MEETING a separately supplied and checked public meeting cancellation.');await openMeeting(owner,id,false);await expect(owner.getByText('You acknowledged version 1 on',{exact:false})).toBeVisible();await meetingApprove(actors.reviewer,id);await openMeeting(owner,id,false);await owner.setViewportSize({width:320,height:440});await expect(owner.getByRole('dialog').locator('.community-state').first()).toHaveText('Meeting cancelled');await expect(owner.getByRole('button',{name:'Acknowledge this version',exact:true})).toHaveCount(0);await owner.getByText('Public cancellation update',{exact:true}).scrollIntoViewIfNeeded();await meetingCapture(owner,'published-cancellation-320-440');const cancelled=await meetingDetail(owner,id,false);expect(cancelled.snapshot.start_at).toBe(original.snapshot.start_at);expect(cancelled.snapshot.homes).toEqual(original.snapshot.homes);expect(cancelled.acknowledgement.required).toBe(false)
  expect((await tenant.request.get('/api/meetings/'+id)).status()).toBe(403);await tenant.goto('/#community?meeting='+id);await expect(tenant.getByRole('dialog').getByRole('alert')).toBeVisible();await tenant.setViewportSize({width:320,height:440});await meetingCapture(tenant,'cross-home-denied-320-440');messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=date('now','+330 minutes') WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101' AND end_date IS NULL\")");await owner.reload();await expect(owner.getByRole('dialog').getByRole('alert')).toBeVisible();await expect(owner.getByText('The society supplied an explicit cancellation of this fictional meeting.',{exact:true})).toHaveCount(0);await meetingCapture(owner,'ended-home-denied-320-440')
  await openMeeting(page,id);await expect(page.getByRole('button',{name:'Prepare a revised agenda',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Propose meeting withdrawal',exact:true}).click();await page.getByLabel('Private meeting proposal reason',{exact:true}).fill('PRIVATE_MEETING separately supplied withdrawal retains the original and personal responses.');await page.getByRole('button',{name:'Review exact meeting proposal',exact:true}).click();await page.getByRole('checkbox',{name:meetingProposalConfirmation,exact:true}).check();await page.getByRole('button',{name:'Submit meeting for separate review',exact:true}).click();await meetingApprove(actors.reviewer,id);expect((await page.request.get('/api/meetings/'+id)).status()).toBe(404);await openMeeting(page,id);await expect(page.getByRole('dialog').locator('.community-state').first()).toHaveText('Publication withdrawn');await page.setViewportSize({width:375,height:640});await page.getByRole('button',{name:'View personal responses',exact:true}).click();await expect(page.locator('.meeting-response-counts strong')).toHaveText(['0','0','0','1']);await meetingCapture(page,'withdrawn-retained-response-375');const retained=await meetingDetail(page,id);expect(retained.event_total).toBe(10);expect(retained.events.at(-1).snapshot.action).toBe('AGENDA');expect(retained.events.at(-1).snapshot.start_at).toBe(original.snapshot.start_at)
 }finally{messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=NULL WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101'\")");await Promise.allSettled([actors.close(),oc.close(),tc.close()])}
})
