import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mkdirSync, chmodSync } from 'node:fs'
import { resolve } from 'node:path'
import { createHash } from 'node:crypto'
import { login, navigate, chooseOption } from './helpers'
import { plainPDF } from './document-fixtures'

async function capture(page: Page, name: string, fullPage = false) {
  if (!process.env.SOCIETY_CAPTURE_UI) return
  await page.evaluate(() => document.fonts.ready)
  if (fullPage) await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  const folder = resolve('../reports/local/overview-review'); mkdirSync(folder, { recursive: true, mode: 0o700 })
  const path = resolve(folder, name + '.png'); await page.screenshot({ path, fullPage, animations: 'disabled' }); chmodSync(path, 0o600)
}
async function overview(page: Page) { await navigate(page, 'Overview'); await expect(page.getByRole('heading', { name: 'Good things, in order.' })).toBeVisible(); await expect(page.getByRole('button', { name: 'Refresh overview' })).toBeEnabled(); await page.getByRole('button', { name: 'Refresh overview' }).click(); await expect(page.getByRole('button', { name: 'Refresh overview' })).toBeEnabled() }
async function post(page: Page, path: string, data: Record<string, unknown>) { const me = await (await page.request.get('/api/auth/me')).json(); const response = await page.request.post(path, { headers: { Origin: new URL(page.url()).origin, 'X-CSRF-Token': me.csrf_token }, data: { operation_key: crypto.randomUUID(), ...data } }); expect(response.status(), await response.text()).toBe(200); return response.json() }
async function reviewFixture(page: Page, title: string, audience = '') { return (await post(page, '/api/reviews', { kind: audience ? 'NOTICE' : 'MAINTENANCE', title, body: 'A fictional request with enough detail for independent overview verification.', flat_id: audience ? '' : 'demo-flat-A-101', audience, building_code: '', estimate: '' })).id as string }
async function entry(page: Page, description: string, kind: string, amount: string, home: string, confirmed = true) { const date = new Intl.DateTimeFormat('en-CA', { year: 'numeric', month: '2-digit', day: '2-digit', timeZone: 'Asia/Kolkata' }).format(new Date()); const id = (await post(page, '/api/entries', { flat_id: home, kind, amount, date, description, payer: kind === 'RECEIVED' ? 'Fictional payer' : '', method: kind === 'RECEIVED' ? 'UPI' : '', reference: kind === 'RECEIVED' ? 'DAY-REFERENCE' : '' })).id as string; if (confirmed) await post(page, '/api/entries/' + id + '/post', { confirmed: true, reason: '' }); return id }

test('the empty overview and every new destination work with keyboard and exact navigation', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 }); await login(page); await expect(page.getByRole('button', { name: 'Refresh overview' })).toBeEnabled()
  await expect(page.getByRole('heading', { name: 'All clear for now.' })).toBeVisible(); await expect(page.locator('.stat-item')).toHaveCount(0); await expect(page.getByRole('region', { name: 'What is changing' }).locator('.overview-metric strong')).toHaveText(['0','0','0','0']); await capture(page, 'empty-desktop', true)
  const destinations = [ ['Open for your decision', 'Every idea deserves a thoughtful review.'], ['Open active service requests','Little things, well taken care of.'], ['Open document attention','A place for the papers that matter.'], ['Open recent notices','Good to know. Good to share.'], ['Open entries','The entry book'], ['View receipts','Your receipt collection'], ['All notices','Good to know. Good to share.'], ['Open homes & people','Homes & people'], ['Document library','A place for the papers that matter.'], ['Open requests & approvals','Every idea deserves a thoughtful review.'], ['Open help & repairs','Little things, well taken care of.'] ]
  for (const [label, heading] of destinations) { const target = page.getByRole('link', { name: label, exact: true }); await target.focus(); await page.keyboard.press('Enter'); await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible(); await overview(page) }
  await page.getByRole('button', { name: 'Refresh overview' }).focus(); const read = page.waitForResponse(response => response.url().endsWith('/api/overview/service')); await page.keyboard.press('Enter'); expect((await read).status()).toBe(200); await expect(page.getByRole('button', { name: 'Refresh overview' })).toBeFocused()
})

test('overview refresh preserves a destination the user focuses before the refresh finishes', async ({ page }) => {
  await login(page); await expect(page.getByRole('button', { name: 'Refresh overview' })).toBeEnabled()
  let release: () => void = () => {}; const pending = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/overview/service', async route => { await pending; await route.continue() })
  await page.getByRole('button', { name: 'Refresh overview' }).click(); await expect(page.getByRole('button', { name: 'Refresh overview' })).toBeDisabled()
  const destination = page.getByRole('link', { name: 'View receipts', exact: true }); await destination.focus(); await expect(destination).toBeFocused(); release()
  await expect(page.getByRole('button', { name: 'Refresh overview' })).toBeEnabled()
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  await destination.scrollIntoViewIfNeeded(); await expect(destination).toBeInViewport()
  await capture(page, 'refresh-preserved-destination-focus'); await expect(destination).toBeFocused(); await page.keyboard.press('Enter'); await expect(page.getByRole('heading', { name: 'Your receipt collection', exact: true })).toBeVisible()
})

test('real resident reports and uploads become scoped staff work with full counts and exact detail links', async ({ page }) => {
  test.setTimeout(90000); await login(page, 'Owner'); await navigate(page, 'Help & repairs'); await page.getByRole('button', { name: 'Report an issue', exact: true }).click(); await chooseOption(page,'Service request home','Home A-101'); await chooseOption(page,'Service category','Plumbing'); await chooseOption(page,'Service priority','Urgent'); await page.getByRole('textbox',{name:'Subject',exact:true}).fill('DAY Urgent water leak'); await page.getByRole('textbox',{name:'Details',exact:true}).fill('A fictional urgent water leak needs a handler and a progress update.'); await page.getByRole('button',{name:'Save service request',exact:true}).click(); await expect(page.getByRole('dialog').locator('.case-status')).toHaveText('Open'); await page.getByRole('button',{name:'Close service request details',exact:true}).click()
  const requests: string[] = []; for (let i=0;i<6;i++) requests.push(await reviewFixture(page,'DAY Maintenance decision '+i)); const notice = await reviewFixture(page,'DAY Water supply update','ALL_RESIDENTS'); const ownersNotice = await reviewFixture(page,'DAY Owners meeting update','OWNERS_ONLY')
  await navigate(page,'Documents'); await page.getByRole('button',{name:'Add a document',exact:true}).click(); await page.getByLabel('Document file',{exact:true}).setInputFiles({name:'day-contract.pdf',mimeType:'application/pdf',buffer:plainPDF()}); await page.getByRole('textbox',{name:'Title',exact:true}).fill('DAY Lift service contract'); await chooseOption(page,'Document category','Contract'); await chooseOption(page,'Document audience','Current society residents'); const date = new Date(Date.now()+10*86400000).toISOString().slice(0,10); await page.getByLabel('Document expiry date',{exact:true}).fill(date); await page.getByRole('button',{name:'Upload for review',exact:true}).click(); await expect(page.getByRole('button',{name:'Download original',exact:true})).toBeEnabled(); await page.getByRole('button',{name:'Close document details',exact:true}).click(); await overview(page); await expect(page.getByRole('region',{name:'What is changing'}).getByText('8 of your requests await a reviewer',{exact:true})).toBeVisible(); await capture(page,'owner-awaiting-decisions',true)
  await page.getByRole('button',{name:'Sign out',exact:true}).click(); await login(page); await overview(page); await expect(page.getByRole('region',{name:'For your decision'}).locator('strong')).toHaveText('8'); await expect(page.getByRole('link',{name:'Urgent service request: DAY Urgent water leak',exact:true})).toBeVisible(); const target = page.locator('.overview-action-list a[aria-label^="A decision from you: DAY Maintenance decision"]').first(); await expect(target).toBeVisible(); const changedTitle=(await target.getAttribute('aria-label'))!.split(': ')[1]; await capture(page,'staff-populated-queue',true)
  await target.click(); await expect(page.getByRole('dialog').getByRole('heading',{name:changedTitle,exact:true})).toBeVisible(); await chooseOption(page,'Review decision','Request changes'); await page.getByRole('textbox',{name:'Reason for this decision',exact:true}).fill('Please add the fictional service date before independent review.'); await page.getByRole('checkbox').check(); await page.getByRole('button',{name:'Request these changes',exact:true}).click(); await expect(page.getByRole('dialog').locator('.review-status')).toHaveText('Changes requested'); await capture(page,'request-decision-dialog'); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0); await expect.poll(()=>new URL(page.url()).hash).toBe('#reviews'); await page.reload(); await expect(page.getByRole('dialog')).toHaveCount(0)
  for (const id of [notice,ownersNotice]) await post(page,'/api/reviews/'+id+'/decision',{version:1,decision:'APPROVED',reason:'Fictional content and target audience independently reviewed',confirmed:true})
  await overview(page); await page.getByRole('link',{name:'Review this document: DAY Lift service contract',exact:true}).click(); await expect(page.getByRole('dialog').getByRole('heading',{name:'DAY Lift service contract',exact:true})).toBeVisible(); await chooseOption(page,'Document decision','Approve this version'); await page.getByRole('textbox',{name:'Document decision reason'}).fill('The fictional contract and its society audience have been independently checked'); await page.getByRole('checkbox',{name:'I have checked this version, its audience and my decision.'}).check(); await page.getByRole('button',{name:'Save document decision',exact:true}).click(); await expect(page.getByRole('dialog').locator('.review-state')).toHaveText('Approved'); await page.keyboard.press('Escape')
  await overview(page); await page.getByRole('link',{name:'Urgent service request: DAY Urgent water leak',exact:true}).click(); await expect(page.getByRole('dialog').getByRole('heading',{name:'DAY Urgent water leak',exact:true})).toBeVisible(); await page.keyboard.press('Escape'); await overview(page); await page.getByRole('link',{name:'Read notice: DAY Water supply update',exact:true}).click(); await expect(page.getByRole('dialog').getByRole('heading',{name:'DAY Water supply update',exact:true})).toBeVisible(); await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'Sign out',exact:true}).click(); await login(page,'Owner'); await overview(page); await page.getByRole('link',{name:'Update your submission: '+changedTitle,exact:true}).click(); await expect(page.getByRole('dialog').getByRole('heading',{name:changedTitle,exact:true})).toBeVisible(); await page.keyboard.press('Escape'); await overview(page); await capture(page,'owner-changes-and-deadline',true)
  await page.getByRole('button',{name:'Sign out',exact:true}).click(); await login(page,'Tenant'); await overview(page); await expect(page.getByRole('heading',{name:'Money, accounted for.'})).toHaveCount(0); await expect(page.getByText('DAY Owners meeting update',{exact:true})).toHaveCount(0); await expect(page.getByText('DAY Urgent water leak',{exact:true})).toHaveCount(0); await page.getByRole('link',{name:'Document expiry approaching: DAY Lift service contract',exact:true}).click(); await expect(page.getByRole('button',{name:'Download original',exact:true})).toBeEnabled(); await page.keyboard.press('Escape'); await overview(page); await capture(page,'tenant-permitted-overview',true)
})

test('recorded balances retain exact per-home credits and a draft links to its human confirmation', async ({ page }) => {
  await login(page); await entry(page,'DAY Supplied charge','CHARGE','100.10','demo-flat-A-101'); await entry(page,'DAY Opening surplus','OPENING_CREDIT','200.00','demo-flat-A-102'); await entry(page,'DAY Externally received','RECEIVED','25.25','demo-flat-A-101'); const id=await entry(page,'DAY Draft to check','CHARGE','500.00','demo-flat-A-101',false); await overview(page)
  const finance=page.getByRole('region',{name:'Money, accounted for.'}); await expect(finance.locator('.overview-finance-balance strong')).toHaveText('₹74.85'); await expect(finance.locator('.overview-finance-lines strong')).toHaveText(['₹200.00','-₹125.15','₹25.25']); await capture(page,'finance-per-home-balances',true)
  await page.getByRole('link',{name:'Confirm supplied entry: DAY Draft to check',exact:true}).click(); expect(new URL(page.url()).hash).toBe('#entries?entry='+id); await expect(page.getByRole('dialog').getByRole('heading',{name:'Review this draft.',exact:true})).toBeVisible(); await expect(page.getByRole('button',{name:'Confirm this entry',exact:true})).toBeDisabled(); await capture(page,'draft-deep-link'); await page.keyboard.press('Escape'); await expect.poll(()=>new URL(page.url()).hash).toBe('#entries'); await page.reload(); await expect(page.getByRole('dialog')).toHaveCount(0); await page.goBack(); await expect(page.getByRole('heading',{name:'Good things, in order.'})).toBeVisible()
})

test('each source failure is isolated and its retry refreshes real data without false zeroes', async ({ page }) => {
  await login(page); await overview(page)
  for (const [section,label,metric] of [['reviews','Requests','For your decision'],['service','Service requests','Active service requests'],['documents','Documents','Document attention'],['notices','Notices','Recent notices'],['finance','Financial records','']] as const) {
    await page.route('**/api/overview/'+section,route=>route.fulfill({status:503,contentType:'application/json',body:'{}'})); await page.getByRole('button',{name:'Refresh overview'}).click(); await expect(page.getByRole('alert').getByText(label+' unavailable',{exact:true})).toBeVisible(); if (metric) await expect(page.getByRole('region',{name:metric,exact:true}).locator('strong')).toHaveText('—'); else await expect(page.locator('.overview-finance-balance strong')).toHaveText('—'); await capture(page,'source-error-'+section,true)
    await page.unroute('**/api/overview/'+section); await page.getByRole('button',{name:'Retry '+label.toLowerCase(),exact:true}).click(); await expect(page.getByRole('alert')).toHaveCount(0); await expect(page.getByRole('button',{name:'Refresh overview'})).toBeEnabled()
  }
})

test('a slow source keeps its value unknown and navigation aborts its pending read', async ({ page }) => {
  await login(page); await overview(page); let release: () => void=()=>{}; const waiting=new Promise<void>(resolve=>{release=resolve}); await page.route('**/api/overview/service',async route=>{await waiting; await route.continue().catch(()=>{})}); await page.getByRole('button',{name:'Refresh overview'}).click(); await expect(page.getByRole('region',{name:'Active service requests',exact:true}).locator('strong')).toHaveText('—'); await expect(page.getByRole('button',{name:'Refresh overview'})).toBeDisabled(); await expect(page.getByText('Updating service requests…',{exact:true})).toBeVisible(); await capture(page,'source-pending',true); await page.getByRole('link',{name:'Open homes & people',exact:true}).click(); await expect(page.getByRole('heading',{name:'Homes & people',exact:true})).toBeVisible(); release(); await page.unroute('**/api/overview/service'); await overview(page); await expect(page.getByRole('button',{name:'Refresh overview'})).toBeEnabled()
})

test('populated overview, direct dialogs and opened menus fit four sizes with clear focus', async ({ page }) => {
  await page.emulateMedia({reducedMotion:'reduce'}); await login(page)
  for (const viewport of [{width:1440,height:900},{width:768,height:1024},{width:375,height:812},{width:320,height:568}]) { await page.setViewportSize(viewport); await overview(page); await page.evaluate(()=>window.scrollTo(0,0)); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true); await capture(page,'populated-'+viewport.width,true); await page.getByRole('button',{name:'Refresh overview'}).focus(); await capture(page,'refresh-focus-'+viewport.width); await page.getByRole('link',{name:'Urgent service request: DAY Urgent water leak',exact:true}).click(); await expect(page.getByRole('dialog').getByRole('heading',{name:'DAY Urgent water leak',exact:true})).toBeVisible(); await page.getByRole('combobox',{name:'Service update type',exact:true}).click(); await expect(page.getByRole('listbox')).toBeInViewport({ratio:1}); await capture(page,'linked-case-menu-'+viewport.width); await page.keyboard.press('Escape'); await page.getByRole('button',{name:'Close service request details',exact:true}).click(); await page.goBack(); await expect(page.getByRole('heading',{name:'Good things, in order.'})).toBeVisible(); await expect(page.getByRole('link',{name:'Urgent service request: DAY Urgent water leak',exact:true})).toBeFocused() }
})

test('denied and stale request or entry deep links disclose no hidden record and retain retry controls', async ({ page }) => {
  await login(page,'Tenant'); for (const [view,label,retry] of [['reviews?request='+ 'A'.repeat(43),'Close request details','Reload request'],['entries?entry='+ 'A'.repeat(43),'','']] as const) { await page.goto('/#'+view); if (label) { await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible(); await expect(page.getByRole('heading',{name:'Request unavailable',exact:true})).toBeVisible(); await expect(page.getByRole('button',{name:retry,exact:true})).toBeEnabled(); await capture(page,'request-unavailable'); await page.getByRole('button',{name:label,exact:true}).click() } else { await expect(page.getByRole('heading',{name:'These records need access.',exact:true})).toBeVisible(); await capture(page,'finance-denied') } }
})

test('a combined source outage shows unknowns and section retries restore usable work', async ({ page }) => {
  await login(page); await page.route('**/api/overview/*', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{}' })); await overview(page)
  await expect(page.locator('.overview-metric > strong')).toHaveText(['—','—','—','—']); await expect(page.getByRole('alert')).toHaveCount(8); await expect(page.getByRole('region', { name: 'Maintenance, in view.', exact: true }).locator('.overview-maintenance-amounts strong')).toHaveText(['—','—','—']); await expect(page.getByRole('region', { name: 'Collections, in view.', exact: true }).locator('.overview-maintenance-amounts strong')).toHaveText(['—','—','—']); await expect(page.getByRole('heading', { name: 'All clear for now.' })).toHaveCount(0); await expect(page.getByText('Some sections need a retry', { exact: true })).toBeVisible(); await capture(page, 'combined-source-outage', true)
  await page.unroute('**/api/overview/*'); await page.getByRole('button', { name: 'Retry service requests', exact: true }).click(); await expect(page.getByRole('alert')).toHaveCount(7); await expect(page.getByRole('link', { name: 'Urgent service request: DAY Urgent water leak', exact: true })).toBeVisible(); await capture(page, 'partial-outage-recovery', true); await page.getByRole('button', { name: 'Refresh overview' }).click(); await expect(page.getByRole('alert')).toHaveCount(0)
})

test('an interrupted original appears as uploader work and clears after a real resumed upload', async ({ page }) => {
  await login(page,'Owner'); const bytes=plainPDF(); const id=(await post(page,'/api/documents',{title:'DAY Interrupted original',filename:'interrupted.pdf',size_bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),category:'RESIDENT_DOCUMENT',visibility:'RESIDENT_SPECIFIC',flat_id:'',subject_resident_id:'',expiry_date:'',replaces_document_id:'',version:0})).id as string
  await overview(page); await page.getByRole('link',{name:'Your upload needs attention: DAY Interrupted original',exact:true}).click(); await expect(page.getByRole('dialog').getByRole('heading',{name:'DAY Interrupted original',exact:true})).toBeVisible(); await expect(page.getByRole('button',{name:'Download original',exact:true})).toHaveCount(0); await capture(page,'uploader-resume-dialog'); await page.getByRole('button',{name:'Finish this upload',exact:true}).click(); await page.getByLabel('Document file',{exact:true}).setInputFiles({name:'interrupted.pdf',mimeType:'application/pdf',buffer:bytes}); await page.getByRole('button',{name:'Finish upload',exact:true}).click(); await expect(page.getByRole('button',{name:'Download original',exact:true})).toBeEnabled(); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0); await overview(page); await expect(page.getByRole('link',{name:'Your upload needs attention: DAY Interrupted original',exact:true})).toHaveCount(0); await capture(page,'uploader-attention-cleared',true)
  expect((await page.request.get('/api/documents/'+id)).status()).toBe(200)
})
