import { test, expect } from '@playwright/test'
import { login, navigate } from './helpers'
import { budgetEntry, budgetGet, budgetActors } from './budgets-fixtures'
import { checklistDesk, checklistPost } from './checklists-fixtures'
import { apiFund, apiFundAction, apiFundReport } from './collections-fixtures'
import { performanceCapture, performanceWithin, screenModule } from './performance-fixtures'

test.setTimeout(90000)
test('initial browser payload meets independent byte budget and all operational deep links load actual screens',async({page})=>{
 const requests:string[]=[];page.on('request',r=>{if(new URL(r.url()).pathname.endsWith('.js'))requests.push(new URL(r.url()).pathname)});await page.goto('/');await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();const bytes=await page.evaluate(()=>performance.getEntriesByType('resource').filter(e=>new URL(e.name).pathname.endsWith('.js')).reduce((sum,e)=>sum+(e as PerformanceResourceTiming).decodedBodySize,0));expect(bytes).toBeGreaterThan(0);expect(bytes).toBeLessThanOrEqual(879715)
 for(const name of ['Records','Statements','Fines','MoveChecklists','webmcp-register'])expect(requests).not.toContain(screenModule(name));await page.setViewportSize({width:375,height:640});await performanceCapture(page,'initial-signin-375-640');await login(page);await expect(page.getByRole('heading',{name:'Good things, in order.',exact:true})).toBeVisible();await performanceCapture(page,'initial-current-overview-375-640')
 for(const [hash,title] of [['entries','Every detail'],['receipts','Every detail'],['reviews',''],['community',''],['help',''],['documents',''],['maintenance',''],['upkeep',''],['collections',''],['conduct',''],['fines',''],['contacts',''],['messages',''],['statements',''],['homes?panel=checklists','']]){await page.goto('/#'+hash);await page.reload();await expect(page.locator('main h1')).toBeVisible();await expect(page.getByRole('heading',{name:'Opening this screen…',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'This screen could not be opened.',exact:true})).toHaveCount(0);if(title)expect(await page.locator('main h1').innerText()).not.toBe('');await performanceWithin(page)}
 await page.setViewportSize({width:1440,height:1000});await performanceCapture(page,'checklist-loaded-desktop');await navigate(page,'Maintenance');await expect(page.getByRole('combobox',{name:'Filter maintenance by home',exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Filter maintenance by home',exact:true}).click();await expect(page.getByRole('option',{name:'All permitted homes',exact:true})).toBeVisible();await page.getByRole('option',{name:'Home A-101',exact:true}).hover();await performanceCapture(page,'loaded-menu-desktop');await page.keyboard.press('Home');await expect(page.getByRole('option',{name:'All permitted homes',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('combobox',{name:'Filter maintenance by home',exact:true})).toBeFocused()
})

test('slow screen loading preserves navigation signout and responsive layouts and abandoned imports do not reopen old views',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await login(page);const module=screenModule('Records');let release=()=>{},ready!:()=>void;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r});await page.route('**'+module,async route=>{ready();await held;await route.continue().catch(()=>{})})
 try{await navigate(page,'Entries');await entered;await expect(page.getByRole('heading',{name:'Opening this screen…',exact:true})).toBeVisible();for(const [width,height] of [[1440,1000],[768,1000],[375,640],[320,440]]){await page.setViewportSize({width,height});await performanceCapture(page,'loading-'+width+'-'+height);await performanceWithin(page);await expect(page.getByRole('button',{name:'Sign out',exact:true})).toBeEnabled()}release();await expect(page.getByRole('heading',{name:'Opening this screen…',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'The entry book',exact:true})).toBeVisible();await page.unroute('**'+module)
 const review=screenModule('Reviews');let captured!:()=>void;const readyReview=new Promise<void>(r=>{captured=r}),holdReview=new Promise<void>(r=>{release=r});await page.route('**'+review,async route=>{captured();await holdReview;await route.continue().catch(()=>{})});await navigate(page,'Requests & approvals');await readyReview;await expect(page.getByRole('heading',{name:'Opening this screen…',exact:true})).toBeVisible();await navigate(page,'Overview');await expect(page.getByRole('heading',{name:'Good things, in order.',exact:true})).toBeVisible();release();await page.unroute('**'+review);await expect(page.locator('.breadcrumb strong')).toHaveText('Overview');await expect(page.getByRole('heading',{name:'Good things, in order.',exact:true})).toBeVisible();await performanceCapture(page,'abandoned-import-current-overview-320-440')
 }finally{release()}
})

test('failed deep-link module gives deliberate reload and retains exact already-received entry and receipt',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await login(page);const id=await budgetEntry(page,'43.21','2026-10-01'),before=await budgetGet<{amount_paise:number;receipt_id:string;receipt_number:string;state:string}>(page,'/api/entries/'+id),module=screenModule('Records');await page.route('**'+module,route=>route.fulfill({status:404,contentType:'application/javascript',body:'/* unavailable old chunk */'}));await page.goto('/#entries?entry='+id);await expect(page.getByRole('heading',{name:'This screen could not be opened.',exact:true})).toBeVisible();expect(page.url()).toContain('#entries?entry='+id);await expect(page.getByRole('button',{name:'Reload this screen',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Sign out',exact:true})).toBeEnabled();for(const [width,height] of [[1440,1000],[768,1000],[375,640],[320,440]]){await page.setViewportSize({width,height});await performanceCapture(page,'failed-screen-'+width+'-'+height);await performanceWithin(page)}
 await page.getByRole('button',{name:'Reload this screen',exact:true}).scrollIntoViewIfNeeded();await performanceCapture(page,'failed-screen-actions-320-440');await page.unroute('**'+module);await page.getByRole('button',{name:'Reload this screen',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('.record-detail-amount strong')).toHaveText('₹43.21');const after=await budgetGet<typeof before>(page,'/api/entries/'+id);expect(after).toMatchObject({amount_paise:4321,state:'POSTED',receipt_id:before.receipt_id,receipt_number:before.receipt_number});expect((await budgetGet<{total:number}>(page,'/api/entries?receipts=true')).total).toBe(1);for(const [width,height] of [[1440,1000],[768,1000],[375,640],[320,440]]){await page.setViewportSize({width,height});await page.locator('.record-detail-amount').scrollIntoViewIfNeeded();await performanceCapture(page,'reloaded-original-deep-link-'+width+'-'+height);await performanceWithin(page)}await page.getByRole('button',{name:'Close entry details',exact:true}).click()
})

test('load error notifications preserve human draft and logout during an import discards late private work',async({page})=>{
 await page.setViewportSize({width:375,height:640});await login(page);await checklistDesk(page);await page.getByRole('button',{name:'Prepare a checklist',exact:true}).click();const marker='PRIVATE_PERF the supplied human explanation must remain here.';await page.getByRole('textbox',{name:'Checklist explanation',exact:true}).fill(marker);const writes:string[]=[];page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))writes.push(new URL(r.url()).pathname)});await page.evaluate(()=>{const event=new Event('vite:preloadError');Object.assign(event,{payload:new Error('A deferred screen could not be fetched.')});window.dispatchEvent(event)});await expect(page.getByRole('textbox',{name:'Checklist explanation',exact:true})).toHaveValue(marker);expect(writes).toEqual([]);await page.getByRole('textbox',{name:'Checklist explanation',exact:true}).scrollIntoViewIfNeeded();await performanceCapture(page,'human-draft-preserved-375-640');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)
 const module=screenModule('Contacts');let release=()=>{},ready!:()=>void;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r});await page.route('**'+module,async route=>{ready();await held;await route.continue().catch(()=>{})});try{await navigate(page,'Contacts');await entered;await expect(page.getByRole('heading',{name:'Opening this screen…',exact:true})).toBeVisible();await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();release();await page.unroute('**'+module);await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('body')).not.toContainText(marker);expect(writes).toEqual(['/api/auth/logout']);await performanceCapture(page,'logout-during-import-375-640')}finally{release()}
})

test('current report fragment wins while Collections first loads and closed-fund revision remains a claim',async({page,browser})=>{
 const a=await budgetActors(page,browser),context=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await context.newPage();let release=()=>{}
 try{await owner.setViewportSize({width:1440,height:1000});const fund=await apiFund(page,'Deferred current-link collection');await apiFundAction(a.reviewer,fund,'PUBLISHED');await login(owner,'Owner');const report=await apiFundReport(owner,fund,'10.00','PERF-FRAGMENT-'+fund);await checklistPost(page,'/api/payment-reports/'+report+'/actions',{version:1,action:'REJECTED',reason:'The supplied external report needs an independently reviewed explanation.'});await apiFundAction(a.reviewer,fund,'CLOSED');const module=screenModule('Collections');let ready!:()=>void;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r});await owner.route('**'+module,async route=>{ready();await held;await route.continue().catch(()=>{})});await owner.goto('/#collections?campaign='+fund);await entered;await expect(owner.getByRole('heading',{name:'Opening this screen…',exact:true})).toBeVisible();release();await owner.goto('/#collections?report='+report);await expect(owner.getByRole('button',{name:'Revise this report',exact:true})).toBeVisible();await expect(owner.getByRole('dialog').getByText('Not verified',{exact:true})).toBeVisible();expect(owner.url()).toContain('#collections?report='+report);await performanceCapture(owner,'rapid-current-report-desktop');await owner.setViewportSize({width:320,height:440});await owner.getByRole('button',{name:'Revise this report',exact:true}).scrollIntoViewIfNeeded();await performanceCapture(owner,'rapid-current-report-action-320-440');await performanceWithin(owner)
 await owner.getByRole('button',{name:'Revise this report',exact:true}).click();await owner.getByRole('textbox',{name:'Supporting comment (optional)',exact:true}).fill('The actual supplied explanation is retained after deferred first navigation.');await owner.getByRole('button',{name:'Review payment report',exact:true}).click();await owner.getByRole('dialog').getByRole('checkbox').check();await owner.getByRole('button',{name:'Send revised payment report',exact:true}).click();await expect(owner.getByRole('dialog').getByText('Awaiting verification',{exact:true})).toBeVisible();await owner.setViewportSize({width:375,height:640});await performanceCapture(owner,'rapid-current-report-revised-375-640');const current=await budgetGet<{version:number;receipt:string;amount_paise:number}>(owner,'/api/payment-reports/'+report);expect(current).toMatchObject({version:3,receipt:'',amount_paise:1000});expect((await budgetGet<{outstanding_paise:number}>(page,'/api/collections/'+fund)).outstanding_paise).toBe(150025)
 }finally{release();await context.close();await a.close()}
})
