import { test, expect } from '@playwright/test'
import { login, chooseFilter } from './helpers'

test.beforeEach(async ({ page }) => {
  await login(page)
  await expect(page.getByRole('heading', { name: 'Good things, in order.' })).toBeVisible()
})

test('overview links to home counts, wing registry, details and working filters', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Good things, in order.' })).toBeVisible()
  await page.getByRole('link', { name: 'Open homes & people', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Explore Wing A, 40 homes' })).toBeVisible()
  await expect(page.locator('.stat-item').filter({ hasText: 'Owners' }).locator('strong')).toHaveText('118')
  await expect(page.locator('.stat-item').filter({ hasText: 'Tenants' }).locator('strong')).toHaveText('35')
  await expect(page.locator('.stat-item').filter({ has: page.getByText('Occupied', { exact: true }) }).locator('strong')).toHaveText('109')
  await expect(page.locator('.stat-item').filter({ hasText: 'Vacant' }).locator('strong')).toHaveText('9')
  await page.getByRole('button', { name: 'Explore Wing A, 40 homes' }).click()
  await expect(page.getByRole('status')).toHaveText('40 homes found')
  await page.getByRole('link', { name: 'Skip to content', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Every home has a story.', exact: true })).toBeVisible()
  expect(new URL(page.url()).hash).toBe('#homes')
  await page.getByRole('button', { name: 'View home A-101', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Home 101', exact: true })).toBeVisible()
  await expect(page.getByText('Demo Joint Owner A-101', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'View home A-101', exact: true })).toBeFocused()
  await page.getByLabel('Search homes or people').fill('Demo Owner A-101')
  await expect(page.getByRole('status')).toHaveText('2 homes found')
  await page.getByLabel('Search homes or people').fill('Does not exist')
  await expect(page.getByRole('heading', { name: 'No homes found.' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('118 homes found')
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  await expect(page.getByText('Page 2 of 10', { exact: true })).toBeVisible()
  await chooseFilter(page, 'Filter by occupancy', 'VACANT')
  await expect(page.getByRole('status')).toHaveText('9 homes found')
  expect(errors).toEqual([])
})

test('small phone has no page overflow and accessible detail dismissal', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.getByRole('link', { name: 'Open homes & people', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('link', { name: 'Open homes & people', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('118 homes found')
  await page.getByRole('button', { name: 'View home A-101', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Close details', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('connection failure has a working retry', async ({ page }) => {
  await page.route('**/api/flats?**', route => route.fulfill({ status: 503, body: '{}' }))
  await page.goto('/#homes')
  await expect(page.getByRole('heading', { name: 'Let’s try that again.' })).toBeVisible()
  await page.unroute('**/api/flats?**')
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('118 homes found')
})
