import { test,expect } from '@playwright/test'
import { login,chooseOption } from './helpers'
import { messagePost,messageApprove,messagePrivateFixture,messageProposal,openMessage } from './messages-fixtures'
import { apiFund,apiFundAction,apiFundReport } from './collections-fixtures'
import { meetingProposal,meetingApprove,meetingPost,openMeeting,meetingAckConfirmation } from './meetings-fixtures'
import { reminderActors,reminderMaintenance,reminderPayment,reminderAllocate,reminderMessage,reminderActionUI,reminderStartUI,reminderCapture,reminderWithin,reminderPreviewCheck } from './reminders-fixtures'

test.setTimeout(90000)
test('private exception empty loading error retry real menus and access render across five layouts',async({page,browser})=>{
 await login(page);await page.goto('/#messages?panel=exceptions');await expect(page.getByRole('heading',{name:'No delivery exceptions in this view.',exact:true})).toBeVisible()
 for(const [width,height] of [[1440,1000],[768,1000],[375,640],[320,640],[320,440]]){await page.setViewportSize({width,height});await page.getByRole('navigation',{name:'Communication views'}).scrollIntoViewIfNeeded();if(width<=760){const geometry=await page.locator('.message-exceptions > .section-heading').evaluate(node=>{const copy=node.querySelector('div')!.getBoundingClientRect(),badge=node.querySelector('.result-count')!.getBoundingClientRect();return {copyBottom:copy.bottom,badgeTop:badge.top}});expect(geometry.badgeTop).toBeGreaterThanOrEqual(geometry.copyBottom)}await reminderCapture(page,'empty-exceptions-'+width+'-'+height);await reminderWithin(page);await page.getByRole('combobox',{name:'Filter delivery exceptions',exact:true}).click();await page.getByRole('option',{name:'Definite failures',exact:true}).hover();await reminderCapture(page,'exception-menu-'+width+'-'+height);await reminderWithin(page);await page.keyboard.press('End');await expect(page.getByRole('option',{name:'Handoff pending',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('combobox',{name:'Filter delivery exceptions',exact:true})).toContainText('Handoff pending');await page.getByRole('button',{name:'Clear exception filter',exact:true}).click()}
 let release!:()=>void,ready!:()=>void;const held=new Promise<void>(r=>{release=r}),entered=new Promise<void>(r=>{ready=r})
 await page.route('**/api/messages/exceptions?**',async route=>{ready();await held;await route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporarily_unavailable"}'})});await page.reload();await entered;await expect(page.getByText('Checking retained delivery outcomes…',{exact:true})).toBeVisible();await page.getByText('Checking retained delivery outcomes…',{exact:true}).scrollIntoViewIfNeeded();await reminderCapture(page,'exceptions-loading-320-440');release();await expect(page.getByRole('heading',{name:'Delivery exceptions could not be opened.',exact:true})).toBeVisible();await reminderCapture(page,'exceptions-error-320-440');await page.unroute('**/api/messages/exceptions?**');await page.getByRole('button',{name:'Retry delivery exceptions',exact:true}).click();await expect(page.getByRole('heading',{name:'No delivery exceptions in this view.',exact:true})).toBeVisible()
 const context=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await context.newPage();try{await login(owner,'Owner');expect((await owner.request.get('/api/messages/exceptions')).status()).toBe(403);await owner.goto('/#messages?panel=exceptions');await expect(owner.getByRole('heading',{name:'Your message history',exact:true})).toBeVisible();await expect(owner.getByRole('region',{name:'Private delivery exceptions',exact:true})).toHaveCount(0);await owner.setViewportSize({width:320,height:440});await reminderCapture(owner,'resident-private-queue-denied-320-440')}finally{await context.close()}
})

test('maintenance reminder exact selected home preview separate approval and changed amount omission use actual controls',async({page,browser})=>{
 const actors=await reminderActors(page,browser),context=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await context.newPage()
 try{
  const cycle=await reminderMaintenance(page,actors.reviewer,'RMD UI exact maintenance');const receipt=await reminderPayment(page,cycle.lines[0].entry_id,'600.00','400.00')
  await reminderStartUI(page,'Outstanding maintenance reminder','RMD UI exact maintenance');await page.setViewportSize({width:320,height:440});await page.getByRole('combobox',{name:'Reminder criterion',exact:true}).click();await page.getByRole('option',{name:'Supplied deadline has passed',exact:true}).hover();await reminderCapture(page,'reminder-criterion-menu-320-440');await page.keyboard.press('End');await expect(page.getByRole('option',{name:'Supplied deadline has passed',exact:true})).toBeFocused();await page.keyboard.press('Enter');await chooseOption(page,'Recipient group','Selected homes');await page.getByRole('checkbox',{name:'A-101',exact:true}).check();await reminderCapture(page,'selected-home-320-440');await reminderWithin(page)
  await page.getByRole('button',{name:'Preview exact recipients',exact:true}).click();await expect(page.locator('.message-counts strong')).toHaveText(['2','2','2','2','1','0']);await expect(page.locator('.message-binding')).toHaveText(['₹600.00 outstanding across 1 home','₹600.00 outstanding across 1 home']);await expect(page.getByRole('region',{name:'Exact message preview'})).not.toContainText('₹600');await expect(page.getByRole('region',{name:'Exact message preview'})).not.toContainText('RMD UI exact maintenance')
  for(const [width,height] of [[1440,1000],[768,1000],[375,640],[320,440]]){await page.setViewportSize({width,height});await page.getByRole('heading',{name:'The right words. The right people.',exact:true}).scrollIntoViewIfNeeded();await reminderCapture(page,'maintenance-preview-'+width+'-'+height);await page.getByRole('region',{name:'Recipient decisions'}).scrollIntoViewIfNeeded();await reminderCapture(page,'maintenance-bindings-'+width+'-'+height);await reminderWithin(page)}
  await page.getByRole('checkbox',{name:reminderPreviewCheck,exact:true}).check();const saved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/messages'&&r.request().method()==='POST');await page.getByRole('button',{name:'Propose for separate review',exact:true}).click();const id=(await(await saved).json()).id as string;await expect(page.getByRole('dialog').locator('.contact-state').first()).toHaveText('Awaiting separate review');await expect(page.getByRole('button',{name:'Review for approval',exact:true})).toHaveCount(0)
  await openMessage(actors.reviewer,id);await actors.reviewer.setViewportSize({width:375,height:440});await reminderActionUI(actors.reviewer,'Review for approval');await reminderCapture(actors.reviewer,'maintenance-separate-review-375-440');await actors.reviewer.getByRole('button',{name:'Approve frozen proposal',exact:true}).click();await expect(actors.reviewer.getByRole('dialog').locator('.contact-state').first()).toHaveText('Approved for delivery')
  await login(owner,'Owner');await openMessage(owner,id);await owner.setViewportSize({width:320,height:440});await expect(owner.getByRole('dialog').getByRole('heading',{name:'Private reminder',exact:true})).toBeVisible();await expect(owner.locator('.message-binding')).toHaveCount(0);await expect(owner.getByRole('dialog')).not.toContainText('₹600');await reminderCapture(owner,'own-maintenance-history-320-440')
  await reminderAllocate(page,receipt.id,cycle.lines[0].entry_id,'200.00');await openMessage(page,id);await reminderActionUI(page,'Run simulated delivery');await page.getByRole('button',{name:'Run simulated delivery',exact:true}).click();await expect(page.getByText('Simulation recorded. Inspect the reported outcomes below.',{exact:true})).toBeVisible();const current=await reminderMessage(page,id);expect(current.outcomes).toEqual({SKIPPED:1});expect(current.recipients.map(x=>x.reason)).toEqual(['REMINDER_CHANGED','REMINDER_CHANGED']);expect(current.deliveries[0].attempts).toBe(0);await page.getByRole('region',{name:'Recipient decisions'}).scrollIntoViewIfNeeded();await reminderCapture(page,'changed-amount-suppressed-320-440');await reminderWithin(page)
 }finally{await actors.close();await context.close()}
})

test('fixed fund reminder future deadline omissions pending reports and approved exemption preserve given money',async({page,browser})=>{
 const actors=await reminderActors(page,browser),context=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await context.newPage()
 try{
  const fund=await apiFund(page,'RMD UI fixed fund',{due_date:'2030-01-10'});await apiFundAction(actors.reviewer,fund,'PUBLISHED');await login(owner,'Owner');await apiFundReport(owner,fund,'1000.00','RMD-UNCONFIRMED-'+crypto.randomUUID())
  await reminderStartUI(page,'Outstanding fixed fund reminder','RMD UI fixed fund');await chooseOption(page,'Reminder criterion','Supplied deadline has passed');await chooseOption(page,'Recipient group','Selected people');await page.getByRole('checkbox',{name:'Demo Owner A-101',exact:true}).check();await page.getByRole('button',{name:'Preview exact recipients',exact:true}).click();await expect(page.getByText('No eligible destination. Change the audience or verify registered contacts before proposing delivery.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Propose for separate review',exact:true})).toBeDisabled();await page.setViewportSize({width:320,height:440});await page.getByText('No eligible destination. Change the audience or verify registered contacts before proposing delivery.',{exact:true}).scrollIntoViewIfNeeded();await reminderCapture(page,'future-deadline-omission-320-440');await page.getByRole('region',{name:'Recipient decisions',exact:true}).scrollIntoViewIfNeeded();await reminderCapture(page,'deadline-omission-decisions-320-440')
  await page.getByRole('button',{name:'Edit proposal',exact:true}).click();await chooseOption(page,'Reminder criterion','Recorded amount outstanding');await page.getByRole('button',{name:'Preview exact recipients',exact:true}).click();await expect(page.locator('.message-binding')).toHaveText('₹1,500.25 outstanding across 2 homes');await page.getByRole('checkbox',{name:reminderPreviewCheck,exact:true}).check();const saved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/messages'&&r.request().method()==='POST');await page.getByRole('button',{name:'Propose for separate review',exact:true}).click();const id=(await(await saved).json()).id as string;await messageApprove(actors.reviewer,id)
  const waiver=await messagePost(page,'/api/fund-waivers',{campaign_id:fund,flat_id:'demo-flat-A-101',participant_version:1,amount:'1000.00',source_reference:'RMD supplied full exemption',reason:'RMD deliberately supplied and separately reviewed exemption.'});await messagePost(actors.reviewer,'/api/fund-waivers/'+waiver.id+'/actions',{version:1,action:'APPROVED',reason:'RMD independently reviewed the supplied full exemption.'})
  await openMessage(page,id);await reminderActionUI(page,'Run simulated delivery');await page.getByRole('button',{name:'Run simulated delivery',exact:true}).click();await expect(page.getByText('Simulation recorded. Inspect the reported outcomes below.',{exact:true})).toBeVisible();const current=await reminderMessage(page,id);expect(current.outcomes).toEqual({SKIPPED:1});expect(current.recipients[0].reason).toBe('REMINDER_CHANGED');expect(current.recipients[0].reminder?.outstanding_paise).toBe(150025)
  await reminderStartUI(page,'Outstanding fixed fund reminder','RMD UI fixed fund');await chooseOption(page,'Recipient group','Selected people');await page.getByRole('checkbox',{name:'Demo Owner A-101',exact:true}).check();await page.getByRole('button',{name:'Preview exact recipients',exact:true}).click();await expect(page.locator('.message-binding')).toHaveText('₹500.25 outstanding across 1 home');await page.getByRole('region',{name:'Recipient decisions'}).scrollIntoViewIfNeeded();await reminderCapture(page,'fresh-fund-after-exemption-320-440');await reminderWithin(page)
 }finally{await actors.close();await context.close()}
})

test('meeting acknowledgement removes only its person and uncertain shared handoff reconciles after withdrawal',async({page,browser})=>{
 const actors=await reminderActors(page,browser),context=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await context.newPage()
 try{
  const meeting=await meetingProposal(page,'RMD UI requested meeting',{ack_deadline:Math.floor(Date.now()/1000)-3600});await meetingApprove(actors.reviewer,meeting)
  await reminderStartUI(page,'Requested meeting acknowledgement','RMD UI requested meeting');await chooseOption(page,'Reminder criterion','Supplied deadline has passed');await chooseOption(page,'Recipient group','Selected people');await page.getByRole('checkbox',{name:'Demo Owner A-101',exact:true}).check();await page.getByRole('checkbox',{name:'Demo Joint Owner A-101',exact:true}).check();await page.getByRole('button',{name:'Preview exact recipients',exact:true}).click();await expect(page.locator('.message-counts strong')).toHaveText(['2','2','2','2','1','0']);await page.setViewportSize({width:375,height:640});await reminderCapture(page,'meeting-reminder-preview-375');await page.getByRole('checkbox',{name:reminderPreviewCheck,exact:true}).check();const saved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/messages'&&r.request().method()==='POST');await page.getByRole('button',{name:'Propose for separate review',exact:true}).click();const id=(await(await saved).json()).id as string;await messageApprove(actors.reviewer,id)
  await login(owner,'Owner');await openMeeting(owner,meeting,false);await owner.setViewportSize({width:320,height:440});await owner.getByRole('button',{name:'Acknowledge this version',exact:true}).click();await owner.getByRole('checkbox',{name:meetingAckConfirmation,exact:true}).check();await owner.getByRole('button',{name:'Record my acknowledgement',exact:true}).click();await expect(owner.getByText('You acknowledged version 1 on',{exact:false})).toBeVisible();await reminderCapture(owner,'personal-acknowledgement-before-handoff-320-440')
  await openMessage(page,id);await reminderActionUI(page,'Run simulated delivery','Lost response · reconcile before retry');await page.getByRole('button',{name:'Run simulated delivery',exact:true}).click();await expect(page.getByText('Simulation recorded. Inspect the reported outcomes below.',{exact:true})).toBeVisible();const current=await reminderMessage(page,id);expect(current.outcomes).toEqual({UNKNOWN:1});expect(current.recipients.find(x=>x.id==='demo-owner-A-101')?.reason).toBe('ACKNOWLEDGED');expect(current.deliveries[0].attempts).toBe(1)
  await openMessage(owner,id);await expect(owner.getByRole('region',{name:'Reported delivery outcomes'})).toContainText('Skipped');await expect(owner.getByRole('region',{name:'Reported delivery outcomes'})).not.toContainText('Needs reconciliation');await owner.getByRole('region',{name:'Reported delivery outcomes',exact:true}).scrollIntoViewIfNeeded();await reminderCapture(owner,'own-acknowledged-shared-envelope-skipped-320-440')
  await page.getByRole('button',{name:'Close message',exact:true}).click();await page.getByRole('button',{name:'Delivery exceptions',exact:true}).click();await expect(page.locator('.message-exception-counts strong')).toHaveText(['1','0','0'])
  for(const [width,height] of [[1440,1000],[768,1000],[375,640],[320,440]]){await page.setViewportSize({width,height});await page.getByRole('navigation',{name:'Communication views'}).scrollIntoViewIfNeeded();await reminderCapture(page,'uncertain-exception-queue-'+width+'-'+height);await page.locator('.message-exception-cards').scrollIntoViewIfNeeded();await reminderCapture(page,'uncertain-exception-card-'+width+'-'+height);await reminderWithin(page)}
  await meetingPost(page,'/api/meetings/'+meeting+'/proposals',{version:2,action:'WITHDRAW',reason:'PRIVATE_RMD deliberately withdraw the source while its original handoff needs reconciliation.'});await meetingApprove(actors.reviewer,meeting);await page.reload();await expect(page.getByText('Source no longer available',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:new RegExp('^Open needs reconciliation for Meeting acknowledgement · RMD UI requested meeting at ')}).click();await expect(page.locator('.message-delivery-selected')).toHaveAttribute('data-delivery-id',current.deliveries[0].id);await reminderCapture(page,'withdrawn-source-same-attempt-320-440');await reminderActionUI(page,'Reconcile handoff');await page.getByRole('button',{name:'Reconcile this handoff',exact:true}).click();await expect(page.getByText('The existing handoff was reconciled without another send.',{exact:true})).toBeVisible();const reconciled=await reminderMessage(page,id);expect(reconciled.outcomes).toEqual({ACCEPTED:1});expect(reconciled.deliveries[0]).toMatchObject({attempts:1,delivered_at:0,read_at:0});await page.locator('.message-delivery-selected').evaluate(node=>node.scrollIntoView({block:'start'}));await expect(page.locator('.message-delivery-selected .message-outcome-accepted')).toBeInViewport({ratio:1});await reminderCapture(page,'reconciled-original-attempt-320-440')
  await openMessage(owner,id);await expect(owner.getByRole('link',{name:'Open meeting publication',exact:true})).toHaveCount(0);expect((await reminderMessage(owner,id)).recipients).toHaveLength(1)
 }finally{await actors.close();await context.close()}
})

test('stale exact reminder preview preserves human input and lost save retries the original proposal',async({page,browser})=>{
 const actors=await reminderActors(page,browser)
 try{
  const cycle=await reminderMaintenance(page,actors.reviewer,'RMD UI stale exact source',[{flat_id:'demo-flat-A-101',amount:'1000.00'}]);const receipt=await reminderPayment(page,cycle.lines[0].entry_id,'10.00','0.01')
  await reminderStartUI(page,'Outstanding maintenance reminder','RMD UI stale exact source');await chooseOption(page,'Recipient group','Selected people');await page.getByRole('checkbox',{name:'Demo Owner A-101',exact:true}).check();await page.getByRole('button',{name:'Preview exact recipients',exact:true}).click();await page.getByRole('checkbox',{name:reminderPreviewCheck,exact:true}).check();await reminderAllocate(page,receipt.id,cycle.lines[0].entry_id,'0.01');await page.getByRole('button',{name:'Propose for separate review',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('record');await page.setViewportSize({width:320,height:440});await page.getByRole('dialog').getByRole('alert').scrollIntoViewIfNeeded();await reminderCapture(page,'stale-preview-preserved-320-440');await page.getByRole('button',{name:'Reload current record',exact:true}).click();await expect(page.locator('.message-binding')).toHaveText('₹999.98 outstanding across 1 home');await expect(page.getByRole('checkbox',{name:reminderPreviewCheck,exact:true})).not.toBeChecked();await expect(page.getByText('Proposal reason: PRIVATE_RMD_PROPOSAL exact supplied source, current criterion and intended homes reviewed.',{exact:true})).toBeVisible();await page.getByRole('region',{name:'Recipient decisions',exact:true}).scrollIntoViewIfNeeded();await reminderCapture(page,'stale-preview-reloaded-320-440')
  const bodies:string[]=[];let lost=true;await page.route('**/api/messages',async route=>{if(route.request().method()!=='POST'){await route.continue();return};bodies.push(route.request().postData()!);const response=await route.fetch();if(lost){lost=false;await route.abort('failed')}else await route.fulfill({response})})
  await page.getByRole('checkbox',{name:reminderPreviewCheck,exact:true}).check();await page.getByRole('button',{name:'Propose for separate review',exact:true}).click();await expect(page.getByRole('button',{name:'Retry this proposal',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await reminderCapture(page,'uncertain-proposal-retry-320-440');await page.getByRole('button',{name:'Retry this proposal',exact:true}).click();await expect(page.getByRole('dialog').locator('.contact-state').first()).toHaveText('Awaiting separate review');expect(bodies).toHaveLength(2);expect(bodies[0]).toBe(bodies[1]);await page.unroute('**/api/messages');await reminderWithin(page)
 }finally{await actors.close()}
})

test('delivery exception full counts filters later destination page and bounded definite retry are real controls',async({page,browser})=>{
 const actors=await reminderActors(page,browser)
 try{
  for(let i=0;i<21;i++){
   const n=String(i).padStart(2,'0');messagePrivateFixture(`row=db.execute("SELECT id FROM residents WHERE id LIKE 'demo-owner-B-%' ORDER BY id LIMIT 1 OFFSET ${i}").fetchone();db.execute("INSERT INTO users(id,login,display_name,password_hash,status,resident_id,is_demo,verified_at,auth_version,created_at) SELECT ?,?, ?,password_hash,'ACTIVE',?,0,verified_at,1,created_at FROM users WHERE id='demo-user-owner'",('rmd-account-${n}','rmd-${n}@example.test','Fictional RMD recipient',row[0]))`)
  }
  // Deliberately registered/verified contacts use actual protected endpoints.
  const candidates=await(await page.request.get('/api/messages/targets?source_kind=NOTICE&source_id='+actors.notice+'&kind=PEOPLE&q=Demo%20Owner%20B&page=1')).json();const candidates2=await(await page.request.get('/api/messages/targets?source_kind=NOTICE&source_id='+actors.notice+'&kind=PEOPLE&q=Demo%20Owner%20B&page=2')).json();const people=[...candidates.items,...candidates2.items].slice(0,21) as {id:string;label:string}[];expect(people).toHaveLength(21)
  for(const [i,person] of people.entries()){const current=await(await page.request.get('/api/contacts/'+person.id)).json();await messagePost(page,'/api/contacts/'+person.id+'/register',{version:current.version,email:'rmd-destination-'+i+'@example.test',phone:'+919001'+String(i).padStart(6,'0'),preferred_channel:'EMAIL',community_whatsapp:true,community_email:true,finance_whatsapp:true,finance_email:true,consent_source:'RMD explicitly supplied identity and separate contact permissions',reason:'RMD deliberately registered the fictional current contact.'});const pending=await(await actors.reviewer.request.get('/api/contacts/'+person.id)).json();await messagePost(actors.reviewer,'/api/contacts/'+person.id+'/actions',{version:pending.version,action:'VERIFIED',reason:'RMD independently checked the fictional identity and destination.'})}
  const id=await messageProposal(page,actors.notice);await messageApprove(actors.reviewer,id);await messagePost(page,'/api/messages/'+id+'/dispatch',{version:2,action:'DISPATCH',outcome:'UNKNOWN',reason:'RMD deliberately exercises twenty-three distinct retained uncertain outcomes.'})
  await page.setViewportSize({width:320,height:440});await page.goto('/#messages?panel=exceptions');await expect(page.locator('.message-exception-counts strong')).toHaveText(['23','0','0']);await expect(page.locator('.message-exception-cards > button')).toHaveCount(12);await page.getByRole('button',{name:'Next delivery exceptions page',exact:true}).click();await expect(page.locator('.message-exception-cards > button')).toHaveCount(11)
  const response=await page.request.get('/api/messages/exceptions?page=2'),queue=await response.json();const later=queue.items.find((x:{message_id:string;delivery_page:number})=>x.message_id===id&&x.delivery_page===2);expect(later).toBeTruthy();await page.getByRole('button',{name:`Open needs reconciliation for ${later.title} at ${later.destination}`,exact:true}).click();await expect(page.locator('.message-delivery-selected')).toHaveAttribute('data-delivery-id',later.delivery_id);expect(new URL(page.url()).hash).toContain('delivery_page=2');await expect(page.locator('.message-delivery-selected').getByRole('button',{name:'Reconcile handoff',exact:true})).toBeInViewport({ratio:1});await expect(page.locator('.message-delivery-selected').getByText(later.destination,{exact:true})).toBeInViewport({ratio:1});await reminderCapture(page,'later-destination-page-320-440');await reminderWithin(page);await page.getByRole('button',{name:'Close message',exact:true}).click()
  const failed=await messageProposal(page,actors.notice,{kind:'PEOPLE',wing:'',ids:['demo-owner-A-101']});await messageApprove(actors.reviewer,failed);await messagePost(page,'/api/messages/'+failed+'/dispatch',{version:2,action:'DISPATCH',outcome:'REJECTED',reason:'RMD deliberately records a definite failure for bounded retry review.'})
  await page.reload();await chooseOption(page,'Filter delivery exceptions','Definite failures');await expect(page.locator('.message-exception-counts strong')).toHaveText(['23','1','0']);await expect(page.locator('.message-exception-cards > button')).toHaveCount(1);await page.locator('.message-exception-cards > button').click()
  for(let attempt=2;attempt<=3;attempt++){await reminderActionUI(page,'Run simulated delivery','Definite rejection · retry allowed');await page.getByRole('button',{name:'Run simulated delivery',exact:true}).click();await expect.poll(async()=>(await reminderMessage(page,failed)).deliveries[0].attempts).toBe(attempt)}
  await expect(page.getByRole('button',{name:'Run simulated delivery',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Close message',exact:true}).click();await expect(page.getByText('The three-attempt limit has been reached.',{exact:true})).toBeVisible();await reminderCapture(page,'definite-failure-attempt-limit-320-440');await reminderWithin(page)
 }finally{await actors.close()}
})

test('extended source menu read retries focus scrolling and pending save dismissal remain usable on a short phone',async({page,browser})=>{
 const actors=await reminderActors(page,browser);let release=()=>{}
 try{
  const meeting=await meetingProposal(page,'RMD UI source and pending checks',{scope:'HOMES',home_ids:['demo-flat-A-101']});await meetingApprove(actors.reviewer,meeting);await page.goto('/#messages');await page.setViewportSize({width:320,height:440});await page.getByRole('button',{name:'Prepare a message',exact:true}).click()
  const sourceMenu=page.getByRole('combobox',{name:'Message source',exact:true});await sourceMenu.click();await expect(page.getByRole('option')).toHaveCount(6);await page.getByRole('option',{name:'Outstanding fixed fund reminder',exact:true}).hover();await reminderCapture(page,'six-source-menu-hover-320-440');await reminderWithin(page);await page.keyboard.press('Home');await expect(page.getByRole('option',{name:'Published community notice',exact:true})).toBeFocused();await page.keyboard.press('End');await expect(page.getByRole('option',{name:'Outstanding fixed fund reminder',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(sourceMenu).toBeFocused()
  await page.route('**/api/messages/sources?**',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporarily_unavailable"}'}));await chooseOption(page,'Message source','Requested meeting acknowledgement');const sourcePicker=page.getByRole('region',{name:'Published sources',exact:true});await expect(sourcePicker.getByRole('alert')).toBeVisible();await sourcePicker.getByRole('alert').scrollIntoViewIfNeeded();await reminderCapture(page,'source-read-retry-320-440');await page.unroute('**/api/messages/sources?**');await sourcePicker.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('textbox',{name:'Search published message sources',exact:true}).fill('RMD UI source and pending checks');await page.getByRole('button',{name:/^Meeting acknowledgement · RMD UI source and pending checks/}).click()
  await page.route('**/api/messages/targets?**',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporarily_unavailable"}'}));await chooseOption(page,'Recipient group','Selected people');const targetPicker=page.getByRole('region',{name:'Select message recipients',exact:true});await expect(targetPicker.getByRole('alert')).toBeVisible();await targetPicker.getByRole('alert').scrollIntoViewIfNeeded();await reminderCapture(page,'target-read-retry-320-440');await page.unroute('**/api/messages/targets?**');await targetPicker.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('checkbox',{name:'Demo Owner A-101',exact:true}).check();await page.getByRole('textbox',{name:'Proposal reason',exact:true}).fill('PRIVATE_RMD_PENDING deliberately reviewed this exact source and person.');await page.getByRole('button',{name:'Preview exact recipients',exact:true}).click();await page.getByRole('checkbox',{name:reminderPreviewCheck,exact:true}).check()
  let ready!:()=>void;const held=new Promise<void>(r=>{release=r}),entered=new Promise<void>(r=>{ready=r});await page.route('**/api/messages',async route=>{if(route.request().method()!=='POST'){await route.continue();return};const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});const save=page.getByRole('button',{name:'Propose for separate review',exact:true});await save.click();await entered;await expect(page.getByRole('button',{name:'Saving…',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Close message proposal',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();expect(Number(await page.getByRole('button',{name:'Close message proposal',exact:true}).evaluate(node=>getComputedStyle(node).opacity))).toBeLessThan(1);await reminderCapture(page,'pending-save-dismissal-320-440');await reminderWithin(page);release();await expect(page.getByRole('dialog').locator('.contact-state').first()).toHaveText('Awaiting separate review');await page.unroute('**/api/messages');
  const originalMessage=new URLSearchParams(page.url().split('?')[1]).get('message')!,original=await reminderMessage(page,originalMessage),area=await(await page.request.get('/api/meetings/options')).json(),now=Math.floor(Date.now()/1000)
  await meetingPost(page,'/api/meetings/'+meeting+'/proposals',{version:2,action:'AGENDA',title:'RMD UI deliberately supplied successor',body:'A newly supplied agenda and wider audience require a new reminder proposal.',location:'Fictional community room',scope:'ALL',area_key:area.area_key,start_at:now+3600,ack_required:true,ack_deadline:0,reason:'PRIVATE_RMD publish a separate society-wide successor after the one-home reminder was prepared.'});await meetingApprove(actors.reviewer,meeting);await page.reload();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Withdraw this proposal and prepare a new reminder');await expect(page.getByRole('button',{name:'Refresh recipient snapshot',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Decline proposal',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Withdraw proposal',exact:true})).toBeVisible();const retained=await reminderMessage(page,originalMessage);expect(retained.snapshot_version).toBe(1);expect(retained.source).toEqual(original.source);await reminderCapture(page,'changed-publication-original-heading-320-440');await page.getByRole('dialog').getByRole('alert').scrollIntoViewIfNeeded();await expect(page.getByRole('button',{name:'Withdraw proposal',exact:true})).toBeInViewport({ratio:1});await reminderCapture(page,'changed-publication-withdraw-only-320-440');await reminderActionUI(page,'Withdraw proposal');await page.getByRole('button',{name:'Withdraw proposal',exact:true}).click();await expect(page.getByRole('dialog').locator('.contact-state').first()).toHaveText('Withdrawn');await page.getByRole('button',{name:'Close message',exact:true}).click()
  await page.getByRole('button',{name:'Prepare a message',exact:true}).click();await page.getByRole('textbox',{name:'Proposal reason',exact:true}).scrollIntoViewIfNeeded();const scrolling=await page.getByRole('dialog').locator('.dialog-scroll').evaluate(node=>({scroll:node.scrollTop,height:node.scrollHeight,client:node.clientHeight}));expect(scrolling.scroll).toBeGreaterThan(0);expect(scrolling.height).toBeGreaterThan(scrolling.client);await reminderCapture(page,'internal-scroll-close-320-440');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Prepare a message',exact:true})).toBeFocused()
  messagePrivateFixture("db.execute(\"UPDATE role_grants SET valid_until=strftime('%s','now')-1 WHERE user_id='demo-user-committee' AND role='TREASURER' AND revoked_at IS NULL\")");await actors.reviewer.reload();await actors.reviewer.goto('/#messages');await actors.reviewer.getByRole('button',{name:'Prepare a message',exact:true}).click();await actors.reviewer.setViewportSize({width:320,height:440});await actors.reviewer.getByRole('combobox',{name:'Message source',exact:true}).click();await expect(actors.reviewer.getByRole('option')).toHaveCount(2);await expect(actors.reviewer.getByRole('option',{name:'Outstanding maintenance reminder',exact:true})).toHaveCount(0);expect((await actors.reviewer.request.get('/api/messages/sources?kind=MAINTENANCE_REMINDER')).status()).toBe(403);await actors.reviewer.getByRole('option',{name:'Requested meeting acknowledgement',exact:true}).hover();await reminderCapture(actors.reviewer,'current-community-only-sources-320-440')
 }finally{release();messagePrivateFixture("db.execute(\"UPDATE role_grants SET valid_until=strftime('%s','now')+30*86400 WHERE user_id='demo-user-committee' AND role='TREASURER' AND revoked_at IS NULL\")");await actors.close()}
})
