import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mkdirSync, chmodSync } from 'node:fs'
import { resolve } from 'node:path'
import { login, navigate, chooseOption } from './helpers'

async function capture(page: Page, name: string) {
  if (!process.env.SOCIETY_CAPTURE_UI) return
  await page.evaluate(() => document.fonts.ready)
  const folder = resolve('../reports/local/reviews-review'); mkdirSync(folder, { recursive: true, mode: 0o700 })
  const path = resolve(folder, name + '.png'); await page.screenshot({ path, animations: 'disabled' }); chmodSync(path, 0o600)
}
async function desk(page: Page) {
  const menu = page.getByRole('button', { name: 'Menu', exact: true })
  if (await menu.isVisible() && await menu.getAttribute('aria-expanded') === 'false') await menu.click()
  const staff = page.getByRole('link', { name: 'Requests & approvals', exact: true })
  await navigate(page, await staff.count() ? 'Requests & approvals' : 'Your requests')
  await expect(page.getByRole('heading', { name: 'Every idea deserves a thoughtful review.' })).toBeVisible()
}
async function close(page: Page) { await page.getByRole('button', { name: 'Close request details', exact: true }).click() }
async function switchTo(page: Page, account: string) {
  const details = page.getByRole('button', { name: 'Close request details', exact: true })
  if (await details.count()) await details.click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click(); await login(page, account)
}
async function submission(page: Page, title: string, kind = 'Maintenance request') {
  await desk(page); await page.getByRole('button', { name: 'Submit a request', exact: true }).click()
  await chooseOption(page, 'Request type', kind)
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill(title)
  await page.getByRole('textbox', { name: 'Description', exact: true }).fill('Fictional details for review. This is a submitted proposal, with preserved history.')
}
async function save(page: Page, resubmit = false) {
  const response = page.waitForResponse(response => response.request().method() === 'POST' && (resubmit ? response.url().endsWith('/resubmit') : response.url().endsWith('/api/reviews')))
  await page.getByRole('button', { name: resubmit ? 'Resubmit for review' : 'Send for review', exact: true }).click()
  const result = await response; expect(result.status()).toBe(200)
  return (await result.json()).id as string
}
async function review(page: Page, title: string, choice = 'Approve for follow-up', reason = 'Reviewed the fictional evidence and approved follow-up') {
  await desk(page)
  await page.getByRole('searchbox', { name: 'Search requests', exact: true }).fill(title)
  await page.getByRole('button', { name: 'Open ' + title, exact: true }).click()
  await chooseOption(page, 'Review decision', choice)
  await page.getByRole('textbox', { name: 'Reason for this decision', exact: true }).fill(reason)
  await page.getByRole('checkbox').check()
}
async function createFixture(page: Page, title: string, kind = 'MAINTENANCE') {
  const user = await (await page.request.get('/api/auth/me')).json()
  const response = await page.request.post('/api/reviews', { headers: { Origin: new URL(page.url()).origin, 'X-CSRF-Token': user.csrf_token }, data: { operation_key: crypto.randomUUID(), version: 0, kind, title, body: 'Synthetic fixture for a bounded browser scenario. Review histories remain private.', flat_id: kind === 'NOTICE' ? '' : 'demo-flat-A-101', audience: kind === 'NOTICE' ? 'ALL_RESIDENTS' : '', building_code: '', estimate: '' } })
  expect(response.status()).toBe(200); return (await response.json()).id as string
}

test('a resident proposes an expense and a separate reviewer approves without posting money', async ({ page }) => {
  await login(page, 'Owner'); await submission(page, 'REVIEW Expense for garden benches', 'Expense proposal')
  await chooseOption(page, 'Request home', 'Home A-101')
  await page.getByRole('textbox', { name: 'Estimated amount in rupees (optional)' }).fill('123.45')
  const id = await save(page)
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByText('Awaiting review', { exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Approve request', exact: true })).toHaveCount(0)
  await capture(page, 'owner-request-pending')
  await switchTo(page, 'Registry officer')
  const before = await (await page.request.get('/api/entries')).json()
  await review(page, 'REVIEW Expense for garden benches')
  await capture(page, 'desktop-separate-reviewer')
  await page.getByRole('button', { name: 'Approve request', exact: true }).click()
  await expect(dialog.getByText('Approved', { exact: true }).first()).toBeVisible()
  await expect(dialog.locator('.review-history li')).toHaveCount(2)
  const after = await (await page.request.get('/api/entries')).json()
  expect([after.total, after.debit_paise, after.credit_paise]).toEqual([before.total, before.debit_paise, before.credit_paise])
  const item = await (await page.request.get('/api/reviews/' + id)).json()
  expect(item.estimate_paise).toBe(12345); expect(item.author_id).not.toBe((await (await page.request.get('/api/auth/me')).json()).id)
  await switchTo(page, 'Owner'); await desk(page)
  await page.getByRole('searchbox', { name: 'Search requests' }).fill('REVIEW Expense for garden benches')
  await page.getByRole('button', { name: 'Open REVIEW Expense for garden benches', exact: true }).click()
  await expect(page.getByRole('dialog').locator('.review-history li')).toHaveCount(2)
  await capture(page, 'owner-approved-history')
})

test('a notice is revised, separately approved, audience scoped, linked and archived', async ({ page }) => {
  await login(page, 'Committee'); await submission(page, 'REVIEW Owners meeting notice', 'Notice proposal')
  await chooseOption(page, 'Notice audience', 'Current owners')
  const id = await save(page)
  await expect(page.getByRole('combobox', { name: 'Review decision' })).toHaveCount(0)
  await switchTo(page, 'Registry officer')
  await review(page, 'REVIEW Owners meeting notice', 'Request changes', 'Please include the confirmed meeting location')
  await page.getByRole('button', { name: 'Request these changes', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Changes requested', { exact: true }).first()).toBeVisible()
  await capture(page, 'notice-changes-requested')
  await switchTo(page, 'Committee'); await desk(page)
  await page.getByRole('searchbox', { name: 'Search requests' }).fill('REVIEW Owners meeting notice')
  await page.getByRole('button', { name: 'Open REVIEW Owners meeting notice' }).click()
  await page.getByRole('button', { name: 'Revise this request', exact: true }).click()
  await page.getByRole('textbox', { name: 'Description', exact: true }).fill('The owners meeting will take place in the community garden.\nThis revised location is fictional.')
  await save(page, true)
  await switchTo(page, 'Registry officer'); await review(page, 'REVIEW Owners meeting notice', 'Approve & publish notice')
  await page.getByRole('button', { name: 'Approve & publish', exact: true }).click()
  await expect(page.getByRole('dialog').locator('.review-history li')).toHaveCount(4)
  await switchTo(page, 'Tenant'); await navigate(page, 'Community')
  await page.getByRole('searchbox', { name: 'Search notices' }).fill('REVIEW Owners meeting notice')
  await expect(page.getByRole('status')).toHaveText('0 notices found')
  expect((await page.request.get('/api/notices/' + id)).status()).toBe(404)
  await switchTo(page, 'Owner'); await page.goto('/#community?notice=' + id)
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'REVIEW Owners meeting notice' })).toBeVisible()
  await expect(page.getByRole('dialog').locator('.review-history')).toHaveCount(0)
  const shared = await page.getByRole('link', { name: 'Share notice link on WhatsApp' }).getAttribute('href')
  expect(decodeURIComponent(shared!)).toContain('#community?notice=' + id)
  expect(decodeURIComponent(shared!)).not.toContain('owners meeting will take place')
  await capture(page, 'owner-published-notice')
  await switchTo(page, 'Registry officer'); await desk(page)
  await page.getByRole('searchbox', { name: 'Search requests' }).fill('REVIEW Owners meeting notice')
  await page.getByRole('button', { name: 'Open REVIEW Owners meeting notice' }).click()
  await page.getByRole('textbox', { name: 'Reason for this decision' }).fill('The meeting is complete and this notice can be archived')
  await page.getByRole('checkbox').check(); await page.getByRole('button', { name: 'Archive notice', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Archived', { exact: true }).first()).toBeVisible()
  expect((await page.request.get('/api/notices/' + id)).status()).toBe(404)
})

test('declined and withdrawn requests remain searchable with preserved history', async ({ page }) => {
  await login(page, 'Owner'); await submission(page, 'REVIEW Withdraw duplicated request')
  await save(page); await page.getByRole('textbox', { name: 'Reason for this decision' }).fill('This was submitted in duplicate by mistake')
  await page.getByRole('checkbox').check(); await page.getByRole('button', { name: 'Withdraw request', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Withdrawn', { exact: true }).first()).toBeVisible()
  await close(page); await submission(page, 'REVIEW Decline unnecessary request'); await save(page)
  await switchTo(page, 'Registry officer'); await review(page, 'REVIEW Decline unnecessary request', 'Decline request')
  await page.getByRole('button', { name: 'Decline request', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Declined', { exact: true }).first()).toBeVisible(); await close(page)
  await chooseOption(page, 'Filter requests by status', 'Declined')
  await expect(page.getByRole('button', { name: 'Open REVIEW Decline unnecessary request' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear', exact: true }).click()
  await capture(page, 'desktop-review-desk')
})

test('review forms and menus fit desktop, tablet and small phones with keyboard and required-field behavior', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' }); await login(page, 'Owner')
  for (const viewport of [{ width: 1440, height: 900 }, { width: 768, height: 1024 }, { width: 375, height: 812 }, { width: 320, height: 568 }]) {
    await page.setViewportSize(viewport); await desk(page)
    await capture(page, `requests-${viewport.width}-page`)
    await page.getByRole('combobox', { name: 'Filter requests by status' }).click()
    await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 }); await capture(page, `requests-${viewport.width}-status-menu`); await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Submit a request', exact: true }).click()
    await page.getByRole('textbox', { name: 'Title', exact: true }).fill('REVIEW Long content viewport ' + viewport.width)
    await page.getByRole('textbox', { name: 'Description', exact: true }).fill('A long fictional proposal. '.repeat(80))
    const labels = await page.locator('.records-fieldset > label').evaluateAll(elements => elements.map(el => ({ direction: getComputedStyle(el).flexDirection, display: getComputedStyle(el).display })))
    expect(labels.every(label => label.direction === 'column' && label.display === 'flex')).toBe(true)
    const selectWidths = await page.locator('.records-fieldset .select-field').evaluateAll(elements => elements.map(el => ({ field: el.getBoundingClientRect().width, trigger: el.querySelector('button')!.getBoundingClientRect().width })))
    expect(selectWidths.every(item => Math.abs(item.field - item.trigger) < 2)).toBe(true)
    await chooseOption(page, 'Request type', 'Expense proposal')
    const home = page.getByRole('combobox', { name: 'Request home', exact: true }); await home.click()
    await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 }); await capture(page, `requests-${viewport.width}-home-menu`); await page.keyboard.press('Escape'); await expect(home).toBeFocused()
    await chooseOption(page, 'Request home', 'Home A-102'); await chooseOption(page, 'Request home', 'Shared area / no specific home'); await expect(home).toHaveText('Shared area / no specific home')
    await chooseOption(page, 'Request type', 'Notice proposal')
    await page.getByRole('button', { name: 'Send for review', exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Notice audience' })).toBeFocused()
    expect(await page.getByRole('alert').evaluate(el => getComputedStyle(el).display)).toBe('block')
    await page.keyboard.press('Enter'); await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 }); await capture(page, `requests-${viewport.width}-audience-menu`)
    await page.getByRole('option', { name: 'A selected wing', exact: true }).click()
    await page.getByRole('combobox', { name: 'Notice wing' }).click(); await expect(page.getByRole('listbox')).toBeInViewport({ ratio: 1 }); await capture(page, `requests-${viewport.width}-wing-menu`)
    await page.keyboard.press('End'); await expect(page.getByRole('option', { name: 'Wing C', exact: true })).toBeFocused(); await page.keyboard.press('Enter'); await expect(page.getByRole('combobox', { name: 'Notice wing' })).toHaveText('Wing C')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0)
  }
})

test('lost submission and decision responses retry once with the same identity and block busy dismissal', async ({ page }) => {
  await login(page, 'Owner'); await submission(page, 'REVIEW Retried request identity')
  const keys: string[] = []
  await page.route('**/api/reviews', async route => {
    if (route.request().method() !== 'POST') return route.continue()
    keys.push(route.request().postDataJSON().operation_key)
    await route.fetch(); await route.abort()
  })
  await page.getByRole('button', { name: 'Send for review', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await capture(page, 'request-unknown-response')
  await page.unroute('**/api/reviews')
  page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/api/reviews')) keys.push(request.postDataJSON().operation_key) })
  await page.getByRole('button', { name: 'Retry this submission', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Awaiting review', { exact: true })).toBeVisible()
  expect(keys).toHaveLength(2); expect(keys[0]).toBe(keys[1])
  await switchTo(page, 'Registry officer'); await review(page, 'REVIEW Retried request identity')
  const decisions: string[] = []; let release!: () => void
  const hold = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/reviews/*/decision', async route => {
    decisions.push(route.request().postDataJSON().operation_key)
    await route.fetch(); await hold; await route.abort()
  })
  await page.getByRole('button', { name: 'Approve request', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Recording your decision…' })).toBeDisabled()
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toBeVisible()
  release(); await expect(page.getByRole('alert')).toBeVisible()
  await page.unroute('**/api/reviews/*/decision')
  page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/decision')) decisions.push(request.postDataJSON().operation_key) })
  await page.getByRole('button', { name: 'Retry this decision', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Approved', { exact: true }).first()).toBeVisible()
  expect(decisions).toHaveLength(2); expect(decisions[0]).toBe(decisions[1])
  await expect(page.getByRole('dialog').locator('.review-history li')).toHaveCount(2)
})

test('review list and detail failures recover and stale decisions cannot overwrite another reviewer', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 }); await login(page, 'Owner')
  const id = await createFixture(page, 'REVIEW Conflicting committee decisions')
  await switchTo(page, 'Registry officer')
  await page.route('**/api/reviews?**', route => route.fulfill({ status: 503, json: { error: 'unavailable' } }))
  await desk(page); await expect(page.getByRole('alert')).toBeInViewport({ ratio: 1 }); await expect(page.getByRole('button', { name: 'Try again', exact: true })).toBeInViewport({ ratio: 1 }); await capture(page, 'requests-phone-list-error')
  await page.unroute('**/api/reviews?**'); await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open REVIEW Conflicting committee decisions' })).toBeVisible()
  await page.route('**/api/reviews/' + id, route => route.fulfill({ status: 503, json: { error: 'unavailable' } }))
  await page.getByRole('button', { name: 'Open REVIEW Conflicting committee decisions' }).click()
  await expect(page.getByRole('button', { name: 'Reload request', exact: true })).toBeVisible()
  await page.unroute('**/api/reviews/' + id); await page.getByRole('button', { name: 'Reload request', exact: true }).click()
  await page.getByRole('textbox', { name: 'Reason for this decision' }).fill('A stale reviewer decision that must not overwrite history')
  await page.getByRole('checkbox').check()
  const user = await (await page.request.get('/api/auth/me')).json()
  expect((await page.request.post('/api/reviews/' + id + '/decision', { headers: { Origin: new URL(page.url()).origin, 'X-CSRF-Token': user.csrf_token }, data: { operation_key: crypto.randomUUID(), version: 1, decision: 'CHANGES_REQUESTED', reason: 'A separate completed decision wins before the stale client', confirmed: true } })).status()).toBe(200)
  await page.getByRole('button', { name: 'Approve request', exact: true }).click()
  await expect(page.getByRole('alert')).toBeInViewport(); await capture(page, 'requests-phone-stale-decision')
  await page.getByRole('button', { name: 'Reload latest details', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Changes requested', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('dialog').locator('.review-history li')).toHaveCount(2)
})

test('review pagination visits every fixture and clamps after filters change', async ({ page }) => {
  await login(page, 'Owner')
  for (let i = 0; i < 13; i++) await createFixture(page, 'REVIEW Page sample ' + String(i).padStart(2, '0'))
  await desk(page); await page.getByRole('searchbox', { name: 'Search requests' }).fill('REVIEW Page sample')
  await expect(page.getByRole('status')).toHaveText('13 requests found')
  await expect(page.getByRole('button', { name: /^Open REVIEW Page sample/ })).toHaveCount(12)
  await page.getByRole('button', { name: 'Next requests page' }).click(); await expect(page.getByRole('button', { name: /^Open REVIEW Page sample/ })).toHaveCount(1)
  await page.getByRole('button', { name: /^Open REVIEW Page sample/ }).click(); await expect(page.getByRole('dialog')).toBeVisible(); await close(page)
  await page.getByRole('searchbox', { name: 'Search requests' }).fill('REVIEW Page sample 00')
  await expect(page.getByRole('status')).toHaveText('1 requests found'); await expect(page.getByText('Page 1 of 1', { exact: true })).toBeVisible()
})
