import { test,expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mkdirSync,chmodSync,readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { login,navigate,chooseOption } from './helpers'
import { financialHeaders,apiReceived } from './maintenance-fixtures'
import { statementActors,fillStatementUpload,openStatement,statementOriginal,statementApprove,statementPublish,statementDecisionUI,originalCSV,uploadCheck,publicationCheck,statementWorkbook } from './statements-fixtures'
import { plainPDF } from './document-fixtures'

test.setTimeout(90000)
async function capture(page:Page,name:string){if(!process.env.SOCIETY_CAPTURE_UI)return;await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>{const root=document.querySelector('.statements-page');return !root||root.getAnimations().every(a=>a.playState==='finished')});if(name.startsWith('register-empty'))await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));const root=resolve(process.env.SOCIETY_STATEMENT_CAPTURE_ROOT??'../reports/local/statements-review');mkdirSync(root,{recursive:true,mode:0o700});const path=resolve(root,name+'.png');await page.screenshot({path,animations:'disabled',fullPage:name.startsWith('register-empty')});chmodSync(path,0o600)}
async function within(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const d=page.getByRole('dialog');if(await d.count()){await expect(d.locator('.dialog-close')).toBeInViewport({ratio:1});const x=await d.evaluate(el=>({width:el.scrollWidth,client:el.clientWidth,gap:el.querySelector('.dialog-scroll')!.getBoundingClientRect().top-el.querySelector('.dialog-close')!.getBoundingClientRect().bottom}));expect(x.width).toBeLessThanOrEqual(x.client);expect(x.gap).toBeGreaterThanOrEqual(8)}}

test('prepared statement register upload menus empty loading error retries and four widths are rendered',async({page})=>{
 await login(page)
 for(const width of [1440,768,375,320]){await page.setViewportSize({width,height:width<=375?640:1000});await navigate(page,'Statements');await expect(page.getByRole('heading',{name:'The accounts start with an original.'})).toBeVisible();await capture(page,'register-empty-'+width);await within(page);if(width===1440){const geometry=await page.locator('.statement-filters').evaluate(el=>{const controls=[...el.querySelectorAll('.search-control,.select-field')];return controls.map(c=>({top:c.getBoundingClientRect().top,display:getComputedStyle(c).display}))});expect(geometry[1].display,'a select wrapper participates in flex layout').toBe('block');expect(Math.max(...geometry.map(x=>x.top))-Math.min(...geometry.map(x=>x.top)),'desktop controls share one row').toBeLessThanOrEqual(1)}
 await page.getByRole('combobox',{name:'Filter statement type',exact:true}).click();await expect(page.getByRole('option',{name:'All statement types',exact:true})).toHaveAttribute('aria-selected','true');await page.getByRole('option',{name:'Balance sheet',exact:true}).hover();await capture(page,'type-menu-hover-'+width);await page.keyboard.press('End');await expect(page.getByRole('option',{name:'Audit report',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByRole('combobox',{name:'Filter statement type',exact:true})).toContainText('Audit report');await page.getByRole('button',{name:'Clear',exact:true}).click()
 await page.getByRole('button',{name:'Add prepared statement',exact:true}).click();await page.getByRole('combobox',{name:'Statement type',exact:true}).click();await expect(page.getByRole('option',{name:'Income statement',exact:true})).toHaveAttribute('aria-selected','true');await capture(page,'upload-type-menu-'+width);await page.keyboard.press('Escape');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Add prepared statement',exact:true})).toBeFocused()}
 let release!:()=>void,ready!:()=>void;const held=new Promise<void>(r=>{release=r}),started=new Promise<void>(r=>{ready=r});await page.route('**/api/financial-statements?*',async route=>{ready();await held;await route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporary_failure"}'})});await page.getByRole('textbox',{name:'Search statements',exact:true}).fill('missing');await started;await expect(page.getByText('Opening current statements…',{exact:true})).toBeVisible();await capture(page,'register-loading-320');release();await expect(page.getByRole('heading',{name:'Statements could not be opened.'})).toBeVisible();await capture(page,'register-error-320');await page.unroute('**/api/financial-statements?*');await page.getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByRole('heading',{name:'No statements match these choices.'})).toBeVisible()
 await page.route('**/api/overview/statements?*',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporary_failure"}'}));await navigate(page,'Overview');await navigate(page,'Statements');await expect(page.getByText('Statement attention counts are unavailable. The register remains usable.')).toBeVisible();await expect(page.locator('.statement-attention strong')).toHaveText(['—','—','—','—']);await page.unroute('**/api/overview/statements?*');await page.getByRole('button',{name:'Retry statement counts',exact:true}).click();await expect(page.locator('.statement-attention strong')).toHaveText(['0','0','0','0'])
})

test('actual original upload separate internal review tenant publication download and removal preserve original money',async({page,browser})=>{
 const a=await statementActors(page,browser),tenantContext=await browser.newContext({baseURL:new URL(page.url()).origin}),tenant=await tenantContext.newPage(),ownerContext=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await ownerContext.newPage()
 try{const entry=await apiReceived(page,'432.19');await login(tenant,'Tenant');await login(owner,'Owner');await page.setViewportSize({width:375,height:640});await fillStatementUpload(page,'UI September income original');await capture(page,'upload-filled-375');await page.getByRole('button',{name:'Preview original',exact:true}).click();await expect(page.getByRole('heading',{name:'One original, clearly recorded.'})).toBeVisible();await expect(page.getByRole('button',{name:'Upload for separate review',exact:true})).toBeDisabled()
 for(const width of [1440,768,375,320]){await page.setViewportSize({width,height:width<=375?640:1000});await page.getByRole('heading',{name:'One original, clearly recorded.'}).scrollIntoViewIfNeeded();await capture(page,'upload-preview-'+width);await within(page)}
 await page.getByRole('checkbox',{name:uploadCheck,exact:true}).check();await page.getByRole('button',{name:'Upload for separate review',exact:true}).click();await expect(page).toHaveURL(/#statements\?statement=/);await expect(page.getByRole('dialog').getByRole('heading',{name:'UI September income original',exact:true,level:2})).toBeVisible();const id=new URLSearchParams(page.url().split('?')[1]).get('statement')!;expect(id).toBeTruthy();await expect.poll(async()=> (await(await page.request.get('/api/financial-statements/'+id)).json()).validation).toBe('AVAILABLE');if(await page.getByRole('button',{name:'Check again',exact:true}).count())await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('dialog').locator('.contact-state').first()).toHaveText('Awaiting separate review');await capture(page,'original-awaiting-review-320');await expect(page.getByRole('button',{name:'Review original for approval',exact:true})).toHaveCount(0)
 expect((await tenant.request.get('/api/financial-statements/'+id)).status()).toBe(404);await openStatement(a.reviewer,id);await statementDecisionUI(a.reviewer,'Review original for approval');await capture(a.reviewer,'internal-approval-desktop');await a.reviewer.getByRole('button',{name:'Approve internally',exact:true}).click();await expect(a.reviewer.getByRole('dialog').locator('.contact-state').first()).toHaveText('Approved internally');expect((await tenant.request.get('/api/financial-statements/'+id)).status()).toBe(404)
 await openStatement(page,id);await page.getByRole('button',{name:'Choose publication audience',exact:true}).click();await chooseOption(page,'Statement audience','Tenants');await page.getByRole('textbox',{name:'Publication reason',exact:true}).fill('Deliberately share this externally prepared original with current tenants.');await page.getByRole('button',{name:'Preview audience',exact:true}).click();await expect(page.getByRole('region',{name:'Proposed statement audience'})).toContainText('35 current people');await capture(page,'tenant-publication-preview-320');await page.getByRole('checkbox',{name:publicationCheck,exact:true}).check();await page.getByRole('button',{name:'Propose publication',exact:true}).click();await expect(page.getByRole('region',{name:'Statement publication register'})).toContainText('Publication awaiting review');await expect(page.getByRole('button',{name:'Review publication',exact:true})).toHaveCount(0)
 await openStatement(a.reviewer,id);await statementDecisionUI(a.reviewer,'Review publication',true);await capture(a.reviewer,'publication-approval-desktop');await a.reviewer.getByRole('button',{name:'Approve publication',exact:true}).click();await expect(a.reviewer.getByRole('dialog').locator('.contact-state').first()).toHaveText('Shared with its audience')
 await openStatement(tenant,id);await tenant.setViewportSize({width:320,height:640});await capture(tenant,'tenant-published-320');await within(tenant);await expect(tenant.getByRole('region',{name:'Statement publication register'})).toHaveCount(0);await expect(tenant.getByRole('region',{name:'Statement activity'})).toHaveCount(0);await expect(tenant.getByRole('button',{name:'Choose publication audience',exact:true})).toHaveCount(0)
 const downloading=tenant.waitForEvent('download');await tenant.getByRole('button',{name:'Download original',exact:true}).click();const download=await downloading;expect(readFileSync((await download.path())!)).toEqual(originalCSV);expect((await tenant.request.get('/api/entries/'+entry.id)).status()).toBe(403);expect((await owner.request.get('/api/financial-statements/'+id)).status()).toBe(404)
 await openStatement(a.reviewer,id);await statementDecisionUI(a.reviewer,'Remove publication',true);await a.reviewer.getByRole('button',{name:'Remove this publication',exact:true}).click();await expect(a.reviewer.getByRole('region',{name:'Statement publication register'})).toContainText('Publication removed');expect((await tenant.request.get('/api/financial-statements/'+id+'/download')).status()).toBe(404)
 const original=await(await page.request.get('/api/entries/'+entry.id)).json();expect(original.amount_paise).toBe(43219);expect(original.receipt_id).toBe(entry.receipt_id);await capture(a.reviewer,'publication-removed-desktop')
 }finally{await tenantContext.close();await ownerContext.close();await a.close()}
})

test('plain CSV PDF and XLSX checks actually run while active formulas and corrupted originals are rejected',async({page})=>{
 await login(page)
 for(const [filename,data,mime] of [['checked-original.csv',originalCSV,'text/csv; charset=utf-8'],['checked-original.pdf',plainPDF(),'application/pdf'],['checked-original.xlsx',statementWorkbook(),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']] as const){const id=await statementOriginal(page,'UI accepted '+filename,data,filename);const x=await(await page.request.get('/api/financial-statements/'+id)).json();expect(x.validation).toBe('AVAILABLE');expect(x.content_type).toBe(mime);const response=await page.request.get('/api/financial-statements/'+id+'/download');expect(response.status()).toBe(200);expect(await response.body()).toEqual(data)}
 for(const [filename,data,code] of [['active.csv',Buffer.from('Description,Formula\nFictional,=1+1\n'),'ACTIVE_SPREADSHEET_CONTENT'],['active.xlsx',statementWorkbook(true),'ACTIVE_SPREADSHEET_CONTENT'],['corrupt.pdf',Buffer.from('%PDF-1.7\nbroken\n'),'INVALID_PDF']] as const){const id=await statementOriginal(page,'UI rejected '+filename,data,filename);const x=await(await page.request.get('/api/financial-statements/'+id)).json();expect(x.validation).toBe('REJECTED');expect(x.validation_code).toBe(code);expect(x.can_download).toBe(false);expect((await page.request.get('/api/financial-statements/'+id+'/download')).status()).toBe(409);await openStatement(page,id);await expect(page.getByRole('button',{name:'Review original for approval',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Retry unavailable checks',exact:true})).toHaveCount(0);await capture(page,'rejected-'+filename.replace('.','-'));await page.getByRole('button',{name:'Close statement',exact:true}).click()}
})

test('publication audiences selected people homes keyboard menus and short phone review are exact',async({page,browser})=>{
 const a=await statementActors(page,browser)
 try{const id=await statementOriginal(page,'UI precise audience original');await statementApprove(a.reviewer,id);await openStatement(page,id);await page.setViewportSize({width:320,height:440});await page.getByRole('button',{name:'Choose publication audience',exact:true}).click();await page.getByRole('textbox',{name:'Publication reason',exact:true}).fill('Deliberate original publication to the exact current chosen audience.')
 for(const [group,count] of [['All current people',153],['Owners',118],['Tenants',35],['One wing',52]] as const){await chooseOption(page,'Statement audience',group);await page.getByRole('button',{name:'Preview audience',exact:true}).click();await expect(page.getByRole('region',{name:'Proposed statement audience'})).toContainText(count+' current people');await within(page);await page.getByRole('button',{name:'Edit audience',exact:true}).click()}
 await chooseOption(page,'Statement audience','Selected people');await page.getByRole('textbox',{name:'Search statement audience',exact:true}).fill('Demo Owner A-101');await page.getByRole('checkbox',{name:'Demo Owner A-101',exact:true}).check();await page.getByRole('textbox',{name:'Search statement audience',exact:true}).fill('Demo Tenant A-103');await page.getByRole('checkbox',{name:'Demo Tenant A-103',exact:true}).check();await capture(page,'selected-people-short-320');await page.getByRole('button',{name:'Remove Demo Owner A-101',exact:true}).click();await page.getByRole('button',{name:'Preview audience',exact:true}).click();await expect(page.getByRole('region',{name:'Proposed statement audience'})).toContainText('1 current person');await page.getByRole('button',{name:'Edit audience',exact:true}).click()
 await chooseOption(page,'Statement audience','Selected homes');await page.getByRole('textbox',{name:'Search statement audience',exact:true}).fill('A-101');await page.getByRole('checkbox',{name:'A-101',exact:true}).check();expect(await page.getByRole('textbox',{name:'Search statement audience',exact:true}).evaluate(el=>getComputedStyle(el).borderLeftWidth)).toBe('0px');await page.getByRole('button',{name:'Preview audience',exact:true}).click();await expect(page.getByRole('region',{name:'Proposed statement audience'})).toContainText('2 current people');await page.getByRole('checkbox',{name:publicationCheck,exact:true}).check();await page.getByRole('button',{name:'Propose publication',exact:true}).scrollIntoViewIfNeeded();await capture(page,'publication-short-phone-bottom-320');await within(page);await page.getByRole('button',{name:'Propose publication',exact:true}).click();await expect(page.getByRole('region',{name:'Statement publication register'})).toContainText('Publication awaiting review');const p=(await(await page.request.get('/api/financial-statements/'+id)).json()).publications[0];expect(p.target).toMatchObject({kind:'HOMES',ids:['demo-flat-A-101']});expect(p.target_people).toBe(2)
 }finally{await a.close()}
})

test('lost original and approval responses keep pending controls locked and retry one exact operation',async({page,browser})=>{
 const a=await statementActors(page,browser)
 try{await page.setViewportSize({width:375,height:640});await fillStatementUpload(page,'UI stable original retry');await page.getByRole('button',{name:'Preview original',exact:true}).click();await page.getByRole('checkbox',{name:uploadCheck,exact:true}).check();let first=true;const reservations:Record<string,unknown>[]=[]
 await page.route('**/api/financial-statements',async route=>{if(route.request().method()!=='POST'){await route.continue();return}reservations.push(route.request().postDataJSON());const response=await route.fetch();expect(response.status()).toBe(200);if(first){first=false;await route.abort('failed')}else await route.fulfill({response})})
 await page.getByRole('button',{name:'Upload for separate review',exact:true}).click();await expect(page.getByRole('button',{name:'Retry this upload',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Edit original details',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Close statement upload',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(1);await capture(page,'upload-lost-response-375');await page.getByRole('button',{name:'Retry this upload',exact:true}).click();await expect(page).toHaveURL(/#statements\?statement=/);await page.unroute('**/api/financial-statements');expect(reservations).toHaveLength(2);expect(reservations[1]).toEqual(reservations[0]);const id=new URLSearchParams(page.url().split('?')[1]).get('statement')!;await expect.poll(async()=> (await(await page.request.get('/api/financial-statements/'+id)).json()).validation).toBe('AVAILABLE')
 await openStatement(a.reviewer,id);await statementDecisionUI(a.reviewer,'Review original for approval');let lost=true;const decisions:Record<string,unknown>[]=[];await a.reviewer.route('**/api/financial-statements/'+id+'/actions',async route=>{decisions.push(route.request().postDataJSON());const response=await route.fetch();expect(response.status()).toBe(200);if(lost){lost=false;await route.abort('failed')}else await route.fulfill({response})});await a.reviewer.getByRole('button',{name:'Approve internally',exact:true}).click();await expect(a.reviewer.getByRole('button',{name:'Retry this decision',exact:true})).toBeEnabled();await expect(a.reviewer.getByRole('textbox',{name:'Statement decision reason',exact:true})).toBeDisabled();await a.reviewer.keyboard.press('Escape');await expect(a.reviewer.getByRole('dialog')).toHaveCount(1);await capture(a.reviewer,'approval-lost-response-desktop');await a.reviewer.getByRole('button',{name:'Retry this decision',exact:true}).click();await expect(a.reviewer.getByRole('dialog').locator('.contact-state').first()).toHaveText('Approved internally');expect(decisions).toHaveLength(2);expect(decisions[1]).toEqual(decisions[0]);const x=await(await page.request.get('/api/financial-statements/'+id)).json();expect(x.event_total).toBe(5);expect(x.version).toBe(5);expect(x.version_total).toBe(1)
 }finally{await a.close()}
})

test('stale internal decision reload retains the reason clears attestation and disables an inapplicable decision',async({page,browser})=>{
 const a=await statementActors(page,browser)
 try{const id=await statementOriginal(page,'UI stale internal original');await openStatement(a.reviewer,id);await statementDecisionUI(a.reviewer,'Review original for approval');const marker=await a.reviewer.getByRole('textbox',{name:'Statement decision reason',exact:true}).inputValue();await statementApprove(a.reviewer,id);await a.reviewer.getByRole('button',{name:'Approve internally',exact:true}).click();await expect(a.reviewer.getByRole('button',{name:'Reload current record',exact:true})).toBeVisible();await a.reviewer.getByRole('button',{name:'Reload current record',exact:true}).click();await expect(a.reviewer.getByRole('textbox',{name:'Statement decision reason',exact:true})).toHaveValue(marker);await expect(a.reviewer.getByRole('checkbox',{name:/I reviewed this exact original/})).not.toBeChecked();await a.reviewer.getByRole('checkbox',{name:/I reviewed this exact original/}).check();await expect(a.reviewer.getByRole('button',{name:'Approve internally',exact:true})).toBeDisabled();await capture(a.reviewer,'stale-original-reloaded-desktop')
 }finally{await a.close()}
})

test('replacement original retains old tenant publication until separate publication and original downloads stay unchanged',async({page,browser})=>{
 const a=await statementActors(page,browser),context=await browser.newContext({baseURL:new URL(page.url()).origin}),tenant=await context.newPage()
 try{await login(tenant,'Tenant');const old=await statementOriginal(page,'UI old retained published original');await statementApprove(a.reviewer,old);await statementPublish(page,a.reviewer,old);await openStatement(page,old);await page.getByRole('button',{name:'Prepare replacement',exact:true}).click();await expect(page.getByRole('combobox',{name:'Statement type',exact:true})).toBeDisabled();await expect(page.getByLabel('Period from',{exact:true})).toBeDisabled();const nextData=Buffer.from('Description,Amount\nChanged external original,531.20\n');await page.getByLabel('Statement original',{exact:true}).setInputFiles({name:'replacement.csv',mimeType:'text/csv',buffer:nextData});await page.getByRole('textbox',{name:'Statement title',exact:true}).fill('UI separately reviewed replacement original');await page.getByRole('textbox',{name:'Upload reason',exact:true}).fill('Retain the former publication until separate new publication.');await page.getByRole('button',{name:'Preview original',exact:true}).click();await page.getByRole('checkbox',{name:uploadCheck,exact:true}).check();await page.getByRole('button',{name:'Upload for separate review',exact:true}).click();await expect(page).not.toHaveURL(new RegExp('statement='+old+'$'));await expect(page).toHaveURL(/#statements\?statement=/);const id=new URLSearchParams(page.url().split('?')[1]).get('statement')!;await expect.poll(async()=> (await(await page.request.get('/api/financial-statements/'+id)).json()).validation).toBe('AVAILABLE');await statementApprove(a.reviewer,id);await openStatement(page,id);await expect(page.getByRole('dialog').locator('.contact-state').first()).toHaveText('Approved internally');const visible=await(await tenant.request.get('/api/financial-statements')).json();expect(visible.items.some((x:{id:string})=>x.id===old)).toBe(true);expect(visible.items.some((x:{id:string})=>x.id===id)).toBe(false)
 await statementPublish(page,a.reviewer,id);expect((await tenant.request.get('/api/financial-statements/'+old+'/download')).status()).toBe(404);const download=await tenant.request.get('/api/financial-statements/'+id+'/download');expect(await download.body()).toEqual(nextData);await openStatement(a.reviewer,id);await a.reviewer.getByRole('region',{name:'Statement publication register'}).getByText('Original and decision history',{exact:true}).first().click();await capture(a.reviewer,'replacement-publication-history-desktop');const x=await(await page.request.get('/api/financial-statements/'+id)).json();expect(x.revision).toBe(2);expect(x.versions).toHaveLength(2);expect(x.publications.some((p:{state:string})=>p.state==='SUPERSEDED')).toBe(true)
 const rejected=await page.request.post('/api/financial-statements/publication-preview',{headers:await financialHeaders(page),data:{file_id:old,file_version:5,target:{kind:'TENANTS',wing:'',ids:[]}}});expect(rejected.status()).toBe(409)
 const pending=await statementOriginal(page,'UI withdrawn original');await openStatement(page,pending);await statementDecisionUI(page,'Withdraw this original');await page.getByRole('button',{name:'Withdraw this original',exact:true}).click();await expect(page.getByRole('dialog').locator('.contact-state').first()).toHaveText('Withdrawn')
 }finally{await context.close();await a.close()}
})

test('populated pagination detail loading error retry downloads and current overview remain usable',async({page})=>{
 await login(page)
 const before=(await(await page.request.get('/api/overview/statements')).json()).counts
 const ids:string[]=[];for(let i=0;i<13;i++)ids.push(await statementOriginal(page,'UI paged fictional original '+String(i).padStart(2,'0')))
 for(const width of [1440,768,375,320]){await page.setViewportSize({width,height:width<=375?640:1000});await navigate(page,'Statements');await page.getByRole('textbox',{name:'Search statements',exact:true}).fill('UI paged fictional original');await expect(page.locator('.statement-card')).toHaveCount(12);await expect(page.locator('.result-count')).toHaveText('13 statements in this view');await capture(page,'register-populated-'+width);await within(page);const positions=await page.locator('.statement-attention > div').evaluateAll(elements=>elements.map(el=>({row:el.getBoundingClientRect().top,value:el.querySelector('strong')!.getBoundingClientRect().top})));for(const item of positions)for(const peer of positions.filter(p=>Math.abs(p.row-item.row)<1))expect(Math.abs(item.value-peer.value)).toBeLessThanOrEqual(1)}
 await page.getByRole('button',{name:'Next statements page',exact:true}).click();await expect(page.locator('.statement-card')).toHaveCount(1);await page.getByRole('button',{name:'Previous statements page',exact:true}).click();await expect(page.locator('.statement-card')).toHaveCount(12)
 let release!:()=>void,ready!:()=>void;const held=new Promise<void>(r=>{release=r}),started=new Promise<void>(r=>{ready=r}),id=ids[12]
 await page.route('**/api/financial-statements/'+id+'?*',async route=>{ready();await held;await route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporary_failure"}'})});await page.getByRole('button',{name:'Open statement UI paged fictional original 12',exact:true}).click();await started;await expect(page.getByRole('dialog').getByText('Opening the current record…',{exact:true})).toBeVisible();await capture(page,'detail-loading-320');release();await expect(page.getByRole('heading',{name:'This record is unavailable.',exact:true})).toBeVisible();await capture(page,'detail-error-320');await page.unroute('**/api/financial-statements/'+id+'?*');await page.getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByRole('dialog').locator('.contact-state').first()).toHaveText('Awaiting separate review')
 await page.route('**/api/financial-statements/'+id+'/download',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"temporary_failure"}'}));await page.getByRole('button',{name:'Download original',exact:true}).click();await expect(page.getByText('The original could not be downloaded. Try again.',{exact:true})).toBeVisible();await capture(page,'download-error-320');await page.unroute('**/api/financial-statements/'+id+'/download');const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Download original',exact:true}).click();expect(readFileSync((await(await downloading).path())!)).toEqual(originalCSV);await page.getByRole('button',{name:'Close statement',exact:true}).click()
 await navigate(page,'Overview');await expect(page.getByRole('region',{name:'Accounts, with context.',exact:true})).toContainText(before.upload_attention+' uploads need attention.');const after=(await(await page.request.get('/api/overview/statements')).json()).counts;expect(after.awaiting_other_reviewer-before.awaiting_other_reviewer).toBe(13);expect(after.upload_attention).toBe(before.upload_attention)
})
