import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { mkdirSync, chmodSync } from 'node:fs'
import { resolve } from 'node:path'
import { login, navigate, chooseOption } from './helpers'

async function capture(page: Page, name: string) {
  if (!process.env.SOCIETY_CAPTURE_UI) return
  await page.evaluate(() => document.fonts.ready)
  const folder = resolve('../reports/local/ui-review', process.env.SOCIETY_UI_PHASE ?? 'after')
  mkdirSync(folder, { recursive: true, mode: 0o700 })
  const path = resolve(folder, name + '.png')
  await page.screenshot({ path })
  chmodSync(path, 0o600)
}

test('desktop navigation and home dialogs remain usable in a short viewport', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await login(page)
  await capture(page, 'overview-desktop')
  await expect(page.locator('.workspace-profile')).toBeInViewport({ ratio: 1 })
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
  await navigate(page, 'Homes & people')
  await page.getByRole('button', { name: 'View home A-101', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Home 101' })).toBeVisible()
  await capture(page, 'home-desktop')
  await page.getByRole('button', { name: 'Manage home', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save occupancy', exact: true })).toBeInViewport({ ratio: 1 })
  await capture(page, 'manage-desktop')
  await page.getByRole('button', { name: 'History', exact: true }).click()
  await capture(page, 'history-desktop')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'View home A-101', exact: true })).toBeFocused()
})

test('invitation form and security fields work at desktop and phone sizes', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await login(page)
  await navigate(page, 'Access & invitations')
  await expect(page.locator('.account-row')).not.toHaveCount(0)
  await capture(page, 'access-desktop')
  await page.getByRole('button', { name: 'Invite a person', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Create personal link', exact: true })).toBeInViewport({ ratio: 1 })
  await chooseOption(page, 'Access', 'ADMINISTRATOR')
  await capture(page, 'invitation-desktop')
  await page.getByLabel('Find a person').fill('Demo Owner C-101')
  await chooseOption(page, 'Person in the registry', 'Demo Owner C-101')
  await page.getByRole('checkbox', { name: 'I verified this person’s identity, email and home relationship.' }).check()
  await page.getByLabel('Find a person').fill('Demo Owner C-102')
  await expect(page.getByLabel('Person in the registry')).toHaveText('Choose a person…')
  await expect(page.getByRole('checkbox', { name: 'I verified this person’s identity, email and home relationship.' })).not.toBeChecked()
  await page.getByLabel('Verification note').fill('A fictional visual review, without issuing a link.')
  await page.locator('.dialog-scroll').evaluate(el => { el.scrollTop = el.scrollHeight })
  await capture(page, 'invitation-scrolled-desktop')
  await expect(page.getByRole('button', { name: 'Close invitation', exact: true })).toBeInViewport({ ratio: 1 })
  await expect(page.getByRole('button', { name: 'Create personal link', exact: true })).toBeInViewport({ ratio: 1 })
  const backgroundScroll = await page.evaluate(() => scrollY)
  await page.mouse.move(40, 400)
  await page.mouse.wheel(0, 1000)
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(backgroundScroll)
  await page.getByRole('dialog').click({ position: { x: 2, y: 2 } })
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Invite a person', exact: true })).toBeFocused()
  await navigate(page, 'Account security')
  const current = page.getByLabel('Current password', { exact: true })
  await current.first().fill('Visual review only')
  await expect(current.last()).toHaveValue('')
  await current.last().fill('A separate visual review')
  await expect(current.first()).toHaveValue('Visual review only')
  await capture(page, 'security-desktop')
  await page.setViewportSize({ width: 375, height: 812 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await capture(page, 'security-phone')
  await navigate(page, 'Access & invitations')
  await expect(page.getByRole('heading', { name: 'A personal welcome.' })).toBeVisible()
  await capture(page, 'access-phone')
  await page.getByRole('button', { name: 'Invite a person', exact: true }).click()
  await capture(page, 'invitation-phone')
  await page.getByLabel('Verification note').fill('A fictional visual review, without issuing a link.')
  await page.locator('.dialog-scroll').evaluate(el => { el.scrollTop = el.scrollHeight })
  await capture(page, 'invitation-scrolled-phone')
  await expect(page.getByRole('button', { name: 'Close invitation', exact: true })).toBeInViewport({ ratio: 1 })
  await expect(page.getByRole('button', { name: 'Create personal link', exact: true })).toBeInViewport({ ratio: 1 })
  await page.keyboard.press('Escape')
})

test('small phone login and overview fit the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await capture(page, 'login-small-phone')
  await login(page)
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
  await expect(page.getByRole('heading', { name: 'Good things, in order.' })).toBeInViewport()
  await capture(page, 'overview-small-phone')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('navigation and dialog controls fit tablet, narrow and reduced-height screens', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await login(page)
  for (const viewport of [{ width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 320, height: 568 }, { width: 375, height: 500 }]) {
    await page.setViewportSize(viewport)
    await page.evaluate(() => window.scrollTo(0, 0))
    if (viewport.width <= 850) {
      await page.getByRole('button', { name: 'Menu', exact: true }).click()
      await page.keyboard.press('Escape')
      await expect(page.getByRole('button', { name: 'Menu', exact: true })).toHaveAttribute('aria-expanded', 'false')
      await page.getByRole('button', { name: 'Menu', exact: true }).click()
      for (const name of ['Overview', 'Homes & people', 'Access & invitations', 'Entries', 'Receipts', 'Requests & approvals', 'Community', 'Help & repairs', 'Account security', 'Documents']) {
        await page.getByRole('link', { name, exact: true }).scrollIntoViewIfNeeded()
        await expect(page.getByRole('link', { name, exact: true })).toBeInViewport({ ratio: 1 })
      }
      await capture(page, `navigation-${viewport.width}x${viewport.height}`)
      await page.getByRole('link', { name: 'Account security', exact: true }).focus()
      await page.keyboard.press('Escape')
      await expect(page.getByRole('button', { name: 'Menu', exact: true })).toBeFocused()
      await expect(page.getByRole('button', { name: 'Menu', exact: true })).toHaveAttribute('aria-expanded', 'false')
    } else {
      await expect(page.locator('.workspace-profile')).toBeInViewport({ ratio: 1 })
      const accessIcon = await page.getByRole('link', { name: 'Access & invitations', exact: true }).locator('svg').boundingBox()
      expect(accessIcon?.width).toBeGreaterThanOrEqual(16)
      await capture(page, `navigation-${viewport.width}x${viewport.height}`)
    }
    await navigate(page, 'Access & invitations')
    await expect(page.getByRole('heading', { name: 'A personal welcome.' })).toBeVisible()
    await page.getByRole('button', { name: 'Invite a person', exact: true }).click()
    await page.locator('.dialog-scroll').evaluate(el => { el.scrollTop = el.scrollHeight })
    await expect(page.getByRole('button', { name: 'Close invitation', exact: true })).toBeInViewport({ ratio: 1 })
    await expect(page.getByRole('button', { name: 'Create personal link', exact: true })).toBeInViewport({ ratio: 1 })
    expect(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await capture(page, `invitation-${viewport.width}x${viewport.height}`)
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: 'Invite a person', exact: true })).toBeFocused()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
})
