import { test,expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { chmodSync,mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { login,navigate,chooseOption } from './helpers'
import { financialHeaders } from './maintenance-fixtures'
import { apiCareRecord,apiWork,apiWorkAction,careDate } from './upkeep-fixtures'

async function capture(page:Page,name:string){
 if(!process.env.SOCIETY_CAPTURE_UI)return
 await page.evaluate(()=>document.fonts.ready)
 await page.evaluate(async()=>{await Promise.allSettled(document.getAnimations().filter(a=>a.effect?.getComputedTiming().iterations!==Infinity).map(a=>a.finished))})
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))))
 const modal=await page.getByRole('dialog').count()>0
 if(modal)await expect(page.getByRole('dialog').locator('.dialog-close')).toBeInViewport({ratio:1})
 const y=await page.evaluate(()=>window.scrollY)
 if(modal)await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}))
 const folder=resolve('../reports/local/upkeep-review');mkdirSync(folder,{recursive:true,mode:0o700});const path=resolve(folder,name+'.png')
 try{await page.screenshot({path,animations:'allow'});chmodSync(path,0o600)}finally{if(modal)await page.evaluate(y=>window.scrollTo({top:y,behavior:'instant'}),y)}
}
async function within(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);if(await page.getByRole('dialog').count())expect(await page.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)}
async function fillWork(page:Page,title:string){
 await page.getByRole('button',{name:'Plan work',exact:true}).click();await page.getByRole('textbox',{name:'Work title',exact:true}).fill(title);await page.getByRole('textbox',{name:'Private work details',exact:true}).fill('PRIVATE supplied scope for the fictional pump service visit and independent check.');await chooseOption(page,'Work category','Water');await chooseOption(page,'Work priority','High');await page.getByLabel('Work due date',{exact:true}).fill(careDate(-1));await page.getByLabel('Scheduled visit (optional)',{exact:true}).fill(careDate(1));await page.getByRole('spinbutton',{name:'Repeat interval in days',exact:true}).fill('30')
}
async function action(page:Page,label:string,confirmation:string){
 await chooseOption(page,'Work action',label);await page.getByRole('textbox',{name:'Work action reason',exact:true}).fill('PRIVATE checked original supplied work and evidence before this action');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:confirmation,exact:true}).click();await expect(page.getByRole('button',{name:'Save private note',exact:true})).toBeVisible()
}

test('work preparation filters opened menus keyboard focus and dialog review remain aligned on four viewports',async({page})=>{
 test.setTimeout(60000);await login(page);await navigate(page,'Upkeep')
 for(const width of [1440,768,375,320]){
  await page.setViewportSize({width,height:900});await expect(page.getByRole('button',{name:'Plan work',exact:true})).toBeEnabled();await within(page);await capture(page,'queue-'+width)
  const filter=page.getByRole('combobox',{name:'Filter work by state',exact:true});await filter.click();await page.getByRole('option',{name:'Ready for check',exact:true}).hover();await capture(page,'work-filter-open-'+width);await page.keyboard.press('Escape');await expect(filter).toBeFocused();await filter.click();await expect(page.getByRole('option',{name:'All work',exact:true})).toBeFocused();await page.keyboard.press('End');await expect(page.getByRole('option',{name:'Cancelled',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(filter).toContainText('Cancelled');await page.getByRole('button',{name:'Clear',exact:true}).click()
  await fillWork(page,'Viewport pump plan '+width);await page.getByRole('combobox',{name:'Work assignee',exact:true}).click();await page.getByRole('option',{name:'Demo Registry Officer',exact:true}).hover();await capture(page,'work-assignee-open-'+width);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Review work plan',exact:true}).click();await expect(page.getByRole('heading',{name:'Viewport pump plan '+width,exact:true})).toBeFocused();await page.getByRole('dialog').getByRole('checkbox').check();await within(page);await capture(page,'work-preview-'+width);await page.getByRole('button',{name:'Edit work plan',exact:true}).click();await expect(page.getByRole('textbox',{name:'Work title',exact:true})).toHaveValue('Viewport pump plan '+width);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Plan work',exact:true})).toBeFocused()
 }
})

test('vendor and asset registers review contacts dates and active links with tablet and phone editing',async({page})=>{
 test.setTimeout(60000);await login(page);await navigate(page,'Upkeep');await page.getByRole('tab',{name:'Vendors',exact:true}).click();await page.getByRole('button',{name:'Add vendor',exact:true}).click()
 const vendor='Fictional care partner '+Date.now();await page.getByRole('textbox',{name:'Vendor name',exact:true}).fill(vendor);await page.getByRole('textbox',{name:'Register category',exact:true}).fill('Water service');await page.getByRole('textbox',{name:'Contact person (optional)',exact:true}).fill('PRIVATE supplier contact');await page.getByRole('textbox',{name:'Phone (optional)',exact:true}).fill('+91 98765 43210');await page.getByRole('textbox',{name:'Email (optional)',exact:true}).fill('supplier@example.test');await page.getByRole('textbox',{name:'Private source reference',exact:true}).fill('PRIVATE supplied vendor contract');await page.getByRole('textbox',{name:'Reason for saving',exact:true}).fill('Checked supplied fictional vendor details');await page.getByRole('button',{name:'Review vendor record',exact:true}).click();await capture(page,'vendor-review-desktop');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Confirm vendor record',exact:true}).click();await expect(page.getByRole('button',{name:'Edit vendor',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close vendor details',exact:true}).click()
 await page.getByRole('tab',{name:'Assets',exact:true}).click();await page.getByRole('button',{name:'Add asset',exact:true}).click();const name='Fictional water pump '+Date.now();await page.getByRole('textbox',{name:'Asset name',exact:true}).fill(name);await page.getByRole('textbox',{name:'Register category',exact:true}).fill('Water');await page.getByRole('textbox',{name:'Asset location',exact:true}).fill('PRIVATE pump room');await chooseOption(page,'Asset vendor',vendor);await page.getByLabel('AMC starts (optional)',{exact:true}).fill('2026-01-01');await page.getByLabel('AMC ends (optional)',{exact:true}).fill(careDate(-1));await page.getByLabel('Next inspection (optional)',{exact:true}).fill(careDate(1));await page.getByRole('textbox',{name:'Private source reference',exact:true}).fill('PRIVATE supplied pump contract');await page.getByRole('textbox',{name:'Reason for saving',exact:true}).fill('Verified the fictional supplied asset dates and links')
 for(const width of [768,375,320]){await page.setViewportSize({width,height:900});await within(page);await page.getByRole('combobox',{name:'Asset vendor',exact:true}).click();await expect(page.getByRole('option',{name:vendor,exact:true})).toHaveAttribute('data-state','checked');await capture(page,'asset-vendor-menu-'+width);await page.keyboard.press('Escape')}
 await page.getByRole('button',{name:'Review asset record',exact:true}).click();await capture(page,'asset-review-320');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Confirm asset record',exact:true}).click();await expect(page.getByRole('button',{name:'Edit asset',exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit asset',exact:true}).click();await chooseOption(page,'Register state','Inactive');await page.getByRole('textbox',{name:'Reason for saving',exact:true}).fill('Retired this fictional asset while preserving its history');await page.getByRole('button',{name:'Review asset record',exact:true}).click();await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Confirm asset record',exact:true}).click();await expect(page.getByRole('dialog').getByText('Water · Inactive',{exact:true})).toBeVisible();await capture(page,'retired-asset-history-320');await page.getByRole('button',{name:'Close asset details',exact:true}).click();await chooseOption(page,'Filter asset state','Inactive');await expect(page.getByRole('button',{name:'Open asset '+name,exact:true})).toBeVisible();await capture(page,'retired-asset-register-320')
 const tab=page.getByRole('tab',{name:'Assets',exact:true});await tab.focus();await page.keyboard.press('ArrowRight');await expect(page.getByRole('tab',{name:'Vendors',exact:true})).toBeFocused();await expect(page.getByRole('tab',{name:'Vendors',exact:true})).toHaveAttribute('aria-selected','true')
})

test('work progresses through wait return separate completion check and explicit repeat without changing the source',async({page,browser})=>{
 test.setTimeout(60000);await login(page);const committee=await browser.newContext({baseURL:new URL(page.url()).origin}),other=await committee.newPage();await login(other,'Committee');const title='Checked upkeep '+Date.now();await navigate(page,'Upkeep');await fillWork(page,title);await chooseOption(page,'Work assignee','Demo Registry Officer');await page.getByRole('button',{name:'Review work plan',exact:true}).click();await page.getByRole('dialog').getByRole('checkbox').check();const saved=page.waitForResponse(r=>r.url().endsWith('/api/upkeep/tasks')&&r.request().method()==='POST');await page.getByRole('button',{name:'Confirm work plan',exact:true}).click();const id=(await(await saved).json()).id;await expect(page.getByRole('combobox',{name:'Work action',exact:true})).toBeVisible()
 await action(page,'Start work','Confirm start');await action(page,'Mark waiting','Confirm waiting');await capture(page,'waiting-work');await action(page,'Start work','Confirm start');await action(page,'Submit for checking','Submit for separate check');await expect(page.getByRole('dialog').getByText('Ready for check',{exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Work action',exact:true}).click();await expect(page.getByRole('option',{name:'Confirm completion',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');await capture(page,'self-check-blocked')
 await other.goto('/#upkeep?task='+id);await expect(other.getByRole('dialog').getByRole('heading',{name:title,exact:true})).toBeVisible();await action(other,'Return to work','Confirm return to work');await other.getByRole('button',{name:'Close work details',exact:true}).click();await page.getByRole('button',{name:'Close work details',exact:true}).click();await page.getByRole('button',{name:'Open work '+title,exact:true}).click();await action(page,'Submit for checking','Submit for separate check');await other.goto('/#upkeep?task='+id);await action(other,'Confirm completion','Confirm completion');await expect(other.getByRole('dialog').getByText('Done',{exact:true})).toBeVisible();await capture(other,'separately-checked-work');const original=await(await other.request.get('/api/upkeep/tasks/'+id)).json();expect(original.ready_by).toBe('demo-user-admin');expect(original.checked_by).toBe('demo-user-committee');expect(original.event_total).toBe(8)
 await other.getByRole('button',{name:'Prepare next occurrence',exact:true}).click();await expect(other.getByRole('textbox',{name:'Work title',exact:true})).toHaveValue(title);await other.getByLabel('Work due date',{exact:true}).fill(careDate(30));await other.getByRole('button',{name:'Review work plan',exact:true}).click();await capture(other,'repeat-preview');await other.getByRole('dialog').getByRole('checkbox').check();await other.getByRole('button',{name:'Confirm work plan',exact:true}).click();await expect(other.getByRole('combobox',{name:'Work action',exact:true})).toBeVisible();const after=await(await other.request.get('/api/upkeep/tasks/'+id)).json();expect(after).toEqual(original);const children=await(await other.request.get('/api/upkeep?q='+encodeURIComponent(title))).json();expect(children.items.some((work:{parent_id:string;state:string})=>work.parent_id===id&&work.state==='PLANNED')).toBe(true);await committee.close()
})

test('explicit public updates stay frozen through private notes and completion and never expose the directory',async({page,browser})=>{
 test.setTimeout(60000);await login(page);const title='Private supply task '+Date.now(),id=await apiWork(page,title,{due_date:careDate(-1)});await page.goto('/#upkeep?task='+id);await chooseOption(page,'Work action','Publish resident update');await page.getByRole('textbox',{name:'Resident-facing title',exact:true}).fill('Shared water service update');await page.getByRole('textbox',{name:'Resident-facing update',exact:true}).fill('Water supply work is planned. Thank you for your patience.');await chooseOption(page,'Work publication audience','A specific wing');await chooseOption(page,'Work publication wing','Wing A');await page.getByRole('textbox',{name:'Work action reason',exact:true}).fill('Checked publication wording and Wing A resident audience');await page.getByRole('dialog').getByRole('checkbox').check();await capture(page,'resident-publication-preview');await page.getByRole('button',{name:'Publish reviewed update',exact:true}).click();await expect(page.getByRole('button',{name:'Save private note',exact:true})).toBeVisible()
 const context=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await context.newPage();await login(owner,'Owner');await navigate(owner,'Upkeep');await owner.getByRole('button',{name:'Open work Shared water service update',exact:true}).click();await expect(owner.getByRole('tab')).toHaveCount(0);await expect(owner.getByRole('combobox',{name:'Work action',exact:true})).toHaveCount(0);await expect(owner.getByRole('heading',{name:'Private activity',exact:true})).toHaveCount(0);const before=await(await owner.request.get('/api/upkeep/tasks/'+id)).json();expect(before.state).toBe('PLANNED');expect(before.version).toBe(1);expect(JSON.stringify(before)).not.toContain('PRIVATE');expect((await owner.request.get('/api/upkeep/register/VENDOR')).status()).toBe(403)
 await action(page,'Add a private note','Save private note');await action(page,'Start work','Confirm start');await action(page,'Submit for checking','Submit for separate check');expect(await(await owner.request.get('/api/upkeep/tasks/'+id)).json()).toEqual(before);await owner.setViewportSize({width:320,height:900});await capture(owner,'resident-frozen-update-320');await within(owner)
 await apiWorkAction(page,id,'UNPUBLISH');await owner.getByRole('button',{name:'Close work details',exact:true}).click();await navigate(owner,'Overview');await navigate(owner,'Upkeep');await expect(owner.getByRole('button',{name:'Open work Shared water service update',exact:true})).toHaveCount(0);expect((await owner.request.get('/api/upkeep/tasks/'+id)).status()).toBe(404);await context.close()
})

test('lost work action response freezes pending controls and retries one version while a stale change requires reload',async({page})=>{
 await login(page);const title='Retry work '+Date.now(),id=await apiWork(page,title);await page.goto('/#upkeep?task='+id);await chooseOption(page,'Work action','Start work');await page.getByRole('textbox',{name:'Work action reason',exact:true}).fill('Retry preserves this exact fictional work action');await page.getByRole('dialog').getByRole('checkbox').check()
 let release!:()=>void;let calls=0;const keys:string[]=[]
 await page.route('**/api/upkeep/tasks/*/actions',async route=>{keys.push(route.request().postDataJSON().operation_key);calls++;if(calls===1){await new Promise<void>(resolve=>{release=resolve});await route.fetch();await route.abort('failed')}else await route.continue()})
 await page.getByRole('button',{name:'Confirm start',exact:true}).click();await expect(page.getByRole('button',{name:'Close work details',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('textbox',{name:'Work action reason',exact:true})).toBeDisabled();await expect.poll(()=>typeof release).toBe('function');await capture(page,'pending-action');release();await expect(page.getByRole('button',{name:'Retry work action',exact:true})).toBeEnabled();await capture(page,'lost-response-retry');await page.getByRole('button',{name:'Retry work action',exact:true}).click();await expect(page.getByRole('button',{name:'Save private note',exact:true})).toBeVisible();expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);const current=await(await page.request.get('/api/upkeep/tasks/'+id)).json();expect(current.state).toBe('IN_PROGRESS');expect(current.version).toBe(2);expect(current.event_total).toBe(2);await page.unroute('**/api/upkeep/tasks/*/actions')
 await chooseOption(page,'Work action','Mark waiting');await page.getByRole('textbox',{name:'Work action reason',exact:true}).fill('This fictional reason becomes stale after another update');await page.getByRole('dialog').getByRole('checkbox').check();await apiWorkAction(page,id,'COMMENT');await page.getByRole('button',{name:'Confirm waiting',exact:true}).click();await expect(page.getByRole('alert')).toContainText('changed');await capture(page,'stale-action');await page.getByRole('button',{name:'Reload work',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.getByRole('dialog').getByText('In progress',{exact:true})).toBeVisible()
})

test('work loading failures filtered emptiness and source retries replace old values with unknowns',async({page})=>{
 await login(page);const title='Failure state work '+Date.now();await apiWork(page,title);await page.route('**/api/upkeep?**',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await navigate(page,'Upkeep');await expect(page.getByRole('heading',{name:'Work unavailable.',exact:true})).toBeVisible();await expect(page.locator('.upkeep-metrics strong')).toHaveText(['—','—','—','—']);await capture(page,'work-error');await page.unroute('**/api/upkeep?**');await page.getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByRole('button',{name:'Open work '+title,exact:true})).toBeVisible();let release!:()=>void;await page.route('**/api/upkeep?**',async route=>{await new Promise<void>(resolve=>{release=resolve});await route.continue()});await page.getByRole('searchbox',{name:'Search work',exact:true}).fill('No such fictional upkeep');await expect(page.locator('.upkeep-metrics strong')).toHaveText(['—','—','—','—']);await expect(page.getByRole('button',{name:'Plan work',exact:true})).toBeDisabled();await capture(page,'filtered-loading');await expect.poll(()=>typeof release).toBe('function');release();await expect(page.getByRole('heading',{name:'No work matches.',exact:true})).toBeVisible();await capture(page,'filtered-empty');await page.unroute('**/api/upkeep?**');await page.getByRole('button',{name:'Clear',exact:true}).click();await page.getByRole('button',{name:'Open work '+title,exact:true}).click();await page.getByRole('button',{name:'Close work details',exact:true}).click();await page.route('**/api/upkeep/tasks/*',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await page.getByRole('button',{name:'Open work '+title,exact:true}).click();await expect(page.getByRole('button',{name:'Reload work',exact:true})).toBeVisible();await expect(page.getByRole('dialog').getByRole('heading',{name:'Work unavailable.',exact:true})).toBeVisible();await capture(page,'work-detail-error');await page.unroute('**/api/upkeep/tasks/*');await page.getByRole('button',{name:'Reload work',exact:true}).click();await expect(page.getByRole('combobox',{name:'Work action',exact:true})).toBeVisible()
})

test('upkeep overview uses independently supplied deadlines and exact work and asset links with a local source retry',async({page})=>{
 await login(page);const previous=await(await page.request.get('/api/upkeep')).json();for(const work of previous.items)if(!['DONE','CANCELLED'].includes(work.state))await apiWorkAction(page,work.id,'CANCEL');expect((await(await page.request.get('/api/overview/upkeep')).json()).counts.open).toBe(0);const title='Overview care '+Date.now(),id=await apiWork(page,title,{due_date:careDate(-1),assigned_to:'demo-user-admin'});const name='Overview pump '+Date.now(),asset=await apiCareRecord(page,'ASSET',name,{amc_start:'2020-01-01',amc_end:careDate(-1),inspection_date:careDate(1)});await navigate(page,'Overview');await expect(page.getByRole('button',{name:'Refresh overview',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Refresh overview',exact:true}).click();await expect(page.getByRole('button',{name:'Refresh overview',exact:true})).toBeEnabled();const panel=page.getByRole('region',{name:'Everyday care, in view.',exact:true});await expect(panel.locator('.overview-maintenance-amounts strong')).toHaveText(['1','1','0']);const data=await(await page.request.get('/api/overview/upkeep')).json();expect(data.counts.amc_expired).toBe(1);expect(data.counts.inspection_upcoming).toBe(1)
 await page.getByRole('link',{name:'AMC date passed: '+name,exact:true}).click();await expect(page.getByRole('dialog').getByRole('heading',{name,exact:true})).toBeVisible();expect(page.url()).toContain('asset='+asset);await capture(page,'overview-asset-deadline');await page.getByRole('button',{name:'Close asset details',exact:true}).click();await navigate(page,'Overview');await page.getByRole('link',{name:'Work needs attention: '+title,exact:true}).click();await expect(page.getByRole('dialog').getByRole('heading',{name:title,exact:true})).toBeVisible();expect(page.url()).toContain('task='+id);await page.getByRole('button',{name:'Close work details',exact:true}).click();await navigate(page,'Overview');await page.route('**/api/overview/upkeep',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await page.getByRole('button',{name:'Refresh overview',exact:true}).click();await expect(panel.locator('.overview-maintenance-amounts strong')).toHaveText(['—','—','—']);await panel.scrollIntoViewIfNeeded();await capture(page,'upkeep-overview-error');await page.unroute('**/api/overview/upkeep');await panel.getByRole('button',{name:'Retry upkeep',exact:true}).click();await expect(panel.locator('.overview-maintenance-amounts strong')).toHaveText(['1','1','0'])
})

test('retired links remain readable but new work needs current choices and service cases connect through the actual screen',async({page})=>{
 await login(page);const vendor=await apiCareRecord(page,'VENDOR','Private linked supplier'),asset=await apiCareRecord(page,'ASSET','Private linked pump',{vendor_id:vendor});const id=await apiWork(page,'Historical linked work',{asset_id:asset,vendor_id:vendor});const headers=await financialHeaders(page)
 for(const [kind,record]of[['VENDOR',vendor],['ASSET',asset]]){const item=await(await page.request.get('/api/upkeep/register/'+kind+'/'+record)).json();const response=await page.request.post('/api/upkeep/register/'+kind+'/'+record,{headers,data:{operation_key:crypto.randomUUID(),version:item.version,name:item.name,category:item.category,location:item.location,contact:item.contact,phone:item.phone,email:item.email,vendor_id:item.vendor_id,source_reference:item.source_reference,amc_start:item.amc_start,amc_end:item.amc_end,inspection_date:item.inspection_date,state:'INACTIVE',reason:'Retired fictional link and preserved the supplied history',confirmed:true}});expect(response.status(),await response.text()).toBe(200)}
 await page.goto('/#upkeep?task='+id);await expect(page.getByRole('dialog').getByText('Private linked pump · Private linked supplier',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Close work details',exact:true}).click();await page.getByRole('button',{name:'Plan work',exact:true}).click();await page.getByRole('combobox',{name:'Work asset',exact:true}).click();await expect(page.getByRole('option',{name:'Private linked pump',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');await page.getByRole('combobox',{name:'Work vendor',exact:true}).click();await expect(page.getByRole('option',{name:'Private linked supplier',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Close work preparation',exact:true}).click()
 const response=await page.request.post('/api/complaints',{headers,data:{operation_key:crypto.randomUUID(),flat_id:'demo-flat-A-101',category:'WATER',subject:'Fictional linked water issue',description:'Fictional service issue with a supplied plan for work',priority:'HIGH'}});expect(response.status()).toBe(200);const caseID=(await response.json()).id;await page.goto('/#help?case='+caseID);await expect(page.getByRole('heading',{name:'Fictional linked water issue',exact:true})).toBeVisible();await page.getByRole('link',{name:'Plan upkeep for this request',exact:true}).click();await expect(page.getByText(/Private service link/)).toBeVisible();await page.getByRole('textbox',{name:'Work title',exact:true}).fill('Work for the linked service issue');await page.getByRole('textbox',{name:'Private work details',exact:true}).fill('Reviewed private service details for this fictional work');await page.getByRole('button',{name:'Review work plan',exact:true}).click();await capture(page,'linked-service-work-preview');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Confirm work plan',exact:true}).click();await expect(page.getByRole('link',{name:/Open linked service request/})).toBeVisible();await page.getByRole('link',{name:/Open linked service request/}).click();await expect(page.getByRole('heading',{name:'Fictional linked water issue',exact:true})).toBeVisible()
})

test('assignment rescheduling cancellation reopening and publication removal use reviewed controls at each size',async({page,browser})=>{
 test.setTimeout(60000);await login(page);const context=await browser.newContext({baseURL:new URL(page.url()).origin}),committee=await context.newPage();await login(committee,'Committee');await context.close();const title='Reviewed care actions '+Date.now(),id=await apiWork(page,title);await page.goto('/#upkeep?task='+id)
 for(const width of [1440,768,375,320]){await page.setViewportSize({width,height:900});await page.getByRole('combobox',{name:'Work action',exact:true}).click();await page.getByRole('option',{name:'Reschedule work',exact:true}).hover();await capture(page,'action-menu-'+width);await page.keyboard.press('Escape');await within(page)}
 await chooseOption(page,'Work action','Assign work');await chooseOption(page,'Updated work assignee','Demo Committee Member');await page.getByRole('textbox',{name:'Work action reason',exact:true}).fill('Verified current fictional committee assignment');await page.getByRole('dialog').getByRole('checkbox').check();await capture(page,'assignment-review-320');await page.getByRole('button',{name:'Confirm assignment',exact:true}).click();await expect(page.getByRole('button',{name:'Save private note',exact:true})).toBeVisible();await expect(page.getByRole('dialog').locator('.record-facts dd').filter({hasText:'Demo Committee Member'})).toBeVisible()
 await chooseOption(page,'Work action','Reschedule work');await page.getByLabel('Updated work due date',{exact:true}).fill(careDate(7));await page.getByLabel('Updated scheduled visit',{exact:true}).fill(careDate(6));await page.getByRole('textbox',{name:'Work action reason',exact:true}).fill('Reviewed explicit replacement dates with the fictional operator');await page.getByRole('dialog').getByRole('checkbox').check();await capture(page,'schedule-review-320');await page.getByRole('button',{name:'Confirm schedule',exact:true}).click();await expect(page.getByRole('button',{name:'Save private note',exact:true})).toBeVisible();let current=await(await page.request.get('/api/upkeep/tasks/'+id)).json();expect(current.due_date).toBe(careDate(7));expect(current.visit_date).toBe(careDate(6));expect(current.assigned_to).toBe('demo-user-committee')
 await action(page,'Cancel work','Confirm cancellation');await expect(page.getByRole('dialog').getByText('Cancelled',{exact:true})).toBeVisible();await capture(page,'cancelled-work-320');await action(page,'Reopen work','Confirm reopening');await expect(page.getByRole('dialog').getByText('Planned',{exact:true})).toBeVisible();await capture(page,'reopened-work-320')
 await chooseOption(page,'Work action','Publish resident update');await page.getByRole('textbox',{name:'Resident-facing title',exact:true}).fill('Reviewed shared care schedule');await page.getByRole('textbox',{name:'Resident-facing update',exact:true}).fill('A fictional shared service is scheduled for the supplied dates.');await page.getByRole('textbox',{name:'Work action reason',exact:true}).fill('Deliberately checked fictional public wording and audience');await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('button',{name:'Publish reviewed update',exact:true}).click();await expect(page.getByRole('button',{name:'Save private note',exact:true})).toBeVisible();await action(page,'Remove resident update','Remove published update');current=await(await page.request.get('/api/upkeep/tasks/'+id)).json();expect(current.audience).toBe('INTERNAL');expect(current.public_version).toBe(2);await expect(page.getByText('RETAINED, NO LONGER SHARED',{exact:true})).toBeVisible();await capture(page,'unpublished-history-320')
})

test('register failures and lost creation responses keep one identity and stale edits require current record review',async({page})=>{
 test.setTimeout(60000);await login(page);await navigate(page,'Upkeep');await page.route('**/api/upkeep/register/VENDOR?**',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await page.getByRole('tab',{name:'Vendors',exact:true}).click();await expect(page.getByRole('button',{name:'Try again',exact:true})).toBeVisible();await capture(page,'vendor-register-error');await page.unroute('**/api/upkeep/register/VENDOR?**');await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('button',{name:'Add vendor',exact:true}).click();const title='Retry supplier '+Date.now();await page.getByRole('textbox',{name:'Vendor name',exact:true}).fill(title);await page.getByRole('textbox',{name:'Register category',exact:true}).fill('Care');await page.getByRole('textbox',{name:'Private source reference',exact:true}).fill('PRIVATE source for response-loss supplier');await page.getByRole('textbox',{name:'Reason for saving',exact:true}).fill('Checked fictional source and the supplier identity');await page.getByRole('button',{name:'Review vendor record',exact:true}).click();await page.getByRole('dialog').getByRole('checkbox').check()
 let calls=0,release!:()=>void;const keys:string[]=[];await page.route('**/api/upkeep/register/VENDOR',async route=>{keys.push(route.request().postDataJSON().operation_key);calls++;if(calls===1){await new Promise<void>(resolve=>{release=resolve});await route.fetch();await route.abort('failed')}else await route.continue()});await page.getByRole('button',{name:'Confirm vendor record',exact:true}).click();await expect(page.getByRole('button',{name:'Close vendor details',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await expect.poll(()=>typeof release).toBe('function');await capture(page,'register-pending');release();await expect(page.getByRole('button',{name:'Retry saving record',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Edit before saving',exact:true})).toBeDisabled();await capture(page,'register-lost-response');await page.getByRole('button',{name:'Retry saving record',exact:true}).click();await expect(page.getByRole('button',{name:'Edit vendor',exact:true})).toBeVisible();expect(keys).toHaveLength(2);expect(keys[0]).toBe(keys[1]);await page.unroute('**/api/upkeep/register/VENDOR');const result=await(await page.request.get('/api/upkeep/register/VENDOR?q='+encodeURIComponent(title))).json();expect(result.total).toBe(1);const id=result.items[0].id;expect((await(await page.request.get('/api/upkeep/register/VENDOR/'+id)).json()).event_total).toBe(1)
 await page.getByRole('button',{name:'Edit vendor',exact:true}).click();await page.getByRole('textbox',{name:'Reason for saving',exact:true}).fill('Fictional edit that will become stale before confirmation');await page.getByRole('button',{name:'Review vendor record',exact:true}).click();await page.getByRole('dialog').getByRole('checkbox').check();const previous=await(await page.request.get('/api/upkeep/register/VENDOR/'+id)).json();const changed=await page.request.post('/api/upkeep/register/VENDOR/'+id,{headers:await financialHeaders(page),data:{operation_key:crypto.randomUUID(),version:previous.version,name:title,category:'Care',source_reference:'PRIVATE concurrent corrected source',state:'ACTIVE',reason:'Fictional concurrent correction checked original supplier',confirmed:true}});expect(changed.status(),await changed.text()).toBe(200);await page.getByRole('button',{name:'Confirm vendor record',exact:true}).click();await expect(page.getByRole('alert')).toContainText('changed');await capture(page,'register-stale-review');await page.getByRole('button',{name:'Reload register record',exact:true}).click();await expect(page.getByRole('dialog').getByText('PRIVATE concurrent corrected source',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Close vendor details',exact:true}).click()
 await page.route('**/api/upkeep/options',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await page.getByRole('button',{name:'Add vendor',exact:true}).click();await expect(page.getByRole('button',{name:'Reload choices',exact:true})).toBeVisible();await capture(page,'register-choice-error');await page.unroute('**/api/upkeep/options');await page.getByRole('button',{name:'Reload choices',exact:true}).click();await expect(page.getByRole('textbox',{name:'Vendor name',exact:true})).toBeVisible()
})

test('filtered work and private event pages stay bounded while history navigation preserves the human note',async({page})=>{
 test.setTimeout(60000);await login(page);const prefix='Paged care '+Date.now();const ids:string[]=[];for(let i=0;i<13;i++)ids.push(await apiWork(page,prefix+' '+String(i).padStart(2,'0')))
 await navigate(page,'Upkeep');await page.getByRole('searchbox',{name:'Search work',exact:true}).fill(prefix);await expect(page.locator('.upkeep-grid > button')).toHaveCount(12);await page.getByRole('button',{name:'Next work items page',exact:true}).click();await expect(page.locator('.upkeep-grid > button')).toHaveCount(1);await expect(page.getByText('Page 2 of 2',{exact:true})).toBeVisible();await capture(page,'work-second-page');await page.getByRole('button',{name:'Previous work items page',exact:true}).click();await expect(page.locator('.upkeep-grid > button')).toHaveCount(12)
 for(let i=0;i<21;i++)await apiWorkAction(page,ids[0],'COMMENT');await page.getByRole('button',{name:'Open work '+prefix+' 00',exact:true}).click();await expect(page.getByRole('region',{name:'Private work history',exact:true}).getByRole('listitem')).toHaveCount(20);await page.getByRole('textbox',{name:'Work action reason',exact:true}).fill('PRIVATE human note retained through history navigation');await page.getByRole('button',{name:'Next private activity page',exact:true}).click();await expect(page.getByRole('region',{name:'Private work history',exact:true}).getByRole('listitem')).toHaveCount(2);await expect(page.getByRole('textbox',{name:'Work action reason',exact:true})).toHaveValue('PRIVATE human note retained through history navigation');await page.setViewportSize({width:320,height:900});await capture(page,'private-history-second-page-320');await within(page)
})
