import { test,expect } from '@playwright/test'
import { login } from './helpers'
import { names,execute } from './native-webmcp-helpers'
import type { ContextDocument } from './native-webmcp-helpers'
import { statementActors,statementOriginal,statementApprove,statementPublish,openStatement } from './statements-fixtures'
import { messagePrivateFixture } from './messages-fixtures'
import { financialHeaders } from './maintenance-fixtures'

test.setTimeout(90000)
test('actual native statement tools return bounded status only preserve human review and never mutate or download',async({page,browser})=>{
 const a=await statementActors(page,browser)
 try{const id=await statementOriginal(page,'PRIVATE_NATIVE_EXTERNAL figures and preparer');await expect.poll(()=>names(a.reviewer)).toContain('society_read_financial_statement');await openStatement(a.reviewer,id);await a.reviewer.getByRole('button',{name:'Review original for approval',exact:true}).click();const marker='PRIVATE_NATIVE_REASON preserve this deliberate human review';await a.reviewer.getByRole('textbox',{name:'Statement decision reason',exact:true}).fill(marker)
 const writes:string[]=[];a.reviewer.on('request',r=>{if(!['GET','HEAD'].includes(r.method())||r.url().endsWith('/download'))writes.push(r.url())});const metadata=JSON.parse(await execute(a.reviewer,'society_read_financial_statement',{statement_id:id}));expect(Object.keys(metadata).sort()).toEqual(['id','kind','state','validation','revision','version','current','published','can_download','can_review','can_publish'].sort());expect(metadata).toMatchObject({id,kind:'INCOME',state:'PENDING',validation:'AVAILABLE',published:false,can_review:true,revision:0});for(const key of ['title','filename','source','prepared_by','sha256','uploader_id','reviewer_id','events','publications','versions','reason','amount_paise'])expect(metadata).not.toHaveProperty(key);expect(JSON.stringify(metadata)).not.toContain('PRIVATE')
 const pageData=JSON.parse(await execute(a.reviewer,'society_find_financial_statements',{state:'PENDING'}));expect(pageData.items).toEqual([metadata]);expect(pageData.page_size).toBe(12);await expect(a.reviewer.getByRole('textbox',{name:'Statement decision reason',exact:true})).toHaveValue(marker);await expect(execute(a.reviewer,'society_open_workspace',{screen:'statements'})).rejects.toThrow();expect(writes).toEqual([])
 for(let i=0;i<12;i++)await statementOriginal(page,'PRIVATE native bounded original '+i)
 const bounded=JSON.parse(await execute(page,'society_find_financial_statements',{}));expect(bounded.total).toBe(13);expect(bounded.items).toHaveLength(12);expect(JSON.parse(await execute(page,'society_find_financial_statements',{page:2})).items).toHaveLength(1);expect((await names(page)).filter(x=>x.includes('financial_statement')).sort()).toEqual(['society_find_financial_statements','society_read_financial_statement'])
 }finally{await a.close()}
})

test('native statement reads enforce deliberate tenant scope and discard held reads after membership changes',async({page,browser})=>{
 const a=await statementActors(page,browser),tc=await browser.newContext({baseURL:new URL(page.url()).origin}),tenant=await tc.newPage(),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage();let release=()=>{}
 try{await login(tenant,'Tenant');await login(owner,'Owner');const id=await statementOriginal(page,'PRIVATE tenant publication native original');await expect(execute(tenant,'society_read_financial_statement',{statement_id:id})).rejects.toThrow();await statementApprove(a.reviewer,id);await expect(execute(tenant,'society_read_financial_statement',{statement_id:id})).rejects.toThrow();await statementPublish(page,a.reviewer,id);await expect(execute(owner,'society_read_financial_statement',{statement_id:id})).rejects.toThrow();const own=JSON.parse(await execute(tenant,'society_read_financial_statement',{statement_id:id}));expect(own).toMatchObject({published:true,can_review:false,can_publish:false,version:0});await openStatement(tenant,id)
 let ready!:()=>void;const held=new Promise<void>(r=>{release=r}),captured=new Promise<void>(r=>{ready=r});await tenant.route('**/api/financial-statements/'+id,async route=>{const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});const reading=execute(tenant,'society_read_financial_statement',{statement_id:id});await captured
 messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=date('now') WHERE resident_id='demo-tenant-A-103' AND end_date IS NULL\")");release();await expect(reading).rejects.toThrow();await tenant.unroute('**/api/financial-statements/'+id);await expect(tenant.getByRole('dialog')).toHaveCount(0);await expect(execute(tenant,'society_read_financial_statement',{statement_id:id})).rejects.toThrow()
 }finally{release();messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=NULL WHERE resident_id='demo-tenant-A-103'\")");await tc.close();await oc.close();await a.close()}
})

test('native statement schemas reject actions types bounds cancellation and held results from ended sessions',async({page})=>{
 await login(page);await expect.poll(()=>names(page)).toContain('society_find_financial_statements')
 for(const [tool,args] of [['society_find_financial_statements',{page:0}],['society_find_financial_statements',{page:10001}],['society_find_financial_statements',{kind:'RECEIPT'}],['society_find_financial_statements',{kind:['INCOME']}],['society_find_financial_statements',{state:'PUBLISHED'}],['society_find_financial_statements',{filename:'original.pdf'}],['society_read_financial_statement',{statement_id:''}],['society_read_financial_statement',{statement_id:'x'.repeat(101)}],['society_read_financial_statement',{statement_id:'missing',action:'PUBLISHED'}]] as const)await expect(execute(page,tool,args)).rejects.toThrow()
 const cancelled=await page.evaluate(async()=>{const c=(document as ContextDocument).modelContext,tool=(await c.getTools()).find(t=>t.name==='society_find_financial_statements')!,controller=new AbortController();controller.abort();const major=Number(navigator.userAgent.match(/Chrome\/(\d+)/)?.[1]);try{await c.executeTool(tool,major<155?'{}':{},{signal:controller.signal});return false}catch{return true}});expect(cancelled).toBe(true)
 let release!:()=>void,ready!:()=>void;const held=new Promise<void>(r=>{release=r}),captured=new Promise<void>(r=>{ready=r});await page.route('**/api/financial-statements?*',async route=>{const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});const reading=execute(page,'society_find_financial_statements',{});await captured
 try{await page.request.post('/api/auth/logout',{headers:await financialHeaders(page),data:{}});release();await expect(reading).rejects.toThrow();await expect.poll(()=>names(page)).toEqual([])}finally{release();await page.unroute('**/api/financial-statements?*')}
})
