import { test,expect } from '@playwright/test'
import { login } from './helpers'
import { names,execute } from './native-webmcp-helpers'
import type { ContextDocument } from './native-webmcp-helpers'
import { budgetActors,budgetGet,budgetPost,apiBudget,apiPaid,budgetEntry,openBudget } from './budgets-fixtures'
import { financialHeaders } from './maintenance-fixtures'
import { messagePrivateFixture } from './messages-fixtures'
import type { BudgetDetail,PaidExpenseDetail } from '../src/budgets'

test.setTimeout(90000)
const budgetTools=['society_find_budgets','society_read_budget','society_find_paid_expenses','society_read_paid_expense']
function privateFieldsExcluded(value:unknown){const text=JSON.stringify(value);for(const field of ['PRIVATE_BDG','amount_paise','collections_paise','expenses_paise','source_reference','source_note','payee','category','reference','reason','current_key','paid_date','period_start','period_end','title','125025','200000'])expect(text).not.toContain(field)}

test('actual native budget tools discover bounded private status schemas and deliberate navigation without leaking supplied figures',async({page,browser})=>{
 const a=await budgetActors(page,browser),context=await browser.newContext({baseURL:new URL(page.url()).origin}),tenant=await context.newPage()
 try{const id=await apiBudget(page,a.reviewer,1,'PRIVATE_BDG native supplied plan',2024),paid=await apiPaid(page,a.reviewer,id,1,'PRIVATE_BDG native paid source','32.51',true,2024);await expect.poll(()=>names(page)).toEqual(expect.arrayContaining(budgetTools));const metadata=JSON.parse(await execute(page,'society_read_budget',{budget_id:id}));expect(metadata).toMatchObject({id,state:'OPEN',version:2,proposal_version:1,approved_version:1,plan_version:1,comparison_available:true,paid_records:1,received_records:0,pending_expense_proposals:0});expect(Object.keys(metadata).sort()).toEqual(['id','version','state','decision','proposal_version','approved_version','plan_version','events','comparison_available','received_records','paid_records','pending_expense_proposals'].sort());privateFieldsExcluded(metadata);const expense=JSON.parse(await execute(page,'society_read_paid_expense',{expense_id:paid}));expect(expense).toMatchObject({id:paid,budget_id:id,state:'CONFIRMED',version:2,approved_version:1,original_budget_version:1,events:2});privateFieldsExcluded(expense)
 for(let i=0;i<12;i++)await apiPaid(page,a.reviewer,id,1,'PRIVATE_BDG bounded native payee '+i,'1.00',false,2024);const bounded=JSON.parse(await execute(page,'society_find_paid_expenses',{budget_id:id}));expect(bounded.total).toBe(13);expect(bounded.page_size).toBe(12);expect(bounded.items).toHaveLength(12);expect(bounded.counts).toMatchObject({pending:12,confirmed:1});privateFieldsExcluded(bounded);expect(JSON.parse(await execute(page,'society_find_paid_expenses',{budget_id:id,page:2})).items).toHaveLength(1);const found=JSON.parse(await execute(page,'society_find_budgets',{query:'PRIVATE_BDG native supplied plan'}));expect(found.items).toHaveLength(1);privateFieldsExcluded(found);await execute(page,'society_open_workspace',{screen:'budgets'});await expect(page.getByRole('heading',{name:'The operating plans.',exact:true})).toBeVisible()
 for(const [tool,args] of [['society_find_budgets',{page:0}],['society_find_budgets',{page:10001}],['society_find_budgets',{state:'PAID'}],['society_find_budgets',{action:'APPROVED'}],['society_read_budget',{budget_id:''}],['society_read_budget',{budget_id:'x'.repeat(101)}],['society_read_budget',{budget_id:id,amount:'1.00'}],['society_find_paid_expenses',{}],['society_find_paid_expenses',{budget_id:id,state:'CLOSED'}],['society_read_paid_expense',{expense_id:paid,action:'VOID'}]] as const)await expect(execute(page,tool,args)).rejects.toThrow();await login(tenant,'Tenant');expect(await names(tenant)).toEqual(expect.not.arrayContaining(budgetTools));await expect(execute(tenant,'society_read_budget',{budget_id:id})).rejects.toThrow();await expect(execute(tenant,'society_read_paid_expense',{expense_id:paid})).rejects.toThrow();await expect(execute(tenant,'society_open_workspace',{screen:'budgets'})).rejects.toThrow()
 }finally{await context.close();await a.close()}
})

test('native held budget comparison and paid detail discard changed cash and pending version sources',async({page,browser})=>{
 const a=await budgetActors(page,browser);let release=()=>{}
 try{const id=await apiBudget(page,a.reviewer,2,'PRIVATE_BDG native held source',2024),paid=await apiPaid(page,a.reviewer,id,2,'PRIVATE_BDG held original','32.51',true,2024);await expect.poll(()=>names(page)).toContain('society_read_budget');for(const kind of ['budget','expense']){let ready!:()=>void,calls=0;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r}),pattern=kind==='budget'?'**/api/budgets/'+id+'/comparison?**':'**/api/paid-expenses/'+paid;await page.route(pattern,async route=>{if(++calls>1){await route.continue();return}const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});const reading=execute(page,kind==='budget'?'society_read_budget':'society_read_paid_expense',kind==='budget'?{budget_id:id}:{expense_id:paid});await entered;if(kind==='budget')await budgetEntry(page,'0.01','2024-02-10');else{const current=await budgetGet<PaidExpenseDetail>(a.reviewer,'/api/paid-expenses/'+paid);await budgetPost(a.reviewer,'/api/paid-expenses/'+paid+'/proposals',{version:current.version,action:'CORRECTION',budget_id:id,amount:'25.01',paid_date:current.snapshot.paid_date,payee:'PRIVATE_BDG held changed payee',category:current.snapshot.category,method:current.snapshot.method,reference:current.snapshot.reference,source_note:current.snapshot.source_note,reason:'Independent source mutation invalidates the held native status.'})}release();await expect(reading).rejects.toThrow();await page.unroute(pattern)}privateFieldsExcluded(JSON.parse(await execute(page,'society_read_budget',{budget_id:id})))
 }finally{release();await a.close()}
})

test('explicit auditor reads exclude writes and expiry never inherits broad committee or personal household finance scope',async({page,browser})=>{
 const a=await budgetActors(page,browser),context=await browser.newContext({baseURL:new URL(page.url()).origin}),auditor=await context.newPage();let release=()=>{}
 try{const id=await apiBudget(page,a.reviewer,3,'PRIVATE_BDG auditor source',2024),account=await(await page.request.get('/api/admin/accounts/demo-user-owner')).json();const granted=await page.request.post('/api/admin/accounts/demo-user-owner/roles',{headers:await financialHeaders(page),data:{version:account.version,confirmed:true,reason:'Explicit fictional independent auditor for private budget checks.',role:'AUDITOR',term_days:30}});expect(granted.status(),await granted.text()).toBe(201);await login(auditor,'Owner');await expect.poll(()=>names(auditor)).toContain('society_read_budget');privateFieldsExcluded(JSON.parse(await execute(auditor,'society_read_budget',{budget_id:id})));await openBudget(auditor,id);await expect(auditor.getByRole('button',{name:'Revise plan',exact:true})).toHaveCount(0);expect((await auditor.request.post('/api/budgets/'+id+'/decisions',{headers:await financialHeaders(auditor),data:{version:2,action:'APPROVED',reason:'An auditor cannot create a finance decision.',confirmed:true,operation_key:crypto.randomUUID()}})).status()).toBe(403)
 let ready!:()=>void,calls=0;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r});await a.reviewer.route('**/api/budgets?**',async route=>{if(++calls>1){await route.continue();return}const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});const reading=execute(a.reviewer,'society_find_budgets',{});await entered;messagePrivateFixture("db.execute(\"UPDATE role_grants SET valid_from=strftime('%s','now')-172800,valid_until=strftime('%s','now')-1 WHERE user_id='demo-user-committee' AND role='TREASURER' AND revoked_at IS NULL\")");release();await expect(reading).rejects.toThrow();await a.reviewer.unroute('**/api/budgets?**');expect((await(await a.reviewer.request.get('/api/auth/me')).json()).can_read_all_records).toBe(true);await expect.poll(()=>names(a.reviewer)).not.toContain('society_find_budgets');messagePrivateFixture("db.execute(\"UPDATE role_grants SET valid_from=strftime('%s','now')-172800,valid_until=strftime('%s','now')-1 WHERE user_id='demo-user-owner' AND role='AUDITOR' AND revoked_at IS NULL\")");await expect(execute(auditor,'society_read_budget',{budget_id:id})).rejects.toThrow();await expect.poll(()=>names(auditor)).not.toContain('society_read_budget');expect((await auditor.request.get('/api/budgets/'+id)).status()).toBe(403);await expect(auditor.getByRole('dialog')).toHaveCount(0)
 }finally{release();messagePrivateFixture("db.execute(\"UPDATE role_grants SET valid_from=strftime('%s','now')-172800,valid_until=strftime('%s','now')+30*86400 WHERE user_id='demo-user-committee' AND role='TREASURER' AND revoked_at IS NULL\")");await context.close();await a.close()}
})

test('native reads preserve active human form abort before and during execution and clear tools after logout without domain writes',async({page,browser})=>{
 const a=await budgetActors(page,browser);let release=()=>{}
 try{const id=await apiBudget(page,a.reviewer,4,'PRIVATE_BDG untouched human form',2024),paid=await apiPaid(page,a.reviewer,id,4,'PRIVATE_BDG untouched native payee','32.51',true,2024);await openBudget(page,id);await page.getByRole('button',{name:'Revise plan',exact:true}).click();const marker='PRIVATE_BDG deliberately entered human text';await page.getByRole('textbox',{name:'Plan title',exact:true}).fill(marker);const writes:string[]=[];page.on('request',request=>{if(!['GET','HEAD'].includes(request.method()))writes.push(request.url())});for(const [tool,args] of [['society_find_budgets',{}],['society_read_budget',{budget_id:id}],['society_find_paid_expenses',{budget_id:id}],['society_read_paid_expense',{expense_id:paid}]] as const)privateFieldsExcluded(JSON.parse(await execute(page,tool,args)));await expect(page.getByRole('textbox',{name:'Plan title',exact:true})).toHaveValue(marker);await expect(execute(page,'society_open_workspace',{screen:'budgets'})).rejects.toThrow();expect(writes).toEqual([]);const cancelled=await page.evaluate(async()=>{const context=(document as ContextDocument).modelContext,tool=(await context.getTools()).find(t=>t.name==='society_find_budgets')!,controller=new AbortController();controller.abort();const major=Number(navigator.userAgent.match(/Chrome\/(\d+)/)?.[1]);try{await context.executeTool(tool,major<155?'{}':{},{signal:controller.signal});return false}catch{return true}});expect(cancelled).toBe(true)
 let ready!:()=>void,calls=0;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r});await page.route('**/api/budgets?**',async route=>{if(++calls>1){await route.continue();return}const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});const aborting=page.evaluate(async()=>{const context=(document as ContextDocument).modelContext,tool=(await context.getTools()).find(t=>t.name==='society_find_budgets')!,controller=new AbortController();(window as Window&{budgetAbort?:()=>void}).budgetAbort=()=>controller.abort();const major=Number(navigator.userAgent.match(/Chrome\/(\d+)/)?.[1]);try{await context.executeTool(tool,major<155?'{}':{},{signal:controller.signal});return false}catch{return true}});await entered;await page.evaluate(()=>(window as Window&{budgetAbort?:()=>void}).budgetAbort?.());release();expect(await aborting).toBe(true);await page.unroute('**/api/budgets?**');await expect(page.getByRole('textbox',{name:'Plan title',exact:true})).toHaveValue(marker);expect(writes).toEqual([]);expect((await budgetGet<BudgetDetail>(page,'/api/budgets/'+id)).version).toBe(2);const loggedOut=await page.request.post('/api/auth/logout',{headers:await financialHeaders(page),data:{}});expect(loggedOut.status()).toBe(200);await expect(execute(page,'society_find_budgets',{})).rejects.toThrow();await expect.poll(()=>names(page)).toEqual([]);await expect(page.getByRole('dialog')).toHaveCount(0)
 }finally{release();await a.close()}
})
