import { test, expect } from '@playwright/test'
import { login } from './helpers'
import { names, execute } from './native-webmcp-helpers'
import { checklistDesk } from './checklists-fixtures'
import { performanceCapture, performanceWithin, screenModule } from './performance-fixtures'

test.setTimeout(90000)
test('native registration deferred through logout cannot install stale tools and rediscovery uses the new authenticated scope',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});const module=screenModule('webmcp-register');let ready!:()=>void,release=()=>{};const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r});await page.route('**'+module,async route=>{ready();await held;await route.continue().catch(()=>{})})
 try{await login(page);await entered;await expect(page.getByRole('heading',{name:'Good things, in order.',exact:true})).toBeVisible();expect(await names(page)).toEqual([]);await expect(execute(page,'society_find_homes',{})).rejects.toThrow();await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();release();await page.unroute('**'+module);await expect.poll(()=>names(page)).toEqual([]);await expect(page.getByRole('dialog')).toHaveCount(0)
 await login(page,'Tenant');await expect.poll(()=>names(page)).toContain('society_find_homes');const homes=JSON.parse(await execute(page,'society_find_homes',{}));expect(homes.items.map((x:{id:string})=>x.id)).toEqual(['demo-flat-A-103']);expect(await names(page)).not.toContain('society_find_accounts');await execute(page,'society_open_workspace',{screen:'checklists'});await expect(page.getByRole('heading',{name:'Your requests, thoughtfully kept.',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'This screen could not be opened.',exact:true})).toHaveCount(0)
 }finally{release()}
})

test('actual native tools preserve human draft and remain current while another screen is deliberately loading',async({page})=>{
 await page.setViewportSize({width:375,height:640});await login(page);await expect.poll(()=>names(page)).toContain('society_find_move_checklists');await checklistDesk(page);await page.getByRole('button',{name:'Prepare a checklist',exact:true}).click();const marker='PRIVATE_PERF native reads preserve this supplied human draft.';await page.getByRole('textbox',{name:'Checklist explanation',exact:true}).fill(marker);const writes:string[]=[];page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))writes.push(new URL(r.url()).pathname)});const current=JSON.parse(await execute(page,'society_find_move_checklists',{}));expect(current.total).toBe(0);await expect(execute(page,'society_open_workspace',{screen:'entries'})).rejects.toThrow();await expect(page.getByRole('textbox',{name:'Checklist explanation',exact:true})).toHaveValue(marker);expect(writes).toEqual([]);await page.getByRole('button',{name:'Close checklist proposal',exact:true}).click()
 const module=screenModule('Records');let release=()=>{},ready!:()=>void;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r});await page.route('**'+module,async route=>{ready();await held;await route.continue().catch(()=>{})});try{expect(JSON.parse(await execute(page,'society_open_workspace',{screen:'entries'}))).toEqual({screen:'entries'});await entered;await expect(page.getByRole('heading',{name:'Opening this screen…',exact:true})).toBeVisible();const homes=JSON.parse(await execute(page,'society_find_homes',{page:1}));expect(homes.total).toBe(118);expect(homes.items).toHaveLength(12);const overview=JSON.parse(await execute(page,'society_read_overview',{section:'finance'}));expect(overview.counts.received_paise).toBe(0);await performanceCapture(page,'native-current-tools-during-load-375-640');await performanceWithin(page);expect(writes).toEqual([]);await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();release();await page.unroute('**'+module);await expect.poll(()=>names(page)).toEqual([]);await expect(page.getByRole('dialog')).toHaveCount(0);expect(writes).toEqual(['/api/auth/logout']);await expect(page.locator('body')).not.toContainText(marker)
 }finally{release()}
})
