import { test, expect } from '@playwright/test'
import { names, execute } from './native-webmcp-helpers'
import type { ContextDocument } from './native-webmcp-helpers'
import { financialHeaders } from './maintenance-fixtures'
import { messagePrivateFixture } from './messages-fixtures'
import { checklistActors, checklistGet, apiChecklist, apiChecklistAction, readyChecklist, openChecklist } from './checklists-fixtures'
import type { ChecklistDetail } from '../src/checklists'

test.setTimeout(90000)
const tools=['society_find_move_checklists','society_read_move_checklist']
function privateFieldsExcluded(value:unknown){for(const key of ['PRIVATE_CHK','person_name','resident_id','flat_id','home_label','effective_date','reference','reason','source_key','membership_key','checked_by','ready_by','actor','note','snapshot','source','can_check','can_complete'])expect(JSON.stringify(value)).not.toContain(key)}

test('native checklist metadata is bounded private validated scoped and navigates to the actual desk',async({page,browser})=>{
 const a=await checklistActors(page,browser)
 try{const id=await apiChecklist(a.owner,'PRIVATE_CHK native completed record');await readyChecklist(page,id);await apiChecklistAction(a.reviewer,id,'APPROVED');await expect.poll(()=>names(page)).toEqual(expect.arrayContaining(tools));const detail=JSON.parse(await execute(page,'society_read_move_checklist',{checklist_id:id}));expect(detail).toMatchObject({id,kind:'MOVE_IN',phase:'COMPLETED',state:'COMPLETED',version:8,pending:false,approved_version:8,checked_items:3,not_applicable_items:2,checks_needing_review:0,events:8});privateFieldsExcluded(detail)
 for(let i=0;i<12;i++)await apiChecklist(a.owner,'PRIVATE_CHK native bounded '+i);const found=JSON.parse(await execute(a.owner,'society_find_move_checklists',{}));expect(found).toMatchObject({total:13,page_size:12,counts:{checking:12,completed:1}});expect(found.items).toHaveLength(12);privateFieldsExcluded(found);expect(JSON.parse(await execute(a.owner,'society_find_move_checklists',{page:2})).items).toHaveLength(1);const filtered=JSON.parse(await execute(a.owner,'society_find_move_checklists',{query:'PRIVATE_CHK native completed record'}));expect(filtered.total).toBe(1);expect(filtered.counts.checking).toBe(12);privateFieldsExcluded(filtered)
 for(const [tool,args] of [['society_find_move_checklists',{page:0}],['society_find_move_checklists',{page:10001}],['society_find_move_checklists',{state:'PAID'}],['society_find_move_checklists',{action:'APPROVED'}],['society_find_move_checklists',{query:'x'.repeat(101)}],['society_read_move_checklist',{}],['society_read_move_checklist',{checklist_id:''}],['society_read_move_checklist',{checklist_id:'x'.repeat(101)}],['society_read_move_checklist',{checklist_id:id,reference:'private'}]] as const)await expect(execute(page,tool,args)).rejects.toThrow()
 expect(JSON.parse(await execute(a.tenant,'society_find_move_checklists',{})).total).toBe(0);await expect(execute(a.tenant,'society_read_move_checklist',{checklist_id:id})).rejects.toThrow();await execute(page,'society_open_workspace',{screen:'checklists'});await expect(page.getByRole('heading',{name:'The checklist desk.',exact:true})).toBeVisible()
 }finally{await a.close()}
})

test('native held checklist reads discard registry contact and proposal changes',async({page,browser})=>{
 const a=await checklistActors(page,browser);let release=()=>{}
 try{const id=await apiChecklist(a.owner,'PRIVATE_CHK native held context');for(const kind of ['registry','contact','proposal']){let ready!:()=>void,calls=0;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r}),pattern='**/api/move-checklists/'+id;await page.route(pattern,async route=>{if(++calls>1){await route.continue();return}const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});const reading=execute(page,'society_read_move_checklist',{checklist_id:id});await entered
 if(kind==='registry')messagePrivateFixture("db.execute(\"UPDATE flats SET version=version+1 WHERE id='demo-flat-A-101'\")")
 else if(kind==='contact'){const c=await checklistGet<{version:number}>(a.owner,'/api/contacts/me');const r=await a.owner.request.post('/api/contacts/me/register',{headers:await financialHeaders(a.owner),data:{operation_key:crypto.randomUUID(),confirmed:true,version:c.version,phone:'+919000000901',email:'checklist-native@example.test',preferred_channel:'EMAIL',community_whatsapp:false,community_email:true,finance_whatsapp:false,finance_email:false,consent_source:'PRIVATE_CHK separately supplied current profile choices.',reason:'PRIVATE_CHK actual profile change invalidates a held source.'}});expect(r.status(),await r.text()).toBe(200)}
 else await apiChecklistAction(a.owner,id,'REVISE',{effective_date:'2026-10-16',note:'PRIVATE_CHK deliberate changed supplied proposal.'})
 release();await expect(reading).rejects.toThrow();await page.unroute(pattern)}privateFieldsExcluded(JSON.parse(await execute(page,'society_read_move_checklist',{checklist_id:id})))
 }finally{release();await a.close()}
})

test('native authority rechecks discard ended household and expired staff results while retaining limited own history',async({page,browser})=>{
 const a=await checklistActors(page,browser);let release=()=>{}
 try{const own=await apiChecklist(a.owner,'PRIVATE_CHK own limited outcome'),staff=await apiChecklist(a.reviewer,'PRIVATE_CHK staff private case','demo-flat-A-103','demo-tenant-A-103');await openChecklist(a.owner,own)
 for(const target of [a.owner,a.reviewer]){const id=target===a.owner?own:staff;let ready!:()=>void,calls=0;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r}),pattern='**/api/move-checklists/'+id;await target.route(pattern,async route=>{if(++calls>1){await route.continue();return}const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});const reading=execute(target,'society_read_move_checklist',{checklist_id:id});await entered
 if(target===a.owner)messagePrivateFixture("r=db.execute(\"UPDATE flat_memberships SET end_date='2026-01-01' WHERE resident_id='demo-owner-A-101'\");assert r.rowcount==2")
 else messagePrivateFixture("db.execute(\"UPDATE role_grants SET valid_from=strftime('%s','now')-172800,valid_until=strftime('%s','now')-1 WHERE user_id='demo-user-committee' AND role='ADMINISTRATOR' AND revoked_at IS NULL\")")
 release();await expect(reading).rejects.toThrow();await target.unroute(pattern)}
 await expect(a.owner.getByRole('dialog')).toHaveCount(0);await expect.poll(()=>names(a.owner)).toEqual(expect.arrayContaining(tools));privateFieldsExcluded(JSON.parse(await execute(a.owner,'society_read_move_checklist',{checklist_id:own})));await expect(execute(a.owner,'society_read_move_checklist',{checklist_id:staff})).rejects.toThrow();const former=await checklistGet<ChecklistDetail>(a.owner,'/api/move-checklists/'+own);expect(former.source.home_label).toBe('');expect(former.can_open_home).toBe(false);expect(former.can_cancel).toBe(true)
 await expect.poll(()=>names(a.reviewer)).toEqual(expect.not.arrayContaining(tools));const me=await checklistGet<{can_read_all_records:boolean;can_read_checklists:boolean}>(a.reviewer,'/api/auth/me');expect(me.can_read_all_records).toBe(true);expect(me.can_read_checklists).toBe(false);await expect(execute(a.reviewer,'society_open_workspace',{screen:'checklists'})).rejects.toThrow();expect((await a.reviewer.request.get('/api/move-checklists/'+staff)).status()).toBe(403)
 }finally{release();messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=NULL WHERE resident_id='demo-owner-A-101'\");db.execute(\"UPDATE role_grants SET valid_from=strftime('%s','now')-172800,valid_until=strftime('%s','now')+30*86400 WHERE user_id='demo-user-committee' AND role='ADMINISTRATOR' AND revoked_at IS NULL\")");await a.close()}
})

test('native checklist reads preserve active human form abort in flight and unregister on logout without domain writes',async({page,browser})=>{
 const a=await checklistActors(page,browser);let release=()=>{}
 try{const id=await apiChecklist(a.owner,'PRIVATE_CHK native active human form');await openChecklist(a.owner,id);await a.owner.getByRole('button',{name:'Revise request',exact:true}).click();const marker='PRIVATE_CHK human text stays in this unfinished proposal.';await a.owner.getByRole('textbox',{name:'Checklist explanation',exact:true}).fill(marker);const writes:string[]=[];a.owner.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))writes.push(r.url())});for(const [tool,args] of [[tools[0],{}],[tools[1],{checklist_id:id}]] as const)privateFieldsExcluded(JSON.parse(await execute(a.owner,tool,args)));await expect(execute(a.owner,'society_open_workspace',{screen:'checklists'})).rejects.toThrow();await expect(a.owner.getByRole('textbox',{name:'Checklist explanation',exact:true})).toHaveValue(marker);expect(writes).toEqual([])
 const before=await a.owner.evaluate(async()=>{const c=(document as ContextDocument).modelContext,t=(await c.getTools()).find(t=>t.name==='society_find_move_checklists')!,ac=new AbortController();ac.abort();try{await c.executeTool(t,Number(navigator.userAgent.match(/Chrome\/(\d+)/)?.[1])<155?'{}':{},{signal:ac.signal});return false}catch{return true}});expect(before).toBe(true)
 let ready!:()=>void,calls=0;const entered=new Promise<void>(r=>{ready=r}),held=new Promise<void>(r=>{release=r});await a.owner.route('**/api/move-checklists?**',async route=>{if(++calls>1){await route.continue();return}const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});const reading=a.owner.evaluate(async()=>{const c=(document as ContextDocument).modelContext,t=(await c.getTools()).find(t=>t.name==='society_find_move_checklists')!,ac=new AbortController();(window as Window&{checklistAbort?:()=>void}).checklistAbort=()=>ac.abort();try{await c.executeTool(t,Number(navigator.userAgent.match(/Chrome\/(\d+)/)?.[1])<155?'{}':{},{signal:ac.signal});return false}catch{return true}});await entered;await a.owner.evaluate(()=>(window as Window&{checklistAbort?:()=>void}).checklistAbort?.());release();expect(await reading).toBe(true);await a.owner.unroute('**/api/move-checklists?**');await expect(a.owner.getByRole('textbox',{name:'Checklist explanation',exact:true})).toHaveValue(marker);expect(writes).toEqual([]);expect((await checklistGet<ChecklistDetail>(a.owner,'/api/move-checklists/'+id)).version).toBe(1);expect((await a.owner.request.post('/api/auth/logout',{headers:await financialHeaders(a.owner),data:{}})).status()).toBe(200);await expect(execute(a.owner,tools[0],{})).rejects.toThrow();await expect.poll(()=>names(a.owner)).toEqual([]);await expect(a.owner.getByRole('dialog')).toHaveCount(0)
 }finally{release();await a.close()}
})
