import { test,expect } from '@playwright/test'
import { login,navigate } from './helpers'
import { names,execute } from './native-webmcp-helpers'
import type { ContextDocument } from './native-webmcp-helpers'
import { messageActors,messagePrivateFixture } from './messages-fixtures'
import { meetingApprove,meetingDetail,meetingPost,meetingProposal } from './meetings-fixtures'

test.setTimeout(120000)
test('actual native meeting discovery exposes bounded published metadata and preserves an open human form',async({page,browser})=>{
 const actors=await messageActors(page,browser)
 try{
  const quiet={start_at:Math.floor(Date.now()/1000)+31*86400,end_at:0,ack_required:false,ack_deadline:0}
  const id=await meetingProposal(page,'PRIVATE_NATIVE_MEETING deliberately supplied agenda',quiet);await meetingApprove(actors.reviewer,id);const pending=await meetingProposal(page,'PRIVATE_NATIVE_MEETING unpublished proposal',quiet)
  await expect.poll(()=>names(page)).toContain('society_read_meeting');expect((await names(page)).filter(x=>x==='society_find_meetings'||x==='society_read_meeting').sort()).toEqual(['society_find_meetings','society_read_meeting']);await execute(page,'society_open_workspace',{screen:'meetings'});await expect(page.getByRole('heading',{name:'Dates worth keeping.',exact:true})).toBeVisible();await page.getByRole('button',{name:'Prepare a meeting',exact:true}).click();await page.getByLabel('Meeting title',{exact:true}).fill('Keep this human meeting title');await page.getByLabel('Private meeting proposal reason',{exact:true}).fill('PRIVATE_NATIVE_MEETING human reason to preserve')
  const writes:string[]=[];const listener=(r:{method:()=>string;url:()=>string})=>{if(!['GET','HEAD'].includes(r.method()))writes.push(r.url())};page.on('request',listener)
  const metadata=JSON.parse(await execute(page,'society_read_meeting',{meeting_id:id}));expect(Object.keys(metadata).sort()).toEqual(['id','state','version','start_at','end_at','held_at','homes_count','published_at','acknowledgement_required','acknowledged','acknowledgement_deadline'].sort());expect(metadata).toMatchObject({id,state:'UPCOMING',version:1,end_at:0,held_at:0,homes_count:118,acknowledgement_required:false,acknowledged:false,acknowledgement_deadline:0})
  for(const secret of ['PRIVATE_NATIVE_MEETING','PRIVATE_MEETING','body','minutes','location','fingerprint','reason','submitted_by','resident_id','title','events'])expect(JSON.stringify(metadata)).not.toContain(secret)
  const found=JSON.parse(await execute(page,'society_find_meetings',{}));expect(found.total).toBe(1);expect(found.items).toEqual([metadata]);expect(found.page_size).toBe(12);await expect(execute(page,'society_read_meeting',{meeting_id:pending})).rejects.toThrow();await expect(page.getByLabel('Meeting title',{exact:true})).toHaveValue('Keep this human meeting title');await expect(page.getByRole('textbox',{name:'Private meeting proposal reason',exact:true})).toHaveValue('PRIVATE_NATIVE_MEETING human reason to preserve');await expect(execute(page,'society_open_workspace',{screen:'overview'})).rejects.toThrow()
  for(const [tool,args] of [['society_find_meetings',{page:0}],['society_find_meetings',{page:10001}],['society_find_meetings',{state:'PENDING'}],['society_find_meetings',{desk:true}],['society_find_meetings',{resident_id:'another-person'}],['society_read_meeting',{meeting_id:''}],['society_read_meeting',{meeting_id:'x'.repeat(101)}],['society_read_meeting',{meeting_id:id,action:'ACKNOWLEDGE'}],['society_read_meeting',{meeting_id:id,fingerprint:'a'.repeat(64)}]] as const)await expect(execute(page,tool,args)).rejects.toThrow()
  expect(writes).toEqual([]);page.off('request',listener);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)
  for(let i=0;i<12;i++){const next=await meetingProposal(page,'PRIVATE_NATIVE_MEETING bounded agenda '+i,quiet);await meetingApprove(actors.reviewer,next)}const bounded=JSON.parse(await execute(page,'society_find_meetings',{}));expect(bounded.total).toBe(13);expect(bounded.items).toHaveLength(12);expect(JSON.parse(await execute(page,'society_find_meetings',{page:2})).items).toHaveLength(1);messagePrivateFixture("assert db.execute('SELECT COUNT(*) FROM meeting_acknowledgements').fetchone()[0]==0;assert db.execute('SELECT COUNT(*) FROM entries').fetchone()[0]==0")
 }finally{await actors.close()}
})

test('native meeting reads deny cross-home access honor abort and discard held results after membership or publication ends',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage(),tc=await browser.newContext({baseURL:new URL(page.url()).origin}),tenant=await tc.newPage();let release=()=>{}
 try{
  const id=await meetingProposal(page,'PRIVATE_NATIVE_MEETING current home',{scope:'HOMES',home_ids:['demo-flat-A-101']});await meetingApprove(actors.reviewer,id);await login(owner,'Owner');await login(tenant,'Tenant');await expect.poll(()=>names(owner)).toContain('society_read_meeting');await expect(execute(tenant,'society_read_meeting',{meeting_id:id})).rejects.toThrow();expect(JSON.parse(await execute(owner,'society_read_meeting',{meeting_id:id})).homes_count).toBe(1)
  const aborted=await owner.evaluate(async()=>{const c=(document as ContextDocument).modelContext,tool=(await c.getTools()).find(t=>t.name==='society_find_meetings')!,controller=new AbortController();controller.abort();const major=Number(navigator.userAgent.match(/Chrome\/(\d+)/)?.[1]);try{await c.executeTool(tool,major<155?'{}':{},{signal:controller.signal});return false}catch{return true}});expect(aborted).toBe(true);console.info('Meeting native: abort and cross-home checks complete')
  let ready!:()=>void;let held=new Promise<void>(r=>{release=r}),captured=new Promise<void>(r=>{ready=r});await owner.route('**/api/meetings/'+id,async route=>{const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});let reading=execute(owner,'society_read_meeting',{meeting_id:id});await captured;messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=date('now','+330 minutes') WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101' AND end_date IS NULL\")");release();await expect(reading).rejects.toThrow();console.info('Meeting native: held membership result discarded');await owner.unroute('**/api/meetings/'+id);await expect(execute(owner,'society_read_meeting',{meeting_id:id})).rejects.toThrow();messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=NULL WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101'\")");await owner.reload();await expect.poll(()=>names(owner)).toContain('society_read_meeting')
  const pub=await meetingDetail(owner,id,false);await meetingPost(owner,'/api/meetings/'+id+'/acknowledgements',{version:pub.version,fingerprint:pub.acknowledgement.fingerprint});expect(JSON.parse(await execute(owner,'society_read_meeting',{meeting_id:id})).acknowledged).toBe(true);console.info('Meeting native: own acknowledgement metadata complete');expect(JSON.parse(await execute(tenant,'society_find_meetings',{})).items.every((x:{id:string})=>x.id!==id)).toBe(true)
  held=new Promise<void>(r=>{release=r});captured=new Promise<void>(r=>{ready=r});let calls=0;await owner.route('**/api/meetings/'+id,async route=>{if(++calls>1){await route.continue();return}const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});reading=execute(owner,'society_read_meeting',{meeting_id:id});await captured;await meetingPost(page,'/api/meetings/'+id+'/proposals',{version:2,action:'WITHDRAW',reason:'PRIVATE_NATIVE_MEETING withdraw this exact publication while its read is held'});await meetingApprove(actors.reviewer,id);console.info('Meeting native: publication withdrawn before held result');release();await expect(reading).rejects.toThrow();console.info('Meeting native: held publication result discarded');await owner.unroute('**/api/meetings/'+id);await expect(execute(owner,'society_read_meeting',{meeting_id:id})).rejects.toThrow()
 }finally{release();messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=NULL WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101'\")");await Promise.allSettled([actors.close(),oc.close(),tc.close()])}
})

test('native meeting overview keeps full current counts bounded rows and private wording out of metadata',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage()
 try{
  for(let i=0;i<5;i++){const id=await meetingProposal(page,'PRIVATE_NATIVE_MEETING upcoming '+i);await meetingApprove(actors.reviewer,id)}
  const now=Math.floor(Date.now()/1000),past=await meetingProposal(page,'PRIVATE_NATIVE_MEETING past acknowledgement',{start_at:now-3600,end_at:now-1800});await meetingApprove(actors.reviewer,past);const far=await meetingProposal(page,'PRIVATE_NATIVE_MEETING far acknowledgement',{start_at:now+40*86400,end_at:0});await meetingApprove(actors.reviewer,far)
  await login(owner,'Owner');const overview=JSON.parse(await execute(owner,'society_read_overview',{section:'meetings'}));expect(overview.counts).toMatchObject({upcoming:5,acknowledgements_needed:7,attention_items:7,needs_your_decision:0,awaiting_other_reviewer:0});expect(overview.items).toHaveLength(4);for(const row of overview.items){expect(Object.keys(row).sort()).toEqual(['id','kind','state','at'].sort());expect(row.state).toBe('ACKNOWLEDGEMENT')};for(const field of ['PRIVATE_NATIVE_MEETING','body','minutes','location','fingerprint','reason','homes','submitted_by','title'])expect(JSON.stringify(overview)).not.toContain(field)
  const privileged=JSON.parse(await execute(actors.reviewer,'society_read_overview',{section:'meetings'}));expect(privileged.counts).toMatchObject({upcoming:5,acknowledgements_needed:0,needs_your_decision:1,attention_items:6});expect(privileged.items).toHaveLength(4);await navigate(owner,'Community');await owner.getByRole('link',{name:'Meetings & minutes',exact:true}).click();await execute(owner,'society_open_workspace',{screen:'overview'});await expect(owner.getByRole('heading',{name:'Good things, in order.',exact:true})).toBeVisible()
 }finally{await actors.close();await oc.close()}
})

test('native held meeting lists and Overview discard results when publication changes',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage();let release=()=>{}
 try{
  await login(owner,'Owner')
  for(const tool of ['society_find_meetings','society_read_overview']){
   const id=await meetingProposal(page,'PRIVATE_NATIVE_MEETING held source '+tool,{ack_required:false,ack_deadline:0});await meetingApprove(actors.reviewer,id);let ready!:()=>void;const held=new Promise<void>(r=>{release=r}),captured=new Promise<void>(r=>{ready=r});const pattern=tool==='society_find_meetings'?'**/api/meetings?**':'**/api/overview/meetings';let calls=0
   await owner.route(pattern,async route=>{if(++calls>1){await route.continue();return}const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});const reading=execute(owner,tool,tool==='society_find_meetings'?{}:{section:'meetings'});await captured;await meetingPost(page,'/api/meetings/'+id+'/proposals',{version:2,action:'WITHDRAW',reason:'PRIVATE_NATIVE_MEETING withdraw the current source while bounded metadata is held'});await meetingApprove(actors.reviewer,id);release();await expect(reading).rejects.toThrow();await owner.unroute(pattern)
  }
 }finally{release();await Promise.allSettled([actors.close(),oc.close()])}
})
