import { test,expect } from '@playwright/test'
import { login,navigate } from './helpers'
import { names,execute } from './native-webmcp-helpers'
import type { ContextDocument } from './native-webmcp-helpers'
import { messageActors,messagePrivateFixture } from './messages-fixtures'
import { communityApprove,communityDetail,communityPost,communityProposal } from './community-fixtures'

test.setTimeout(90000)
test('actual native service tools expose bounded published status only and preserve the human preparation form',async({page,browser})=>{
 const actors=await messageActors(page,browser)
 try{
  const id=await communityProposal(page,'NATIVE COMMUNITY supplied private directory');await communityApprove(actors.reviewer,id);const pending=await communityProposal(page,'PRIVATE_NATIVE_PENDING retained draft');await expect.poll(()=>names(page)).toContain('society_read_community_update');expect((await names(page)).filter(x=>x.includes('community_update')).sort()).toEqual(['society_find_community_updates','society_read_community_update'])
  await navigate(page,'Community');await page.getByRole('link',{name:'Publication desk',exact:true}).click();await page.getByRole('button',{name:'Prepare an update',exact:true}).click();await page.getByLabel('Update title',{exact:true}).fill('Keep this human service title unchanged');await page.getByLabel('Private proposal reason',{exact:true}).fill('PRIVATE_NATIVE form supplied by this human');const writes:string[]=[];const listener=(r:{method:()=>string;url:()=>string})=>{if(!['GET','HEAD'].includes(r.method())||r.url().startsWith('tel:'))writes.push(r.url())};page.on('request',listener)
  const metadata=JSON.parse(await execute(page,'society_read_community_update',{update_id:id}));expect(Object.keys(metadata).sort()).toEqual(['id','kind','service','state','version','start_at','estimated_end','resolved_at','homes_count','published_at'].sort());expect(metadata).toMatchObject({id,kind:'CONTACT',service:'WATER',state:'AVAILABLE',version:1,homes_count:118,start_at:0,estimated_end:0,resolved_at:0});for(const field of ['phone','body','title','attestation','reason','submitted_by','homes','events'])expect(metadata).not.toHaveProperty(field);for(const secret of ['PRIVATE_COMMUNITY','9000000101'])expect(JSON.stringify(metadata)).not.toContain(secret)
  const found=JSON.parse(await execute(page,'society_find_community_updates',{}));expect(found.total).toBe(1);expect(found.items).toEqual([metadata]);expect(found.page_size).toBe(12);await expect(execute(page,'society_read_community_update',{update_id:pending})).rejects.toThrow();await expect(page.getByLabel('Update title',{exact:true})).toHaveValue('Keep this human service title unchanged');await expect(page.getByRole('textbox',{name:'Private proposal reason',exact:true})).toHaveValue('PRIVATE_NATIVE form supplied by this human');await expect(execute(page,'society_open_workspace',{screen:'overview'})).rejects.toThrow()
  for(const [tool,args] of [['society_find_community_updates',{page:0}],['society_find_community_updates',{page:10001}],['society_find_community_updates',{kind:'PRIVATE'}],['society_find_community_updates',{state:'PENDING'}],['society_find_community_updates',{desk:true}],['society_find_community_updates',{phone:'+919000000101'}],['society_read_community_update',{update_id:''}],['society_read_community_update',{update_id:'x'.repeat(101)}],['society_read_community_update',{update_id:id,action:'RESOLVE'}]] as const)await expect(execute(page,tool,args)).rejects.toThrow();expect(writes).toEqual([]);page.off('request',listener);await page.keyboard.press('Escape')
  for(let i=0;i<12;i++){const next=await communityProposal(page,'NATIVE COMMUNITY bounded directory '+i);await communityApprove(actors.reviewer,next)}const bounded=JSON.parse(await execute(page,'society_find_community_updates',{kind:'CONTACT'}));expect(bounded.total).toBe(13);expect(bounded.items).toHaveLength(12);expect(JSON.parse(await execute(page,'society_find_community_updates',{page:2})).items).toHaveLength(1);messagePrivateFixture("assert db.execute('SELECT COUNT(*) FROM receipts').fetchone()[0]==0;assert db.execute('SELECT COUNT(*) FROM message_batches').fetchone()[0]==0")
 }finally{await actors.close()}
})
test('native service reads honor abort deny cross-home access and discard held metadata after current membership ends',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage(),tc=await browser.newContext({baseURL:new URL(page.url()).origin}),tenant=await tc.newPage();let release=()=>{}
 try{
  const id=await communityProposal(page,'NATIVE COMMUNITY current-home contact','CONTACT','HOMES',['demo-flat-A-101']);await communityApprove(actors.reviewer,id);await login(owner,'Owner');await login(tenant,'Tenant');await expect.poll(()=>names(owner)).toContain('society_read_community_update');await expect(execute(tenant,'society_read_community_update',{update_id:id})).rejects.toThrow();expect(JSON.parse(await execute(owner,'society_read_community_update',{update_id:id})).homes_count).toBe(1)
  const aborted=await owner.evaluate(async()=>{const c=(document as ContextDocument).modelContext,tool=(await c.getTools()).find(t=>t.name==='society_find_community_updates')!,controller=new AbortController();controller.abort();const major=Number(navigator.userAgent.match(/Chrome\/(\d+)/)?.[1]);try{await c.executeTool(tool,major<155?'{}':{},{signal:controller.signal});return false}catch{return true}});expect(aborted).toBe(true)
  let ready!:()=>void;const held=new Promise<void>(r=>{release=r}),captured=new Promise<void>(r=>{ready=r});await owner.route('**/api/community/'+id,async route=>{const response=await route.fetch();ready();await held;await route.fulfill({response}).catch(()=>{})});const reading=execute(owner,'society_read_community_update',{update_id:id});await captured;messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=date('now') WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101' AND end_date IS NULL\")");release();await expect(reading).rejects.toThrow();await owner.unroute('**/api/community/'+id);await expect(execute(owner,'society_read_community_update',{update_id:id})).rejects.toThrow();expect(JSON.parse(await execute(owner,'society_find_community_updates',{kind:'CONTACT'})).items.every((x:{id:string})=>x.id!==id)).toBe(true)
 }finally{release();messagePrivateFixture("db.execute(\"UPDATE flat_memberships SET end_date=NULL WHERE resident_id='demo-owner-A-101' AND flat_id='demo-flat-A-101'\")");await actors.close();await oc.close();await tc.close()}
})
test('native community overview counts only started unresolved publications and omits wording contacts and private decisions',async({page,browser})=>{
 const actors=await messageActors(page,browser),oc=await browser.newContext({baseURL:new URL(page.url()).origin}),owner=await oc.newPage()
 try{
  for(let i=0;i<5;i++){const id=await communityProposal(page,'NATIVE COMMUNITY active water '+i,'INTERRUPTION');await communityApprove(actors.reviewer,id)}
  const options=await(await page.request.get('/api/community/options')).json();const now=Math.floor(Date.now()/1000);const future=(await communityPost(page,'/api/community',{kind:'INTERRUPTION',action:'PUBLISH',title:'PRIVATE_NATIVE future interruption title',body:'A fictional planned event must stay outside current active attention.',service:'POWER',scope:'ALL',area_key:options.area_key,start_at:now+3600,estimated_end:0,reason:'PRIVATE_NATIVE exact future timing supplied'})).id;await communityApprove(actors.reviewer,future)
  const resolved=await communityProposal(page,'NATIVE COMMUNITY restored lift','INTERRUPTION');await communityApprove(actors.reviewer,resolved);await communityPost(page,'/api/community/'+resolved+'/proposals',{version:2,action:'RESOLVE',resolved_at:now-30,update_text:'PRIVATE_NATIVE explicitly supplied public restoration update.',reason:'PRIVATE_NATIVE exact restoration supplied'});await communityApprove(actors.reviewer,resolved)
  await login(owner,'Owner');const overview=JSON.parse(await execute(owner,'society_read_overview',{section:'community'}));expect(overview.counts).toMatchObject({active:5,update_needed:5,needs_your_decision:0,awaiting_other_reviewer:0});expect(overview.items).toHaveLength(4);for(const row of overview.items){expect(Object.keys(row).sort()).toEqual(['id','kind','state','at'].sort());expect(row.state).toBe('UPDATE_NEEDED')};for(const field of ['PRIVATE_NATIVE','phone','body','title','reason','homes','submitted_by'])expect(JSON.stringify(overview)).not.toContain(field)
  const pending=await communityDetail(page,(await(await page.request.get('/api/community?desk=true&state=PENDING')).json()).items[0].id);expect(pending.state).toBe('PENDING');const privileged=JSON.parse(await execute(actors.reviewer,'society_read_overview',{section:'community'}));expect(privileged.counts.needs_your_decision).toBe(1);expect(privileged.items).toHaveLength(4);messagePrivateFixture("assert db.execute('SELECT COUNT(*) FROM receipts').fetchone()[0]==0;assert db.execute('SELECT COUNT(*) FROM simulation_messages').fetchone()[0]==0")
 }finally{await actors.close();await oc.close()}
})
