// Read-only UI/HTTP measurement on an isolated fictional database and pinned pair.
import { spawn, execFileSync } from 'node:child_process'
import { mkdtempSync, mkdirSync, openSync, closeSync, rmSync, readdirSync, readFileSync, writeFileSync, chmodSync, copyFileSync } from 'node:fs'
import { tmpdir, platform, arch, cpus } from 'node:os'
import { resolve, join } from 'node:path'
import { createServer } from 'node:net'
import { createRequire } from 'node:module'
import { createHash } from 'node:crypto'
import { completePreviewMFA, navigate } from '../web/tests/helpers.ts'

const require=createRequire(resolve('web/package.json')),{chromium}=require('@playwright/test')
const args=Object.fromEntries(process.argv.slice(2).map(arg=>{const split=arg.indexOf('=');if(!arg.startsWith('--')||split<0)throw new Error('Use --release=local/path --out=local/path --samples=5');return[arg.slice(2,split),arg.slice(split+1)]}))
if(Object.keys(args).some(key=>!['release','out','samples'].includes(key))||!args.release||!args.out)throw new Error('Explicit local pinned release and output are required.')
const release=resolve(args.release),destination=resolve(args.out),samples=Number(args.samples??5)
if(!Number.isInteger(samples)||samples<3||samples>10||!release.startsWith(resolve('var/preview-releases')+'/')||!destination.startsWith(resolve('reports/local')+'/'))throw new Error('Require3–10 samples, a pinned local release, and private local report.')
const sha=path=>createHash('sha256').update(readFileSync(path)).digest('hex'),walk=path=>readdirSync(path,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?walk(join(path,entry.name)):[join(path,entry.name)]),runtime=Object.fromEntries(walk(release).map(path=>[path.slice(release.length+1),sha(path)]))
const record={started_at_utc:new Date().toISOString(),release,version:JSON.parse(execFileSync(join(release,'society-server'),['version'],{encoding:'utf8'})),git_head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),runtime_sha256:runtime,samples,environment:{platform:platform(),arch:arch(),cpu:cpus()[0].model,node:process.version,viewport:{width:1440,height:1000},service_workers:'blocked',cold_cache_disabled:true,warm_cache_primed_once:true},runs:[],limitations:'Synthetic macOS development measurements; no actual Windows/8GB host, production network, constrained CPU or population beyond118homes claim. Timing descriptive; correctness and byte/request boundaries separate. Authentication uses real password/MFA and is reported separately.'}
const temporary=mkdtempSync(join(tmpdir(),'society-performance-')),db=join(temporary,'society.db'),reservation=createServer();await new Promise((ok,no)=>{reservation.once('error',no);reservation.listen(0,'127.0.0.1',ok)});const port=reservation.address().port;await new Promise(ok=>reservation.close(ok));const base='http://127.0.0.1:'+port,log=openSync(join(temporary,'server.log'),'wx',0o600)
let server,browser
const started=performance.now(),timed=async fn=>{const tick=performance.now();await fn();return performance.now()-tick}
const resourceMetrics=page=>page.evaluate(()=>({navigation:performance.getEntriesByType('navigation').map(e=>({dom_interactive:e.domInteractive,dom_content_loaded:e.domContentLoadedEventEnd,load:e.loadEventEnd,encoded_body:e.encodedBodySize,decoded_body:e.decodedBodySize,transfer:e.transferSize})),javascript:performance.getEntriesByType('resource').filter(e=>new URL(e.name).pathname.endsWith('.js')).map(e=>({path:new URL(e.name).pathname,encoded_body:e.encodedBodySize,decoded_body:e.decodedBodySize,transfer:e.transferSize,duration:e.duration}))}))
try{
 execFileSync(join(release,'society-server'),['seed-demo','--demo','--db',db],{stdio:'ignore'});server=spawn(join(release,'society-server'),['serve','--demo','--db',db,'--mfa-key-file',join(temporary,'mfa.key'),'--addr','127.0.0.1:'+port,'--web-dir',join(release,'web')],{stdio:['ignore',log,log]})
 for(let attempts=0;;attempts++){try{if((await fetch(base+'/ready')).ok)break}catch{}if(attempts>150||server.exitCode!==null)throw new Error('Isolated measurement server failed.');await new Promise(ok=>setTimeout(ok,100))}
 browser=await chromium.launch({headless:true});record.environment.browser=browser.version();record.fixture={homes:118,fictional:true,isolated:true}
 for(let i=0;i<samples;i++){
  const context=await browser.newContext({baseURL:base,viewport:record.environment.viewport,serviceWorkers:'block'}),page=await context.newPage(),client=await context.newCDPSession(page),writes=[]
  page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))writes.push(new URL(r.url()).pathname)})
  try{
   await client.send('Network.enable');await client.send('Network.setCacheDisabled',{cacheDisabled:true});await client.send('Network.clearBrowserCache')
   const cold_signin_ms=await timed(async()=>{await page.goto('/');await page.getByRole('button',{name:'Sign in',exact:true}).waitFor({state:'visible'});await page.evaluate(()=>document.fonts.ready)})
   const signin=await resourceMetrics(page),authentication_ms=await timed(async()=>{await page.getByRole('button',{name:/^Registry officer/}).click();const response=page.waitForResponse(r=>r.url().endsWith('/api/auth/login'));await page.getByRole('button',{name:'Sign in',exact:true}).click();if((await response).status()!==200)throw new Error('Fictional password sign-in failed.');await page.getByRole('button',{name:'Sign in',exact:true}).waitFor({state:'hidden'});await completePreviewMFA(page);await page.getByRole('button',{name:'Sign out',exact:true}).waitFor({state:'visible'})});const overview_data_ready_ms=await timed(async()=>{await page.getByRole('heading',{name:'Good things, in order.',exact:true}).waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('.overview-source-state'))}),overview=await resourceMetrics(page)
   const routes=[];for(const [label,paths] of [['Homes & people',['/api/flats']],['Maintenance',['/api/maintenance']],['Collections',['/api/collections']],['Community',['/api/notices','/api/community','/api/meetings']],['Statements',['/api/financial-statements','/api/budgets']],['Entries',['/api/entries']],['Rules & conduct',['/api/rules','/api/incidents','/api/incident-notices']]] ){
    const before=new Set((await resourceMetrics(page)).javascript.map(x=>x.path)),loaded=page.waitForResponse(r=>paths.includes(new URL(r.url()).pathname)&&r.status()===200);const elapsed_ms=await timed(async()=>{await navigate(page,label);await page.locator('main h1').waitFor({state:'visible'});await loaded;await page.waitForFunction(()=>!document.querySelector('main [aria-busy=true],main .skeleton,main .overview-source-state'));await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>new Promise(ok=>requestAnimationFrame(()=>requestAnimationFrame(ok))))})
    routes.push({screen:label,ready_response_paths:paths,elapsed_ms,new_javascript:(await resourceMetrics(page)).javascript.filter(x=>!before.has(x.path))})
   }
   await navigate(page,'Overview');await client.send('Network.setCacheDisabled',{cacheDisabled:false});await page.reload();await page.getByRole('heading',{name:'Good things, in order.',exact:true}).waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('.overview-source-state'));await page.evaluate(()=>document.fonts.ready)
   const warm_overview_ms=await timed(async()=>{await page.reload();await page.getByRole('heading',{name:'Good things, in order.',exact:true}).waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('.overview-source-state'));await page.evaluate(()=>document.fonts.ready)}),warm=await resourceMetrics(page)
   const http=[];for(let request=0;request<100;request++){const tick=performance.now(),response=await page.request.get('/api/flats?page=1&page_size=12');if(response.status()!==200)throw new Error('Protected list measurement failed.');const data=await response.json();if(data.total!==118||data.items.length!==12)throw new Error('Measurement fixture changed.');http.push(performance.now()-tick)}
   const domainWrites=writes.filter(path=>!path.startsWith('/api/auth/'));if(domainWrites.length)throw new Error('Measurement performed a domain mutation: '+domainWrites.join(','))
   record.runs.push({sample:i+1,cold_signin_ms,authentication_ms,overview_data_ready_ms,signin,overview,routes,warm_overview_ms,warm,http_list_ms:http,server_rss_kib:Number(execFileSync('ps',['-p',String(server.pid),'-o','rss='],{encoding:'utf8'}).trim()),domain_writes:domainWrites,authentication_writes:writes});process.stdout.write('Measured synthetic sample '+(i+1)+'/'+samples+'\n')
  }finally{await context.close()}
 }
 for(const [name,digest] of Object.entries(runtime))if(sha(join(release,name))!==digest)throw new Error('Pinned runtime changed during measurement.')
 const stats=values=>{const x=[...values].sort((a,b)=>a-b);return{min:x[0],median:x[Math.floor(x.length/2)],p95:x[Math.min(x.length-1,Math.ceil(x.length*.95)-1)],max:x.at(-1),samples:x.length}}
 record.statistics={cold_signin_ms:stats(record.runs.map(x=>x.cold_signin_ms)),authentication_ms:stats(record.runs.map(x=>x.authentication_ms)),sign_in_to_current_overview_ms:stats(record.runs.map(x=>x.authentication_ms+x.overview_data_ready_ms)),warm_overview_ms:stats(record.runs.map(x=>x.warm_overview_ms)),http_list_ms:stats(record.runs.flatMap(x=>x.http_list_ms)),cold_signin_javascript_decoded_bytes:stats(record.runs.map(x=>x.signin.javascript.reduce((total,item)=>total+item.decoded_body,0))),cold_signin_javascript_transfer_bytes:stats(record.runs.map(x=>x.signin.javascript.reduce((total,item)=>total+item.transfer,0))),observed_server_rss_kib:stats(record.runs.map(x=>x.server_rss_kib))};record.completed_at_utc=new Date().toISOString();record.elapsed_ms=performance.now()-started;record.runtime_unchanged=true;mkdirSync(resolve('reports/local'),{recursive:true,mode:0o700});writeFileSync(destination,JSON.stringify(record,null,2)+'\n',{flag:'wx',mode:0o600});process.stdout.write(JSON.stringify(record.statistics)+'\n')
}finally{
 if(browser)await browser.close();if(server&&server.exitCode===null){const done=new Promise(ok=>server.once('exit',ok));server.kill('SIGTERM');const timer=setTimeout(()=>server.kill('SIGKILL'),6000);await done;clearTimeout(timer)}closeSync(log);if(record.completed_at_utc){copyFileSync(join(temporary,'server.log'),destination+'.server.log');chmodSync(destination+'.server.log',0o600)}rmSync(temporary,{recursive:true,force:true})
}
