export { useFundLoad as useMessageLoad } from './collections'
export { useFineWrite as useMessageWrite } from './fines'
export type MessageTarget = { kind:string; wing:string; ids:string[] }
export type MessageSource = { kind:string; id:string; version:string; title:string; audience:string; wing:string; home_id:string; entry_id:string; link:string }
export type MessageCounts = { target_people:number; source_people:number; consented_people:number; eligible_people:number; destinations:number; omitted_people:number; reasons:Record<string,number> }
export type MessageRecipient = { id:string; name:string; contact_version:number; destination?:string; reason:string; delivery_id?:string; state?:string }
export type MessagePreview = { source:MessageSource; channel:string; purpose:string; target:MessageTarget; counts:MessageCounts; envelope:string; preview_hash:string; recipients:MessageRecipient[]; page:number; page_size:number; simulation:boolean }
export type MessageBatch = { id:string; source:MessageSource; target:MessageTarget; counts:MessageCounts; preview_hash:string; channel:string; purpose:string; portal_origin:string; envelope:string; state:string; proposed_by:string; proposed_at:number; reviewed_by:string; reviewed_at:number; updated_at:number; snapshot_version:number; version:number; simulation:boolean; can_approve:boolean; can_refresh:boolean; can_withdraw:boolean; can_dispatch:boolean; can_cancel:boolean; review_problem:string; outcomes:Record<string,number>; retryable_deliveries:number }
export type MessageDelivery = { id:string; destination:string; state:string; attempts:number; provider_id:string; reason:string; accepted_at:number; delivered_at:number; read_at:number; updated_at:number }
export type MessageDetail = MessageBatch & { recipients:MessageRecipient[]; recipient_page:number; recipient_total:number; deliveries:MessageDelivery[]; delivery_page:number; delivery_total:number; events:{version:number; action:string; actor:string; reason:string; at:number; snapshot:MessageBatch}[]; event_page:number; event_total:number; page_size:number; staff:boolean }
export type MessagePage = { items:MessageBatch[]; total:number; page:number; page_size:number }
export type MessageSummary = { batches:Record<string,number>; outcomes:Record<string,number>; simulation:boolean }
export type MessageSourcePage = { items:MessageSource[]; total:number; page:number; page_size:number }
export type MessageTargetPage = { items:{id:string; label:string}[]; total:number; page:number; page_size:number }
export type MessageConfig = { simulation_enabled:boolean; whatsapp_live:boolean; email_live:boolean; attempt_limit:number; dispatch_limit:number }
export const messageStates:Record<string,string> = { PENDING:'Awaiting separate review', APPROVED:'Approved for delivery', DECLINED:'Declined', WITHDRAWN:'Withdrawn', CANCELLED:'Unsent delivery cancelled' }
export const deliveryStates:Record<string,string> = { QUEUED:'Queued', CLAIMED:'Handoff pending', ACCEPTED:'Provider accepted', DELIVERED:'Delivery reported', READ:'Read reported', FAILED:'Definitively failed', SKIPPED:'Skipped', OPTED_OUT:'Opted out', CANCELLED:'Cancelled', UNKNOWN:'Needs reconciliation', HANDED_OFF:'Handed off', ELIGIBLE:'Eligible when checked', OMITTED:'Omitted' }
export const messageReasons:Record<string,string> = { DECLINED:'Proposal declined', WITHDRAWN:'Proposal withdrawn', CANCELLED:'Unsent messages cancelled', NO_CURRENT_HOME:'No current home relationship', NO_SOURCE_ACCESS:'Outside this record’s audience', CONTACT_NONE:'No registered contact', CONTACT_PENDING:'Verification pending', CONTACT_DECLINED:'Verification declined', CONTACT_WITHDRAWN:'Contact withdrawn', NO_DESTINATION:'No destination for this channel', OPTED_OUT:'Selected messages not permitted', NO_ACTIVE_ACCOUNT:'No active linked portal account', CONTACT_CHANGED:'Contact changed after approval', SOURCE_UNAVAILABLE:'Source no longer available', SOURCE_CHANGED:'Source version changed', APPROVAL_AUTHORITY_ENDED:'An approving appointment ended', PROPOSER_AUTHORITY_ENDED:'Proposer’s appointment ended', DISPATCH_AUTHORITY_ENDED:'Dispatcher’s appointment ended', PREVIEW_CHANGED:'Recipients changed since this snapshot', NO_ELIGIBLE_RECIPIENT:'No eligible person remains', SNAPSHOT_REFRESHED:'Replaced by a refreshed snapshot' }
export const messageTargetLabel = (x:MessageTarget) => x.kind==='WING'?'Wing '+x.wing:x.kind==='HOMES'?x.ids.length+' selected '+(x.ids.length===1?'home':'homes'):x.kind==='PEOPLE'?x.ids.length+' selected '+(x.ids.length===1?'person':'people'):({ALL:'All current people',OWNERS:'Current owners',TENANTS:'Current tenants',PERSONAL:'Your own delivery'} as Record<string,string>)[x.kind]??x.kind
