import { useEffect, useRef, useState } from 'react'
import { request } from '../api'
import { moneyInput, previewPaise, useBudgetWrite } from '../budgets'
import type { BudgetResource, BudgetSnapshot } from '../budgets'
import { BudgetPlanCard, BudgetWriteFeedback } from './BudgetShared'
import { PortalDialog } from './PortalDialog'
import { Icon } from './Icon'

export function BudgetForm({existing,closePeriod=false,onClose,onSaved}:{existing?:BudgetResource;closePeriod?:boolean;onClose:()=>void;onSaved:(id:string)=>void}){
 const seed=existing?.decision==='PENDING'?existing.snapshot:existing?.approved??existing?.snapshot
 const [current,setCurrent]=useState(existing),[title,setTitle]=useState(seed?.title??''),[start,setStart]=useState(seed?.period_start??''),[end,setEnd]=useState(seed?.period_end??''),[source,setSource]=useState(seed?.source_reference??''),[collections,setCollections]=useState(seed?moneyInput(seed.collections_paise):''),[expenses,setExpenses]=useState(seed?moneyInput(seed.expenses_paise):''),[reason,setReason]=useState(''),[preview,setPreview]=useState(false),[checked,setChecked]=useState(false),[localError,setLocalError]=useState(''),[reloading,setReloading]=useState(false)
 const scroll=useRef<HTMLDivElement>(null),write=useBudgetWrite(),frozen=write.busy||write.locked||reloading,dismissBlocked=write.busy||(write.locked&&!write.conflict),action=closePeriod?'CLOSE':'PLAN'
 const allowed=!current||(closePeriod?(current.can_close||(current.can_cancel&&current.snapshot.action==='CLOSE')):current.can_revise)
 useEffect(()=>{if(write.reauth)setChecked(false)},[write.reauth])
 useEffect(()=>{scroll.current?.scrollTo({top:0})},[preview])
 const reload=async()=>{if(!current)return;setReloading(true);setLocalError('');try{const fresh=await request<BudgetResource>('/api/budgets/'+encodeURIComponent(current.id));setCurrent(fresh);if(fresh.approved){setStart(fresh.approved.period_start);setEnd(fresh.approved.period_end)}setPreview(false);setChecked(false);write.reset()}catch(error){setLocalError((error as Error).message)}finally{setReloading(false)}}
 const showPreview=()=>{setLocalError('');if(!allowed)return;if(!closePeriod){const amount=previewPaise(collections),cost=previewPaise(expenses),days=(Date.parse(end)-Date.parse(start))/86400000;if(amount===null||cost===null){setLocalError('Use exact rupee amounts from zero to ₹1,00,00,000 with at most two decimal places.');return}if(!Number.isFinite(days)||days<0||days>365){setLocalError('Choose an inclusive period of at most 366 days.');return}}setPreview(true);setChecked(false)}
 const submit=async()=>{if(!checked||(!allowed&&!write.locked))return;const payload=closePeriod?{version:current?.version??0,action,reason}:{version:current?.version??0,action,title,period_start:start,period_end:end,source_reference:source,planned_collections:collections,planned_expenses:expenses,reason};const result=await write.send(current?'/api/budgets/'+encodeURIComponent(current.id)+'/proposals':'/api/budgets',payload);if(result)onSaved(result.id)}
 const draft:BudgetSnapshot=closePeriod&&current?.approved?{...current.approved,action:'CLOSE'}:{version:(current?.version??0)+1,plan_version:(current?.version??0)+1,action,title,period_start:start,period_end:end,source_reference:source,collections_paise:previewPaise(collections)??0,expenses_paise:previewPaise(expenses)??0,submitted_by:'',submitted_at:0,reason}
 return <PortalDialog titleId="budget-form-heading" closeLabel="Close budget proposal" onClose={onClose} busy={dismissBlocked} className="budget-dialog"><div className="dialog-scroll" ref={scroll}><span className="eyebrow">A LITTLE FORESIGHT</span><h2 id="budget-form-heading">{closePeriod?'Close the period. Keep its story.':preview?'The plan, before the decision.':existing?'Give the plan a considered update.':'Make room for what comes next.'}</h2><p className="dialog-description">{closePeriod?'A separate approval closes new expense intake and preserves the plan, existing records and linked corrections.':'Supply your approved planning figures and period. A different finance reviewer makes this exact proposal effective.'}</p>
 {!allowed&&<div className="form-error" role="status"><p>This record is no longer available for this proposal. Your entered text is retained for review.</p></div>}
 <form onSubmit={event=>{event.preventDefault();if(preview)void submit();else showPreview()}}>
 {!preview&&!closePeriod&&<fieldset disabled={frozen||!allowed}><label>Plan title<input aria-label="Plan title" value={title} onChange={event=>setTitle(event.target.value)} required minLength={5} maxLength={120} placeholder="Our annual operating plan"/></label><div className="budget-form-pair"><label>Period starts<input type="date" aria-label="Budget period starts" value={start} onChange={event=>setStart(event.target.value)} required disabled={!!current?.approved}/></label><label>Period ends<input type="date" aria-label="Budget period ends" min={start||undefined} value={end} onChange={event=>setEnd(event.target.value)} required disabled={!!current?.approved}/></label></div>{current?.approved&&<p className="form-help">This approved period stays fixed while its supplied plan changes.</p>}<div className="budget-form-pair"><label>Planned collections<input aria-label="Planned collections" inputMode="decimal" value={collections} onChange={event=>setCollections(event.target.value)} required maxLength={12} placeholder="0.00"/></label><label>Planned expenses<input aria-label="Planned expenses" inputMode="decimal" value={expenses} onChange={event=>setExpenses(event.target.value)} required maxLength={12} placeholder="0.00"/></label></div><p className="form-help">Amounts in rupees. Zero is a meaningful plan.</p><label>Supplied source / reference<input aria-label="Budget source reference" value={source} onChange={event=>setSource(event.target.value)} required minLength={5} maxLength={300} placeholder="Committee resolution or prepared budget reference"/></label></fieldset>}
 {!preview&&closePeriod&&current?.approved&&<BudgetPlanCard plan={current.approved} label="Accepted plan retained on closure"/>}
 {!preview&&<fieldset disabled={frozen||!allowed}><label>Proposal reason<textarea aria-label="Proposal reason" value={reason} onChange={event=>setReason(event.target.value)} required minLength={10} maxLength={800} rows={4}/></label></fieldset>}
 {preview&&<><BudgetPlanCard plan={draft} label={closePeriod?'Exact period closure':'Exact proposed plan'}/><p className="budget-proposal-reason"><span>Proposal reason</span>{reason}</p><label className="confirmation"><input type="checkbox" checked={checked} disabled={frozen} onChange={event=>setChecked(event.target.checked)}/>I reviewed these exact planning figures, dates, source and proposal.</label></>}
 {localError&&<div className="form-error" role="alert"><p>{localError}</p></div>}{reloading&&<p role="status">Opening the current record…</p>}<BudgetWriteFeedback write={write} onReload={()=>{void reload()}}/>
 <div className="form-actions"><button type="button" className="button button-quiet" disabled={preview?frozen:dismissBlocked} onClick={()=>{if(preview){setPreview(false);setChecked(false);write.reset()}else onClose()}}>{preview?'Edit proposal':'Cancel'}</button><button type="submit" className="button button-dark" disabled={write.busy||reloading||write.conflict||!allowed||(preview&&!checked)}>{write.busy?'Saving…':write.locked?'Retry this proposal':preview?'Submit for separate review':'Preview supplied plan'}<Icon name="arrow"/></button></div>
 </form></div></PortalDialog>
}
