import { useState } from 'react'
import { budgetActions, budgetDecisions, useBudgetLoad } from '../budgets'
import type { BudgetDetail as Detail, BudgetResource, PaidExpensePage, PaidExpenseResource, BudgetDetailView } from '../budgets'
import { money } from '../maintenance'
import { careTime } from '../upkeep'
import { BudgetComparison } from './BudgetComparison'
import { BudgetDecision } from './BudgetDecision'
import { BudgetPlanCard, BudgetReadError } from './BudgetShared'
import { PortalDialog } from './PortalDialog'
import { FilterSelect } from './FilterSelect'
import { PageControls } from './Maintenance'
import { Icon } from './Icon'

export function BudgetDetail({id,view,onView,onClose,onEdit,onAddExpense,onExpense,onChanged}:{id:string;view:BudgetDetailView;onView:(next:Partial<BudgetDetailView>)=>void;onClose:()=>void;onEdit:(record:BudgetResource,close?:boolean)=>void;onAddExpense:(record:BudgetResource)=>void;onExpense:(record:PaidExpenseResource)=>void;onChanged:()=>void}){
 const [revision,setRevision]=useState(0),[decision,setDecision]=useState<'review'|'withdraw'|null>(null)
 const {expense_page:expensePage,event_page:eventPage,query,state}=view, onExpensePage=(page:number)=>onView({expense_page:page}),setEventPage=(page:number)=>onView({event_page:page}),setQuery=(query:string)=>onView({query,expense_page:1}),setState=(state:string)=>onView({state,expense_page:1})
 const load=useBudgetLoad<Detail>('/api/budgets/'+encodeURIComponent(id)+'?event_page='+eventPage+'&refresh='+revision),data=!load.loading&&!load.error?load.data:null
 const expenses=useBudgetLoad<PaidExpensePage>('/api/paid-expenses?'+new URLSearchParams({budget_id:id,q:query,state,page:String(expensePage),refresh:String(revision)})),rows=!expenses.loading&&!expenses.error?expenses.data:null
 const refresh=()=>{setRevision(v=>v+1);onChanged()}
 if(decision)return <BudgetDecision kind="budget" id={id} withdraw={decision==='withdraw'} onClose={()=>setDecision(null)} onSaved={()=>{setDecision(null);refresh()}}/>
 return <PortalDialog titleId="budget-detail-heading" closeLabel="Close budget details" onClose={onClose} className="budget-dialog budget-detail-dialog"><div className="dialog-scroll"><span className="eyebrow">A PERIOD, KEPT IN PERSPECTIVE</span><h2 id="budget-detail-heading">{data?.snapshot.title??'Opening the budget…'}</h2>
 {load.loading?<p className="empty-state" role="status">Opening the current plan and history…</p>:load.error?<BudgetReadError title="This budget could not be opened." error={load.error} onRetry={load.reload}/>:data&&<>
 <div className="budget-record-status"><span className="contact-state">{data.state==='OPEN'?'Open period':data.state==='CLOSED'?'Closed period':'Awaiting first approval'}</span>{data.decision!=='APPROVED'&&<span>{budgetDecisions[data.decision]}</span>}</div>
 {data.approved&&<BudgetPlanCard plan={data.approved} label="Accepted operating plan"/>}{(!data.approved||data.snapshot.version!==data.approved.version)&&<><BudgetPlanCard plan={data.snapshot} label={data.decision==='PENDING'?'Proposal awaiting separate review':'Latest retained proposal'}/><p className="budget-proposal-reason"><span>Proposal reason</span>{data.snapshot.reason}</p></>}
 <div className="budget-record-actions">{data.can_decide&&<button type="button" className="button button-dark" onClick={()=>setDecision('review')}>Review budget proposal<Icon name="check"/></button>}{data.can_cancel&&<button type="button" className="button button-quiet" onClick={()=>setDecision('withdraw')}>Withdraw proposal</button>}{data.can_revise&&data.snapshot.action==='PLAN'&&<button type="button" className="button button-quiet" onClick={()=>onEdit(data)}>Revise plan</button>}{data.can_close&&<button type="button" className="text-link" onClick={()=>onEdit(data,true)}>Prepare period closure<Icon name="arrow"/></button>}</div>
 <BudgetComparison id={id} version={data.version} revision={revision} onReloadRecord={load.reload}/>
 <section className="budget-expenses" aria-label="Paid expense register"><div className="section-heading"><div><span className="eyebrow">THE PAID RECORDS</span><h3>Every expense, accounted for.</h3></div><span className="result-count">{rows?rows.total+' '+(rows.total===1?'record':'records'):'Checking records…'}</span></div>{data.can_add_expense&&<button type="button" className="button button-dark" onClick={()=>onAddExpense(data)}>Record a paid expense<Icon name="arrow"/></button>}
 <div className="budget-expense-filters"><label className="search-control"><Icon name="search"/><input aria-label="Search paid expenses" placeholder="Payee, category or retained reference…" value={query} maxLength={100} onChange={event=>{setQuery(event.target.value);onExpensePage(1)}}/></label><FilterSelect label="Filter paid expenses" value={state} options={[{value:'',label:'All paid records'},{value:'PENDING',label:'Awaiting separate review'},{value:'CONFIRMED',label:'Effective recorded expenses'},{value:'VOID',label:'Effect removed'},{value:'UNCONFIRMED',label:'No accepted record yet'}]} onChange={value=>{setState(value);onExpensePage(1)}}/>{(query||state)&&<button type="button" className="clear-button" onClick={()=>{setQuery('');setState('');onExpensePage(1)}}>Clear<Icon name="close"/></button>}</div>
 {rows&&<p className="budget-expense-full-counts">{rows.counts.pending} proposals awaiting review · {rows.counts.confirmed} effective records · {rows.counts.void} removed effects</p>}
 {expenses.loading?<p className="empty-state" role="status">Opening current paid-expense records…</p>:expenses.error?<BudgetReadError title="Paid records could not be opened." error={expenses.error} onRetry={expenses.reload}/>:rows&&<>{rows.items.length?<div className="budget-expense-cards">{rows.items.map(record=>{const effective=record.approved??record.snapshot;return <button type="button" className="budget-expense-card" key={record.id} aria-label={'Open paid expense '+effective.payee} onClick={()=>onExpense(record)}><span className="budget-expense-card-top"><span>{effective.category}</span><Icon name="arrow"/></span><h4>{effective.payee}</h4><strong>{money(effective.amount_paise)}</strong><span>{record.approved?record.state==='VOID'?'Effect removed':'Effective recorded amount':'Proposed amount · awaiting acceptance'}</span>{record.decision==='PENDING'&&<small>{record.snapshot.action==='CORRECTION'?'Linked correction awaiting review':record.snapshot.action==='VOID'?'Removal awaiting review':'Awaiting separate review'}</small>}<small>{effective.reference}</small></button>})}</div>:<div className="empty-state"><Icon name="leaf"/><h4>{query||state?'No paid records match these choices.':'A clear place for the paid records.'}</h4><p>Supplied expenses appear here for independent review. Pending records add no spending.</p></div>}{rows.total>12&&<PageControls label="paid expenses" page={expensePage} total={rows.total} size={12} onPage={onExpensePage}/>}</>}
 </section><section className="budget-history" aria-label="Budget decision history"><h3>A plan with its history.</h3>{data.events.map(event=><article key={event.version}><div><span>{budgetActions[event.action]} · record version {event.version}</span><small>{careTime(event.at)}</small></div><p>{event.reason}</p><small>{event.actor} · proposal version {event.proposal_version}</small></article>)}{data.event_total>12&&<PageControls label="budget history" page={eventPage} total={data.event_total} size={12} onPage={setEventPage}/>}</section>
 </>}
 </div></PortalDialog>
}
