import { useEffect, useState } from 'react'
import type { User } from '../api'
import { budgetDecisions, budgetLink, useBudgetLoad } from '../budgets'
import type { BudgetPage, BudgetResource, PaidExpenseResource, BudgetDetailView } from '../budgets'
import { displayDate, money } from '../maintenance'
import { BudgetDetail } from './BudgetDetail'
import { BudgetForm } from './BudgetForm'
import { PaidExpenseDetail } from './PaidExpenseDetail'
import { PaidExpenseForm } from './PaidExpenseForm'
import { BudgetReadError } from './BudgetShared'
import { FilterSelect } from './FilterSelect'
import { PageControls } from './Maintenance'
import { Icon } from './Icon'

const initialView=():BudgetDetailView=>({expense_page:Math.max(1,Math.min(10000,Number(budgetLink('expense_page'))||1)),event_page:1,query:'',state:''})
function BudgetArt(){return <svg className="budget-art" viewBox="0 0 260 220" fill="none" aria-hidden="true"><ellipse cx="130" cy="192" rx="112" ry="15" fill="#e1e7d5"/><rect x="52" y="29" width="138" height="158" rx="12" transform="rotate(-6 52 29)" fill="#fffef7" stroke="#b6c3a6" strokeWidth="2"/><path d="M72 60h72M69 76h93" stroke="#c8d0ba" strokeWidth="3" strokeLinecap="round"/><path d="M73 155v-28m26 25v-45m27 42V91m27 54v-26" stroke="#8d9b70" strokeWidth="13" strokeLinecap="round"/><path d="m68 111 31-18 27-21 27 13" stroke="#536b43" strokeWidth="2" strokeLinecap="round"/><circle cx="199" cy="151" r="34" fill="#eee6d7"/><path d="m187 151 10 10 18-22" stroke="#a48a65" strokeWidth="2" strokeLinecap="round"/><path d="M203 104V57m0 24-15-14m15 5 13-17" stroke="#738758" strokeWidth="2" strokeLinecap="round"/><ellipse cx="213" cy="46" rx="11" ry="17" transform="rotate(30 213 46)" fill="#b9c59e"/></svg>}
export function Budgets({user}:{user:User}){
 const [query,setQuery]=useState(''),[state,setState]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[selected,setSelected]=useState(budgetLink('budget')),[expense,setExpense]=useState(budgetLink('expense')),[view,setView]=useState<BudgetDetailView>(initialView),[form,setForm]=useState<BudgetResource|'new'|null>(null),[closePeriod,setClosePeriod]=useState(false),[paidForm,setPaidForm]=useState<{budget:BudgetResource;existing?:PaidExpenseResource;action:'PAID'|'CORRECTION'|'VOID'}|null>(null),[expenseHistory,setExpenseHistory]=useState(1)
 const load=useBudgetLoad<BudgetPage>('/api/budgets?'+new URLSearchParams({q:query,state,page:String(page),refresh:String(revision)})),data=!load.loading&&!load.error?load.data:null
 const url=(budget:string,paid:string,expensePage=view.expense_page)=>{const q=new URLSearchParams({panel:'budgets'});if(budget)q.set('budget',budget);if(paid)q.set('expense',paid);if(budget&&expensePage>1)q.set('expense_page',String(expensePage));window.history.replaceState(null,'','#statements?'+q)}
 const open=(id:string,reset=true)=>{setSelected(id);setExpense('');setForm(null);setPaidForm(null);if(reset)setView({expense_page:1,event_page:1,query:'',state:''});url(id,'',reset?1:view.expense_page)}
 const openExpense=(record:PaidExpenseResource)=>{setSelected(record.budget_id);setExpense(record.id);setExpenseHistory(1);setPaidForm(null);url(record.budget_id,record.id)}
 const close=()=>{setSelected('');setExpense('');url('','')},closeExpense=()=>{setExpense('');url(selected,'')},refresh=()=>setRevision(v=>v+1)
 const changeView=(next:Partial<BudgetDetailView>)=>{setView(value=>({...value,...next}));if(next.expense_page)url(selected,expense,next.expense_page)}
 useEffect(()=>{const change=()=>{setSelected(budgetLink('budget'));setExpense(budgetLink('expense'));setForm(null);setPaidForm(null);setView(initialView())};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change)},[])
 return <div className="page-enter budgets-page"><section className="maintenance-hero budget-hero"><div><span className="eyebrow">THE COMMUNITY’S RESOURCES, CONSIDERED</span><h1>A little foresight.<br/><em>A steadier tomorrow.</em></h1><p>Bring the plan, collections and paid records into one clear perspective.</p>{user.can_manage_records&&<button type="button" className="button button-dark" disabled={!data?.can_prepare} onClick={()=>{setForm('new');setClosePeriod(false)}}>Prepare a budget<Icon name="arrow"/></button>}</div><BudgetArt/></section>
 <section className="budget-attention" aria-label="Budget attention">{[['Open periods','open'],['Proposals awaiting review','pending'],['Closed periods','closed']].map(([label,key])=><button type="button" key={key} disabled={!data} onClick={()=>{setState(key==='pending'?'PENDING':key.toUpperCase());setPage(1)}}><span>{label}</span><strong>{data?data.counts[key]:'—'}</strong><Icon name="arrow"/></button>)}</section>
 <section className="budget-register"><div className="section-heading"><div><span className="eyebrow">A CLEAR PLACE TO BEGIN</span><h2>The operating plans.</h2><p>Open a period to compare its accepted plan and reviewed paid records.</p></div><span className="result-count">{data?data.total+' '+(data.total===1?'plan':'plans'):'Checking plans…'}</span></div><div className="budget-register-filters"><label className="search-control"><Icon name="search"/><input aria-label="Search budgets" placeholder="Find a plan or supplied reference…" maxLength={100} value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}}/></label><FilterSelect label="Filter budgets" value={state} options={[{value:'',label:'All periods'},{value:'OPEN',label:'Open approved periods'},{value:'PENDING',label:'Proposals awaiting review'},{value:'CLOSED',label:'Closed periods'},{value:'UNAPPROVED',label:'No approved plan yet'}]} onChange={value=>{setState(value);setPage(1)}}/>{(query||state)&&<button type="button" className="clear-button" onClick={()=>{setQuery('');setState('');setPage(1)}}>Clear<Icon name="close"/></button>}</div>
 {load.loading?<p className="empty-state" role="status">Opening the current operating plans…</p>:load.error?<BudgetReadError title="The budget desk could not be opened." error={load.error} onRetry={load.reload}/>:data&&<>{data.items.length?<div className="budget-cards">{data.items.map(record=>{const plan=record.approved??record.snapshot;return <button type="button" className="budget-card" key={record.id} aria-label={'Open budget '+plan.title} onClick={()=>open(record.id)}><div className="budget-card-top"><span>{record.state==='OPEN'?'Open period':record.state==='CLOSED'?'Closed period':'Awaiting first approval'}</span><Icon name="arrow"/></div><h3>{plan.title}</h3><p>{displayDate(plan.period_start)} – {displayDate(plan.period_end)}</p><div className="budget-card-money"><div><span>Planned collections</span><strong>{money(plan.collections_paise)}</strong></div><div><span>Planned expenses</span><strong>{money(plan.expenses_paise)}</strong></div></div>{record.decision!=='APPROVED'&&<span className="contact-state">{record.approved?'Latest proposal: ':''}{budgetDecisions[record.decision]}</span>}{!record.approved&&<small>Proposed figures · a separate approval makes the plan effective</small>}</button>})}</div>:<div className="empty-state"><Icon name="leaf"/><h3>{query||state?'No plans match these choices.':'A considered plan starts here.'}</h3><p>{user.can_manage_records?'Supply a dated plan, review its exact figures and invite a different finance reviewer.':'Approved plans and retained proposals will appear in this private finance view.'}</p></div>}{data.total>12&&<PageControls label="budgets" page={page} total={data.total} size={12} onPage={setPage}/>}</>}
 </section><p className="records-footnote"><Icon name="shield"/>Plans, original paid records and linked corrections stay together.</p>
 {form?<BudgetForm existing={form==='new'?undefined:form} closePeriod={closePeriod} onClose={()=>setForm(null)} onSaved={id=>{const reset=form==='new';setForm(null);refresh();open(id,reset)}}/>:paidForm?<PaidExpenseForm {...paidForm} onClose={()=>setPaidForm(null)} onSaved={id=>{const parent=paidForm.budget.id;setPaidForm(null);setExpense(id);setSelected(parent);setExpenseHistory(1);url(parent,id);refresh()}}/>:expense?<PaidExpenseDetail id={expense} eventPage={expenseHistory} onEventPage={setExpenseHistory} onClose={closeExpense} onChanged={refresh} onEdit={(budget,record,action)=>setPaidForm({budget,existing:record,action})}/>:selected?<BudgetDetail id={selected} view={view} onView={changeView} onClose={close} onEdit={(record,closing=false)=>{setForm(record);setClosePeriod(closing)}} onAddExpense={budget=>setPaidForm({budget,action:'PAID'})} onExpense={openExpense} onChanged={refresh}/>:null}
 </div>
}
