import { useEffect, useState } from 'react'
import type { User } from '../api'
import { fundLink, fundStates, reportStates, selectOptions, useFundLoad } from '../collections'
import type { Contribution, ContributionPage, Fund, FundDetail, FundLine, FundPage, PaymentReport, ReportPage, WaiverPage } from '../collections'
import { displayDate, money } from '../maintenance'
import type { FinancialHome } from '../maintenance'
import { careTime } from '../upkeep'
import { AttributeFundCredit, FundContributionDialog, FundWaiverDialog, NewFundWaiver } from './FundAdjustments'
import { FundCampaignDialog, NewFund } from './FundCampaign'
import { FundReportDialog, NewFundReport } from './FundReport'
import { FilterSelect } from './FilterSelect'
import { Icon } from './Icon'
import { PageControls } from './Maintenance'
import { FinanceExportAction } from './FinanceExports'

type Modal = {kind:'fund'|'report'|'waiver';id:string}|{kind:'new'}|{kind:'report-new'|'waiver-new'|'attribute';campaign:FundDetail;line:FundLine}|{kind:'revision';report:PaymentReport}|{kind:'contribution';item:Contribution}|null
function linkedModal():Modal{for(const kind of ['fund','report','waiver'] as const){const id=fundLink(kind==='fund'?'campaign':kind);if(id)return {kind,id}}return null}
function GardenArt(){return <svg className="fund-art" aria-hidden="true" viewBox="0 0 260 210" fill="none"><ellipse cx="126" cy="182" rx="112" ry="17" fill="#e1e7d3"/><path d="M113 170V67m0 54L79 91m34 9 34-35m-34 82 45-33" stroke="#748968" strokeWidth="4" strokeLinecap="round"/><ellipse cx="103" cy="55" rx="32" ry="43" transform="rotate(-12 103 55)" fill="#c4d1ae"/><ellipse cx="74" cy="91" rx="22" ry="33" transform="rotate(-41 74 91)" fill="#a6b995"/><ellipse cx="145" cy="70" rx="23" ry="35" transform="rotate(40 145 70)" fill="#8fa77a"/><ellipse cx="162" cy="108" rx="25" ry="32" transform="rotate(41 162 108)" fill="#c5d3b0"/><path d="M55 177v-29m0 12-14-15m14 9 16-18" stroke="#7b9267" strokeWidth="2.5" strokeLinecap="round"/><ellipse cx="42" cy="142" rx="10" ry="15" transform="rotate(-37 42 142)" fill="#a4b992"/><ellipse cx="69" cy="134" rx="10" ry="16" transform="rotate(31 69 134)" fill="#bfcea7"/><path d="M80 169h66l-7 24H88l-8-24Z" fill="#ccb699"/><path d="M82 170h62" stroke="#a98e70" strokeWidth="3"/><circle cx="207" cy="139" r="26" fill="#fdfbf1" stroke="#d9dfcc"/><path d="m197 139 7 8 14-17" stroke="#779365" strokeWidth="2.5" strokeLinecap="round"/></svg>}
function FundCard({item,onOpen}:{item:Fund;onOpen:()=>void}){
 const live=item.state==='PUBLISHED'||item.state==='CLOSED',voluntary=item.contribution_type==='VOLUNTARY',confirmed=item.allocated_paise+item.voluntary_paise,denominator=voluntary?item.target_paise:item.active_paise
 return <button className={'maintenance-card fund-card fund-card-'+item.state.toLowerCase()} onClick={onOpen} aria-label={'Open fund '+item.title}><span className="maintenance-card-top"><span className={'fund-state fund-state-'+item.state.toLowerCase()}>{fundStates[item.state]}</span><Icon name="arrow"/></span><span className="fund-card-kind">{voluntary?'A voluntary contribution':'Fixed supplied amounts'}</span><h3>{item.title}</h3><p>{item.purpose}</p><span className="maintenance-card-amount"><small>{live?voluntary?'Confirmed for this purpose':'Outstanding':'Supplied proposal'}</small><strong>{!live&&voluntary?'Voluntary':money(live?voluntary?confirmed:item.outstanding_paise:item.requested_paise)}</strong></span>{live&&<><span className="maintenance-progress"><span style={{width:(denominator?Math.min(100,confirmed/denominator*100):0)+'%'}}/></span><span className="fund-card-progress-label">{voluntary?(item.target_paise?'Target '+money(item.target_paise):'No target supplied'):`${item.paid_homes} paid · ${item.partial_homes} part paid · ${item.unpaid_homes} unpaid`}</span></>}<span className="maintenance-card-bottom"><span>{item.participants} {item.participants===1?'home':'homes'}</span><span>Due {displayDate(item.due_date)}</span></span></button>
}
export function Collections({user}:{user:User}){
 const [tab,setTab]=useState(()=>fundLink('report')?'REPORTS':fundLink('waiver')?'WAIVERS':'FUNDS'),[query,setQuery]=useState(''),[home,setHome]=useState(''),[state,setState]=useState(()=>fundLink('state')),[page,setPage]=useState(1),[modal,setModal]=useState<Modal>(linkedModal),[revision,setRevision]=useState(0)
 const load=useFundLoad<FundPage>('/api/collections?'+new URLSearchParams({q:query,home,state,page:String(page),refresh:String(revision)}),user.can_read_records)
 const metrics=useFundLoad<FundPage>('/api/collections?'+new URLSearchParams({home,page:'1',refresh:String(revision)}),user.can_read_records)
 useEffect(()=>{const update=()=>{const next=linkedModal();setModal(next);if(next?.kind==='report')setTab('REPORTS');if(next?.kind==='waiver')setTab('WAIVERS');if(next?.kind==='fund')setTab('FUNDS');if(fundLink('state')){setState(fundLink('state'));setPage(1)}};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update)},[])
 const changed=()=>setRevision(value=>value+1),close=()=>{setModal(null);window.history.replaceState(null,'','#collections')},open=(kind:'fund'|'report'|'waiver',id:string)=>{setModal({kind,id});window.history.replaceState(null,'','#collections?'+(kind==='fund'?'campaign':kind)+'='+id)}
 const clear=()=>{setQuery('');setHome('');setState('');setPage(1)},counts=!metrics.loading&&!metrics.error?metrics.data?.totals:undefined
 const flow=(kind:'report-new'|'waiver-new'|'attribute',campaign:FundDetail,line:FundLine)=>{setModal({kind,campaign,line});window.history.replaceState(null,'','#collections')}
 if(!user.can_read_records)return <section className="empty-state"><Icon name="shield"/><h1>Collections needs financial access.</h1><p>The officer can review financial access for your current homes.</p><a className="button button-dark" href="#homes">Return to your homes<Icon name="arrow"/></a></section>
 return <div className="page-enter collections-page"><section className="maintenance-hero fund-hero"><div><span className="eyebrow">FOR THE THINGS WE BELIEVE IN, TOGETHER</span><h1>Small contributions.<br/><em>Shared possibilities.</em></h1><p>Keep each fund’s purpose, participating homes and already-paid contributions together.</p><div className="finance-workspace-actions">{user.can_manage_records&&<button className="button button-dark" disabled={load.loading||!!load.error||!load.data?.homes.length} onClick={()=>{setModal({kind:'new'});window.history.replaceState(null,'','#collections')}}>Prepare a fund<Icon name="plus"/></button>}<FinanceExportAction user={user} report="FUNDS" home={home} /></div></div><GardenArt/></section>
 <div className="maintenance-metrics fund-metrics" aria-label="Collections in your financial scope">{[['Confirmed for funds',counts?counts.allocated_paise+counts.voluntary_paise:undefined,'Linked receipts and voluntary purpose assignments'],['Outstanding',counts?.outstanding_paise,'Current supplied fixed charges'],['Past due',counts?.overdue_paise,'Outstanding after supplied due dates'],['Awaiting verification',counts?.pending_reports,'Reported payments are still claims']].map(([label,value,hint],index)=><div key={String(label)}><span>{label}</span><strong>{value===undefined?'—':index===3?value:money(Number(value))}</strong><small>{hint}</small></div>)}</div>{metrics.error&&<div className="fund-metrics-error" role="alert"><p>Collection totals unavailable. {metrics.error}</p><button className="text-link" onClick={metrics.reload}>Retry totals<Icon name="refresh"/></button></div>}
 <p className="maintenance-scope">{user.can_read_all_records?'Treasury view across participating homes.':'Only your current financial homes and your own payment reports are shown.'} Payments happen outside the portal.</p>
 <div className="upkeep-tabs fund-tabs" role="tablist" aria-label="Collection workspaces" onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const tabs=Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('[role="tab"]')),current=tabs.indexOf(document.activeElement as HTMLButtonElement);if(current<0)return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(current+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next]?.click();tabs[next]?.focus()}}>{[['FUNDS','Funds'],['REPORTS','Payment reports'],['CONTRIBUTIONS','Voluntary history'],...(user.can_read_all_records?[['WAIVERS','Exemptions']]:[])].map(([value,label])=><button key={value} role="tab" tabIndex={tab===value?0:-1} aria-selected={tab===value} aria-controls="collection-panel" onClick={()=>setTab(value)}>{label}</button>)}</div>
 <div id="collection-panel" role="tabpanel">{tab==='REPORTS'?<ReportsPanel key={revision} homes={load.data?.homes??[]} onOpen={id=>open('report',id)}/>:tab==='CONTRIBUTIONS'?<ContributionsPanel key={revision} homes={load.data?.homes??[]} onOpen={item=>setModal({kind:'contribution',item})}/>:tab==='WAIVERS'&&user.can_read_all_records?<WaiversPanel key={revision} onOpen={id=>open('waiver',id)}/>:<section className="registry-panel"><div className="registry-toolbar"><div><h2>A purpose for every fund.</h2><p>Open a collection to see confirmed contributions and each home’s current position.</p></div><span className="result-count" role="status">{load.loading?'Opening funds…':load.error?'Connection unavailable':`${load.data?.total??0} ${load.data?.total===1?"fund":"funds"} found`}</span></div><div className="filter-row fund-filters"><label className="search-control"><span className="sr-only">Search funds</span><Icon name="search"/><input type="search" maxLength={100} value={query} placeholder="Find a shared purpose…" onChange={event=>{setQuery(event.target.value);setPage(1)}}/></label><FilterSelect label="Filter funds by home" value={home} onChange={value=>{setHome(value);setPage(1)}} options={[{value:'',label:'All homes'},...(load.data?.homes??[]).map(item=>({value:item.id,label:'Home '+item.label}))]}/><FilterSelect label="Filter funds by state" value={state} onChange={value=>{setState(value);setPage(1)}} options={[{value:'',label:'All funds'},...selectOptions(fundStates).filter(option=>user.can_read_all_records||['PUBLISHED','CLOSED'].includes(option.value))]}/><button className="clear-button" disabled={!query&&!home&&!state} onClick={clear}>Clear<Icon name="close"/></button></div><CollectionResults error={load.error} loading={load.loading} empty={!load.data?.items.length} filtered={!!query||!!home||!!state} onRetry={load.reload} onClear={clear} emptyTitle="A little room for possibility." emptyHint={user.can_manage_records?'Prepare a supplied fixed or voluntary fund, then ask a different treasury reviewer to publish.':'Your reviewed funds will appear here.'}><div className="maintenance-grid fund-grid">{load.data?.items.map(item=><FundCard key={item.id} item={item} onOpen={()=>open('fund',item.id)}/>)}</div></CollectionResults>{load.data&&!load.loading&&!load.error&&load.data.total>0&&<PageControls label={load.data.total===1?"fund":"funds"} page={load.data.page} total={load.data.total} size={load.data.page_size} onPage={setPage}/>}</section>}</div>
 <p className="records-footnote"><Icon name="leaf"/>Every reported payment has a review. Every confirmed receipt keeps its original record.</p>
 {modal?.kind==='new'&&user.can_manage_records&&<NewFund homes={load.data?.homes??[]} onClose={close} onCreated={id=>{changed();open('fund',id)}}/>}
 {modal?.kind==='fund'&&<FundCampaignDialog key={modal.id} id={modal.id} user={user} onClose={close} onSaved={changed} onReport={(campaign,line)=>flow('report-new',campaign,line)} onWaiver={(campaign,line)=>flow('waiver-new',campaign,line)} onAttribute={(campaign,line)=>flow('attribute',campaign,line)}/>}
 {modal?.kind==='report-new'&&<NewFundReport user={user} campaign={modal.campaign} line={modal.line} onClose={close} onSaved={id=>{changed();setTab('REPORTS');open('report',id)}}/>}
 {modal?.kind==='revision'&&<NewFundReport user={user} campaign={{id:modal.report.campaign_id,title:modal.report.campaign}} line={modal.report} initial={modal.report} onClose={close} onSaved={id=>{changed();open('report',id)}}/>}
 {modal?.kind==='report'&&<FundReportDialog key={modal.id} id={modal.id} user={user} onClose={close} onSaved={changed} onRevise={report=>setModal({kind:'revision',report})}/>}
 {modal?.kind==='waiver-new'&&user.can_manage_records&&<NewFundWaiver campaign={modal.campaign} line={modal.line} onClose={close} onSaved={id=>{changed();setTab('WAIVERS');open('waiver',id)}}/>}
 {modal?.kind==='waiver'&&<FundWaiverDialog key={modal.id} id={modal.id} user={user} onClose={close} onSaved={changed}/>}
 {modal?.kind==='attribute'&&user.can_manage_records&&<AttributeFundCredit campaign={modal.campaign} line={modal.line} onClose={close} onSaved={()=>{changed();close();setTab('CONTRIBUTIONS')}}/>}
 {modal?.kind==='contribution'&&<FundContributionDialog item={modal.item} user={user} onClose={close} onSaved={()=>{changed();close()}}/>}
 </div>
}

function CollectionResults({error,loading,empty,filtered,onRetry,onClear,emptyTitle,emptyHint,children}:{error:string;loading:boolean;empty:boolean;filtered?:boolean;onRetry:()=>void;onClear?:()=>void;emptyTitle:string;emptyHint:string;children:React.ReactNode}){return <div aria-busy={loading}>{error?<div className="empty-state" role="alert"><h3>Collections unavailable.</h3><p>{error}</p><button className="button button-dark" onClick={onRetry}>Try again<Icon name="refresh"/></button></div>:loading?<div className="home-skeleton skeleton" aria-hidden="true"/>:empty?<div className="records-empty"><span className="chapter-icon"><Icon name="leaf"/></span><h3>{filtered?'No records match.':emptyTitle}</h3><p>{filtered?'Try another home, title or state.':emptyHint}</p>{filtered&&onClear&&<button className="text-link" onClick={onClear}>Clear filters<Icon name="close"/></button>}</div>:children}</div>}
function ReportsPanel({homes,onOpen}:{homes:FinancialHome[];onOpen:(id:string)=>void}){
 const [query,setQuery]=useState(''),[home,setHome]=useState(''),[state,setState]=useState(''),[page,setPage]=useState(1),load=useFundLoad<ReportPage>('/api/payment-reports?'+new URLSearchParams({q:query,home,state,page:String(page)})),clear=()=>{setQuery('');setHome('');setState('');setPage(1)}
 return <section className="registry-panel"><div className="registry-toolbar"><div><h2>The paid details, together.</h2><p>Claims stay separate from confirmed receipts until the external record is checked.</p></div><span className="result-count" role="status">{load.loading?'Opening reports…':load.error?'Connection unavailable':`${load.data?.total??0} payment reports`}</span></div><div className="filter-row fund-filters"><label className="search-control"><span className="sr-only">Search payment reports</span><Icon name="search"/><input type="search" maxLength={100} value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Find a fund or home…"/></label><FilterSelect label="Filter payment reports by home" value={home} onChange={value=>{setHome(value);setPage(1)}} options={[{value:'',label:'All homes'},...homes.map(item=>({value:item.id,label:'Home '+item.label}))]}/><FilterSelect label="Filter payment reports by state" value={state} onChange={value=>{setState(value);setPage(1)}} options={[{value:'',label:'All reports'},...selectOptions(reportStates).filter(item=>item.value!=='CORRECTED')]}/><button className="clear-button" disabled={!query&&!home&&!state} onClick={clear}>Clear<Icon name="close"/></button></div><CollectionResults error={load.error} loading={load.loading} empty={!load.data?.items.length} filtered={!!query||!!home||!!state} onRetry={load.reload} onClear={clear} emptyTitle="Nothing reported just yet." emptyHint="Open a published fund and report a payment already made outside the portal."><div className="fund-report-list">{load.data?.items.map(item=><button key={item.id} className="fund-report-row" aria-label={'Open payment report '+item.home+' '+item.campaign} onClick={()=>onOpen(item.id)}><span className="record-icon received"><Icon name="receipt"/></span><span className="fund-report-row-copy"><strong>{item.campaign}</strong><small>Home {item.home} · {displayDate(item.payment_date)}</small><span className={'fund-state fund-report-state-'+item.current_state.toLowerCase()}>{reportStates[item.current_state]}</span></span><span className="fund-report-row-money"><strong>{money(item.amount_paise)}</strong><small>{item.receipt||'Reported · no receipt yet'}</small></span><Icon name="arrow"/></button>)}</div></CollectionResults>{load.data&&!load.loading&&!load.error&&load.data.total>0&&<PageControls label="payment reports" page={load.data.page} total={load.data.total} size={load.data.page_size} onPage={setPage}/>}</section>
}
function WaiversPanel({onOpen}:{onOpen:(id:string)=>void}){
 const [state,setState]=useState(''),[page,setPage]=useState(1),load=useFundLoad<WaiverPage>('/api/fund-waivers?'+new URLSearchParams({state,page:String(page)}))
 return <section className="registry-panel"><div className="registry-toolbar"><div><h2>Exceptions, with consideration.</h2><p>Supplied exemptions require a separate treasury reviewer.</p></div><FilterSelect label="Filter exemptions by state" value={state} onChange={value=>{setState(value);setPage(1)}} options={[{value:'',label:'All exemptions'},{value:'PENDING',label:'Awaiting review'},{value:'APPROVED',label:'Approved'},{value:'DECLINED',label:'Declined'},{value:'WITHDRAWN',label:'Withdrawn'}]}/></div><CollectionResults error={load.error} loading={load.loading} empty={!load.data?.items.length} filtered={!!state} onRetry={load.reload} onClear={()=>{setState('');setPage(1)}} emptyTitle="Every home, considered." emptyHint="Open a fixed fund to propose an explicit exemption from its current supplied charge."><div className="fund-report-list">{load.data?.items.map(item=><button key={item.id} className="fund-report-row" aria-label={'Open exemption '+item.home+' '+item.campaign} onClick={()=>onOpen(item.id)}><span className="record-icon"><Icon name="check"/></span><span className="fund-report-row-copy"><strong>{item.campaign}</strong><small>Home {item.home} · Proposed by {item.author}</small><span className="fund-state">{item.state==='PENDING'?'Awaiting review':item.state==='APPROVED'?'Approved':item.state==='DECLINED'?'Declined':'Withdrawn'}</span></span><span className="fund-report-row-money"><strong>{money(item.amount_paise)}</strong><small>Supplied exemption</small></span><Icon name="arrow"/></button>)}</div></CollectionResults>{load.data&&!load.loading&&!load.error&&load.data.total>0&&<PageControls label="exemptions" page={load.data.page} total={load.data.total} size={load.data.page_size} onPage={setPage}/>}</section>
}
function ContributionsPanel({homes,onOpen}:{homes:FinancialHome[];onOpen:(item:Contribution)=>void}){
 const [home,setHome]=useState(''),[page,setPage]=useState(1),load=useFundLoad<ContributionPage>('/api/fund-contributions?'+new URLSearchParams({home,page:String(page)}))
 return <section className="registry-panel"><div className="registry-toolbar"><div><h2>A receipt. A shared purpose.</h2><p>Every voluntary assignment preserves its original receipt and correction history.</p></div><FilterSelect label="Filter voluntary history by home" value={home} onChange={value=>{setHome(value);setPage(1)}} options={[{value:'',label:'All homes'},...homes.map(item=>({value:item.id,label:'Home '+item.label}))]}/></div><CollectionResults error={load.error} loading={load.loading} empty={!load.data?.items.length} filtered={!!home} onRetry={load.reload} onClear={()=>{setHome('');setPage(1)}} emptyTitle="Good things start somewhere." emptyHint="Confirmed payments assigned to voluntary funds will appear here."><div className="fund-report-list">{load.data?.items.map(item=><button key={item.id} className="fund-report-row" aria-label={'Open voluntary assignment '+item.home+' '+item.campaign} onClick={()=>onOpen(item)}><span className="record-icon received"><Icon name="leaf"/></span><span className="fund-report-row-copy"><strong>{item.campaign}</strong><small>Home {item.home} · {careTime(item.created_at)}</small><span className="fund-state">{item.state==='ACTIVE'?'Active assignment':item.state==='CORRECTED'?'Assignment corrected':'Original payment reversed'}</span></span><span className="fund-report-row-money"><strong>{money(item.amount_paise)}</strong><small>{item.receipt}</small></span><Icon name="arrow"/></button>)}</div></CollectionResults>{load.data&&!load.loading&&!load.error&&load.data.total>0&&<PageControls label="voluntary assignments" page={load.data.page} total={load.data.total} size={load.data.page_size} onPage={setPage}/>}</section>
}
