import { useFragmentSync } from '../navigation'
import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { APIError, mutate, request, uploadOriginal } from '../api'
import type { Person, User } from '../api'
import { Icon } from './Icon'
import { FilterSelect, FormSelect } from './FilterSelect'
import { PortalDialog } from './PortalDialog'

type Home = { id: string; label: string }
export type LibraryItem = { id: string; title: string; filename: string; size_bytes: number; sha256: string; content_type: string; category: string; visibility: string; flat_id: string; home: string; subject_resident_id: string; subject: string; expiry_date: string; author_id: string; author: string; created_at: number; expires_at: number; validation_status: string; validation_error_code: string; review_state: string; revision: number; version: number; current: boolean; uploaded: boolean; can_upload: boolean; can_replace: boolean; can_review: boolean; can_withdraw: boolean; can_archive: boolean; can_retry_validation: boolean; replaces_document_id: string; events?: { action: string; reason: string; actor: string; at: number; version: number }[]; versions?: LibraryItem[]; history_total: number; history_page: number }
type LibraryPage = { items: LibraryItem[]; homes: Home[]; can_upload: boolean; total: number; page: number; page_size: number }
const categories: Record<string, string> = { RESIDENT_DOCUMENT: 'Personal record', CIRCULAR: 'Circular', NOTICE: 'Notice', AGM_MINUTES: 'Meeting minutes', AUDIT_REPORT: 'Audit report', CONTRACT: 'Contract', AMC: 'Maintenance agreement', LEGAL: 'Legal record', COMMITTEE_DOCUMENT: 'Committee record', PAYMENT_EVIDENCE: 'Payment evidence', INVOICE: 'Invoice', RECEIPT: 'External receipt', ACCOUNTING_EXPORT: 'Accounting export' }
const audiences: Record<string, string> = { RESIDENT_SPECIFIC: 'Named person & reviewers', FLAT_SPECIFIC: 'Current home members', ALL_AUTHORIZED_RESIDENTS: 'Current society residents', COMMITTEE_ONLY: 'Committee', ACCOUNTING_ONLY: 'Accounting team' }
const decisions: Record<string, string> = { APPROVED: 'Approve this version', DECLINED: 'Decline this version', WITHDRAWN: 'Withdraw this upload', ARCHIVED: 'Archive this collection', RETRY_VALIDATION: 'Retry unavailable file checks' }
const states: Record<string, string> = { PENDING: 'Awaiting review', APPROVED: 'Approved', DECLINED: 'Declined', WITHDRAWN: 'Withdrawn', ARCHIVED: 'Archived' }
const checkErrors: Record<string, string> = { INVALID_PDF: 'The PDF structure could not be verified. Export a fresh plain PDF and upload that copy.', UNSUPPORTED_PDF_CONTENT: 'This PDF contains unsupported active content or exceeds the allowed complexity. Use a plain PDF without forms, scripts, attachments or external actions.', ENCRYPTED_PDF: 'Use an unencrypted PDF that the reviewer can open.', CHECKS_UNAVAILABLE: 'PDF checking is temporarily unavailable. An authorized person can retry these checks after the checker is restored.', PDF_CHECK_LIMIT: 'The PDF exceeded the file-checking limit. Export a smaller, simpler document.', INVALID_IMAGE: 'This image is damaged or incomplete. Choose a fresh PNG or JPEG.', TYPE_MISMATCH: 'The actual file content does not match its filename extension.', IMAGE_TOO_LARGE: 'Use an image up to 8 megapixels, with each dimension at most 8192 pixels.', CHECKSUM_MISMATCH: 'The saved original did not match its upload checksum.', UNSUPPORTED_TYPE: 'Only plain PDF, PNG and JPEG files are supported.' }
const options = (values: Record<string, string>) => Object.entries(values).map(([value, label]) => ({ value, label }))
const size = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`
const date = (value: number) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'Asia/Kolkata' }).format(new Date(value * 1000))
function visibleState(item: LibraryItem) { return item.review_state !== 'PENDING' ? states[item.review_state] : item.validation_status === 'REJECTED' ? 'File needs attention' : item.validation_status === 'ABANDONED' ? 'Upload expired' : !item.uploaded ? 'Upload unfinished' : item.validation_status !== 'AVAILABLE' ? 'Checking file' : 'Awaiting review' }
function reveal(element: HTMLElement | null) { if (!element) return; const scroll = element.closest<HTMLElement>('.dialog-scroll'); if (scroll) { const a = element.getBoundingClientRect(), b = scroll.getBoundingClientRect(); scroll.scrollTo({ top: scroll.scrollTop + a.top - b.top - Math.max(0, (b.height - a.height) / 2), behavior: 'instant' }) } else element.scrollIntoView({ block: 'center', behavior: 'instant' }) }
function initialDocument() { const match = window.location.hash.match(/^#documents\?file=([A-Za-z0-9_-]{43})$/); return match?.[1] ?? '' }

function LibraryArt() { return <svg className="document-art" aria-hidden="true" viewBox="0 0 230 190" fill="none"><circle cx="116" cy="96" r="83" fill="#ebe5d7" /><rect x="68" y="20" width="96" height="132" rx="9" transform="rotate(8 68 20)" fill="#cbd4bb" /><rect x="52" y="24" width="96" height="132" rx="9" transform="rotate(-8 52 24)" fill="#fffef8" stroke="#c6ceba" strokeWidth="2" /><path d="M73 53h47M71 66h57M69 80h43" stroke="#a1af95" strokeWidth="3" strokeLinecap="round" /><path d="M37 96h54l14 13h89v52a10 10 0 0 1-10 10H47a10 10 0 0 1-10-10V96Z" fill="#7e9164" /><path d="M38 120h160l-13 48H49l-11-48Z" fill="#d7dfc7" /><path d="M166 173v-36m0 19-12-12m12 3 10-14" stroke="#536e50" strokeWidth="3" strokeLinecap="round" /><ellipse cx="162" cy="130" rx="18" ry="25" transform="rotate(-25 162 130)" fill="#a3b48c" /><circle cx="186" cy="54" r="16" fill="#f9faf2" /><path d="m180 54 4 4 8-9" stroke="#5d7857" strokeWidth="2.5" strokeLinecap="round" /></svg> }

export function Documents({ user }: { user: User }) {
 const [data, setData] = useState<LibraryPage | null>(null)
 const [query, setQuery] = useState(''), [category, setCategory] = useState(''), [state, setState] = useState(''), [page, setPage] = useState(1)
 const [revision, setRevision] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState('')
 const [selected, setSelected] = useState(initialDocument), [upload, setUpload] = useState<LibraryItem | 'new' | null>(null)
 const feedback = useRef<HTMLDivElement>(null)
 useFragmentSync(()=>{ const callback = () => setSelected(initialDocument()); callback()},[])
 useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); const timer = window.setTimeout(() => request<LibraryPage>('/api/documents?' + new URLSearchParams({ q: query, category, state, page: String(page) }), controller.signal).then(result => { setData(result); setLoading(false) }).catch((err: Error) => { if (!controller.signal.aborted) { setError(err.message); setLoading(false) } }), query ? 180 : 0); return () => { controller.abort(); clearTimeout(timer) } }, [query, category, state, page, revision])
 useEffect(() => { if (error) reveal(feedback.current) }, [error])
 const clear = () => { setQuery(''); setCategory(''); setState(''); setPage(1) }
 const opened = (id: string) => { setSelected(id); setRevision(n => n + 1) }
 return <div className="page-enter documents-page">
  <section className="reviews-hero document-heading"><div><span className="eyebrow">A LITTLE ORDER. A LOT OF REASSURANCE.</span><h1>Good records.<br /><em>Peace of mind.</em></h1><p>The important papers, together. Shared with the right people.</p>{data?.can_upload && <button className="button button-dark" onClick={() => setUpload('new')}>Add a document<Icon name="plus" /></button>}</div><LibraryArt /></section>
  <div className="review-principles"><span><Icon name="document" />The original, kept safely</span><span><Icon name="check" />A second pair of eyes</span><span><Icon name="shield" />Access that follows people</span></div>
  <section className="registry-panel" aria-labelledby="library-title"><div className="registry-toolbar"><div><h2 id="library-title">Your document library</h2><p>{user.can_manage_documents || user.can_read_all_records ? 'Review new files. Keep approved versions easy to find.' : 'Your own uploads and the approved documents you can access.'}</p></div><span className="result-count" role="status">{loading ? 'Opening the library…' : error ? 'Connection unavailable' : `${data?.total ?? 0} documents found`}</span></div>
   <div className="filter-row"><label className="search-control"><Icon name="search" /><span className="sr-only">Search documents</span><input type="search" maxLength={100} placeholder="Find a document or filename…" value={query} onChange={event => { setQuery(event.target.value); setPage(1) }} /></label><FilterSelect label="Filter document category" value={category} onChange={value => { setCategory(value); setPage(1) }} options={[{ value: '', label: 'All categories' }, ...options(categories)]} /><FilterSelect label="Filter document state" value={state} onChange={value => { setState(value); setPage(1) }} options={[{ value: '', label: 'Current & pending' }, ...options(states)]} /><button className="clear-button" disabled={!query && !category && !state} onClick={clear}>Clear<Icon name="close" /></button></div>
   <div aria-busy={loading}>{error ? <div className="empty-state" role="alert" ref={feedback}><Icon name="globe" /><h3>Let’s open that again.</h3><p>{error}</p><button className="button button-dark" onClick={() => setRevision(n => n + 1)}>Try again<Icon name="refresh" /></button></div> : loading ? <div className="home-skeleton skeleton" aria-hidden="true" /> : !data?.items.length ? <div className="records-empty"><span className="chapter-icon"><Icon name="document" /></span><h3>{query || category || state ? 'Nothing matches just yet.' : 'A place for the papers that matter.'}</h3><p>{query || category || state ? 'Try another word, category or review state.' : 'Start with a fictional document. Shared files need a different person to approve them.'}</p>{query || category || state ? <button className="text-link" onClick={clear}>Clear filters<Icon name="arrow" /></button> : data?.can_upload && <button className="text-link" onClick={() => setUpload('new')}>Add your first document<Icon name="plus" /></button>}</div> : <div className="document-grid">{data.items.map(item => <button key={item.id} className="document-card" aria-label={`Open document ${item.title}`} onClick={() => setSelected(item.id)}><span className="document-card-top"><span className={`document-paper paper-${item.category === 'CIRCULAR' || item.category === 'NOTICE' ? 'sand' : item.category === 'RESIDENT_DOCUMENT' ? 'sage' : 'lavender'}`}><Icon name="document" /><small>{item.filename.split('.').at(-1)?.toUpperCase()}</small></span><span className={`review-status review-state review-${item.review_state.toLowerCase()}`}>{visibleState(item)}</span></span><span className="eyebrow">{categories[item.category]}</span><strong>{item.title}</strong><span className="document-filename">{item.filename} · {size(item.size_bytes)}</span><span className="review-row-bottom"><span>{item.home ? 'Home ' + item.home : audiences[item.visibility]}{item.revision ? ' · Revision ' + item.revision : ''}</span><Icon name="arrow" /></span></button>)}</div>}</div>
   {data && !loading && !error && data.total > 0 && <div className="pagination"><span>Showing {(data.page - 1) * 12 + 1}–{Math.min(data.page * 12, data.total)} of {data.total} documents</span><div><button aria-label="Previous documents page" disabled={data.page === 1} onClick={() => setPage(data.page - 1)}><Icon name="left" /></button><span>Page {data.page} of {Math.ceil(data.total / 12)}</span><button aria-label="Next documents page" disabled={data.page * 12 >= data.total} onClick={() => setPage(data.page + 1)}><Icon name="chevron" /></button></div></div>}
  </section><p className="records-footnote"><Icon name="shield" />Only validated originals can be downloaded. Sharing begins after separate approval.</p>
  {selected && !upload && <DocumentDetail key={selected} id={selected} onClose={() => setSelected('')} onSaved={() => setRevision(n => n + 1)} onUpload={setUpload} onOpen={setSelected} />}
  {upload && <UploadDocument user={user} homes={data?.homes ?? []} existing={upload === 'new' ? null : upload} onClose={() => setUpload(null)} onSaved={id => { setUpload(null); opened(id) }} />}
 </div>
}

export function UploadDocument({ user, homes, existing, paymentHome, onClose, onSaved }: { user: User; homes: Home[]; existing: LibraryItem | null; paymentHome?:Home; onClose: () => void; onSaved: (id: string) => void }) {
 const resume = existing && !existing.uploaded
 const [title, setTitle] = useState(existing?.title ?? (paymentHome?'Payment evidence · Home '+paymentHome.label:'')), [category, setCategory] = useState(existing?.category ?? (paymentHome?'PAYMENT_EVIDENCE':'RESIDENT_DOCUMENT'))
 const [audience, setAudience] = useState(existing?.visibility ?? (paymentHome?'FLAT_SPECIFIC':user.can_manage_documents ? 'COMMITTEE_ONLY' : 'RESIDENT_SPECIFIC'))
 const [home, setHome] = useState(existing?.flat_id ?? paymentHome?.id ?? ''), [subject, setSubject] = useState(existing?.subject_resident_id ?? ''), [expiry, setExpiry] = useState(existing?.expiry_date ?? '')
 const [people, setPeople] = useState<Person[]>([]), [personQuery, setPersonQuery] = useState(''), [peopleError, setPeopleError] = useState('')
 const [file, setFile] = useState<File | null>(null), [busy, setBusy] = useState(false), [locked, setLocked] = useState(false), [error, setError] = useState(''), [stage, setStage] = useState('')
 const pending = useRef<{ payload: Record<string, unknown>; id: string } | null>(null)
 const feedback = useRef<HTMLParagraphElement>(null)
 useEffect(() => { if (error || peopleError) reveal(feedback.current) }, [error, peopleError])
 useEffect(() => { if (audience !== 'RESIDENT_SPECIFIC' || !user.can_manage_documents || existing) return; const controller = new AbortController(); const timer = setTimeout(() => request<Person[]>('/api/documents/subjects?' + new URLSearchParams({ q: personQuery }), controller.signal).then(value => { setPeople(value); setPeopleError('') }).catch((err: Error) => { if (!controller.signal.aborted) setPeopleError(err.message) }), 180); return () => { clearTimeout(timer); controller.abort() } }, [audience, personQuery, user.can_manage_documents, existing])
 const finance = ['PAYMENT_EVIDENCE', 'INVOICE', 'RECEIPT', 'ACCOUNTING_EXPORT'].includes(category)
 const categoryOptions = options(categories).filter(item => item.value === 'COMMITTEE_DOCUMENT' ? user.can_manage_documents : ['INVOICE', 'RECEIPT', 'ACCOUNTING_EXPORT'].includes(item.value) ? user.can_read_all_records : item.value !== 'PAYMENT_EVIDENCE' || user.can_read_records)
 const audienceOptions = finance ? options(audiences).filter(item => item.value === 'FLAT_SPECIFIC' || (item.value === 'ACCOUNTING_ONLY' && user.can_read_all_records && category !== 'PAYMENT_EVIDENCE')) : options(audiences).filter(item => item.value !== 'ACCOUNTING_ONLY' && (item.value !== 'COMMITTEE_ONLY' || user.can_manage_documents))
 const changeCategory = (value: string) => { setCategory(value); setHome(''); setSubject(''); setExpiry(''); setAudience(value === 'COMMITTEE_DOCUMENT' ? 'COMMITTEE_ONLY' : ['PAYMENT_EVIDENCE', 'INVOICE', 'RECEIPT', 'ACCOUNTING_EXPORT'].includes(value) ? 'FLAT_SPECIFIC' : user.can_manage_documents ? 'COMMITTEE_ONLY' : 'RESIDENT_SPECIFIC') }
 const save = async (event: FormEvent) => {
  event.preventDefault(); if (!file || busy) return; setBusy(true); setError('')
  try {
   if (!pending.current) {
    if (file.size < 1 || file.size > 20 * 1024 * 1024 || (/\.pdf$/i.test(file.name) && file.size > 4 * 1024 * 1024)) throw new Error('Choose a nonempty file up to 20 MB, or a PDF up to 4 MB.')
    setStage('Checking your file…'); const bytes = await file.arrayBuffer(); const sum = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes))).map(value => value.toString(16).padStart(2, '0')).join('')
    if (resume && (file.size !== existing.size_bytes || sum !== existing.sha256)) throw new Error('This upload needs the original file with the same size and content. Choose that file again.')
    pending.current = { id: resume ? existing.id : '', payload: { operation_key: crypto.randomUUID(), title: title.trim(), filename: file.name, size_bytes: file.size, sha256: sum, category, visibility: audience, flat_id: audience === 'FLAT_SPECIFIC' ? home : '', subject_resident_id: audience === 'RESIDENT_SPECIFIC' ? subject : '', expiry_date: expiry, replaces_document_id: existing && !resume ? existing.id : '', version: existing && !resume ? existing.version : 0 } }
   }
   if (!pending.current.id) { setStage('Saving the upload details…'); const result = await mutate<{ id: string }>('/api/documents', 'POST', pending.current.payload); pending.current.id = result.id }
   setStage('Uploading the original…'); await uploadOriginal(pending.current.id, file); onSaved(pending.current.id)
  } catch (err) { setError((err as Error).message); if (!pending.current?.id && err instanceof APIError && [400, 403, 404, 409].includes(err.status)) { pending.current = null; setLocked(false) } else setLocked(!!pending.current) }
  finally { setBusy(false); setStage('') }
 }
 return <PortalDialog titleId="upload-document-title" closeLabel="Close document upload" busy={busy} onClose={onClose}><div className="dialog-heading reviews-dialog-heading"><span className="eyebrow">{resume ? 'FINISH YOUR UPLOAD' : existing ? 'A NEW VERSION, THE SAME STORY' : 'MAKE ROOM FOR THE IMPORTANT PAPERS'}</span><h2 id="upload-document-title">{resume ? <>Pick up where<br /><em>you left off.</em></> : existing ? <>Keep the record<br /><em>up to date.</em></> : <>A place for<br /><em>this paper.</em></>}</h2><p>{existing && !resume ? 'The approved original stays available until a different person approves this version.' : 'The original stays private while it is checked and reviewed.'}</p></div><div className="dialog-scroll detail-body"><form className="portal-form" onSubmit={save}><fieldset className="records-fieldset" disabled={busy || locked}>
  <label>File<span className="document-upload-target"><input className="document-file-input" type="file" aria-label="Document file" accept=".pdf,.png,.jpg,.jpeg" required onChange={event => { setFile(event.target.files?.[0] ?? null); setError('') }} /><Icon name="document" /><strong>{file?.name ?? 'Choose a document'}</strong><span>{file ? size(file.size) : 'PDF, PNG or JPEG'}</span></span></label>
  <label>Title<input value={title} disabled={!!resume} onChange={event => setTitle(event.target.value)} minLength={5} maxLength={120} required placeholder="A name that is easy to find" /></label>
  {paymentHome ? <p className="document-fixed-scope">Payment evidence · Home {paymentHome.label} · private upload awaiting review</p> : existing ? <p className="document-fixed-scope">{categories[category]} · {audiences[audience]}{existing.home ? ' · Home ' + existing.home : existing.subject ? ' · ' + existing.subject : ''}</p> : <><label>Category<FormSelect label="Document category" value={category} onChange={changeCategory} options={categoryOptions} /></label><label>Who can see it after approval?<FormSelect label="Document audience" value={audience} onChange={value => { setAudience(value); setHome(''); setSubject('') }} options={category === 'COMMITTEE_DOCUMENT' ? [{ value: 'COMMITTEE_ONLY', label: audiences.COMMITTEE_ONLY }] : audienceOptions} /></label>{audience === 'FLAT_SPECIFIC' && <label>Home<FormSelect label="Document home" value={home} onChange={setHome} required options={[{ value: '', label: 'Choose a home…' }, ...homes.map(item => ({ value: item.id, label: 'Home ' + item.label }))]} /></label>}{audience === 'RESIDENT_SPECIFIC' && user.can_manage_documents && <><label>Find the person<input aria-label="Find document subject" value={personQuery} onChange={event => setPersonQuery(event.target.value)} maxLength={100} placeholder="A registry name…" /></label><label>Person<FormSelect label="Document subject" value={subject} onChange={setSubject} required options={[{ value: '', label: 'Choose the person…' }, ...people.map(item => ({ value: item.id, label: item.name }))]} /></label></>}</>}
  {(category === 'CONTRACT' || category === 'AMC') && <label>Expiry date (optional)<input type="date" aria-label="Document expiry date" value={expiry} onChange={event => setExpiry(event.target.value)} /></label>}
  </fieldset>{finance && <p className="form-help">This is an uploaded financial document. It does not confirm money received, post an entry or create a portal receipt.</p>}<p className="form-help">Images: up to 20 MB and 8 megapixels. Plain PDFs: up to 4 MB and 250 pages. No forms, scripts, attachments or encrypted PDFs.</p>{(error || peopleError) && <p className="form-error" role="alert" ref={feedback}>{error || peopleError}</p>}{locked && <p className="form-help">Retry uses this same file and upload identity.</p>}<button className="button button-dark" disabled={busy || !file}>{busy ? stage || 'Saving…' : locked ? 'Retry this upload' : resume ? 'Finish upload' : existing ? 'Upload replacement' : 'Upload for review'}<Icon name="arrow" /></button></form></div></PortalDialog>
}

function DocumentDetail({ id, onClose, onSaved, onUpload, onOpen }: { id: string; onClose: () => void; onSaved: () => void; onUpload: (item: LibraryItem) => void; onOpen: (id: string) => void }) {
 const [item, setItem] = useState<LibraryItem | null>(null), [historyPage, setHistoryPage] = useState(1), [revision, setRevision] = useState(0), [loading, setLoading] = useState(true), [loadError, setLoadError] = useState('')
 const [action, setAction] = useState(''), [reason, setReason] = useState(''), [confirmed, setConfirmed] = useState(false), [busy, setBusy] = useState(false), [locked, setLocked] = useState(false), [error, setError] = useState(''), [downloading, setDownloading] = useState(false)
 const pending = useRef<Record<string, unknown> | null>(null), polls = useRef(0), feedback = useRef<HTMLDivElement>(null)
 useEffect(() => { if (error) reveal(feedback.current) }, [error])
 useEffect(() => { const controller = new AbortController(); setLoading(true); setLoadError(''); request<LibraryItem>(`/api/documents/${encodeURIComponent(id)}?history_page=${historyPage}`, controller.signal).then(value => { setItem(value); setLoading(false) }).catch((err: Error) => { if (!controller.signal.aborted) { if (err instanceof APIError && [403, 404].includes(err.status)) setItem(null); setLoadError(err.message); setLoading(false) } }); return () => controller.abort() }, [id, historyPage, revision])
 useEffect(() => { if (!item?.uploaded || !['PENDING', 'VALIDATING'].includes(item.validation_status) || loading || polls.current >= 24) return; const timer = setTimeout(() => { polls.current++; setRevision(n => n + 1) }, 700); return () => clearTimeout(timer) }, [item, loading])
 const reload = () => { polls.current = 0; pending.current = null; setLocked(false); setError(''); setAction(''); setConfirmed(false); setRevision(n => n + 1) }
 const save = async (event: FormEvent) => { event.preventDefault(); if (!item || busy || loading) return; setBusy(true); setError(''); pending.current ??= { operation_key: crypto.randomUUID(), version: item.version, action, reason: reason.trim(), confirmed }; try { await mutate(`/api/documents/${item.id}/actions`, 'POST', pending.current); pending.current = null; setLocked(false); setReason(''); setAction(''); setConfirmed(false); setRevision(n => n + 1); onSaved() } catch (err) { setError((err as Error).message); if (err instanceof APIError && [400, 403, 404, 409].includes(err.status)) { pending.current = null; setLocked(false) } else setLocked(true) } finally { setBusy(false) } }
 const download = async () => { if (!item || busy) return; setBusy(true); setDownloading(true); setError(''); try { const response = await fetch(`/api/documents/${encodeURIComponent(item.id)}/download`, { cache: 'no-store', credentials: 'same-origin' }); if (!response.ok) { if (response.status === 401) window.dispatchEvent(new Event('session-expired')); throw new Error(response.status === 403 || response.status === 404 ? 'Your current account cannot download this document.' : 'The original could not be downloaded. Try again.') }; const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = item.filename; document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000) } catch (err) { setError((err as Error).message) } finally { setDownloading(false); setBusy(false) } }
 const allowed = item ? [...(item.can_review ? item.validation_status === 'AVAILABLE' ? ['APPROVED', 'DECLINED'] : ['DECLINED'] : []), ...(item.can_withdraw ? ['WITHDRAWN'] : []), ...(item.can_archive ? ['ARCHIVED'] : []), ...(item.can_retry_validation ? ['RETRY_VALIDATION'] : [])] : []
 return <PortalDialog titleId="document-detail-title" closeLabel="Close document details" busy={busy} onClose={onClose}><div className="dialog-heading reviews-dialog-heading review-detail-heading"><span className="eyebrow">{item ? categories[item.category] : 'YOUR DOCUMENT'}</span><h2 id="document-detail-title">{item?.title ?? (loadError ? 'Document unavailable' : 'Opening the record…')}</h2>{item && <span className={`review-status review-state review-${item.review_state.toLowerCase()}`}>{visibleState(item)}</span>}</div><div className="dialog-scroll detail-body" aria-busy={loading}>
  {loadError ? <div className="empty-state" role="alert"><p>{loadError}</p><button className="button button-dark" onClick={reload}>Reload document<Icon name="refresh" /></button></div> : !item ? <p role="status">Opening the details…</p> : <>
   <div className="document-original"><span className="document-paper paper-sage"><Icon name="document" /></span><div><strong>{item.filename}</strong><p>{size(item.size_bytes)}{item.revision ? ' · Revision ' + item.revision : ''}</p></div>{item.validation_status === 'AVAILABLE' && <button className="button button-dark" disabled={busy || loading} onClick={() => void download()}>{downloading ? 'Downloading…' : 'Download original'}<Icon name="arrow" /></button>}</div>
   <dl className="record-facts"><div><dt>Audience after approval</dt><dd>{audiences[item.visibility]}{item.home ? ' · Home ' + item.home : item.subject ? ' · ' + item.subject : ''}</dd></div><div><dt>Added by</dt><dd>{item.author} · {date(item.created_at)}</dd></div>{item.expiry_date && <div><dt>Expiry date</dt><dd>{item.expiry_date}</dd></div>}</dl>
   {item.validation_status === 'REJECTED' ? <div className="form-error" role="alert">{checkErrors[item.validation_error_code] ?? 'File checks could not accept this original. Choose a fresh supported file.'}</div> : item.validation_status === 'ABANDONED' ? <p className="form-help">The unused upload reservation expired. The approved collection, if any, is preserved. Start a fresh upload.</p> : item.can_upload ? <button className="button button-dark" disabled={busy} onClick={() => onUpload(item)}>Finish this upload<Icon name="arrow" /></button> : item.uploaded && item.validation_status !== 'AVAILABLE' ? <div className="document-checking" role="status"><Icon name="shield" /><p>The original is saved. File checks must finish before anyone can approve or download it.</p><button className="text-link" onClick={reload}>Check again<Icon name="refresh" /></button></div> : item.review_state === 'PENDING' ? <p className="form-help">The file passed its checks. A different authorized person must review the file and audience before sharing begins.</p> : null}
   {item.can_replace && <button className="text-link document-replace" disabled={busy || loading} onClick={() => onUpload(item)}>Add a new version<Icon name="plus" /></button>}
   {item.versions && item.versions.length > 0 && <section className="review-history case-conversation document-versions" aria-label="Document versions"><h3>The originals, together.</h3><ol>{item.versions.map(version => <li key={version.id}><button className="document-version-link" disabled={version.id === item.id || busy || loading} onClick={() => onOpen(version.id)}><span><strong>{version.title}</strong><small>{version.revision ? 'Revision ' + version.revision : visibleState(version)} · {version.filename}</small></span>{version.current ? <span className="document-current">Current</span> : <Icon name="arrow" />}</button></li>)}</ol>{item.history_total > 12 && <div className="pagination"><span>{item.history_total} permitted versions</span><div><button aria-label="Newer document versions" disabled={loading || item.history_page === 1} onClick={() => setHistoryPage(item.history_page - 1)}><Icon name="left" /></button><span>{item.history_page}/{Math.ceil(item.history_total / 12)}</span><button aria-label="Older document versions" disabled={loading || item.history_page * 12 >= item.history_total} onClick={() => setHistoryPage(item.history_page + 1)}><Icon name="chevron" /></button></div></div>}</section>}
   {item.events?.length ? <section className="review-history case-conversation" aria-label="Private document review history"><h3>The review trail.</h3><ol>{item.events.map(event => <li key={event.version}><strong>{decisions[event.action] ?? event.action.replaceAll('_', ' ').toLowerCase()}</strong><p>{event.reason}</p><small>{event.actor} · {date(event.at)}</small></li>)}</ol></section> : null}
   {allowed.length > 0 && <form className="portal-form case-update" onSubmit={save}><h3>A thoughtful next step.</h3><fieldset className="records-fieldset" disabled={busy || locked || loading}><label>Decision<FormSelect label="Document decision" value={action} onChange={setAction} required options={[{ value: '', label: 'Choose the next step…' }, ...allowed.map(value => ({ value, label: decisions[value] }))]} /></label><label>Reason<textarea aria-label="Document decision reason" value={reason} onChange={event => setReason(event.target.value)} minLength={5} maxLength={300} rows={3} required placeholder="What did you check, and why this decision?" /></label><label className="checkbox-label"><input type="checkbox" required checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />I have checked this version, its audience and my decision.</label></fieldset><button className="button button-dark" disabled={busy || loading}>{busy ? 'Saving the decision…' : locked ? 'Retry this decision' : 'Save document decision'}<Icon name="check" /></button></form>}
   {error && <div className="form-error" role="alert" ref={feedback}><p>{error}</p>{!locked && <button className="text-link" type="button" onClick={reload}>Reload latest document<Icon name="refresh" /></button>}</div>}{locked && <p className="form-help">Retry preserves this same decision identity.</p>}
  </>}
 </div></PortalDialog>
}
