import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import type { User } from '../api'
import { fundActions, fundStates, lineStates, selectOptions, useFundLoad, useFundWrite } from '../collections'
import type { FundDetail, FundLine } from '../collections'
import { dateToday, displayDate, exactPaise, money } from '../maintenance'
import type { FinancialHome } from '../maintenance'
import { FormSelect } from './FilterSelect'
import { FundCheck, FundFeedback, FundHistory, FundUnavailable } from './FundShared'
import { Icon } from './Icon'
import { PageControls } from './Maintenance'
import { PortalDialog } from './PortalDialog'

export function NewFund({homes,onClose,onCreated}:{homes:FinancialHome[];onClose:()=>void;onCreated:(id:string)=>void}){
 const writer=useFundWrite(),scroll=useRef<HTMLDivElement>(null),review=useRef<HTMLHeadingElement>(null)
 const [title,setTitle]=useState(''),[purpose,setPurpose]=useState(''),[kind,setKind]=useState('FIXED'),[start,setStart]=useState(dateToday),[due,setDue]=useState(''),[target,setTarget]=useState(''),[source,setSource]=useState(''),[note,setNote]=useState('')
 const [lines,setLines]=useState([{key:crypto.randomUUID(),flat_id:'',amount:''}]),[bulk,setBulk]=useState(''),[preview,setPreview]=useState(false),[checked,setChecked]=useState(false),[error,setError]=useState('')
 useEffect(()=>{scroll.current?.scrollTo({top:0});if(preview)review.current?.focus()},[preview])
 const total=kind==='FIXED'?lines.reduce((sum,line)=>sum+(exactPaise(line.amount)??0),0):0
 const prepare=(event:FormEvent)=>{
  event.preventDefault();setError('')
  if(due<start){setError('The due date must be on or after the fund starts.');return}
  if(lines.some(line=>!line.flat_id||(kind==='FIXED'&&exactPaise(line.amount)===null))||new Set(lines.map(line=>line.flat_id)).size!==lines.length){setError('Choose distinct homes and supply each fixed amount to at most two decimal places.');return}
  if(target&&exactPaise(target)===null){setError('An optional target must be a positive amount to at most two decimal places.');return}
  setPreview(true);setChecked(false)
 }
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!checked||writer.conflict)return;const result=await writer.send('/api/collections',{title:title.trim(),purpose:purpose.trim(),contribution_type:kind,start_date:start,due_date:due,target,source_reference:source.trim(),note:note.trim(),lines:lines.map(line=>({flat_id:line.flat_id,amount:kind==='FIXED'?line.amount:''}))});if(result)onCreated(result.id)}
 const includeAll=()=>setLines(old=>[...old.filter(line=>line.flat_id),...homes.filter(home=>!old.some(line=>line.flat_id===home.id)).map(home=>({key:crypto.randomUUID(),flat_id:home.id,amount:''}))])
 return <PortalDialog titleId="new-fund-title" closeLabel="Close fund preparation" busy={writer.busy} onClose={onClose} className="maintenance-dialog fund-dialog"><div className="dialog-heading records-dialog-heading"><span className="eyebrow">{preview?'A SHARED PURPOSE, REVIEWED':'SOMETHING WORTH COMING TOGETHER FOR'}</span><h2 id="new-fund-title">A new <em>possibility.</em></h2><p>{preview?'Check the purpose, participants and supplied amounts before freezing this proposal.':'Prepare a fund from the society’s supplied approval record.'}</p></div><div className="dialog-scroll detail-body" ref={scroll}>
 {!preview?<form className="portal-form" onSubmit={prepare}><fieldset className="records-fieldset"><label>Fund title<input required minLength={5} maxLength={120} value={title} onChange={event=>setTitle(event.target.value)} placeholder="For example, a garden we grow together"/></label><label>Purpose to share with participants<textarea required minLength={10} maxLength={2000} rows={3} value={purpose} onChange={event=>setPurpose(event.target.value)} placeholder="What this collection is for…"/></label><label>Contribution type<FormSelect label="Contribution type" value={kind} onChange={setKind} options={[{value:'FIXED',label:'Fixed supplied amounts'},{value:'VOLUNTARY',label:'Voluntary contributions'}]}/></label><p className="form-help">{kind==='FIXED'?'Publication creates the supplied charges after a different treasury reviewer approves.':'Voluntary participation creates no charge or unpaid balance.'}</p><div className="form-pair"><label>Fund starts<input type="date" required min="1900-01-01" max="2100-12-31" value={start} onChange={event=>setStart(event.target.value)}/></label><label>Supplied due date<input type="date" required min={start} max="2100-12-31" value={due} onChange={event=>setDue(event.target.value)}/></label></div><label>Optional collection target<input inputMode="decimal" maxLength={11} value={target} onChange={event=>setTarget(event.target.value)} placeholder="Leave empty if no target was supplied"/></label><label>Private source / approval reference<input required minLength={5} maxLength={300} value={source} onChange={event=>setSource(event.target.value)} placeholder="The supplied approval reference"/></label><label>Private supporting note (optional)<textarea maxLength={2000} rows={2} value={note} onChange={event=>setNote(event.target.value)}/></label>
 <div className="maintenance-participants"><div className="section-heading"><h3>Participating homes</h3><button type="button" className="text-link" onClick={includeAll}>Include all homes<Icon name="plus"/></button></div>{kind==='FIXED'&&<div className="maintenance-bulk"><label>Supplied amount for selected homes<input inputMode="decimal" maxLength={11} value={bulk} onChange={event=>setBulk(event.target.value)}/></label><button type="button" className="button button-light" onClick={()=>{if(exactPaise(bulk)===null){setError('Enter a positive supplied amount first.');return}setLines(old=>old.map(line=>({...line,amount:bulk})));setError('')}}>Apply supplied amount</button></div>}
 {lines.map((line,index)=><div className={'maintenance-participant '+(kind==='VOLUNTARY'?'fund-voluntary-participant':'')} key={line.key}><label>Home {index+1}<FormSelect label={'Fund participating home '+(index+1)} required value={line.flat_id} onChange={value=>setLines(old=>old.map(item=>item.key===line.key?{...item,flat_id:value}:item))} options={[{value:'',label:'Choose a home…'},...homes.filter(home=>home.id===line.flat_id||!lines.some(item=>item.flat_id===home.id)).map(home=>({value:home.id,label:'Home '+home.label}))]}/></label>{kind==='FIXED'&&<label>Amount for home {index+1}<input required inputMode="decimal" pattern="(0|[1-9][0-9]{0,7})([.][0-9]{1,2})?" maxLength={11} value={line.amount} onChange={event=>setLines(old=>old.map(item=>item.key===line.key?{...item,amount:event.target.value}:item))}/></label>}<button type="button" className="icon-button" aria-label={'Remove fund home '+(index+1)} disabled={lines.length===1} onClick={()=>setLines(old=>old.filter(item=>item.key!==line.key))}><Icon name="close"/></button></div>)}<button type="button" className="text-link" disabled={lines.length>=homes.length} onClick={()=>setLines(old=>[...old,{key:crypto.randomUUID(),flat_id:'',amount:''}])}>Add a participating home<Icon name="plus"/></button></div></fieldset>{error&&<p role="alert" className="form-error">{error}</p>}<div className="maintenance-form-total"><span>{lines.length} participating homes</span><strong>{kind==='FIXED'?money(total):'Voluntary'}</strong></div><button className="button button-dark">Review this fund<Icon name="arrow"/></button></form>:
 <form className="portal-form" onSubmit={submit}><h3 tabIndex={-1} ref={review} className="maintenance-review-title">{title}</h3><p className="review-body">{purpose}</p><dl className="record-facts"><div><dt>Contribution type</dt><dd>{kind==='FIXED'?'Fixed supplied amounts':'Voluntary · no debt'}</dd></div><div><dt>Dates</dt><dd>{displayDate(start)} · Due {displayDate(due)}</dd></div>{target&&<div><dt>Target</dt><dd>{money(exactPaise(target)??0)}</dd></div>}<div><dt>Private source</dt><dd>{source}</dd></div>{note&&<div><dt>Private note</dt><dd>{note}</dd></div>}</dl><ul className="maintenance-review-lines">{lines.map(line=><li key={line.key}><span>Home {homes.find(home=>home.id===line.flat_id)?.label}</span><strong>{kind==='FIXED'?money(exactPaise(line.amount)??0):'Voluntary'}</strong></li>)}</ul><div className="maintenance-form-total"><span>Frozen proposal · {lines.length} homes</span><strong>{kind==='FIXED'?money(total):'No charge'}</strong></div><FundCheck checked={checked} onChange={setChecked} disabled={writer.busy||writer.locked}>I reviewed the supplied purpose, dates, participants and amounts.</FundCheck><FundFeedback writer={writer} onReload={()=>{writer.reset();setPreview(false);setChecked(false)}}/><div className="form-actions"><button className="button button-dark" disabled={!checked||writer.busy||writer.conflict}>{writer.busy?'Submitting fund…':writer.locked?'Retry fund submission':'Submit fund for separate review'}<Icon name="arrow"/></button><button type="button" className="text-link" disabled={writer.busy||writer.locked} onClick={()=>setPreview(false)}>Edit the proposal</button></div><p className="form-help">A different current treasury reviewer must publish this fund. Submission creates no charge or receipt.</p></form>}
 </div></PortalDialog>
}

export function FundCampaignDialog({id,user,onClose,onSaved,onReport,onWaiver,onAttribute}:{id:string;user:User;onClose:()=>void;onSaved:()=>void;onReport:(campaign:FundDetail,line:FundLine)=>void;onWaiver:(campaign:FundDetail,line:FundLine)=>void;onAttribute:(campaign:FundDetail,line:FundLine)=>void}){
 const [linePage,setLinePage]=useState(1),[eventPage,setEventPage]=useState(1),[action,setAction]=useState(''),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[saved,setSaved]=useState('')
 const load=useFundLoad<FundDetail>('/api/collections/'+encodeURIComponent(id)+'?'+new URLSearchParams({line_page:String(linePage),event_page:String(eventPage)})),writer=useFundWrite(),data=load.data
 const reload=()=>{writer.reset();setAction('');setReason('');setChecked(false);load.reload()}
 const available:Record<string,string>={}
 if(data&&user.can_manage_records){if(data.state==='PENDING'){if(data.author_id!==user.id){available.PUBLISHED=fundActions.PUBLISHED;available.DECLINED=fundActions.DECLINED}else available.WITHDRAWN='Withdraw proposal'}if(data.state==='PUBLISHED')available.CLOSED=fundActions.CLOSED;if(data.state==='CLOSED')available.REOPEN=fundActions.REOPEN}
 const save=async(event:FormEvent)=>{event.preventDefault();if(!data||!checked||writer.conflict||load.loading)return;const result=await writer.send('/api/collections/'+id+'/actions',{version:data.version,action,reason:reason.trim()});if(result){setSaved('Fund action recorded.');reload();onSaved()}}
 const live=data?.state==='PUBLISHED'||data?.state==='CLOSED'
 return <PortalDialog titleId="fund-detail-title" closeLabel="Close fund details" busy={writer.busy} onClose={onClose} className="maintenance-dialog fund-dialog"><div className="dialog-heading records-dialog-heading"><span className="eyebrow">A SHARED PURPOSE</span><h2 id="fund-detail-title">{load.error?'Fund unavailable.':data?.title??'Opening this fund…'}</h2>{data&&!load.loading&&!load.error&&<span className={'fund-state fund-state-'+data.state.toLowerCase()}>{fundStates[data.state]}</span>}</div><div className="dialog-scroll detail-body"><FundUnavailable error={load.error} loading={load.loading} onRetry={reload}>{data&&<>
 <p className="review-body">{data.purpose}</p><dl className="record-facts"><div><dt>Contribution type</dt><dd>{data.contribution_type==='FIXED'?'Fixed supplied amounts':'Voluntary · no debt'}</dd></div><div><dt>Dates</dt><dd>{displayDate(data.start_date)} · Due {displayDate(data.due_date)}</dd></div>{data.target_paise>0&&<div><dt>Collection target</dt><dd>{money(data.target_paise)}</dd></div>}{user.can_read_all_records&&<><div><dt>Private source</dt><dd>{data.source_reference}</dd></div>{data.note&&<div><dt>Private note</dt><dd>{data.note}</dd></div>}<div><dt>Proposed by</dt><dd>{data.author}</dd></div></>}</dl>
 <button type="button" className="text-link fund-evidence-download" disabled={writer.busy||writer.locked} onClick={reload}>Refresh fund<Icon name="refresh"/></button>
 {live?<div className="maintenance-metrics compact fund-detail-metrics">{[['Confirmed for this fund',data.allocated_paise+data.voluntary_paise],['Outstanding fixed amounts',data.outstanding_paise],['Past supplied due date',data.overdue_paise],['Approved exemptions',data.waived_paise]].map(([label,value])=><div key={label}><span>{label}</span><strong>{money(Number(value))}</strong></div>)}</div>:<div className="maintenance-proposal-note"><span className="eyebrow">FROZEN PROPOSAL</span><strong>{data.contribution_type==='FIXED'?money(data.requested_paise):'Voluntary'}</strong><p>{data.participants} participating homes · Charges begin only after separate approval.</p></div>}
 {data.contribution_type==='VOLUNTARY'&&<p className="form-help">An optional target measures the collection. Participation creates no debt or unpaid status.</p>}
 {saved&&<p className="form-success" role="status">{saved}</p>}
 {user.can_manage_records&&data.state==='PENDING'&&data.author_id===user.id&&<p className="form-help">A different treasury reviewer must publish your proposal.</p>}
 {Object.keys(available).length>0&&<form className="portal-form maintenance-decision" onSubmit={save}><h3>The next step.</h3><fieldset className="records-fieldset" disabled={writer.busy||writer.locked}><label>Fund action<FormSelect label="Fund action" required value={action} onChange={value=>{setAction(value);setChecked(false)}} options={[{value:'',label:'Choose an action…'},...selectOptions(available)]}/></label>{action&&<><p className="form-help">{action==='PUBLISHED'?data.contribution_type==='FIXED'?'Publication posts each supplied charge and keeps the proposal frozen. No received money or receipt is created.':'Publication invites voluntary contributions without posting charges.':action==='CLOSED'?'New reports close. Existing reports, allocations and history remain available.':action==='REOPEN'?'Participating homes may report already-paid money again.':'The supplied proposal and its history remain preserved.'}</p><label>Reason for the fund action<textarea required minLength={10} maxLength={300} rows={3} value={reason} onChange={event=>setReason(event.target.value)}/></label><FundCheck checked={checked} onChange={setChecked}>I reviewed this fund action and the supplied record.</FundCheck></>}</fieldset><FundFeedback writer={writer} onReload={reload}/>{action&&<button className="button button-dark" disabled={!checked||writer.busy||writer.conflict}>{writer.busy?'Saving action…':writer.locked?'Retry fund action':available[action]}<Icon name="check"/></button>}</form>}
 <div className="section-heading maintenance-lines-heading"><h3>{user.can_read_all_records?'Participating homes':'Your participating homes'}</h3><span>{data.participants} {data.participants===1?'home':'homes'}</span></div><div className="fund-lines">{data.lines.map(line=><div className="fund-line" key={line.flat_id}><div className="fund-line-top"><div><strong>Home {line.home}</strong><span className={'fund-state fund-line-state-'+line.status.toLowerCase()}>{lineStates[line.status]}</span></div><div><small>{live?(data.contribution_type==='FIXED'?'Outstanding':'Confirmed for this purpose'):'Supplied amount'}</small><strong>{data.contribution_type==='VOLUNTARY'&&!live?'Voluntary':money(live?(data.contribution_type==='FIXED'?line.outstanding_paise:line.voluntary_paise):line.requested_paise)}</strong></div></div><p>{data.contribution_type==='FIXED'?`Requested ${money(line.requested_paise)} · Linked ${money(line.allocated_paise)}${line.waived_paise?' · Exempted '+money(line.waived_paise):''}`:'Voluntary participation · no charge'}{line.pending_reports>0?' · '+line.pending_reports+' awaiting verification':''}</p><div className="fund-line-actions">{data.state==='PUBLISHED'&&<button className="text-link" disabled={writer.busy||writer.locked} onClick={()=>onReport(data,line)}>Report money already paid<Icon name="plus"/></button>}<a className="text-link" href={'#maintenance?home='+line.flat_id}>Open home statement<Icon name="arrow"/></a>{user.can_manage_records&&live&&(data.contribution_type==='VOLUNTARY'?<button className="text-link" disabled={writer.busy||writer.locked} onClick={()=>onAttribute(data,line)}>Use confirmed receipt credit<Icon name="receipt"/></button>:line.active_paise>0&&<button className="text-link" disabled={writer.busy||writer.locked} onClick={()=>onWaiver(data,line)}>Propose an exemption<Icon name="check"/></button>)}</div></div>)}</div>{data.participants>data.page_size&&<PageControls label="fund homes" page={data.line_page} total={data.participants} size={data.page_size} onPage={setLinePage} disabled={writer.busy||writer.locked}/>}
 {user.can_read_all_records&&<FundHistory events={data.events??[]} total={data.event_total??0} page={data.event_page??1} size={20} onPage={setEventPage} disabled={writer.busy||writer.locked}/>}
 </>}</FundUnavailable></div></PortalDialog>
}
