import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { request } from '../api'
import type { User } from '../api'
import { fundActions, paymentMethods, reportStates, rupees, selectOptions, useFundLoad, useFundWrite } from '../collections'
import type { ConfirmOptions, FundDetail, FundLine, PaymentReport } from '../collections'
import { dateToday, displayDate, exactPaise, money } from '../maintenance'
import { UploadDocument } from './Documents'
import type { LibraryItem } from './Documents'
import { FormSelect } from './FilterSelect'
import { FundCheck, FundFeedback, FundHistory, FundUnavailable } from './FundShared'
import { Icon } from './Icon'
import { PortalDialog } from './PortalDialog'

export function NewFundReport({user,campaign,line,initial,onClose,onSaved}:{user:User;campaign:{id:string;title:string};line:{flat_id:string;home:string};initial?:PaymentReport;onClose:()=>void;onSaved:(id:string)=>void}){
 const writer=useFundWrite(),scroll=useRef<HTMLDivElement>(null),review=useRef<HTMLHeadingElement>(null)
 const [amount,setAmount]=useState(initial?rupees(initial.amount_paise):''),[date,setDate]=useState(initial?.payment_date??dateToday()),[payer,setPayer]=useState(initial?.payer??user.name),[method,setMethod]=useState(initial?.method??'UPI'),[reference,setReference]=useState(initial?.reference??''),[comment,setComment]=useState(initial?.comment??'')
 const [preview,setPreview]=useState(false),[checked,setChecked]=useState(false),[error,setError]=useState(''),[attaching,setAttaching]=useState(false),[evidence,setEvidence]=useState(initial?.evidence_id??''),[file,setFile]=useState<LibraryItem|null>(null),[fileError,setFileError]=useState(''),[fileRetry,setFileRetry]=useState(0)
 useEffect(()=>{scroll.current?.scrollTo({top:0});if(preview)review.current?.focus()},[preview,attaching])
 useEffect(()=>{if(!evidence){setFile(null);setFileError('');return}let cancelled=false,timer=0;setFile(null);setFileError('');const poll=async()=>{try{const result=await request<LibraryItem>('/api/documents/'+encodeURIComponent(evidence));if(cancelled)return;setFile(result);if(result.validation_status==='AVAILABLE')return;if(['REJECTED','ABANDONED'].includes(result.validation_status)){setFileError('The uploaded original could not be validated. Remove it or use a fresh supported image or plain PDF.');return}timer=window.setTimeout(poll,800)}catch(err){if(!cancelled)setFileError((err as Error).message)}};void poll();return()=>{cancelled=true;clearTimeout(timer)}},[evidence,fileRetry])
 const fileReady=!evidence||file?.validation_status==='AVAILABLE'
 const prepare=(event:FormEvent)=>{event.preventDefault();setError('');if(exactPaise(amount)===null){setError('Supply the already-paid amount to at most two decimal places.');return}if(!fileReady||fileError){setError('Wait for the evidence checks or remove the optional attachment.');return}setPreview(true);setChecked(false)}
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!checked||writer.conflict||!fileReady)return;const result=await writer.send(initial?'/api/payment-reports/'+initial.id+'/revision':'/api/payment-reports',{version:initial?.version??0,campaign_id:campaign.id,flat_id:line.flat_id,amount,payment_date:date,payer:payer.trim(),method,reference:reference.trim(),comment:comment.trim(),evidence_id:evidence});if(result)onSaved(result.id)}
 if(attaching)return <UploadDocument user={user} homes={[{id:line.flat_id,label:line.home}]} existing={null} paymentHome={{id:line.flat_id,label:line.home}} onClose={()=>setAttaching(false)} onSaved={id=>{setEvidence(id);setAttaching(false)}}/>
 return <PortalDialog titleId="report-payment-title" closeLabel="Close payment report" busy={writer.busy} onClose={onClose} className="maintenance-dialog fund-dialog"><div className="dialog-heading records-dialog-heading"><span className="eyebrow">{initial?'MORE DETAILS, THE SAME REPORT':'KEEP THE ALREADY-PAID DETAILS TOGETHER'}</span><h2 id="report-payment-title">{preview?'Before you send.':'Already paid?'}</h2><p>Home {line.home} · {campaign.title}</p></div><div className="dialog-scroll detail-body" ref={scroll}>
 {!preview?<form className="portal-form" onSubmit={prepare}><fieldset className="records-fieldset"><div className="form-pair"><label>Already-paid amount<input required inputMode="decimal" pattern="(0|[1-9][0-9]{0,7})([.][0-9]{1,2})?" maxLength={11} value={amount} onChange={event=>setAmount(event.target.value)} placeholder="0.00"/></label><label>Payment date<input required type="date" min="1900-01-01" max="2100-12-31" value={date} onChange={event=>setDate(event.target.value)}/></label></div><label>Payer name<input required minLength={2} maxLength={120} value={payer} onChange={event=>setPayer(event.target.value)}/></label><label>How it was paid<FormSelect label="Reported payment method" value={method} onChange={setMethod} options={selectOptions(paymentMethods)}/></label><label>{method==='CASH'?'Payment reference (optional)':'External payment reference'}<input required={method!=='CASH'} maxLength={120} value={reference} onChange={event=>setReference(event.target.value)} placeholder="Reference from your external payment"/></label><label>Supporting comment (optional)<textarea rows={3} maxLength={2000} value={comment} onChange={event=>setComment(event.target.value)}/></label></fieldset>
 <section className="fund-evidence"><div className="section-heading"><h3>Evidence, if useful.</h3>{!evidence&&<button type="button" className="text-link" onClick={()=>setAttaching(true)}>Attach payment evidence<Icon name="plus"/></button>}</div>{evidence?<><p>{file?.filename??'Opening your uploaded original…'}</p><small>{fileReady?'Validated original · awaiting separate document review':'Checking the original…'}</small>{fileError&&<div role="alert" className="form-error"><p>{fileError}</p><button type="button" className="text-link" onClick={()=>setFileRetry(value=>value+1)}>Retry evidence checks<Icon name="refresh"/></button></div>}<button type="button" className="text-link" onClick={()=>{setEvidence('');setFile(null)}}>Remove attachment from report<Icon name="close"/></button></>:<p>A PNG, JPEG or plain PDF can support this report. It stays private while the original is checked and reviewed.</p>}</section>
 {error&&<p role="alert" className="form-error">{error}</p>}<p className="form-help">The treasury team checks the external record before confirming money received. Reporting creates no receipt.</p><button className="button button-dark" disabled={!fileReady||!!fileError}>Review payment report<Icon name="arrow"/></button></form>:
 <form className="portal-form" onSubmit={submit}><h3 tabIndex={-1} ref={review} className="maintenance-review-title">Reported {money(exactPaise(amount)??0)}</h3><dl className="record-facts"><div><dt>Fund & home</dt><dd>{campaign.title} · Home {line.home}</dd></div><div><dt>Payment</dt><dd>{displayDate(date)} · {paymentMethods[method]} · {payer}</dd></div><div><dt>External reference</dt><dd>{reference||'No cash reference supplied'}</dd></div>{comment&&<div><dt>Supporting comment</dt><dd>{comment}</dd></div>}{evidence&&<div><dt>Evidence</dt><dd>{file?.filename} · validated original</dd></div>}</dl><div className="fund-claim-note"><Icon name="receipt"/><p>This sends a claim for review. Money is confirmed and a receipt is linked only after separate verification.</p></div><FundCheck checked={checked} onChange={setChecked} disabled={writer.busy||writer.locked}>I checked these details for money already paid outside this portal.</FundCheck><FundFeedback writer={writer} onReload={()=>{writer.reset();setPreview(false);setChecked(false)}}/><div className="form-actions"><button className="button button-dark" disabled={!checked||writer.busy||writer.conflict}>{writer.busy?'Sending report…':writer.locked?'Retry this report':initial?'Send revised payment report':'Send payment report'}<Icon name="arrow"/></button><button type="button" className="text-link" disabled={writer.busy||writer.locked} onClick={()=>setPreview(false)}>Edit these details</button></div></form>}
 </div></PortalDialog>
}

export function FundReportDialog({id,user,onClose,onSaved,onRevise}:{id:string;user:User;onClose:()=>void;onSaved:()=>void;onRevise:(report:PaymentReport)=>void}){
 const [eventPage,setEventPage]=useState(1),[action,setAction]=useState(''),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[saved,setSaved]=useState('')
 const [mode,setMode]=useState('NEW'),[entry,setEntry]=useState(''),[source,setSource]=useState(''),[identity,setIdentity]=useState(''),[allocation,setAllocation]=useState('0.00'),[allocationError,setAllocationError]=useState('')
 const load=useFundLoad<PaymentReport>('/api/payment-reports/'+encodeURIComponent(id)+'?event_page='+eventPage),writer=useFundWrite(),data=load.data
 const canCheck=!!data&&user.can_manage_records&&data.author_id!==user.id&&data.state==='PENDING'
 const choices=useFundLoad<ConfirmOptions>('/api/payment-reports/'+encodeURIComponent(id)+'/options',canCheck)
 const reload=()=>{writer.reset();setAction('');setChecked(false);setReason('');setAllocationError('');load.reload();choices.reload()}
 const available:Record<string,string>={}
 if(data&&['PENDING','NEEDS_INFO','REJECTED'].includes(data.state)&&data.author_id===user.id)available.WITHDRAWN='Withdraw my report'
 if(canCheck){available.CONFIRMED=fundActions.CONFIRMED;available.NEEDS_INFO=fundActions.NEEDS_INFO;available.REJECTED=fundActions.REJECTED}
 const chooseReceipt=(value:string)=>{setEntry(value);setChecked(false);const chosen=choices.data?.entries.find(item=>item.id===value);setSource(chosen?.verification_source??'');setIdentity(chosen?.payment_identity??'');setAllocation(rupees(Math.min(data?.amount_paise??0,chosen?.remaining_paise??0,choices.data?.contribution_type==='FIXED'?choices.data.outstanding_paise:Number.MAX_SAFE_INTEGER)))}
 const initialized=useRef(false)
 const changeAction=(value:string)=>{initialized.current=false;setAction(value);setChecked(false);setAllocationError('')}
 useEffect(()=>{
  if(action!=='CONFIRMED'){initialized.current=false;return}
  if(initialized.current||!choices.data||!data||choices.loading||writer.locked)return
  initialized.current=true
  if(choices.data.entries.length){setMode('LINK');chooseReceipt(choices.data.entries[0].id)}
  else{setMode('NEW');setEntry('');setSource('');setIdentity('');setAllocation(rupees(Math.min(data.amount_paise,choices.data.contribution_type==='FIXED'?choices.data.outstanding_paise:data.amount_paise)))}
 },[action,choices.data,choices.loading,data,writer.locked])

 const allocationPaise=allocation==='0'||allocation==='0.00'?0:exactPaise(allocation)
 const selected=choices.data?.entries.find(item=>item.id===entry)
 const save=async(event:FormEvent)=>{event.preventDefault();if(!data||!checked||writer.conflict||load.loading)return;setAllocationError('');if(action==='CONFIRMED'&&(!choices.data||allocationPaise===null||allocationPaise>data.amount_paise||(choices.data.contribution_type==='FIXED'&&allocationPaise>choices.data.outstanding_paise)||(mode==='LINK'&&(!selected||allocationPaise>selected.remaining_paise)))){setAllocationError('Review an amount within the available same-home credit and current fund balance. Use 0.00 to retain all credit.');return}const extra=action==='CONFIRMED'?{verification_source:source.trim(),payment_identity:identity.trim(),mode,entry_id:mode==='LINK'?entry:'',allocation_amount:allocation}:{};const result=await writer.send('/api/payment-reports/'+id+'/actions',{version:data.version,action,reason:reason.trim(),...extra});if(result){setSaved('Report decision recorded.');reload();onSaved()}}
 return <PortalDialog titleId="payment-report-detail-title" closeLabel="Close payment report details" busy={writer.busy} onClose={onClose} className="maintenance-dialog fund-dialog"><div className="dialog-heading records-dialog-heading"><span className="eyebrow">THE PAYMENT REPORT</span><h2 id="payment-report-detail-title">{load.error?'Report unavailable.':data?'Home '+data.home:'Opening this report…'}</h2>{data&&!load.loading&&!load.error&&<span className={'fund-state fund-report-state-'+data.current_state.toLowerCase()}>{reportStates[data.current_state]}</span>}</div><div className="dialog-scroll detail-body"><FundUnavailable error={load.error} loading={load.loading} onRetry={reload}>{data&&<>
 <div className="fund-report-amount"><span>REPORTED PAYMENT</span><strong>{money(data.amount_paise)}</strong><small>{data.campaign}</small></div><dl className="record-facts"><div><dt>Report author</dt><dd>{data.author}</dd></div><div><dt>Payment</dt><dd>{displayDate(data.payment_date)} · {paymentMethods[data.method]}</dd></div><div><dt>Payer & reference</dt><dd>{data.payer} · {data.reference||'No cash reference supplied'}</dd></div>{data.comment&&<div><dt>Supporting comment</dt><dd>{data.comment}</dd></div>}{data.reviewer&&<div><dt>Review</dt><dd>{data.reviewer} · {data.decision_reason}</dd></div>}</dl>
 <div className="fund-report-tools"><button type="button" className="text-link fund-evidence-download" disabled={writer.busy||writer.locked} onClick={reload}>Refresh report<Icon name="refresh"/></button>
 {data.evidence_id&&<a className="text-link fund-evidence-download" href={'/api/payment-reports/'+data.id+'/evidence'} download>Download payment evidence<Icon name="document"/></a>}</div>
 {data.receipt&&<div className="fund-receipt-result"><Icon name="receipt"/><div><strong>{data.receipt}</strong><p>{data.current_state==='CORRECTED'?'The original receipt remains. A linked correction changed its current effect.':data.state==='DUPLICATE'?'This payment was already recorded. Its original receipt is linked; no new money or receipt was created.':'The verified payment is linked to its original receipt.'}</p><a className="text-link" href={'#receipts?entry='+data.entry_id}>Open original receipt<Icon name="arrow"/></a></div></div>}
 {!data.receipt&&<p className="form-help">This report has not confirmed money received. No receipt has been issued for it.</p>}{saved&&<p className="form-success" role="status">{saved}</p>}
 {data.author_id===user.id&&['NEEDS_INFO','REJECTED'].includes(data.state)&&<button className="button button-light" disabled={writer.busy||writer.locked} onClick={()=>onRevise(data)}>Revise this report<Icon name="arrow"/></button>}
 {user.can_manage_records&&data.author_id===user.id&&data.state==='PENDING'&&<p className="form-help">A different treasury reviewer must verify your own report.</p>}
 {Object.keys(available).length>0&&<form className="portal-form maintenance-decision" onSubmit={save}><h3>{canCheck?'Check the external record.':'Your next step.'}</h3><fieldset className="records-fieldset" disabled={writer.busy||writer.locked}><label>Report action<FormSelect label="Payment report action" required value={action} onChange={changeAction} options={[{value:'',label:'Choose a reviewed action…'},...selectOptions(available).map(option=>option.value==='CONFIRMED'?{...option,label:'Verify payment'}:option)]}/></label>
 {action==='CONFIRMED'&&<FundUnavailable error={choices.error} loading={choices.loading} onRetry={choices.reload}>{choices.data&&<><label>Receipt handling<FormSelect label="Receipt handling" value={mode} onChange={value=>{setMode(value);setChecked(false);setSource('');setIdentity('');if(value==='LINK')chooseReceipt(choices.data?.entries[0]?.id??'');else{setEntry('');setAllocation(rupees(Math.min(data.amount_paise,choices.data?.contribution_type==='FIXED'?choices.data.outstanding_paise:data.amount_paise)))}}} options={[{value:'NEW',label:'New receipt'},{value:'LINK',label:'Existing receipt'}]}/></label>{mode==='LINK'&&<label>Compatible original receipt<FormSelect label="Compatible original receipt" required value={entry} onChange={chooseReceipt} options={[{value:'',label:'Choose the original receipt…'},...choices.data.entries.map(item=>({value:item.id,label:item.receipt+' · available '+money(item.remaining_paise)}))]}/></label>}
 <label>Private verification source<input required minLength={5} maxLength={120} readOnly={mode==='LINK'&&!!selected?.verification_source} value={source} onChange={event=>{setSource(event.target.value);setChecked(false)}} placeholder="For example, the reviewed statement or cashbook"/></label><label>Private payment identity<input required minLength={3} maxLength={120} readOnly={mode==='LINK'&&!!selected?.payment_identity} value={identity} onChange={event=>{setIdentity(event.target.value);setChecked(false)}} placeholder="The unique source line / transaction identity"/></label><p className="form-help">Check both against the external record. The same verified identity links its original receipt, even if several people report it.</p>
 <label>{choices.data.contribution_type==='FIXED'?'Amount to allocate to this fund':'Amount to assign to this voluntary purpose'}<input required inputMode="decimal" maxLength={11} value={allocation} onChange={event=>{setAllocation(event.target.value);setChecked(false)}}/></label><div className="fund-verification-preview"><span className="eyebrow">RECEIPT & PURPOSE, REVIEWED</span><dl><div><dt>Original payment</dt><dd>{money(data.amount_paise)}</dd></div><div><dt>{mode==='LINK'?'Existing available credit':'Available on new receipt'}</dt><dd>{money(mode==='LINK'?selected?.remaining_paise??0:data.amount_paise)}</dd></div><div><dt>For this fund</dt><dd>{money(allocationPaise??0)}</dd></div><div><dt>Available after this link</dt><dd>{money(Math.max(0,(mode==='LINK'?selected?.remaining_paise??0:data.amount_paise)-(allocationPaise??0)))}</dd></div></dl><p>Excess stays as same-home credit. Use 0.00 to retain all credit. If this payment was already confirmed, the report links that record without another allocation.</p></div>
 {mode==='NEW'&&choices.data.entries.length>0&&<p className="form-help">A compatible receipt exists. Check it and link the original when it represents this payment.</p>}</>}</FundUnavailable>}
 {action&&<><label>Decision reason<textarea required minLength={10} maxLength={300} rows={3} value={reason} onChange={event=>{setReason(event.target.value);setChecked(false)}}/></label><FundCheck checked={checked} onChange={setChecked}>{action==='CONFIRMED'?'I independently verified the external payment, identity, receipt handling and fund amount.':'I reviewed this report decision and its reason.'}</FundCheck></>}</fieldset>
 {allocationError&&<p className="form-error" role="alert">{allocationError}</p>}<FundFeedback writer={writer} onReload={reload}/>{action&&<button className="button button-dark" disabled={!checked||writer.busy||writer.conflict||(action==='CONFIRMED'&&(choices.loading||!!choices.error||!choices.data))}>{writer.busy?'Saving decision…':writer.locked?'Retry report decision':available[action]}<Icon name="check"/></button>}</form>}
 <FundHistory events={data.events??[]} total={data.event_total} page={data.event_page} size={20} onPage={setEventPage} disabled={writer.busy||writer.locked}/>
 </>}</FundUnavailable></div></PortalDialog>
}

export type NewReportContext = { campaign:FundDetail;line:FundLine }
