import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { APIError, mutate, request } from '../api'
import type { User } from '../api'
import { displayDate, exactPaise, money } from '../maintenance'
import type { Allocation, HomeStatement, StatementEntry } from '../maintenance'
import { Icon } from './Icon'
import { FormSelect } from './FilterSelect'
import { PortalDialog } from './PortalDialog'
import { PageControls } from './Maintenance'

const allocationState = (state:string) => ({ ACTIVE:'Active',CORRECTED:'Corrected',SOURCE_REVERSED:'Source reversed',CHARGE_REVERSED:'Charge reversed' })[state]??state
const creditLabel = (entry:StatementEntry) => entry.kind==='OPENING_CREDIT'?'Opening credit · '+displayDate(entry.date):entry.receipt||'Confirmed money received'

export function HomeStatementDialog({home,user,onClose,onSaved}:{home:string;user:User;onClose:()=>void;onSaved:()=>void}) {
  const [data,setData]=useState<HomeStatement|null>(null),[loadError,setLoadError]=useState(''),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true)
  const [chargePage,setChargePage]=useState(1),[creditPage,setCreditPage]=useState(1),[allocationPage,setAllocationPage]=useState(1),[tab,setTab]=useState<'charges'|'credits'|'allocations'>('charges')
  const [mode,setMode]=useState(''),[correction,setCorrection]=useState<Allocation|null>(null),[source,setSource]=useState(''),[charge,setCharge]=useState(''),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[checked,setChecked]=useState(false)
  const [busy,setBusy]=useState(false),[locked,setLocked]=useState(false),[conflict,setConflict]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
  const pending=useRef<{path:string;body:Record<string,unknown>}|null>(null),feedback=useRef<HTMLParagraphElement>(null),form=useRef<HTMLFormElement>(null)
  useEffect(()=>{if(error)feedback.current?.scrollIntoView({block:'nearest'})},[error])
  useEffect(()=>{if(mode)form.current?.scrollIntoView({block:'nearest'})},[mode])
  useEffect(()=>{
    const controller=new AbortController();setLoading(true);setLoadError('')
    request<HomeStatement>('/api/statements/'+encodeURIComponent(home)+'?'+new URLSearchParams({charge_page:String(chargePage),credit_page:String(creditPage),allocation_page:String(allocationPage)}),controller.signal).then(value=>{setData(value);setLoading(false)}).catch((err:Error)=>{if(!controller.signal.aborted){setLoadError(err.message);setLoading(false)}})
    return()=>controller.abort()
  },[home,revision,chargePage,creditPage,allocationPage])
  const reload=()=>{setError('');setLocked(false);setConflict(false);setMode('');setChecked(false);pending.current=null;setRevision(value=>value+1);onSaved()}
  const begin=(action:string,allocation:Allocation|null=null)=>{setMode(action);setCorrection(allocation);setSource('');setCharge('');setAmount('');setReason('');setChecked(false);setError('');setSuccess('');pending.current=null}
  const sourceEntry=data?.credits.find(entry=>entry.id===source),chargeEntry=data?.charges.find(entry=>entry.id===charge),paise=exactPaise(amount)
  const submit=async(event:FormEvent)=>{
    event.preventDefault();if(busy||loading||!checked||!data)return;setError('')
    if(!pending.current&&mode==='allocate'&&(!sourceEntry||!chargeEntry||paise===null||paise>sourceEntry.remaining_paise||paise>chargeEntry.remaining_paise)){setError('Choose a positive amount within both the available credit and remaining charge.');return}
    pending.current??={path:mode==='allocate'?'/api/allocations':'/api/allocations/'+encodeURIComponent(correction!.id)+'/reverse',body:mode==='allocate'?{operation_key:crypto.randomUUID(),source_id:source,charge_id:charge,amount,reason:reason.trim(),confirmed:true}:{operation_key:crypto.randomUUID(),reason:reason.trim(),confirmed:true}}
    setBusy(true)
    try{await mutate(pending.current.path,'POST',pending.current.body);const message=mode==='allocate'?'Allocation recorded. The original receipt is unchanged.':'Allocation corrected. The original link remains in history.';reload();setTab('allocations');setSuccess(message)}
    catch(err){setError((err as Error).message);setConflict(err instanceof APIError&&err.status===409);const rejected=err instanceof APIError&&[400,403,404].includes(err.status);setLocked(!rejected);if(rejected)pending.current=null}
    finally{setBusy(false)}
  }
  const changeChargePage=(page:number)=>{setCharge('');setChargePage(page)}
  const changeCreditPage=(page:number)=>{setSource('');setCreditPage(page)}
  return <PortalDialog titleId="home-statement-title" closeLabel="Close home statement" busy={busy} onClose={onClose} className="maintenance-dialog statement-dialog"><div className="dialog-heading records-dialog-heading"><span className="eyebrow">THE HOME STATEMENT</span><h2 id="home-statement-title">{data?'Home '+data.home:'Opening this home…'}</h2><p>Charges, credit and the links that bring them together.</p></div><div className="dialog-scroll detail-body">
    {loadError?<div className="empty-state" role="alert"><h3>Statement unavailable.</h3><p>{loadError}</p><button className="button button-dark" onClick={reload}>Reload statement<Icon name="refresh" /></button></div>:loading?<p role="status">Updating this statement…</p>:data&&<>
      {success&&<p className="form-success" role="status">{success}</p>}
      <div className="statement-outstanding"><span>OUTSTANDING</span><strong>{money(data.outstanding_paise)}</strong><small>Confirmed charges {money(data.debit_paise)} · confirmed credit {money(data.credit_paise)}</small></div>
      <div className="statement-measures"><div><span>Allocated</span><strong>{money(data.allocated_paise)}</strong></div><div><span>Available credit</span><strong>{money(data.unallocated_paise)}</strong></div><div><span>Overdue</span><strong>{money(data.overdue_paise)}</strong></div></div>
      <p className="form-help">Available credit does not settle a charge until explicitly allocated. Only reviewed maintenance or fund charges with a supplied due date can be marked overdue.</p>
      {data.voluntary_paise>0&&<p className="form-help">Voluntary fund contributions: {money(data.voluntary_paise)}. These use confirmed receipt credit without creating dues; available credit excludes them.</p>}
      {user.can_manage_records&&!mode&&<div className="statement-actions"><button type="button" className="button button-dark" disabled={!data.outstanding_paise||!data.unallocated_paise} onClick={()=>begin('allocate')}>Allocate credit<Icon name="plus" /></button><a className="text-link" href="#entries" onClick={onClose}>Record money already received<Icon name="arrow" /></a></div>}
      {mode&&<form ref={form} className="portal-form maintenance-decision" onSubmit={submit}><div className="section-heading"><h3>{mode==='allocate'?'Link this credit.':'Correct this allocation.'}</h3><button className="text-link" type="button" disabled={busy||locked} onClick={()=>setMode('')}>Cancel</button></div>
        {mode==='allocate'?<><fieldset disabled={busy||locked} className="records-fieldset"><label>Credit source<FormSelect required label="Allocation credit source" value={source} onChange={setSource} options={[{value:'',label:'Choose an available credit…'},...data.credits.filter(entry=>entry.remaining_paise>0).map(entry=>({value:entry.id,label:creditLabel(entry)+' · '+money(entry.remaining_paise)+' available'}))]} /></label>{data.credit_total>data.page_size&&<PageControls disabled={busy||locked} label="credit choices" page={data.credit_page} total={data.credit_total} size={data.page_size} onPage={changeCreditPage} />}<label>Charge to settle<FormSelect required label="Allocation charge" value={charge} onChange={setCharge} options={[{value:'',label:'Choose an outstanding charge…'},...data.charges.filter(entry=>entry.remaining_paise>0).map(entry=>({value:entry.id,label:entry.description+' · '+money(entry.remaining_paise)+' due'}))]} /></label>{data.charge_total>data.page_size&&<PageControls disabled={busy||locked} label="charge choices" page={data.charge_page} total={data.charge_total} size={data.page_size} onPage={changeChargePage} />}<label>Amount to allocate<input required inputMode="decimal" pattern="(0|[1-9][0-9]{0,7})([.][0-9]{1,2})?" maxLength={11} value={amount} onChange={event=>setAmount(event.target.value)} placeholder="Supplied amount in rupees" /></label></fieldset>
          {sourceEntry&&chargeEntry&&paise!==null&&paise<=sourceEntry.remaining_paise&&paise<=chargeEntry.remaining_paise&&<div className="allocation-preview"><span>AFTER THIS ALLOCATION</span><div><span>Charge outstanding</span><strong>{money(chargeEntry.remaining_paise-paise)}</strong></div><div><span>Source still available</span><strong>{money(sourceEntry.remaining_paise-paise)}</strong></div><p>{sourceEntry.kind==='OPENING_CREDIT'?'An opening credit creates no receipt.':'The original '+sourceEntry.receipt+' remains '+money(sourceEntry.amount_paise)+'.'}</p></div>}
        </>:<div className="allocation-preview"><strong>{money(correction?.amount_paise??0)}</strong><p>{correction?.receipt||'Opening credit'} → {correction?.description}</p><p>This removes this link’s current effect. Entry and receipt amounts remain unchanged.</p></div>}
        <fieldset disabled={busy||locked} className="records-fieldset"><label>{mode==='allocate'?'Allocation reason':'Correction reason'}<textarea required minLength={5} maxLength={300} rows={2} value={reason} onChange={event=>setReason(event.target.value)} /></label><label className="checkbox-label"><input type="checkbox" checked={checked} onChange={event=>setChecked(event.target.checked)} /><span>I checked this home, source, charge and amount.</span></label></fieldset>
        {error&&<p ref={feedback} className="form-error" role="alert">{error}</p>}{conflict?<button type="button" className="button button-dark" onClick={reload}>Reload statement<Icon name="refresh" /></button>:<button className="button button-dark" disabled={busy||!checked}>{busy?'Recording this link…':locked?'Retry this allocation':mode==='allocate'?'Confirm allocation':'Confirm allocation correction'}<Icon name="check" /></button>}{locked&&!conflict&&<p className="form-help">Retry keeps the original action and identity. No additional receipt will be issued.</p>}
      </form>}
      <div className="detail-tabs statement-tabs" aria-label="Statement sections">{(['charges','credits','allocations'] as const).map(value=><button type="button" key={value} disabled={busy} aria-pressed={tab===value} onClick={()=>setTab(value)}>{value==='charges'?'Charges':value==='credits'?'Receipts & credit':'Allocation history'}</button>)}</div>
      {tab==='charges'?<section aria-label="Home charges"><StatementEntries entries={data.charges} credit={false} /><PageControls disabled={busy||locked} label="charges" page={data.charge_page} total={data.charge_total} size={data.page_size} onPage={changeChargePage} /></section>:tab==='credits'?<section aria-label="Home receipts and credits"><StatementEntries entries={data.credits} credit /><PageControls disabled={busy||locked} label="credits" page={data.credit_page} total={data.credit_total} size={data.page_size} onPage={changeCreditPage} /></section>:<section aria-label="Allocation history">{data.allocations.length?<ol className="allocation-history">{data.allocations.map(allocation=><li key={allocation.id}><div className="allocation-history-top"><span className={'record-status record-status-'+(allocation.state==='ACTIVE'?'posted':'reversed')}>{allocationState(allocation.state)}</span><strong>{money(allocation.amount_paise)}</strong></div><p>{allocation.receipt||'Opening credit'} <Icon name="chevron" /> {allocation.description}</p>{allocation.reason&&<small>{allocation.reason} · {allocation.actor}</small>}{allocation.correction_reason&&<small>Correction: {allocation.correction_reason} · {allocation.corrected_by}</small>}<small>{new Date(allocation.created_at*1000).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</small>{user.can_manage_records&&allocation.state==='ACTIVE'&&<button type="button" className="text-link" disabled={busy||!!mode} aria-label={'Correct allocation '+allocation.id} onClick={()=>begin('correct',allocation)}>Correct this allocation<Icon name="refresh" /></button>}</li>)}</ol>:<p className="statement-empty">No credit has been allocated for this home yet.</p>}<PageControls disabled={busy||locked} label="allocations" page={data.allocation_page} total={data.allocation_total} size={data.page_size} onPage={setAllocationPage} /></section>}
    </>}
  </div></PortalDialog>
}
function StatementEntries({entries,credit}:{entries:StatementEntry[];credit:boolean}) {
  if(!entries.length)return <p className="statement-empty">{credit?'No confirmed receipts or opening credits yet.':'No active confirmed charges or opening dues yet.'}</p>
  return <div className="statement-entry-list">{entries.map(entry=><div key={entry.id} className="statement-entry"><span className={'record-icon '+(credit?'received':'')}><Icon name={credit?'receipt':'records'} /></span><div><strong>{credit?creditLabel(entry):entry.description}</strong><small>{credit?entry.description:displayDate(entry.date)+(entry.due_date?' · Due '+displayDate(entry.due_date):' · No due date supplied')}</small><small>Original {money(entry.amount_paise)} · allocated {money(entry.allocated_paise)}</small></div><span className="statement-entry-amount"><strong>{money(entry.remaining_paise)}</strong><small>{credit?'Available':'Outstanding'}</small></span></div>)}</div>
}
