import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { APIError, mutate, request } from '../api'
import type { User } from '../api'
import { cycleState, dateToday, displayDate, exactPaise, money } from '../maintenance'
import type { FinancialHome, MaintenanceDetail, MaintenancePage, MaintenanceTotals } from '../maintenance'
import { Icon } from './Icon'
import { FilterSelect, FormSelect } from './FilterSelect'
import { PortalDialog } from './PortalDialog'
import { HomeStatementDialog } from './MaintenanceStatement'

const linkedCycle = () => new URLSearchParams(window.location.hash.split('?')[1] ?? '').get('period') ?? ''
const linkedHome = () => new URLSearchParams(window.location.hash.split('?')[1] ?? '').get('home') ?? ''

function MaintenanceArt() {
  return <svg className="maintenance-art" aria-hidden="true" viewBox="0 0 240 190" fill="none"><ellipse cx="122" cy="165" rx="98" ry="13" fill="#dbe1cd" /><g transform="rotate(-7 106 91)"><rect x="39" y="29" width="135" height="122" rx="10" fill="#faf9f1" stroke="#a5b38e" /><path d="M39 61h135" stroke="#d1d9c2" /><path d="M71 20v19M141 20v19" stroke="#68835a" strokeWidth="4" strokeLinecap="round" />{[0,1,2].map(row => [0,1,2,3].map(column => <rect key={row*4+column} x={59+column*27} y={76+row*22} width="12" height="10" rx="3" fill={row===1&&column===2?'#244d3d':'#dfe6d2'} />))}</g><circle cx="185" cy="136" r="34" fill="#294e3e" /><path d="m169 136 11 11 22-25" stroke="#f8f8ee" strokeWidth="2.5" strokeLinecap="round" /><path d="M13 159c-3-23 12-37 24-47 6 17 6 32-10 42" fill="#adbba0" /><path d="m16 164 16-37" stroke="#718965" /></svg>
}
function CycleMetrics({ totals, ready, compact=false }: { totals?: MaintenanceTotals; ready: boolean; compact?: boolean }) {
  return <div className={'maintenance-metrics' + (compact ? ' compact' : '')} aria-label="Maintenance amounts">
    {[['Active expected', totals?.active_paise, 'Published charges · reversals excluded'], ['Allocated', totals?.allocated_paise, 'Explicit links to confirmed credit'], ['Outstanding', totals?.outstanding_paise, 'Expected less live allocations'], ['Overdue', totals?.overdue_paise, 'Outstanding past its explicit due date']].map(([label, amount, hint]) => <div key={String(label)}><span>{label}</span><strong>{ready ? money(Number(amount ?? 0)) : '—'}</strong><small>{hint}</small></div>)}
  </div>
}
export function Maintenance({ user }: { user: User }) {
  const [data,setData]=useState<MaintenancePage|null>(null)
  const [query,setQuery]=useState(''),[home,setHome]=useState(''),[state,setState]=useState(''),[page,setPage]=useState(1)
  const [revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const [creating,setCreating]=useState(false),[selected,setSelected]=useState(linkedCycle),[statementHome,setStatementHome]=useState(linkedHome),[homeChoice,setHomeChoice]=useState('')
  useEffect(()=>{const update=()=>{setSelected(linkedCycle());setStatementHome(linkedHome())};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update)},[])
  useEffect(()=>{
    if (!user.can_read_records) {setLoading(false);return}
    const controller=new AbortController();setLoading(true);setError('')
    const timer=window.setTimeout(()=>request<MaintenancePage>('/api/maintenance?'+new URLSearchParams({q:query,home,state,page:String(page)}),controller.signal).then(value=>{setData(value);setLoading(false)}).catch((err:Error)=>{if(!controller.signal.aborted){setError(err.message);setLoading(false)}}),query?200:0)
    return()=>{controller.abort();clearTimeout(timer)}
  },[user.can_read_records,query,home,state,page,revision])
  const clear=()=>{setQuery('');setHome('');setState('');setPage(1)}
  const changed=()=>setRevision(value=>value+1)
  const closeCycle=()=>{setSelected('');if(linkedCycle())window.history.replaceState(null,'','#maintenance')}
  const closeStatement=()=>{setStatementHome('');if(linkedHome())window.history.replaceState(null,'','#maintenance')}
  if(!user.can_read_records)return <section className="empty-state"><Icon name="shield" /><h1>Maintenance needs financial access.</h1><p>The officer can review your financial access for each home.</p><a className="button button-dark" href="#homes">Return to your homes<Icon name="arrow" /></a></section>
  return <div className="page-enter maintenance-page">
    <section className="maintenance-hero"><div><span className="eyebrow">KEEPING EVERYDAY LIFE RUNNING</span><h1>A little care.<br /><em>A clearer picture.</em></h1><p>Reviewed maintenance periods. Every home’s dues and the receipts that settle them, together.</p>{user.can_manage_records&&<button className="button button-dark" disabled={!data||loading||!!error} onClick={()=>setCreating(true)}>Prepare a period<Icon name="plus" /></button>}</div><MaintenanceArt /></section>
    <CycleMetrics totals={data?.totals} ready={!!data&&!loading&&!error} />
    <p className="maintenance-scope">{home?'For the selected home':user.can_read_all_records?'Across permitted community periods':'For your financially entitled homes'}{query||state?' · matching these filters':''}. Unallocated credits remain available until explicitly linked.</p>
    <section className="registry-panel" aria-labelledby="maintenance-title">
      <div className="registry-toolbar"><div><h2 id="maintenance-title">The maintenance calendar</h2><p>{user.can_read_all_records?'Prepare, review and follow each supplied period.':'Your published periods and remaining amounts.'}</p></div><span className="result-count" role="status">{loading?'Opening periods…':error?'Connection unavailable':`${data?.total??0} periods found`}</span></div>
      <div className="filter-row records-filters"><label className="search-control"><span className="sr-only">Search maintenance periods</span><Icon name="search" /><input type="search" value={query} maxLength={100} placeholder="Find a maintenance period…" onChange={event=>{setQuery(event.target.value);setPage(1)}} /></label>
        <FilterSelect label="Filter maintenance by home" value={home} onChange={value=>{setHome(value);setPage(1)}} options={[{value:'',label:'All permitted homes'},...data?.homes.map(item=>({value:item.id,label:'Home '+item.label}))??[]]} />
        <FilterSelect label="Filter maintenance by state" value={state} onChange={value=>{setState(value);setPage(1)}} options={[{value:'',label:'All periods'},...(user.can_read_all_records?[{value:'PENDING',label:'Awaiting review'},{value:'DECLINED',label:'Declined'},{value:'WITHDRAWN',label:'Withdrawn'}]:[]),{value:'PUBLISHED',label:'Published'}]} />
        <button className="clear-button" disabled={!home&&!query&&!state} onClick={clear}>Clear<Icon name="close" /></button>
      </div>
      <div aria-busy={loading}>{error?<div className="empty-state" role="alert"><Icon name="globe" /><h3>Periods unavailable.</h3><p>{error}</p><button className="button button-dark" onClick={changed}>Try again<Icon name="refresh" /></button></div>:loading?<div className="home-skeleton skeleton" aria-hidden="true" />:!data?.items.length?<div className="records-empty"><span className="chapter-icon"><Icon name="leaf" /></span><h3>{query||home||state?'No periods match.':'A calendar ready for care.'}</h3><p>{query||home||state?'Try another period, home or state.':user.can_manage_records?'Prepare the supplied amounts, then ask a different treasury reviewer to publish.':'Your reviewed maintenance periods will appear here.'}</p>{query||home||state?<button className="text-link" onClick={clear}>Clear filters<Icon name="close" /></button>:null}</div>:<div className="maintenance-grid">{data.items.map(cycle=><button key={cycle.id} className={'maintenance-card '+(cycle.state==='PENDING'?'maintenance-pending':'')} onClick={()=>setSelected(cycle.id)} aria-label={`Open period ${cycle.title}`}><span className="maintenance-card-top"><span className={'record-status record-status-'+(cycle.state==='PUBLISHED'?'posted':cycle.state==='PENDING'?'draft':'discarded')}>{cycleState(cycle.state)}</span><Icon name="arrow" /></span><h3>{cycle.title}</h3><span className="maintenance-dates">{displayDate(cycle.period_start)} – {displayDate(cycle.period_end)}</span><span className="maintenance-card-amount"><small>{cycle.state==='PUBLISHED'?'Outstanding':'Supplied proposal'}</small><strong>{money(cycle.state==='PUBLISHED'?cycle.outstanding_paise:cycle.requested_paise)}</strong></span>{cycle.state==='PUBLISHED'&&<span className="maintenance-progress"><span style={{width:(cycle.active_paise?Math.min(100,cycle.allocated_paise/cycle.active_paise*100):0)+'%'}} /></span>}<span className="maintenance-card-bottom"><span>{cycle.participants} {cycle.participants===1?'home':'homes'}</span><span>Due {displayDate(cycle.due_date)}</span></span></button>)}</div>}</div>
      {data&&!loading&&!error&&data.total>0&&<PageControls label="periods" page={data.page} total={data.total} size={data.page_size} onPage={setPage} />}
    </section>
    <section className="maintenance-home-care"><span className="chapter-icon"><Icon name="homes" /></span><div><span className="eyebrow">A HOME AT A TIME</span><h2>See the whole picture.</h2><p>Charges, original receipts, opening credits and their explicit allocations for one home.</p></div><div className="maintenance-home-choice"><FormSelect label="Statement home" value={homeChoice} onChange={setHomeChoice} options={[{value:'',label:'Choose a home…'},...data?.homes.map(item=>({value:item.id,label:'Home '+item.label}))??[]]} /><button className="button button-dark" disabled={!homeChoice||loading||!!error} onClick={()=>setStatementHome(homeChoice)}>Open statement<Icon name="arrow" /></button></div></section>
    <p className="records-footnote"><Icon name="leaf" />Amounts are supplied and reviewed. Payments happen outside the portal.</p>
    {creating&&data&&<NewMaintenance homes={data.homes} initialHome={home} onClose={()=>setCreating(false)} onCreated={id=>{setCreating(false);setSelected(id);changed()}} />}
    {selected&&!statementHome&&<PeriodDetail key={selected} id={selected} user={user} onClose={closeCycle} onSaved={changed} onStatement={id=>{closeCycle();setStatementHome(id)}} />}
    {statementHome&&<HomeStatementDialog key={statementHome} home={statementHome} user={user} onClose={closeStatement} onSaved={changed} />}
  </div>
}

export function PageControls({label,page,total,size,onPage,disabled=false}:{label:string;page:number;total:number;size:number;onPage:(page:number)=>void;disabled?:boolean}) {
  return <div className="pagination"><span>{total} {label}</span><div><button type="button" aria-label={'Previous '+label+' page'} disabled={disabled||page===1} onClick={()=>onPage(page-1)}><Icon name="left" /></button><span>Page {page} of {Math.max(1,Math.ceil(total/size))}</span><button type="button" aria-label={'Next '+label+' page'} disabled={disabled||page*size>=total} onClick={()=>onPage(page+1)}><Icon name="chevron" /></button></div></div>
}
function NewMaintenance({homes,initialHome,onClose,onCreated}:{homes:FinancialHome[];initialHome:string;onClose:()=>void;onCreated:(id:string)=>void}) {
  const [title,setTitle]=useState(''),[start,setStart]=useState(dateToday),[end,setEnd]=useState(dateToday),[due,setDue]=useState(''),[source,setSource]=useState(''),[note,setNote]=useState('')
  const [lines,setLines]=useState([{key:crypto.randomUUID(),flat_id:initialHome,amount:''}]),[bulk,setBulk]=useState('')
  const [preview,setPreview]=useState(false),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false),[error,setError]=useState('')
  const pending=useRef<Record<string,unknown>|null>(null),feedback=useRef<HTMLParagraphElement>(null),scroll=useRef<HTMLDivElement>(null)
  useEffect(()=>{if(error)feedback.current?.scrollIntoView({block:'nearest'})},[error])
  useEffect(()=>{scroll.current?.scrollTo({top:0});if(preview)scroll.current?.querySelector<HTMLElement>('[data-review-title]')?.focus()},[preview])
  const total=lines.reduce((sum,line)=>sum+(exactPaise(line.amount)??0),0)
  const prepare=(event:FormEvent)=>{
    event.preventDefault();setError('')
    if(lines.some(line=>exactPaise(line.amount)===null)||new Set(lines.map(line=>line.flat_id)).size!==lines.length){setError('Supply a positive amount with at most two decimal places for each distinct home.');return}
    if(end<start||due<start){setError('The period end and due date must be on or after the period starts.');return}
    setPreview(true);setChecked(false)
  }
  const submit=async(event:FormEvent)=>{
    event.preventDefault();if(busy||!checked)return;setBusy(true);setError('')
    pending.current??={operation_key:crypto.randomUUID(),title:title.trim(),period_start:start,period_end:end,due_date:due,source_reference:source.trim(),note:note.trim(),lines:lines.map(line=>({flat_id:line.flat_id,amount:line.amount})),confirmed:true}
    try{const result=await mutate<{id:string}>('/api/maintenance','POST',pending.current);onCreated(result.id)}
    catch(err){setError((err as Error).message);const rejected=err instanceof APIError&&[400,403,404].includes(err.status);setLocked(!rejected);if(rejected)pending.current=null}
    finally{setBusy(false)}
  }
  const applyBulk=()=>{if(exactPaise(bulk)===null){setError('Enter a positive supplied amount before applying it.');return}setLines(old=>old.map(line=>({...line,amount:bulk})));setError('')}
  return <PortalDialog titleId="new-period-title" closeLabel="Close period preparation" busy={busy} onClose={onClose} className="maintenance-dialog"><div className="dialog-heading records-dialog-heading"><span className="eyebrow">{preview?'EVERY DETAIL, BEFORE REVIEW':'PREPARE WITH CARE'}</span><h2 id="new-period-title">A new <em>period.</em></h2><p>{preview?'Review these supplied amounts. Submission freezes the proposal for a different treasury reviewer.':'Use the amounts and due date from the supplied approval record.'}</p></div><div className="dialog-scroll detail-body" ref={scroll}>
    {!preview?<form className="portal-form" onSubmit={prepare}><fieldset className="records-fieldset"><label>Period title<input required minLength={5} maxLength={120} value={title} onChange={event=>setTitle(event.target.value)} placeholder="For example, October maintenance" /></label><div className="form-pair"><label>Period starts<input type="date" required min="1900-01-01" max="2100-12-31" value={start} onChange={event=>setStart(event.target.value)} /></label><label>Period ends<input type="date" required min={start} max="2100-12-31" value={end} onChange={event=>setEnd(event.target.value)} /></label></div><label>Explicit due date<input type="date" required min={start} max="2100-12-31" value={due} onChange={event=>setDue(event.target.value)} /></label><label>Source / approval reference<input required minLength={5} maxLength={300} value={source} onChange={event=>setSource(event.target.value)} placeholder="Reference to the supplied approved record" /></label><label>Private supporting note (optional)<textarea maxLength={2000} value={note} onChange={event=>setNote(event.target.value)} rows={2} /></label>
    <div className="maintenance-participants"><div className="section-heading"><h3>Participating homes</h3><button type="button" className="text-link" onClick={()=>setLines(old=>[...old.filter(line=>line.flat_id),...homes.filter(item=>!old.some(line=>line.flat_id===item.id)).map(item=>({key:crypto.randomUUID(),flat_id:item.id,amount:''}))])}>Include all homes<Icon name="plus" /></button></div>
      <div className="maintenance-bulk"><label>Supplied amount for selected homes<input inputMode="decimal" maxLength={11} value={bulk} onChange={event=>setBulk(event.target.value)} placeholder="Optional · from the supplied record" /></label><button type="button" className="button button-light" onClick={applyBulk}>Apply supplied amount</button></div>
      {lines.map((line,index)=><div key={line.key} className="maintenance-participant"><label>Home {index+1}<FormSelect required label={'Participating home '+(index+1)} value={line.flat_id} onChange={value=>setLines(old=>old.map(item=>item.key===line.key?{...item,flat_id:value}:item))} options={[{value:'',label:'Choose a home…'},...homes.filter(item=>item.id===line.flat_id||!lines.some(other=>other.flat_id===item.id)).map(item=>({value:item.id,label:'Home '+item.label}))]} /></label><label>Amount for home {index+1}<input required inputMode="decimal" pattern="(0|[1-9][0-9]{0,7})([.][0-9]{1,2})?" maxLength={11} value={line.amount} onChange={event=>setLines(old=>old.map(item=>item.key===line.key?{...item,amount:event.target.value}:item))} placeholder="0.00" /></label><button type="button" className="icon-button" aria-label={'Remove participating home '+(index+1)} disabled={lines.length===1} onClick={()=>setLines(old=>old.filter(item=>item.key!==line.key))}><Icon name="close" /></button></div>)}
      <button type="button" className="text-link" disabled={lines.length>=homes.length} onClick={()=>setLines(old=>[...old,{key:crypto.randomUUID(),flat_id:'',amount:''}])}>Add another home<Icon name="plus" /></button>
    </div></fieldset>{error&&<p ref={feedback} className="form-error" role="alert">{error}</p>}<div className="maintenance-form-total"><span>Supplied total · {lines.length} homes</span><strong>{money(total)}</strong></div><button className="button button-dark">Review this period<Icon name="arrow" /></button></form>:
    <form className="portal-form" onSubmit={submit}><h3 data-review-title tabIndex={-1} className="maintenance-review-title">{title}</h3><dl className="record-facts"><div><dt>Period</dt><dd>{displayDate(start)} – {displayDate(end)}</dd></div><div><dt>Due date</dt><dd>{displayDate(due)}</dd></div><div><dt>Private source reference</dt><dd>{source}</dd></div>{note&&<div><dt>Private note</dt><dd>{note}</dd></div>}</dl><ul className="maintenance-review-lines">{lines.map(line=><li key={line.key}><span>Home {homes.find(item=>item.id===line.flat_id)?.label}</span><strong>{money(exactPaise(line.amount)??0)}</strong></li>)}</ul><div className="maintenance-form-total"><span>{lines.length} homes · frozen supplied total</span><strong>{money(total)}</strong></div>
      <label className="checkbox-label"><input type="checkbox" disabled={busy||locked} checked={checked} onChange={event=>setChecked(event.target.checked)} /><span>I checked each supplied amount, the participating homes and the explicit due date.</span></label>
      {error&&<p ref={feedback} className="form-error" role="alert">{error}</p>}{locked&&<p className="form-help">Retry keeps this exact proposal and identity. A lost response cannot submit it twice.</p>}
      <div className="form-actions"><button className="button button-dark" disabled={busy||!checked}>{busy?'Submitting period…':locked?'Retry submitting period':'Submit for separate review'}<Icon name="arrow" /></button><button type="button" className="text-link" disabled={busy||locked} onClick={()=>{setPreview(false);setError('')}}>Edit before submitting</button></div><p className="form-help">Submission creates no charge or receipt. A different current treasury reviewer must approve publication.</p>
    </form>}
  </div></PortalDialog>
}

function PeriodDetail({id,user,onClose,onSaved,onStatement}:{id:string;user:User;onClose:()=>void;onSaved:()=>void;onStatement:(home:string)=>void}) {
  const [data,setData]=useState<MaintenanceDetail|null>(null),[loadError,setLoadError]=useState(''),[revision,setRevision]=useState(0),[linePage,setLinePage]=useState(1),[eventPage,setEventPage]=useState(1),[loading,setLoading]=useState(true)
  const [mode,setMode]=useState(''),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false),[conflict,setConflict]=useState(false),[error,setError]=useState('')
  const pending=useRef<Record<string,unknown>|null>(null),feedback=useRef<HTMLParagraphElement>(null)
  useEffect(()=>{if(error)feedback.current?.scrollIntoView({block:'nearest'})},[error])
  useEffect(()=>{const controller=new AbortController();setLoading(true);setLoadError('');request<MaintenanceDetail>('/api/maintenance/'+encodeURIComponent(id)+'?'+new URLSearchParams({line_page:String(linePage),event_page:String(eventPage)}),controller.signal).then(value=>{setData(value);setLoading(false)}).catch((err:Error)=>{if(!controller.signal.aborted){setLoadError(err.message);setLoading(false)}});return()=>controller.abort()},[id,revision,linePage,eventPage])
  const reload=()=>{setMode('');setError('');setConflict(false);setLocked(false);setChecked(false);pending.current=null;setRevision(value=>value+1);onSaved()}
  const submit=async(event:FormEvent)=>{
    event.preventDefault();if(!data||busy||!checked||loading)return;setBusy(true);setError('')
    pending.current??={operation_key:crypto.randomUUID(),version:data.version,decision:mode,reason:reason.trim(),confirmed:true}
    try{await mutate('/api/maintenance/'+encodeURIComponent(id)+'/decision','POST',pending.current);reload()}
    catch(err){setError((err as Error).message);setConflict(err instanceof APIError&&err.status===409);const rejected=err instanceof APIError&&[400,403,404].includes(err.status);setLocked(!rejected);if(rejected)pending.current=null}
    finally{setBusy(false)}
  }
  const startDecision=(value:string)=>{setMode(value);setReason('');setChecked(false);setError('');pending.current=null}
  return <PortalDialog titleId="period-detail-title" closeLabel="Close period details" busy={busy} onClose={onClose} className="maintenance-dialog"><div className="dialog-heading records-dialog-heading"><span className="eyebrow">MAINTENANCE · {data?cycleState(data.state).toUpperCase():'OPENING PERIOD'}</span><h2 id="period-detail-title">{data?.title??'A clearer picture.'}</h2>{data&&<p>{displayDate(data.period_start)} – {displayDate(data.period_end)} · Due {displayDate(data.due_date)}</p>}</div><div className="dialog-scroll detail-body">
    {loadError?<div className="empty-state" role="alert"><h3>Period unavailable.</h3><p>{loadError}</p><button className="button button-dark" onClick={reload}>Reload period<Icon name="refresh" /></button></div>:loading?<p role="status">Opening this period…</p>:data&&<>
      {data.state==='PUBLISHED'?<CycleMetrics compact totals={data} ready />:<div className="maintenance-proposal-note"><span className="eyebrow">FROZEN SUPPLIED PROPOSAL</span><strong>{money(data.requested_paise)}</strong><p>{data.state==='PENDING'?'Awaiting separate review. No ledger charges have been created.':'This proposal created no charges. Its supplied amounts and decision remain in history.'}</p></div>}
      {data.reversed_paise>0&&<p className="form-help">Original published total {money(data.requested_paise)} · reversed charges {money(data.reversed_paise)}. Current expected excludes those charges.</p>}
      {user.can_read_all_records&&<dl className="record-facts"><div><dt>Submitted by</dt><dd>{data.author}</dd></div><div><dt>Private source reference</dt><dd>{data.source_reference}</dd></div>{data.note&&<div><dt>Private supporting note</dt><dd>{data.note}</dd></div>}{data.decision_reason&&<div><dt>Decision</dt><dd>{data.decision_reason}<small> · {data.decided_by}</small></dd></div>}</dl>}
      {data.state==='PENDING'&&user.can_manage_records&&!mode&&<div className="maintenance-review-actions">{data.author_id===user.id?<><p className="form-help">A different treasury reviewer must decide this proposal.</p><button type="button" className="button button-light" onClick={()=>startDecision('WITHDRAWN')}>Withdraw proposal</button></>:<><button type="button" className="button button-dark" onClick={()=>startDecision('PUBLISHED')}>Approve & publish<Icon name="check" /></button><button type="button" className="button button-light" onClick={()=>startDecision('DECLINED')}>Decline period</button></>}</div>}
      {mode&&<form className="portal-form maintenance-decision" onSubmit={submit}><h3>{mode==='PUBLISHED'?'Publish these supplied charges?':mode==='DECLINED'?'Decline this proposal?':'Withdraw this proposal?'}</h3><p className="form-help">{mode==='PUBLISHED'?`This creates ${data.participants} given charges totalling ${money(data.requested_paise)}. It records no money received and issues no receipt.`:'The proposal remains in history. No ledger charges will be created.'}</p><fieldset className="records-fieldset" disabled={busy||locked}><label>Decision reason<textarea required minLength={10} maxLength={300} rows={2} value={reason} onChange={event=>setReason(event.target.value)} /></label><label className="checkbox-label"><input type="checkbox" checked={checked} onChange={event=>setChecked(event.target.checked)} /><span>I checked the frozen proposal and confirm this decision.</span></label></fieldset>{error&&<p ref={feedback} className="form-error" role="alert">{error}</p>}{conflict?<button type="button" className="button button-dark" onClick={reload}>Reload period<Icon name="refresh" /></button>:<div className="form-actions"><button className="button button-dark" disabled={busy||!checked}>{busy?'Recording decision…':locked?'Retry this decision':mode==='PUBLISHED'?'Confirm publication':mode==='DECLINED'?'Confirm decline':'Confirm withdrawal'}<Icon name="check" /></button><button type="button" className="text-link" disabled={busy||locked} onClick={()=>setMode('')}>Keep reviewing</button></div>}{locked&&!conflict&&<p className="form-help">Retry preserves this exact decision and its identity.</p>}</form>}
      <div className="section-heading maintenance-lines-heading"><h3>{data.state==='PUBLISHED'?'Home charges':'Supplied amounts'}</h3><span>{data.participants} {data.participants===1?'home':'homes'}</span></div><div className="maintenance-line-list">{data.lines.map(line=><div key={line.flat_id} className="maintenance-detail-line"><span><strong>Home {line.home}</strong><small>{line.state==='PROPOSED'?'Supplied · no charge yet':line.state==='REVERSED'?'Reversed · original preserved':`Allocated ${money(line.allocated_paise)}`}</small></span><span className="maintenance-line-amount"><strong>{money(line.state==='POSTED'?line.outstanding_paise:line.amount_paise)}</strong><small>{line.state==='POSTED'?'Outstanding':'Supplied'}</small></span>{data.state==='PUBLISHED'&&<button type="button" className="icon-button" disabled={busy} aria-label={'Open statement for '+line.home} onClick={()=>onStatement(line.flat_id)}><Icon name="arrow" /></button>}</div>)}</div>{data.participants>data.page_size&&<PageControls disabled={busy} label="participating homes" page={data.line_page} total={data.participants} size={data.page_size} onPage={setLinePage} />}
      {user.can_read_all_records&&data.events&&<div className="maintenance-history"><h3>Review history</h3><ol>{data.events.map(event=><li key={event.version}><span className="access-history-dot" /><div><strong>{cycleState(event.action==='SUBMITTED'?'PENDING':event.action)} · {event.actor}</strong><p>{event.reason}</p><small>Version {event.version} · {new Date(event.at*1000).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</small></div></li>)}</ol>{(data.event_total??0)>data.page_size&&<PageControls disabled={busy} label="period history" page={data.event_page??1} total={data.event_total??0} size={data.page_size} onPage={setEventPage} />}</div>}
    </>}
  </div></PortalDialog>
}
