import { useFragmentSync } from '../navigation'
import { useEffect, useState } from 'react'
import type { User } from '../api'
import type { MeetingPage } from '../meetings'
import { meetingDate, meetingStates, useMeetingLoad } from '../meetings'
import { communityLink, communityTime } from '../community'
import { FilterSelect } from './FilterSelect'
import { PageControls } from './Maintenance'
import { Icon } from './Icon'
import { MeetingDialog } from './MeetingDetail'
import { MeetingProposal } from './MeetingProposal'

function meetingRoute(user:User){return {id:communityLink('meeting'),desk:communityLink('desk')==='true'&&user.can_review_requests}}
function MeetingArt(){return <svg className="community-art" viewBox="0 0 210 168" fill="none" aria-hidden="true"><ellipse cx="107" cy="143" rx="81" ry="12" fill="#dce2d2"/><rect x="35" y="30" width="134" height="110" rx="17" fill="#e7e9da" transform="rotate(-6 102 85)"/><rect x="53" y="41" width="134" height="110" rx="17" fill="#fffdf7" stroke="#bcc6ad" transform="rotate(7 120 96)"/><path d="m56 72 130 16M86 35l-2 23m65-15-2 23" stroke="#81946c" strokeWidth="3" strokeLinecap="round"/><circle cx="99" cy="103" r="19" fill="#dfe8c9"/><path d="m90 103 6 6 12-14" stroke="#41604b" strokeWidth="2" strokeLinecap="round"/><path d="m137 108 25 3m-27 12 19 2" stroke="#c7ceb9" strokeWidth="3" strokeLinecap="round"/><circle cx="41" cy="112" r="18" fill="#eadfce"/><path d="M41 104v16m-6-8h12" stroke="#9b8468" strokeWidth="2" strokeLinecap="round"/></svg>}
export function Meetings({user}:{user:User}){
 const [route,setRoute]=useState(()=>meetingRoute(user)),[creating,setCreating]=useState(false),[revision,setRevision]=useState(0)
 useFragmentSync(()=>{const sync=()=>setRoute(meetingRoute(user));sync()},[user.can_review_requests])
 const changed=()=>{setRevision(x=>x+1);window.dispatchEvent(new Event('meetings-changed'))}
 return <><MeetingList key={String(route.desk)} desk={route.desk} canPrepare={user.can_review_requests} revision={revision} onCreate={()=>setCreating(true)} onOpen={id=>{window.location.hash='community?meeting='+id+(route.desk?'&desk=true':'')}}/>
 {route.id&&<MeetingDialog key={route.id+':'+route.desk} id={route.id} desk={route.desk} onClose={()=>{window.location.hash='community?panel=meetings'+(route.desk?'&desk=true':'')}} onChanged={changed}/>}
 {creating&&<MeetingProposal onClose={()=>setCreating(false)} onSaved={id=>{setCreating(false);changed();window.location.hash='community?meeting='+id+'&desk=true'}}/>}</>
}
function MeetingList({desk,canPrepare,revision,onCreate,onOpen}:{desk:boolean;canPrepare:boolean;revision:number;onCreate:()=>void;onOpen:(id:string)=>void}){
 const [state,setState]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1)
 const load=useMeetingLoad<MeetingPage>('/api/meetings?'+new URLSearchParams({desk:String(desk),state,q:query,page:String(page)}))
 useEffect(()=>{if(revision)load.reload()},[revision,load.reload])
 const states=desk?['PENDING','UPCOMING','PAST','MINUTES','CANCELLED','DECLINED','PROPOSAL_CANCELLED','WITHDRAWN']:['UPCOMING','PAST','MINUTES','CANCELLED']
 const clear=()=>{setQuery('');setState('');setPage(1)}
 return <div className="page-enter meeting-workspace"><section className="community-hero"><div><span className="eyebrow">{desk?'SUPPLIED DETAILS. SEPARATE DECISIONS.':'GOOD THINGS HAPPEN WHEN WE COME TOGETHER'}</span><h1>{desk?<>A considered agenda.{' '}<br/><em>A clear record.</em></>:<>A little time,{' '}<br/><em>together.</em></>}</h1><p>{desk?'Prepare agendas, minutes and cancellations. A different reviewer decides the exact version.':'Your community meetings, supplied agendas and approved minutes, kept together.'}</p><div className="meeting-hero-actions">{canPrepare&&<button className="button button-dark" onClick={onCreate}>Prepare a meeting<Icon name="plus"/></button>}{canPrepare&&<a className="text-link" href={'#community?panel=meetings'+(desk?'':'&desk=true')}>{desk?'Published meetings':'Meeting desk'}<Icon name="arrow"/></a>}</div></div><MeetingArt/></section>
 <section className="registry-panel"><div className="registry-toolbar"><div><h2>{desk?'The meeting desk.':'Dates worth keeping.'}</h2><p>{desk?'Private proposals, original agendas and separately reviewed updates.':'Acknowledge a requested version after reading it. Your response stays personal.'}</p></div><span className="result-count" role="status">{load.loading?'Checking meetings…':load.error?'Connection unavailable':load.data?.total+' meetings'}</span></div>
 <div className="filter-row meeting-filters"><label className="search-control"><Icon name="search"/><input aria-label="Search meetings" placeholder="Find a meeting or its minutes…" value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}}/></label><FilterSelect label="Filter meeting status" value={state} options={[{value:'',label:'All meeting statuses'},...states.map(value=>({value,label:meetingStates[value]}))]} onChange={value=>{setState(value);setPage(1)}}/>{(query||state)&&<button className="clear-button" onClick={clear}>Clear<Icon name="close"/></button>}</div>
 {load.error?<div className="empty-state" role="alert"><h3>Meetings unavailable.</h3><p>{load.error}</p><button className="button button-dark" onClick={load.reload}>Retry meetings<Icon name="refresh"/></button></div>:load.loading?<div className="community-loading" role="status"><div className="skeleton"/><div className="skeleton"/><span className="sr-only">Loading current meetings</span></div>:!load.data?.items.length?<div className="empty-state"><Icon name="community"/><h3>{query||state?'No matching meetings.':'Room for the next conversation.'}</h3><p>{desk?'Prepare a supplied agenda when the community has a meeting to review.':'No approved meetings are available for your current homes in this view.'}</p>{(query||state)&&<button className="button button-light" onClick={clear}>Clear meeting filters</button>}</div>:<><div className="community-card-grid meeting-card-grid">{load.data.items.map(x=><button key={x.id} className="community-card meeting-card" onClick={()=>onOpen(x.id)} aria-label={'Open meeting: '+x.snapshot.title}>
 <span className="community-card-top"><span className="meeting-date"><strong>{meetingDate(x.snapshot.start_at,'day')}</strong><span>{meetingDate(x.snapshot.start_at,'month')}</span></span><span className={'community-state meeting-state-'+x.state.toLowerCase()}>{meetingStates[x.state]}</span></span><h3>{x.snapshot.title}</h3><p>{x.snapshot.action==='MINUTES'?x.snapshot.minutes:x.snapshot.action==='CANCEL'?x.snapshot.update_text:x.snapshot.body}</p><span className="community-card-foot"><span>{communityTime(x.snapshot.start_at)}<small>{desk?(x.state==='PENDING'?'Private until separate approval':x.snapshot.homes.length+' approved homes'):x.acknowledgement.acknowledged?'You acknowledged this version':x.acknowledgement.can_acknowledge?'Your acknowledgement is requested':x.snapshot.homes.length+' approved homes'}</small></span><Icon name="arrow"/></span></button>)}</div><PageControls label="meetings" page={load.data.page} total={load.data.total} size={12} onPage={setPage} disabled={load.loading}/></>}
 </section></div>
}
