import { useState } from 'react'
import type { FormEvent } from 'react'
import type { MeetingDetail, MeetingResponses } from '../meetings'
import { useMeetingLoad, useMeetingWrite } from '../meetings'
import { communityActions, communityTime } from '../community'
import { PortalDialog } from './PortalDialog'
import { MeetingPaper } from './MeetingShared'
import { MeetingProposalForm } from './MeetingProposal'
import type { MeetingDraft } from './MeetingProposal'
import { FormSelect } from './FilterSelect'
import { FineFeedback } from './FineShared'
import { FundCheck, FundUnavailable } from './FundShared'
import { PageControls } from './Maintenance'
import { Icon } from './Icon'

export function MeetingDialog({id,desk,onClose,onChanged}:{id:string;desk:boolean;onClose:()=>void;onChanged:()=>void}){
 const [page,setPage]=useState(1),[mode,setMode]=useState('VIEW'),[success,setSuccess]=useState(''),[decision,setDecision]=useState('APPROVED'),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[draft,setDraft]=useState<MeetingDraft|null>(null)
 const load=useMeetingLoad<MeetingDetail>('/api/meetings/'+encodeURIComponent(id)+'?'+new URLSearchParams({desk:String(desk),event_page:String(page)})),writer=useMeetingWrite(),x=load.data
 const saved=()=>{setMode('VIEW');setConfirmed(false);setSuccess(desk?'The exact meeting proposal and decision are retained.':'Your acknowledgement of this exact version is recorded.');load.reload();onChanged()}
 const reload=()=>{writer.reset();setConfirmed(false);load.reload()}
 const start=(next:string)=>{writer.reset();setMode(next);setDraft(null);setReason('');setSuccess('');setDecision('APPROVED');setConfirmed(false)}
 const decide=async(event:FormEvent)=>{event.preventDefault();if(!x||!confirmed||writer.conflict)return;if(await writer.send('/api/meetings/'+encodeURIComponent(id)+'/decisions',{version:x.version,action:mode==='CANCEL_PENDING'?'CANCELLED':decision,reason}))saved()}
 const acknowledge=async(event:FormEvent)=>{event.preventDefault();if(!x||!confirmed||writer.conflict)return;if(await writer.send('/api/meetings/'+encodeURIComponent(id)+'/acknowledgements',{version:x.version,fingerprint:x.acknowledgement.fingerprint}))saved()}
 const editing=['REVISE','MINUTES','CANCEL','WITHDRAW'].includes(mode),proposalAction=mode==='REVISE'?x?.snapshot.action??'AGENDA':mode
 return <PortalDialog titleId="meeting-detail-title" closeLabel="Close meeting" className="community-dialog meeting-dialog" busy={writer.busy||writer.locked} onClose={onClose}>
 <div className="dialog-heading community-dialog-heading"><span className="eyebrow">{desk?'PRIVATE MEETING PUBLICATION & REVIEW':'A SHARED MOMENT. A PERSONAL RESPONSE.'}</span><h2 id="meeting-detail-title">{x?.snapshot.title??'Meeting'}</h2></div><div className="dialog-scroll community-detail"><FundUnavailable error={load.error} loading={load.loading} onRetry={load.reload}>{x&&<>
 {success&&<p className="form-success" role="status">{success}</p>}
 {editing?<MeetingProposalForm key={mode} resource={x} action={proposalAction} draft={draft} setDraft={setDraft} writer={writer} onSaved={saved} onReload={reload} onBack={()=>setMode('VIEW')}/>:mode==='RESPONSES'?<><button className="text-link" onClick={()=>setMode('VIEW')}>Back to meeting<Icon name="arrow"/></button><MeetingResponsesPanel id={id}/></>:<>
 <MeetingPaper snapshot={x.snapshot} state={x.state} privateReview={desk}/>{x.published_at>0&&<p className="community-publication-time">{x.state==='PENDING'?'Approved predecessor published':'Published'} {communityTime(x.published_at)}</p>}
 {desk&&x.state==='PENDING'&&x.published&&<details className="community-history meeting-predecessor"><summary>Read the approved predecessor</summary><MeetingPaper snapshot={x.published}/></details>}
 {(mode==='REVIEW'||mode==='CANCEL_PENDING')?<form className="portal-form community-decision" onSubmit={event=>{void decide(event)}}><h3>{mode==='CANCEL_PENDING'?'Cancel this pending proposal.':'A separate pair of eyes.'}</h3><fieldset className="records-fieldset" disabled={writer.busy||writer.locked}>{mode==='REVIEW'&&<label>Meeting publication decision<FormSelect label="Meeting publication decision" value={decision} options={[{value:'APPROVED',label:'Approve this exact meeting proposal'},{value:'DECLINED',label:'Decline this meeting proposal'}]} onChange={value=>{setDecision(value);setConfirmed(false)}}/></label>}<label>Meeting decision reason<textarea required minLength={10} maxLength={800} value={reason} onChange={event=>{setReason(event.target.value);setConfirmed(false)}}/></label><FundCheck checked={confirmed} onChange={setConfirmed}>I reviewed this exact meeting version, times, homes and acknowledgement choice.</FundCheck></fieldset><p className="form-help">{mode==='CANCEL_PENDING'||decision==='DECLINED'?'The approved predecessor stays published. This proposal and decision remain retained.':x.snapshot.action==='WITHDRAW'?'Approval withdraws current portal access and retains the meeting and all personal responses.':'Approval publishes this exact version. Earlier personal responses stay attached to their original versions.'}</p><FineFeedback writer={writer} onReload={reload}/><div className="form-actions community-form-actions"><button type="button" className="button button-light" disabled={writer.busy||writer.locked} onClick={()=>setMode('VIEW')}>Back to meeting</button><button className="button button-dark" disabled={writer.busy||writer.conflict||!confirmed}>{writer.busy?'Saving meeting decision…':writer.locked?'Retry this meeting decision':mode==='CANCEL_PENDING'?'Cancel pending meeting proposal':decision==='APPROVED'?'Approve this exact meeting proposal':'Decline this meeting proposal'}<Icon name="check"/></button></div></form>:mode==='ACKNOWLEDGE'?<form className="portal-form meeting-ack-form" onSubmit={event=>{void acknowledge(event)}}><h3>Your personal acknowledgement.</h3><p className="form-help">This records that you acknowledged published version {x.version}. It does not record attendance, a vote or consent to a decision.</p><FundCheck checked={confirmed} onChange={setConfirmed} disabled={writer.busy||writer.locked}>I read and personally acknowledge this exact published meeting version.</FundCheck><FineFeedback writer={writer} onReload={reload}/><div className="form-actions community-form-actions"><button type="button" className="button button-light" disabled={writer.busy||writer.locked} onClick={()=>setMode('VIEW')}>Back to meeting</button><button className="button button-dark" disabled={writer.busy||writer.conflict||!confirmed}>{writer.busy?'Recording acknowledgement…':writer.locked?'Retry this acknowledgement':'Record my acknowledgement'}<Icon name="check"/></button></div></form>:desk?<>
 <div className="community-detail-actions">{x.can_decide&&<button className="button button-dark" onClick={()=>start('REVIEW')}>Review meeting proposal<Icon name="check"/></button>}{x.can_revise&&<button className="button button-outline" onClick={()=>start('REVISE')}>{x.state==='PENDING'?'Revise your meeting proposal':x.snapshot.action==='MINUTES'?'Prepare revised minutes':'Prepare a revised agenda'}<Icon name="records"/></button>}{x.can_prepare_minutes&&x.snapshot.action!=='MINUTES'&&<button className="button button-outline" onClick={()=>start('MINUTES')}>Prepare meeting minutes<Icon name="document"/></button>}{x.can_prepare_cancellation&&<button className="button button-outline" onClick={()=>start('CANCEL')}>Propose meeting cancellation<Icon name="close"/></button>}{x.can_withdraw&&<button className="button button-outline" onClick={()=>start('WITHDRAW')}>Propose meeting withdrawal<Icon name="close"/></button>}{x.can_cancel&&<button className="text-link" onClick={()=>start('CANCEL_PENDING')}>Cancel your meeting proposal</button>}{x.published_at>0&&<button className="text-link" onClick={()=>start('RESPONSES')}>View personal responses<Icon name="community"/></button>}</div>
 {x.state==='PENDING'&&<p className="form-help">{x.can_decide?'Ready for your separate decision.':'A different current reviewer must decide this proposal.'} {x.published?'The approved predecessor remains published.':'This proposal stays private until approved.'}</p>}{x.published_at>0&&x.state!=='WITHDRAWN'&&<a className="text-link meeting-reading-link" href={'#community?meeting='+id}>Read published meeting<Icon name="arrow"/></a>}
 </>:<div className="meeting-personal-response">{x.acknowledgement.acknowledged?<p className="form-success"><Icon name="check"/>You acknowledged version {x.version} on {communityTime(x.acknowledgement.at)}.</p>:x.acknowledgement.can_acknowledge?<><p>Your personal acknowledgement is requested for this version.</p><button className="button button-dark" onClick={()=>start('ACKNOWLEDGE')}>Acknowledge this version<Icon name="check"/></button></>:null}</div>}
 </>}
 {desk&&mode==='VIEW'&&x.events&&<section className="review-history community-history" aria-label="Meeting publication history"><h3>Every version, kept together.</h3><ol>{x.events.map(event=><li key={event.version}><strong>{communityActions[event.action]??event.action}</strong><p className="preserve-lines">{event.reason}</p><small>{event.actor} · {communityTime(event.at)}</small><details><summary>Read exact retained meeting · version {event.snapshot.version}</summary><MeetingPaper snapshot={event.snapshot} privateReview/></details></li>)}</ol>{(x.event_total??0)>20&&<PageControls label="meeting history" page={x.event_page??1} total={x.event_total!} size={20} onPage={setPage} disabled={writer.busy||writer.locked}/>}</section>}
 </>}</FundUnavailable></div></PortalDialog>
}

function MeetingResponsesPanel({id}:{id:string}){
 const [page,setPage]=useState(1),[historyPage,setHistoryPage]=useState(1)
 const load=useMeetingLoad<MeetingResponses>('/api/meetings/'+encodeURIComponent(id)+'/responses?'+new URLSearchParams({page:String(page),history_page:String(historyPage)})),x=load.data
 return <section className="meeting-responses" aria-label="Private meeting responses"><h3>Personal responses, kept private.</h3><FundUnavailable error={load.error} loading={load.loading} onRetry={load.reload}>{x&&<><p className="form-help">Current eligible members have an activated account and a current home in the approved area. Earlier responses remain retained separately.</p><div className="meeting-response-counts"><div><span>Current eligible</span><strong>{x.expected}</strong></div><div><span>Acknowledged</span><strong>{x.acknowledged}</strong></div><div><span>Outstanding</span><strong>{x.outstanding}</strong></div><div><span>Retained responses</span><strong>{x.historical_total}</strong></div></div>
 <h4>Current publication · version {x.publication_version||'not published'}</h4>{x.items.length?<ul className="meeting-response-list">{x.items.map(person=><li key={person.resident_id}><div><strong>{person.name}</strong><small>{person.homes.map(h=>h.label).join(' · ')}</small></div><span>{person.acknowledged?'Acknowledged '+communityTime(person.at):'Awaiting personal acknowledgement'}</span></li>)}</ul>:<p className="form-help">No current eligible acknowledgers for this publication.</p>}<PageControls label="current meeting responses" page={x.page} total={x.expected} size={20} onPage={setPage} disabled={load.loading}/>
 <h4>Retained personal originals</h4>{x.history.length?<ul className="meeting-response-list">{x.history.map(person=><li key={person.resident_id+':'+person.version}><div><strong>{person.name}</strong><small>Published version {person.version} · {person.homes.map(h=>h.label).join(' · ')}</small></div><span>{communityTime(person.at)}</span></li>)}</ul>:<p className="form-help">No personal acknowledgements have been recorded.</p>}<PageControls label="retained meeting responses" page={x.history_page} total={x.historical_total} size={20} onPage={setHistoryPage} disabled={load.loading}/></>}</FundUnavailable></section>
}
