import { useEffect, useState } from 'react'
import type { User } from '../api'
import { deliveryStates, messageStates, messageTargetLabel, useMessageLoad } from '../messages'
import type { MessageConfig, MessagePage, MessageSummary } from '../messages'
import { careTime } from '../upkeep'
import { MessageCompose } from './MessageCompose'
import { MessageDetail } from './MessageDetail'
import { FilterSelect } from './FilterSelect'
import { PageControls } from './Maintenance'
import { Icon } from './Icon'

function DeliveryArt(){return <svg className="message-art" aria-hidden="true" viewBox="0 0 280 210" fill="none"><ellipse cx="135" cy="180" rx="112" ry="14" fill="#e3e9d9"/><path d="M33 145c48 9 79-37 93-52s48-40 80-34" stroke="#a1b28a" strokeWidth="2" strokeDasharray="5 7"/><path d="m126 31 121 29-88 71-4-44-29-56Z" fill="#e7edde" stroke="#8ca27a" strokeWidth="2"/><path d="m247 60-92 27-29-56m29 56 4 44 26-25" stroke="#8ca27a" strokeWidth="2"/><rect x="37" y="92" width="77" height="67" rx="12" fill="#fdfbf4" stroke="#c1ccb4" strokeWidth="2"/><path d="m43 99 32 24 33-24m-65 53 23-20m42 20-23-20" stroke="#bac8ab" strokeWidth="2"/><circle cx="228" cy="147" r="25" fill="#eee5d8"/><path d="m216 146 9 10 16-20" stroke="#948268" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
const hashMessage=()=>new URLSearchParams(window.location.hash.split('?')[1]??'').get('message')
export function Messages({user}:{user:User}) {
  const [selected,setSelected]=useState<string|null>(hashMessage),[compose,setCompose]=useState(false),[search,setSearch]=useState(''),[state,setState]=useState(''),[kind,setKind]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0)
  const staff=user.can_review_requests||user.can_manage_records
  const config=useMessageLoad<MessageConfig>('/api/messages/config'),summary=useMessageLoad<MessageSummary>('/api/messages/summary?refresh='+revision),load=useMessageLoad<MessagePage>('/api/messages?'+new URLSearchParams({q:search,state,kind,page:String(page),refresh:String(revision)})),visible=!load.loading&&!load.error?load.data:null
  const open=(id:string)=>{setCompose(false);setSelected(id);window.history.replaceState(null,'','#messages?message='+encodeURIComponent(id))},close=()=>{setCompose(false);setSelected(null);window.history.replaceState(null,'','#messages')}
  useEffect(()=>{const change=()=>{setSelected(hashMessage());setCompose(false)};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change)},[])
  const totals=summary.loading||summary.error?null:summary.data
  return <div className="page-enter messages-page"><section className="maintenance-hero message-hero"><div><span className="eyebrow">THOUGHTFULLY SENT. CLEARLY TRACKED.</span><h1>A little message.<br/><em>A closer community.</em></h1><p>{staff?'The right people, a separate review, and a clear record of what happened.':'Your community’s messages, with your choices respected at every step.'}</p>{staff&&<button className="button button-dark" disabled={config.loading||!!config.error||!config.data?.simulation_enabled} onClick={()=>setCompose(true)}>Prepare a message<Icon name="arrow"/></button>}</div><DeliveryArt/></section>
    <div className="message-channel-banner"><span><Icon name="leaf"/><strong>Local delivery simulation</strong></span><p>WhatsApp and email providers await configuration. No real messages are sent.</p>{config.error&&<button className="text-link" onClick={config.reload}>Retry provider status<Icon name="refresh"/></button>}</div>
    <section className="message-attention" aria-label="Communication attention">{[
      ['Awaiting review',totals?.batches.PENDING??0,'A separate decision before delivery'],['Queued',totals?.outcomes.QUEUED??0,'Approved envelopes to hand off'],['Needs reconciliation',totals?.outcomes.UNKNOWN??0,'Resolve the existing attempt first'],['Definite failures',totals?.outcomes.FAILED??0,'Review eligibility before a bounded retry'],
    ].map(([label,count,hint])=><div key={label}><span>{label}</span><strong>{totals?count:'—'}</strong><small>{hint}</small></div>)}</section>{summary.error&&<div className="connection-error" role="alert"><p>Delivery counts are unavailable. The register remains usable.</p><button onClick={summary.reload}>Retry counts<Icon name="refresh"/></button></div>}
    <section className="message-register"><div className="section-heading"><div><h2>{staff?'The communication register':'Your message history'}</h2><p>{staff?'Keep proposals, recipient decisions and truthful outcomes together.':'Only your approved messages and delivery decisions appear here.'}</p></div><span className="result-count">{visible?visible.total+' messages in this view':'Checking messages…'}</span></div>
      <div className="message-filters"><label className="search-control"><Icon name="search"/><input aria-label="Search message register" placeholder="Find a notice or published statement…" maxLength={100} value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}}/></label><FilterSelect label="Filter message state" value={state} options={[{value:'',label:'All decisions'},...Object.entries(messageStates).map(([value,label])=>({value,label}))]} onChange={value=>{setState(value);setPage(1)}}/><FilterSelect label="Filter message source" value={kind} options={[{value:'',label:'All sources'},{value:'NOTICE',label:'Community notices'},{value:'RECEIPT',label:'Private receipts'},{value:'STATEMENT',label:'Financial statements'}]} onChange={value=>{setKind(value);setPage(1)}}/>{(search||state||kind)&&<button className="clear-button" onClick={()=>{setSearch('');setState('');setKind('');setPage(1)}}>Clear<Icon name="close"/></button>}</div>
      {load.loading?<p className="empty-state" role="status">Opening current messages…</p>:load.error?<div className="empty-state" role="alert"><h3>Messages could not be opened.</h3><p>{load.error}</p><button className="button button-dark" onClick={load.reload}>Try again<Icon name="refresh"/></button></div>:visible&&<>{visible.items.length?<div className="message-cards">{visible.items.map(x=><button className="message-card" key={x.id} aria-label={'Open message '+x.source.title} onClick={()=>open(x.id)}><span className="message-card-top"><span>{x.channel==='EMAIL'?'Email':'WhatsApp'} · simulation</span><Icon name="arrow"/></span><h3>{x.source.title}</h3><span className="contact-state">{messageStates[x.state]}</span><p>{messageTargetLabel(x.target)}{staff?' · '+x.counts.eligible_people+' eligible '+(x.counts.eligible_people===1?'person':'people')+' · '+x.counts.destinations+' '+(x.counts.destinations===1?'destination':'destinations'):''}</p><div className="message-card-outcomes">{Object.entries(x.outcomes).map(([state,count])=><span key={state}>{count} {deliveryStates[state]?.toLowerCase()??state}</span>)}</div><small>{careTime(x.updated_at)}</small></button>)}</div>:<div className="empty-state"><Icon name="community"/><h3>{search||state||kind?'No messages match these choices.':'A conversation starts here.'}</h3><p>{staff?'Prepare a message from an approved notice, original receipt or deliberately published financial statement, then ask a separate eligible reviewer.':'Your approved messages will appear here when the society deliberately shares a permitted update.'}</p></div>}{visible.total>12&&<PageControls label="messages" page={page} total={visible.total} size={12} onPage={setPage}/>}</>}
    </section>{compose&&<MessageCompose user={user} onClose={close} onSaved={id=>{setRevision(value=>value+1);open(id)}}/>}{selected&&<MessageDetail key={selected} id={selected} onClose={close} onChanged={()=>setRevision(value=>value+1)}/>}
  </div>
}
