import { useState } from 'react'
import { deliveryStates, messageKindLabels, messageReasons, useMessageLoad } from '../messages'
import type { MessageException, MessageExceptionPage } from '../messages'
import { careTime } from '../upkeep'
import { FilterSelect } from './FilterSelect'
import { PageControls } from './Maintenance'
import { Icon } from './Icon'

export function MessageExceptions({revision,onOpen}:{revision:number;onOpen:(item:MessageException)=>void}) {
  const [state,setState]=useState(''),[page,setPage]=useState(1)
  const load=useMessageLoad<MessageExceptionPage>('/api/messages/exceptions?'+new URLSearchParams({state,page:String(page),refresh:String(revision)}))
  const data=!load.loading&&!load.error?load.data:null
  return <section className="message-exceptions" aria-label="Private delivery exceptions">
    <div className="section-heading"><div><span className="eyebrow">THE FOLLOW-THROUGH</span><h2>Every loose end, in sight.</h2><p>Open the retained outcome to review a retry or reconcile the same attempt.</p></div><span className="result-count">{data?`${data.total} ${data.total===1?'outcome':'outcomes'} in this view`:'Checking outcomes…'}</span></div>
    <div className="message-exception-counts" aria-label="Full exception counts">{[['UNKNOWN','Needs reconciliation'],['FAILED','Definite failures'],['CLAIMED','Handoff pending']].map(([value,label])=><button type="button" key={value} aria-pressed={state===value} onClick={()=>{setState(state===value?'':value);setPage(1)}}><span>{label}</span><strong>{data?data.counts[value]??0:'—'}</strong><Icon name="arrow"/></button>)}</div>
    <div className="message-filters"><FilterSelect label="Filter delivery exceptions" value={state} options={[{value:'',label:'All exceptions'},{value:'UNKNOWN',label:'Needs reconciliation'},{value:'FAILED',label:'Definite failures'},{value:'CLAIMED',label:'Handoff pending'}]} onChange={value=>{setState(value);setPage(1)}}/>{state&&<button type="button" className="clear-button" onClick={()=>{setState('');setPage(1)}}>Clear exception filter<Icon name="close"/></button>}</div>
    {load.loading?<p className="empty-state" role="status">Checking retained delivery outcomes…</p>:load.error?<div className="empty-state" role="alert"><h3>Delivery exceptions could not be opened.</h3><p>{load.error}</p><button type="button" className="button button-dark" onClick={load.reload}>Retry delivery exceptions<Icon name="refresh"/></button></div>:data&&<>{data.items.length?<div className="message-exception-cards">{data.items.map(item=><button type="button" key={item.delivery_id} className="message-card message-exception-card" aria-label={`Open ${deliveryStates[item.state].toLowerCase()} for ${item.title} at ${item.destination}`} onClick={()=>onOpen(item)}><span className="message-card-top"><span>{messageKindLabels[item.source_kind]}</span><Icon name="arrow"/></span><h3>{item.title}</h3><span className="message-exception-destination">{item.destination}</span><span className={'message-outcome message-outcome-'+item.state.toLowerCase()}>{deliveryStates[item.state]}</span><p>{item.can_reconcile?'Reconcile this retained attempt.':item.can_retry?'A deliberate retry is available after fresh checks.':item.state==='CLAIMED'?'The claimed handoff is still pending.':item.attempts>=3?'The three-attempt limit has been reached.':item.retry_at>Date.now()/1000?`Retry available after ${careTime(item.retry_at)}.`:'Review the current source and eligible recipients before another attempt.'}</p>{item.eligibility_problem&&<p className="message-exception-problem">{messageReasons[item.eligibility_problem]??item.eligibility_problem}</p>}<small>{item.channel==='EMAIL'?'Email':'WhatsApp'} · Attempt {item.attempts} of 3 · {careTime(item.updated_at)}</small></button>)}</div>:<div className="empty-state"><Icon name="leaf"/><h3>No delivery exceptions in this view.</h3><p>Recorded delivery, explicit read and suppressed outcomes remain in their message history.</p></div>}{data.total>12&&<PageControls label="delivery exceptions" page={data.page} total={data.total} size={data.page_size} onPage={setPage}/>}</>}
  </section>
}
