import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { deliveryStates, messageReasons, whatsappReasons, messageStates, messageTargetLabel, useMessageLoad, useMessageWrite } from '../messages'
import type { MessageDetail as Detail } from '../messages'
import { careTime } from '../upkeep'
import { PortalDialog } from './PortalDialog'
import { FormSelect } from './FilterSelect'
import { FundCheck, FundUnavailable } from './FundShared'
import { FineFeedback } from './FineShared'
import { MessageCountFacts, MessageEnvelope, MessageRecipientList, MessageProviderFacts, MessageReminderFacts } from './MessageShared'
import { PageControls } from './Maintenance'
import { Icon } from './Icon'

const actionLabels:Record<string,string>={APPROVED:'Approve frozen proposal',DECLINED:'Decline proposal',REFRESH:'Refresh recipient snapshot',WITHDRAWN:'Withdraw proposal',CANCELLED:'Cancel unsent messages',DISPATCH:'Run simulated delivery',RECONCILE:'Reconcile this handoff'}
const sourceLabels:Record<string,string>={NOTICE:'Open shared notice',RECEIPT:'Open shared receipt',STATEMENT:'Open shared statement',MAINTENANCE_REMINDER:'Open maintenance record',FUND_REMINDER:'Open fund record',MEETING_REMINDER:'Open meeting publication'}
export function MessageDetail({id,initialDeliveryPage=1,selectedDelivery='',onClose,onChanged}:{id:string;initialDeliveryPage?:number;selectedDelivery?:string;onClose:()=>void;onChanged:()=>void}) {
  const [recipientPage,setRecipientPage]=useState(1),[deliveryPage,setDeliveryPage]=useState(initialDeliveryPage),[eventPage,setEventPage]=useState(1),[action,setAction]=useState(''),[delivery,setDelivery]=useState(''),[reason,setReason]=useState(''),[outcome,setOutcome]=useState('ACCEPTED'),[checked,setChecked]=useState(false),[success,setSuccess]=useState('')
  const load=useMessageLoad<Detail>('/api/messages/'+encodeURIComponent(id)+'?'+new URLSearchParams({recipient_page:String(recipientPage),delivery_page:String(deliveryPage),event_page:String(eventPage)})),x=load.data,writer=useMessageWrite(),disabled=writer.busy||writer.locked
  const providerTest=x?.provider_mode==='CLOUD_FIXTURE'
  const destinationShown=useRef(false)
  useEffect(()=>{if(!load.loading&&!load.error&&selectedDelivery&&!destinationShown.current){const node=document.getElementById('message-delivery-'+selectedDelivery);if(node){node.scrollIntoView({block:'center'});destinationShown.current=true}}},[load.loading,load.error,selectedDelivery,x])
  const label=(value:string)=>value==='DISPATCH'&&providerTest?'Send test message':actionLabels[value]
  useEffect(()=>{setChecked(false)},[x?.version])
  const start=(next:string,group='')=>{writer.reset();setAction(next);setDelivery(group);setReason('');setOutcome('ACCEPTED');setChecked(false);setSuccess('')}
  const reload=()=>{writer.reset();setChecked(false);load.reload()}
  const submit=async(event:FormEvent)=>{
    event.preventDefault();if(!x||!checked||writer.conflict)return
    const suffix=action==='DISPATCH'?'/dispatch':action==='RECONCILE'?'/deliveries/'+encodeURIComponent(delivery)+'/reconcile':'/actions'
    const result=await writer.send('/api/messages/'+encodeURIComponent(id)+suffix,{version:x.version,action,reason,...(action==='DISPATCH'&&!providerTest?{outcome}:{})})
    if(result){setSuccess(action==='DISPATCH'?(providerTest?'Provider response recorded. Refresh to see reported delivery updates.':'Simulation recorded. Inspect the reported outcomes below.'):action==='RECONCILE'?'The existing handoff was reconciled without another send.':action==='REFRESH'?'A new recipient snapshot is ready for independent review.':'Decision recorded; original history retained.');setAction('');setChecked(false);load.reload();onChanged()}
  }
  return <PortalDialog titleId="message-detail-title" closeLabel="Close message" onClose={onClose} busy={disabled} className="fine-dialog message-dialog"><div className="dialog-scroll message-detail"><span className="eyebrow">A DELIVERY, KEPT TOGETHER</span><h2 id="message-detail-title">{x?.source.title??'Opening this message…'}</h2><FundUnavailable error={load.error} loading={load.loading} onRetry={load.reload}>{x&&<>
    <span className="contact-state">{messageStates[x.state]}</span><p className="message-simulation"><Icon name="leaf"/>{providerTest?'WhatsApp provider test · External delivery disabled.':"Local simulation · "+(x.channel==='EMAIL'?'Email':'WhatsApp')+" · No real message sent."}</p>{success&&<p className="form-success" role="status">{success}</p>}
    {x.staff&&<><MessageProviderFacts provider={x.provider}/><MessageReminderFacts reminder={x.source.reminder}/></>} {x.envelope&&<MessageEnvelope envelope={x.envelope}/>}{!action&&!disabled&&x.source.link&&sourceLabels[x.source.kind]&&<a className="button button-light" href={x.source.link}>{sourceLabels[x.source.kind]}<Icon name="arrow"/></a>}
    {x.staff?<><p className="form-help">{messageTargetLabel(x.target)} · Snapshot {x.snapshot_version} · Version {x.version}</p><MessageCountFacts counts={x.counts}/></>:<p className="form-help">Only your delivery decision is shown. Other recipients and private review history remain private.</p>}
    {Object.keys(x.outcomes).length>0&&<section className="message-outcomes" aria-label="Reported delivery outcomes">{Object.entries(x.outcomes).map(([state,count])=><span key={state} className={'message-outcome message-outcome-'+state.toLowerCase()}><strong>{count}</strong>{deliveryStates[state]??state}</span>)}</section>}
    {x.review_problem&&<p className="form-error" role="alert">{messageReasons[x.review_problem]??x.review_problem}. {x.source.reminder&&['SOURCE_CHANGED','SOURCE_UNAVAILABLE'].includes(x.review_problem)?'Withdraw this proposal and prepare a new reminder from a current source.':'A fresh snapshot and independent review are required before approval.'}</p>}
    {action?<form className="portal-form message-action-form" onSubmit={event=>{void submit(event)}}><h3>{label(action)}</h3>{action==='RECONCILE'&&<p className="form-help">{providerTest?'Review the existing attempt. This checks retained evidence without sending again.':'Look up the existing simulation attempt. This does not resend the envelope or manufacture delivery/read proof.'}</p>}{action==='CANCELLED'&&<p className="form-help">Only queued or definitively failed envelopes are cancelled. Accepted copies and uncertain handoffs remain recorded.</p>}{action==='REFRESH'&&<p className="form-help">Keep the old recipient decisions and create a new current snapshot. A different eligible reviewer must approve it.</p>}
      <fieldset className="records-fieldset" disabled={disabled}>{action==='DISPATCH'&&!providerTest&&<label>Simulation outcome<FormSelect label="Simulation outcome" value={outcome} options={[{value:'ACCEPTED',label:'Provider accepted · no delivery report'},{value:'DELIVERED',label:'Explicit delivery report'},{value:'READ',label:'Explicit delivery and read reports'},{value:'REJECTED',label:'Definite rejection · retry allowed'},{value:'UNKNOWN',label:'Lost response · reconcile before retry'}]} onChange={value=>{setOutcome(value);setChecked(false)}}/></label>}<label>Decision reason<textarea required minLength={10} maxLength={300} value={reason} onChange={event=>{setReason(event.target.value);setChecked(false)}}/></label><FundCheck checked={checked} onChange={setChecked}>I reviewed the current content, recipients, permissions and this decision’s effect.</FundCheck></fieldset>
      <FineFeedback writer={writer} onReload={reload}/><div className="form-actions message-form-actions"><button type="button" className="button button-light" disabled={disabled} onClick={()=>setAction('')}>Back to message</button><button className="button button-dark" disabled={writer.busy||writer.conflict||!checked||(action==='APPROVED'&&!x.can_approve)}>{writer.busy?'Saving…':writer.locked?'Retry this decision':label(action)}<Icon name="check"/></button></div>
    </form>:x.staff&&<div className="message-detail-actions">{x.can_approve&&<button className="button button-dark" onClick={()=>start('APPROVED')}>Review for approval<Icon name="check"/></button>}{x.state==='PENDING'&&!x.can_withdraw&&<button className="button button-light" onClick={()=>start('DECLINED')}>Decline proposal</button>}{x.can_refresh&&<button className="button button-light" onClick={()=>start('REFRESH')}>Refresh recipient snapshot<Icon name="refresh"/></button>}{x.can_withdraw&&<button className="text-link" onClick={()=>start('WITHDRAWN')}>Withdraw proposal</button>}{x.can_dispatch&&<button className="button button-dark" onClick={()=>start('DISPATCH')}>{label('DISPATCH')}<Icon name="arrow"/></button>}{providerTest&&<button className="button button-light" disabled={disabled} onClick={load.reload}>Refresh delivery status<Icon name="refresh"/></button>}{x.can_cancel&&<button className="button button-light" onClick={()=>start('CANCELLED')}>Cancel unsent messages</button>}</div>}
    <MessageRecipientList items={x.recipients} total={x.recipient_total} page={recipientPage} onPage={setRecipientPage} disabled={disabled}/>
    {x.staff&&x.delivery_total>0&&<section className="message-deliveries" aria-label="Envelope outcomes"><h3>What happened at each destination.</h3><ul>{x.deliveries.map(d=><li key={d.id} id={'message-delivery-'+d.id} data-delivery-id={d.id} className={d.id===selectedDelivery?'message-delivery-selected':''}><div><strong>{d.destination}</strong><span className={'message-outcome message-outcome-'+d.state.toLowerCase()}>{deliveryStates[d.state]}</span><small>Attempt {d.attempts} of 3</small></div>{d.reason&&<p>{whatsappReasons[d.reason]??messageReasons[d.reason]??d.reason}</p>}<dl>{d.accepted_at>0&&<div><dt>Provider accepted</dt><dd>{careTime(d.accepted_at)}</dd></div>}{d.delivered_at>0&&<div><dt>Delivery reported</dt><dd>{careTime(d.delivered_at)}</dd></div>}{d.read_at>0&&<div><dt>Read reported</dt><dd>{careTime(d.read_at)}</dd></div>}{(d.retry_at??0)>0&&<div><dt>Retry available after</dt><dd>{careTime(d.retry_at!)}</dd></div>}</dl>{d.state==='UNKNOWN'&&<button className="button button-light" disabled={disabled} onClick={()=>start('RECONCILE',d.id)}>Reconcile handoff<Icon name="refresh"/></button>}</li>)}</ul>{x.delivery_total>20&&<PageControls label="message destinations" page={deliveryPage} total={x.delivery_total} size={20} onPage={setDeliveryPage} disabled={disabled}/>}</section>}
    {x.staff&&x.event_total>0&&<section className="review-history message-history" aria-label="Message activity"><h3>Every decision stays on record.</h3><ol>{x.events.map(e=><li key={e.version}><strong>{actionLabels[e.action]??e.action.toLowerCase().replaceAll('_',' ')}</strong><p className="preserve-lines">{e.reason}</p><small>{e.actor} · {careTime(e.at)}</small><details><summary>Frozen proposal at this step</summary><MessageProviderFacts provider={e.snapshot.provider}/><MessageCountFacts counts={e.snapshot.counts}/><MessageEnvelope envelope={e.snapshot.envelope}/></details></li>)}</ol>{x.event_total>20&&<PageControls label="message activity" page={eventPage} total={x.event_total} size={20} onPage={setEventPage} disabled={disabled}/>}</section>}
    </>}</FundUnavailable></div></PortalDialog>
}
