import type { ChecklistCheck, ChecklistRecord, ChecklistSnapshot } from '../checklists'
import { checkLabels, checklistKinds, checklistPhases, contactStateLabels } from '../checklists'
import { displayDate } from '../maintenance'
import { careTime } from '../upkeep'
import { Icon } from './Icon'
export { BudgetReadError as ChecklistReadError, BudgetWriteFeedback as ChecklistWriteFeedback } from './BudgetShared'

export function ChecklistGiven({snapshot,label='The supplied request'}:{snapshot:Pick<ChecklistSnapshot,'home_label'|'person_name'|'kind'|'effective_date'|'note'>;label?:string}){return <section className="checklist-paper" aria-label={label}><span className="eyebrow">{label}</span><div className="checklist-paper-heading"><h3>{snapshot.home_label}</h3><span className="contact-state">{checklistKinds[snapshot.kind]}</span></div><p className="checklist-person">{snapshot.person_name}</p><dl><div><dt>Supplied date</dt><dd>{displayDate(snapshot.effective_date)}</dd></div></dl><p className="checklist-note">{snapshot.note}</p></section>}
export function ChecklistSourceCard({record}:{record:ChecklistRecord}){const source=record.source;if(!record.can_open_home&&!source.current)return <div className="checklist-source-note" role="status"><Icon name="shield"/><p>Your submitted outcome stays here. Current household details and new household actions are unavailable.</p></div>;return <section className="checklist-current-source" aria-label="Current checklist source"><span className="eyebrow">THE CURRENT CONTEXT</span><div><p><span>Registry</span><strong>{source.home_label}</strong><small>Record version {source.registry_version} · {source.current?'Active relationship':'No active relationship'}</small></p><p><span>Contact profile</span><strong>{contactStateLabels[source.contact_state]??source.contact_state}</strong><small>{source.contact_version?'Profile version '+source.contact_version:'No contact version on record'}</small></p></div><div className="checklist-source-links">{record.can_open_home&&<a className="text-link" href={'#homes?home='+encodeURIComponent(record.snapshot.flat_id)} target="_blank" rel="noopener">Open registry record<Icon name="arrow"/></a>}{record.can_open_contact&&<a className="text-link" href={'#contacts?person='+encodeURIComponent(record.snapshot.resident_id)} target="_blank" rel="noopener">Open contact preferences<Icon name="arrow"/></a>}</div><p className="form-help">The checklist records a review. Registry, contact choices and access are managed in their own sections.</p></section>}
export function ChecklistCheckRows({checks,currentKey,onCheck,historical=false}:{checks:ChecklistCheck[];currentKey?:string;onCheck?:(kind:string)=>void;historical?:boolean}){return <ol className="checklist-check-rows">{checks.map((check,index)=>{const stale=!historical&&check.state!=='INCOMPLETE'&&!!currentKey&&check.source_key!==currentKey,status=stale?'Needs a current review':check.state==='CHECKED'?'Checked':check.state==='NOT_APPLICABLE'?'Not applicable, explained':'Awaiting a check';return <li key={check.kind} className={stale?'checklist-check-stale':check.state==='INCOMPLETE'?'':'checklist-check-done'}><span className="checklist-step-mark">{check.state==='INCOMPLETE'||stale?String(index+1).padStart(2,'0'):<Icon name="check"/>}</span><div><h4>{checkLabels[check.kind]}</h4><span>{status}</span>{check.reference&&<p>{check.reference}</p>}{check.checked_at>0&&<small>Recorded {careTime(check.checked_at)}</small>}</div>{onCheck&&<button type="button" className="text-link" aria-label={'Review '+checkLabels[check.kind]} onClick={()=>onCheck(check.kind)}>{check.state==='INCOMPLETE'?'Review':'Review again'}<Icon name="arrow"/></button>}</li>})}</ol>}
export function ChecklistState({record}:{record:ChecklistRecord}){return <div className="checklist-state"><span className="contact-state">{checklistPhases[record.state]}</span>{record.pending&&record.approved&&<span>Linked correction · {checklistPhases[record.phase].toLowerCase()}</span>}{record.pending&&record.stale_checks>0&&<span>{record.stale_checks} checks need a current review</span>}</div>}
