import { useEffect, useRef, useState } from 'react'
import { request } from '../api'
import type { User } from '../api'
import { checklistKinds, todayInSociety, useChecklistLoad, useChecklistWrite } from '../checklists'
import type { ChecklistDetail, ChecklistOptions, ChecklistRecord } from '../checklists'
import { ChecklistGiven, ChecklistReadError, ChecklistSourceCard, ChecklistWriteFeedback } from './MoveChecklistShared'
import { FormSelect } from './FilterSelect'
import { PageControls } from './Maintenance'
import { PortalDialog } from './PortalDialog'
import { Icon } from './Icon'

export function MoveChecklistForm({user,existing,correction=false,onClose,onSaved}:{user:User;existing?:ChecklistRecord;correction?:boolean;onClose:()=>void;onSaved:(id:string)=>void}){
 const seed=existing?(correction?existing.approved??existing.snapshot:existing.snapshot):null
 const [current,setCurrent]=useState(existing),[kind,setKind]=useState(seed?.kind??'MOVE_IN'),[home,setHome]=useState(seed?.flat_id??''),[homeLabel,setHomeLabel]=useState(seed?.home_label??''),[person,setPerson]=useState(seed?.resident_id??''),[personName,setPersonName]=useState(seed?.person_name??''),[date,setDate]=useState(seed?.effective_date??todayInSociety()),[note,setNote]=useState(seed?.note??''),[reason,setReason]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[preview,setPreview]=useState(false),[checked,setChecked]=useState(false),[localError,setLocalError]=useState(''),[reloading,setReloading]=useState(false)
 const write=useChecklistWrite(),scroll=useRef<HTMLDivElement>(null),frozen=write.busy||write.locked||reloading,dismissBlocked=write.busy||(write.locked&&!write.conflict),allowed=!current||(correction?current.can_correct:current.can_revise)
 const homeLoad=useChecklistLoad<ChecklistOptions>('/api/move-checklists/options?'+new URLSearchParams({q:search,page:String(page)}),!existing),peopleLoad=useChecklistLoad<ChecklistOptions>('/api/move-checklists/options?home='+encodeURIComponent(home),!existing&&!!home),homes=!homeLoad.loading&&!homeLoad.error?homeLoad.data:null,people=!peopleLoad.loading&&!peopleLoad.error?peopleLoad.data:null
 useEffect(()=>{if(!user.can_manage_registry&&people?.people.length===1){setPerson(people.people[0].id);setPersonName(people.people[0].name)}},[people,user.can_manage_registry])
 useEffect(()=>{scroll.current?.scrollTo({top:0})},[preview]);useEffect(()=>{if(write.reauth)setChecked(false)},[write.reauth])
 const reload=async()=>{if(!current)return;setReloading(true);setLocalError('');try{const fresh=await request<ChecklistDetail>('/api/move-checklists/'+encodeURIComponent(current.id));setCurrent(fresh);setPreview(false);setChecked(false);write.reset()}catch(error){setLocalError((error as Error).message)}finally{setReloading(false)}}
 const showPreview=()=>{setLocalError('');if(!allowed)return;if(!home||!person||!personName||!homeLabel){setLocalError('Choose the current home and person before reviewing the request.');return}setNote(note.trim());setReason(reason.trim());setPreview(true);setChecked(false)}
 const submit=async()=>{if(!checked||(!allowed&&!write.locked))return;const payload=current?{version:current.version,action:correction?'CORRECTION':'REVISE',effective_date:date,note,reason}:{version:0,flat_id:home,resident_id:person,kind,effective_date:date,note,reason};const result=await write.send(current?'/api/move-checklists/'+encodeURIComponent(current.id)+'/actions':'/api/move-checklists',payload);if(result)onSaved(result.id)}
 const options=[{value:'',label:'Choose a current home'},...(home&&!homes?.homes.some(x=>x.id===home)?[{value:home,label:homeLabel}]:[]),...(homes?.homes??[]).map(x=>({value:x.id,label:x.label}))]
 return <PortalDialog titleId="checklist-form-heading" closeLabel="Close checklist proposal" onClose={onClose} busy={dismissBlocked} className="checklist-dialog"><div className="dialog-scroll" ref={scroll}><span className="eyebrow">A NEW CHAPTER, CONSIDERED</span><h2 id="checklist-form-heading">{preview?'The request, before the checks.':correction?'Keep the story. Correct the detail.':current?'Give the request a clear update.':'A thoughtful start. A smoother handover.'}</h2><p className="dialog-description">{correction?'The completed predecessor stays on record while this linked correction receives fresh checks and separate review.':'Keep the supplied details together, then let the registry team check and review them.'}</p>
 {!allowed&&<p className="form-error" role="status">This request is no longer available for this proposal. Your entered text is retained.</p>}
 <form onSubmit={event=>{event.preventDefault();if(preview)void submit();else showPreview()}}>
 {!preview&&<fieldset disabled={frozen||!allowed}>
 {!existing&&<><label>Review type<FormSelect label="Checklist review type" value={kind} options={Object.entries(checklistKinds).map(([value,label])=>({value,label}))} onChange={setKind}/></label><label className="search-control"><Icon name="search"/><input aria-label="Search checklist homes" placeholder="Find a home…" maxLength={100} value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}}/></label>{homeLoad.error?<ChecklistReadError title="Home choices could not be opened." error={homeLoad.error} onRetry={homeLoad.reload}/>:<>{homeLoad.loading&&<p role="status">Opening your current home choices…</p>}<label>Home<FormSelect label="Checklist home" value={home} options={options} required disabled={frozen||homeLoad.loading} onChange={value=>{setHome(value);setHomeLabel(homes?.homes.find(x=>x.id===value)?.label??'');setPerson('');setPersonName('')}}/></label>{homes&&homes.total>12&&<PageControls label="checklist homes" page={page} total={homes.total} size={12} onPage={setPage} disabled={frozen}/>}</>}{home&&<>{peopleLoad.loading?<p role="status">Opening the permitted person choices…</p>:peopleLoad.error?<ChecklistReadError title="Person choices could not be opened." error={peopleLoad.error} onRetry={peopleLoad.reload}/>:user.can_manage_registry?<label>Person<FormSelect label="Checklist person" value={person} options={[{value:'',label:'Choose the current person'},...(people?.people??[]).map(x=>({value:x.id,label:x.name}))]} required disabled={frozen||peopleLoad.loading} onChange={value=>{setPerson(value);setPersonName(people?.people.find(x=>x.id===value)?.name??'')}}/></label>:personName&&<p className="checklist-own-person"><span>For your own record</span><strong>{personName}</strong></p>}</>}</>}
 {existing&&<ChecklistGiven snapshot={seed!} label={correction?'Completed original retained':'Current supplied request'}/>}
 <label>Supplied date<input aria-label="Checklist supplied date" type="date" value={date} onChange={event=>setDate(event.target.value)} required min="1900-01-01" max="2100-12-31"/></label><label>What should be reviewed?<textarea aria-label="Checklist explanation" value={note} onChange={event=>setNote(event.target.value)} required minLength={10} maxLength={800} rows={4} placeholder="The supplied move or contact details, and the review you need."/></label><label>Proposal reason<textarea aria-label="Checklist proposal reason" value={reason} onChange={event=>setReason(event.target.value)} required minLength={10} maxLength={800} rows={3}/></label>
 </fieldset>}
 {preview&&<><ChecklistGiven snapshot={{home_label:homeLabel,person_name:personName,kind,effective_date:date,note}} label="Exact proposed checklist"/>{current&&<ChecklistSourceCard record={current}/>}<p className="checklist-note"><span className="eyebrow">PROPOSAL REASON</span>{reason}</p><label className="confirmation"><input type="checkbox" checked={checked} disabled={frozen} onChange={event=>setChecked(event.target.checked)}/>I reviewed this exact home, person, date and checklist proposal.</label></>}
 {localError&&<div className="form-error" role="alert"><p>{localError}</p></div>}{reloading&&<p role="status">Opening the current checklist…</p>}<ChecklistWriteFeedback write={write} onReload={()=>{void reload()}}/>
 <div className="form-actions"><button type="button" className="button button-quiet" disabled={preview?frozen:dismissBlocked} onClick={()=>{if(preview){setPreview(false);setChecked(false);write.reset()}else onClose()}}>{preview?'Edit proposal':'Cancel'}</button><button type="submit" className="button button-dark" disabled={write.busy||reloading||write.conflict||!allowed||(preview&&!checked)||(!existing&&!preview&&(homeLoad.loading||peopleLoad.loading||!!homeLoad.error||!!peopleLoad.error))}>{write.busy?'Saving…':write.locked?'Retry this proposal':preview?'Submit for checks':'Preview checklist proposal'}<Icon name="arrow"/></button></div>
 </form></div></PortalDialog>
}
