import { useEffect, useState } from 'react'
import type { User } from '../api'
import { checklistKinds, checklistLink, checklistPhases, useChecklistLoad } from '../checklists'
import type { ChecklistPage, ChecklistRecord } from '../checklists'
import { displayDate } from '../maintenance'
import { ChecklistReadError } from './MoveChecklistShared'
import { MoveChecklistForm } from './MoveChecklistForm'
import { MoveChecklistDetails } from './MoveChecklistDetail'
import { FilterSelect } from './FilterSelect'
import { PageControls } from './Maintenance'
import { Icon } from './Icon'

function HandoverArt(){return <svg className="checklist-art" viewBox="0 0 260 230" fill="none" aria-hidden="true"><ellipse cx="130" cy="202" rx="111" ry="14" fill="#e2e8d8"/><path d="m55 91 68-50 72 50v100H55Z" fill="#e9e4d5" stroke="#a9b69c" strokeWidth="2"/><path d="m37 95 86-64 91 64" stroke="#56734f" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/><rect x="83" y="105" width="38" height="48" rx="4" fill="#cad5b8"/><path d="M102 106v46m-18-24h36" stroke="#f8f7ed" strokeWidth="3"/><rect x="145" y="115" width="28" height="76" rx="4" fill="#8e9e78"/><circle cx="166" cy="155" r="2" fill="#f5f1dc"/><circle cx="204" cy="164" r="34" fill="#f2ebdc"/><circle cx="196" cy="155" r="9" stroke="#8c8d60" strokeWidth="3"/><path d="m203 162 18 18m-6-6 5-5m-12-2 5-5" stroke="#8c8d60" strokeWidth="3" strokeLinecap="round"/><path d="M45 193v-33m0 12-10-9m10 2 11-10" stroke="#71845b" strokeWidth="2"/><ellipse cx="50" cy="151" rx="14" ry="23" transform="rotate(25 50 151)" fill="#b8c599"/></svg>}
export function MoveChecklists({user}:{user:User}){
 const [query,setQuery]=useState(''),[state,setState]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[selected,setSelected]=useState(checklistLink('checklist')),[eventPage,setEventPage]=useState(1),[form,setForm]=useState<ChecklistRecord|'new'|null>(null),[correction,setCorrection]=useState(false)
 const load=useChecklistLoad<ChecklistPage>('/api/move-checklists?'+new URLSearchParams({q:query,state,page:String(page),refresh:String(revision)})),data=!load.loading&&!load.error?load.data:null
 const url=(id:string)=>{const params=new URLSearchParams({panel:'checklists'});if(id)params.set('checklist',id);window.history.replaceState(null,'','#homes?'+params)},open=(id:string)=>{setSelected(id);setEventPage(1);setForm(null);url(id)},close=()=>{setSelected('');url('')},refresh=()=>setRevision(value=>value+1)
 useEffect(()=>{const change=()=>{setSelected(checklistLink('checklist'));setForm(null);setEventPage(1)};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change)},[])
 return <div className="page-enter checklists-page"><section className="maintenance-hero checklist-hero"><div><span className="eyebrow">THE LITTLE DETAILS OF BELONGING</span><h1>A new chapter.<br/><em>Every detail, considered.</em></h1><p>{user.can_manage_registry?'Keep move and contact requests, careful checks and separate decisions together.':'Keep your move or contact request, its checks and its outcome in one place.'}</p>{(user.can_manage_registry||data?.can_prepare)&&<button type="button" className="button button-dark" disabled={!data?.can_prepare} onClick={()=>{setForm('new');setCorrection(false)}}>Prepare a checklist<Icon name="arrow"/></button>}</div><HandoverArt/></section>
 <section className="checklist-attention" aria-label="Checklist attention">{[['Awaiting checks','checking','CHECKING'],['Ready for review','ready','READY'],['Information requested','info','INFO']].map(([label,key,value])=><button type="button" key={key} disabled={!data} onClick={()=>{setState(value);setPage(1)}}><span>{label}</span><strong>{data?data.counts[key]:'—'}</strong><Icon name="arrow"/></button>)}</section>
 <section className="checklist-register"><div className="section-heading"><div><span className="eyebrow">A CLEAR NEXT STEP</span><h2>{user.can_manage_registry?'The checklist desk.':'Your requests, thoughtfully kept.'}</h2><p>{user.can_manage_registry?'Open a request to review its supplied details, current context and retained history.':'Only your own submissions and their permitted outcomes appear here.'}</p></div><span className="result-count">{data?data.total+' '+(data.total===1?'checklist':'checklists'):'Checking requests…'}</span></div>
 <div className="checklist-filters"><label className="search-control"><Icon name="search"/><input aria-label="Search checklists" value={query} maxLength={100} placeholder="Find a home, person or supplied note…" onChange={event=>{setQuery(event.target.value);setPage(1)}}/></label><FilterSelect label="Filter checklists" value={state} options={[{value:'',label:'All checklist records'},{value:'CHECKING',label:'Awaiting checks'},{value:'READY',label:'Ready for separate review'},{value:'INFO',label:'Information requested'},{value:'COMPLETED',label:'Completed outcomes'},{value:'CLOSED',label:'Closed without completion'}]} onChange={value=>{setState(value);setPage(1)}}/>{(query||state)&&<button type="button" className="clear-button" onClick={()=>{setQuery('');setState('');setPage(1)}}>Clear<Icon name="close"/></button>}</div>
 {load.loading?<p className="empty-state" role="status">Opening the current checklist desk…</p>:load.error?<ChecklistReadError title="The checklist desk could not be opened." error={load.error} onRetry={load.reload}/>:data&&<>{data.items.length?<div className="checklist-cards">{data.items.map(record=>{const given=record.approved??record.snapshot;return <button type="button" className="checklist-card" key={record.id} aria-label={'Open checklist '+given.home_label+' '+given.person_name} onClick={()=>open(record.id)}><span className="checklist-card-top"><span>{checklistKinds[given.kind]}</span><Icon name="arrow"/></span><h3>{given.home_label}</h3><p>{given.person_name}</p><span className="contact-state">{checklistPhases[record.state]}</span><dl><div><dt>Supplied date</dt><dd>{displayDate(given.effective_date)}</dd></div><div><dt>{record.approved&&record.pending?'Latest proposal':'Recorded checks'}</dt><dd>{record.approved&&record.pending?checklistPhases[record.phase]:record.checked+record.not_applicable+' of 5'}</dd></div></dl>{record.pending&&record.stale_checks>0&&<small>Current context needs {record.stale_checks} checks reviewed again</small>}</button>})}</div>:<div className="empty-state"><Icon name="homes"/><h3>{query||state?'No checklists match these choices.':user.can_manage_registry?'A thoughtful handover starts here.':'A clear place for your next chapter.'}</h3><p>{user.can_manage_registry?'A supplied request begins with checks and receives a different administrator’s final review.':data.can_prepare?'Prepare a request for one of your current homes. The registry team handles its checks and review.':'Your submitted outcome history stays here. New household requests require a current relationship.'}</p></div>}{data.total>12&&<PageControls label="checklists" page={page} total={data.total} size={12} onPage={setPage}/>}</>}
 </section><p className="records-footnote"><Icon name="shield"/>Supplied requests, checked references and separate decisions stay on record.</p>
 {form?<MoveChecklistForm user={user} existing={form==='new'?undefined:form} correction={correction} onClose={()=>setForm(null)} onSaved={id=>{setForm(null);refresh();open(id)}}/>:selected?<MoveChecklistDetails key={selected} id={selected} eventPage={eventPage} onEventPage={setEventPage} onClose={close} onChanged={refresh} onEdit={(record,correct)=>{setForm(record);setCorrection(correct)}}/>:null}
 </div>
}
