import { useEffect, useRef, useState } from 'react'
import { request } from '../api'
import { expenseMethods, moneyInput, previewPaise, todayInSociety, useBudgetWrite } from '../budgets'
import type { BudgetResource, PaidExpenseResource, PaidExpenseSnapshot } from '../budgets'
import { BudgetWriteFeedback, PaidExpenseOriginal } from './BudgetShared'
import { displayDate } from '../maintenance'
import { PortalDialog } from './PortalDialog'
import { FilterSelect } from './FilterSelect'
import { Icon } from './Icon'

export function PaidExpenseForm({budget,existing,action='PAID',onClose,onSaved}:{budget:BudgetResource;existing?:PaidExpenseResource;action?:'PAID'|'CORRECTION'|'VOID';onClose:()=>void;onSaved:(id:string)=>void}){
 const seed=existing?.decision==='PENDING'?existing.snapshot:existing?.approved??existing?.snapshot
 const [current,setCurrent]=useState(existing),[currentBudget,setCurrentBudget]=useState(budget),[amount,setAmount]=useState(seed?moneyInput(seed.amount_paise):''),[date,setDate]=useState(seed?.paid_date??''),[payee,setPayee]=useState(seed?.payee??''),[category,setCategory]=useState(seed?.category??'Repairs'),[method,setMethod]=useState(seed?.method??'CASH'),[reference,setReference]=useState(seed?.reference??''),[source,setSource]=useState(seed?.source_note??''),[reason,setReason]=useState(''),[preview,setPreview]=useState(false),[checked,setChecked]=useState(false),[localError,setLocalError]=useState(''),[reloading,setReloading]=useState(false)
 const scroll=useRef<HTMLDivElement>(null),write=useBudgetWrite(),frozen=write.busy||write.locked||reloading,dismissBlocked=write.busy||(write.locked&&!write.conflict),plan=currentBudget.approved
 const allowed=current?(action==='VOID'?(current.can_void||(current.can_cancel&&current.snapshot.action==='VOID')):action==='CORRECTION'?(current.can_correct||current.can_revise):current.can_revise):currentBudget.can_add_expense
 useEffect(()=>{if(write.reauth)setChecked(false)},[write.reauth])
 useEffect(()=>{scroll.current?.scrollTo({top:0})},[preview])
 const reload=async()=>{setReloading(true);setLocalError('');try{const freshBudget=await request<BudgetResource>('/api/budgets/'+encodeURIComponent(budget.id));if(current){const fresh=await request<PaidExpenseResource>('/api/paid-expenses/'+encodeURIComponent(current.id));setCurrent(fresh)}setCurrentBudget(freshBudget);setPreview(false);setChecked(false);write.reset()}catch(error){setLocalError((error as Error).message)}finally{setReloading(false)}}
 const showPreview=()=>{setLocalError('');if(!allowed||!plan)return;if(action!=='VOID'){if(previewPaise(amount,false)===null){setLocalError('Use an already-paid amount above zero and at most ₹1,00,00,000 with at most two decimal places.');return}if(date<plan.period_start||date>plan.period_end||date>todayInSociety()){setLocalError('The paid date must be inside this period and no later than today in India.');return}}setPreview(true);setChecked(false)}
 const submit=async()=>{if(!checked||!plan||(!allowed&&!write.locked))return;const payload=action==='VOID'?{version:current?.version??0,action,reason}:{version:current?.version??0,action,budget_id:budget.id,amount,paid_date:date,payee,category,method,reference,source_note:source,reason};const result=await write.send(current?'/api/paid-expenses/'+encodeURIComponent(current.id)+'/proposals':'/api/paid-expenses',payload);if(result)onSaved(result.id)}
 const draft:PaidExpenseSnapshot=action==='VOID'&&current?.approved?{...current.approved,action:'VOID',amount_paise:0}:{version:(current?.version??0)+1,action,budget_id:budget.id,budget_version:seed?.budget_version??plan?.version??0,previous_version:current?.approved?.version??0,amount_paise:previewPaise(amount,false)??0,paid_date:date,payee,category,method,reference,source_note:source,submitted_by:'',submitted_at:0,reason}
 return <PortalDialog titleId="paid-expense-form-heading" closeLabel="Close paid expense proposal" onClose={onClose} busy={dismissBlocked} className="budget-dialog"><div className="dialog-scroll" ref={scroll}><span className="eyebrow">A RECORD OF MONEY ALREADY PAID</span><h2 id="paid-expense-form-heading">{action==='VOID'?'Correct the record. Preserve the original.':action==='CORRECTION'?'A correction with a clear trail.':preview?'The paid record, ready for review.':'Every expense has its place.'}</h2><p className="dialog-description">{plan?currentBudget.snapshot.title:'The original budget'}{plan&&<> · {displayDate(plan.period_start)} – {displayDate(plan.period_end)}</>}. {action==='PAID'?'Supply the external payment or cash-voucher evidence for a separate reviewer.':'The accepted predecessor stays effective until this linked correction is approved.'}</p>
 {!allowed&&<div className="form-error" role="status"><p>This proposal is no longer available. Your entered text is retained for review.</p></div>}
 <form onSubmit={event=>{event.preventDefault();if(preview)void submit();else showPreview()}}>
 {!preview&&action!=='VOID'&&<fieldset disabled={frozen||!allowed}><div className="budget-form-pair"><label>Already-paid amount<input aria-label="Already-paid amount" inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} required maxLength={12} placeholder="0.00"/></label><label>Paid on<input type="date" aria-label="Expense paid date" value={date} min={plan?.period_start} max={plan?([plan.period_end,todayInSociety()].sort()[0]):todayInSociety()} onChange={event=>setDate(event.target.value)} required/></label></div><label>Paid to<input aria-label="Expense payee" value={payee} onChange={event=>setPayee(event.target.value)} required minLength={2} maxLength={120} placeholder="Vendor or service provider"/></label><div className="budget-form-pair"><label>Category<input aria-label="Expense category" value={category} onChange={event=>setCategory(event.target.value)} required minLength={2} maxLength={80}/></label><label>Payment method<FilterSelect label="Expense payment method" value={method} options={Object.entries(expenseMethods).map(([value,label])=>({value,label}))} onChange={setMethod}/></label></div><label>Payment / voucher reference<input aria-label="Expense payment reference" value={reference} onChange={event=>setReference(event.target.value)} required minLength={1} maxLength={120} placeholder={method==='CASH'?'Supplied cash-voucher number':'External transaction reference'}/></label><p className="form-help">The same supplied payment or voucher belongs to one retained expense.</p><label>Supplied source note<textarea aria-label="Expense source note" value={source} onChange={event=>setSource(event.target.value)} required minLength={5} maxLength={600} rows={3}/></label></fieldset>}
 {!preview&&action==='VOID'&&current?.approved&&<PaidExpenseOriginal expense={current.approved} label="Accepted original retained"/>}
 {!preview&&<fieldset disabled={frozen||!allowed}><label>Proposal reason<textarea aria-label="Proposal reason" value={reason} onChange={event=>setReason(event.target.value)} required minLength={10} maxLength={800} rows={4}/></label></fieldset>}
 {preview&&<>{current?.approved&&<PaidExpenseOriginal expense={current.approved} label="Current accepted effect"/>}<PaidExpenseOriginal expense={draft} label={action==='VOID'?'Proposed effect after approval':'Exact proposed paid record'}/><p className="budget-proposal-reason"><span>Proposal reason</span>{reason}</p>{action==='VOID'&&<p className="form-help">This corrects the record’s effect. It records no refund or transfer.</p>}<label className="confirmation"><input type="checkbox" checked={checked} disabled={frozen} onChange={event=>setChecked(event.target.checked)}/>I reviewed this exact already-paid record, source and proposed effect.</label></>}
 {localError&&<div className="form-error" role="alert"><p>{localError}</p></div>}{reloading&&<p role="status">Opening the current record…</p>}<BudgetWriteFeedback write={write} onReload={()=>{void reload()}}/>
 <div className="form-actions"><button type="button" className="button button-quiet" disabled={preview?frozen:dismissBlocked} onClick={()=>{if(preview){setPreview(false);setChecked(false);write.reset()}else onClose()}}>{preview?'Edit proposal':'Cancel'}</button><button type="submit" className="button button-dark" disabled={write.busy||reloading||write.conflict||!allowed||(preview&&!checked)}>{write.busy?'Saving…':write.locked?'Retry this proposal':preview?'Submit for separate review':'Preview paid expense'}<Icon name="arrow"/></button></div>
 </form></div></PortalDialog>
}
