import { useState } from 'react'
import type { FormEvent } from 'react'
import { mutate, request } from '../api'
import type { MessageTarget, MessageTargetPage } from '../messages'
import { messageTargetLabel } from '../messages'
import type { PublicationPreview, StatementDetail, StatementFile } from '../statements'
import { useStatementLoad, useStatementWrite } from '../statements'
import { PortalDialog } from './PortalDialog'
import { FormSelect } from './FilterSelect'
import { FundCheck, FundUnavailable } from './FundShared'
import { FineFeedback } from './FineShared'
import { PageControls } from './Maintenance'
import { StatementPaper } from './StatementShared'
import { Icon } from './Icon'

export function StatementPublication({file,onClose,onSaved}:{file:StatementFile;onClose:()=>void;onSaved:()=>void}) {
 const [source,setSource]=useState(file),[target,setTarget]=useState<MessageTarget>({kind:'ALL',wing:'',ids:[]}),[selected,setSelected]=useState<Record<string,string>>({}),[query,setQuery]=useState(''),[page,setPage]=useState(1),[reason,setReason]=useState(''),[preview,setPreview]=useState<PublicationPreview|null>(null),[checked,setChecked]=useState(false),[previewBusy,setPreviewBusy]=useState(false),[previewError,setPreviewError]=useState('')
 const writer=useStatementWrite(),locked=writer.busy||writer.locked,disabled=locked||previewBusy
 const targets=useStatementLoad<MessageTargetPage>(['HOMES','PEOPLE'].includes(target.kind)?'/api/financial-statements/targets?'+new URLSearchParams({target:target.kind,q:query,page:String(page)}):'', ['HOMES','PEOPLE'].includes(target.kind))
 const input={file_id:source.id,file_version:source.version,target}
 const getPreview=async()=>{if(disabled)return;setPreviewBusy(true);setPreviewError('');try{const out=await mutate<PublicationPreview>('/api/financial-statements/publication-preview','POST',input);setPreview(out);setChecked(false)}catch(err){setPreviewError((err as Error).message)}finally{setPreviewBusy(false)}}
 const reload=async()=>{
  if(writer.busy||previewBusy)return;setPreviewBusy(true);setPreviewError('')
  try{const x=await request<StatementDetail>('/api/financial-statements/'+encodeURIComponent(source.id));const next=x.current?x:x.versions.find(v=>v.current&&v.state==='APPROVED');if(!next)throw new Error('The current approved original is unavailable.');setSource(next);writer.reset();setPreview(null);setChecked(false)}catch(err){setPreviewError((err as Error).message)}finally{setPreviewBusy(false)}
 }
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!preview){await getPreview();return}if(!checked||writer.conflict)return;const out=await writer.send('/api/financial-statements/publications',{...input,preview_hash:preview.preview_hash,reason});if(out)onSaved()}
 return <PortalDialog titleId="statement-publication-title" closeLabel="Close publication proposal" onClose={onClose} busy={disabled} className="fine-dialog statement-dialog"><div className="dialog-scroll statement-publication"><span className="eyebrow">AN INTENTIONAL INVITATION TO READ</span><h2 id="statement-publication-title">Share the story.<br/><em>Choose who sees it.</em></h2><p className="form-help">A separate eligible reviewer approves this exact original and audience before portal access begins.</p><form className="portal-form statement-form" onSubmit={event=>{void submit(event)}}>
  <StatementPaper file={preview?.file??source}/>
  {preview?<><section className="statement-audience-preview" aria-label="Proposed statement audience"><span className="eyebrow">THE CHOSEN AUDIENCE</span><h3>{messageTargetLabel(preview.target)}</h3><strong>{preview.target_people} {preview.target_people===1?'current person':'current people'}</strong>{Object.keys(selected).length>0&&<ul>{Object.values(selected).map(label=><li key={label}>{label}</li>)}</ul>}<p>Current relationships determine access. A changed audience before approval needs a new proposal.</p></section><p className="preserve-lines form-help">Proposal reason: {reason}</p><FundCheck checked={checked} onChange={setChecked} disabled={disabled}>I checked this exact original and audience. This proposes portal publication; sending a message follows its own permission and approval process.</FundCheck></>:<fieldset className="records-fieldset" disabled={disabled}>
   <div className="statement-field-grid"><label>Statement audience<FormSelect label="Statement audience" value={target.kind} options={[{value:'ALL',label:'All current people'},{value:'OWNERS',label:'Owners'},{value:'TENANTS',label:'Tenants'},{value:'WING',label:'One wing'},{value:'HOMES',label:'Selected homes'},{value:'PEOPLE',label:'Selected people'}]} onChange={kind=>{setTarget({kind,wing:kind==='WING'?'A':'',ids:[]});setSelected({});setQuery('');setPage(1);setPreviewError('')}}/></label>{target.kind==='WING'&&<label>Statement wing<FormSelect label="Statement wing" value={target.wing} options={['A','B','C'].map(value=>({value,label:'Wing '+value}))} onChange={wing=>setTarget({...target,wing})}/></label>}</div>
   {['HOMES','PEOPLE'].includes(target.kind)&&<section className="message-target-picker" aria-label="Choose statement audience"><h3>{target.kind==='HOMES'?'Choose the homes.':'Choose the people.'}</h3><p className="form-help">Up to 200 choices. Only current relationships can receive access.</p><label className="search-control"><Icon name="search"/><input aria-label="Search statement audience" value={query} maxLength={100} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Find a current home or person…"/></label><FundUnavailable loading={targets.loading} error={targets.error} onRetry={targets.reload}>{targets.data&&<><div className="message-target-options">{targets.data.items.map(x=><FundCheck key={x.id} checked={!!selected[x.id]} disabled={!selected[x.id]&&target.ids.length>=200} onChange={value=>{const next={...selected};if(value)next[x.id]=x.label;else delete next[x.id];setSelected(next);setTarget({...target,ids:Object.keys(next).sort()})}}>{x.label}</FundCheck>)}</div>{!targets.data.items.length&&<p className="form-help">No current choices match.</p>}{targets.data.total>12&&<PageControls label="statement audience choices" page={page} total={targets.data.total} size={12} onPage={setPage} disabled={disabled}/>}</>}</FundUnavailable><div className="message-selected-people"><span>{target.ids.length} selected</span>{Object.entries(selected).map(([id,label])=><button type="button" key={id} aria-label={'Remove '+label} onClick={()=>{const next={...selected};delete next[id];setSelected(next);setTarget({...target,ids:Object.keys(next).sort()})}}>{label}<Icon name="close"/></button>)}</div></section>}
   <label>Publication reason<textarea required minLength={5} maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label>
  </fieldset>}
  {previewError&&<div className="form-error" role="alert"><p>{previewError}</p><button type="button" className="text-link" onClick={()=>{void reload()}}>Reload current original<Icon name="refresh"/></button></div>}{previewBusy&&<p role="status">Checking this exact original and audience…</p>}<FineFeedback writer={writer} onReload={()=>{void reload()}}/>
  <div className="form-actions message-form-actions"><button type="button" className="button button-light" disabled={disabled} onClick={()=>preview?(setPreview(null),setChecked(false)):onClose()}>{preview?'Edit audience':'Cancel'}</button><button className="button button-dark" disabled={writer.busy||writer.conflict||previewBusy||(preview?!checked:(['HOMES','PEOPLE'].includes(target.kind)&&target.ids.length===0))}>{writer.busy?'Saving…':writer.locked?'Retry this proposal':preview?'Propose publication':'Preview audience'}<Icon name="arrow"/></button></div>
 </form></div></PortalDialog>
}
