import { useFragmentSync } from '../navigation'
import { useState } from 'react'
import type { User } from '../api'
import { canReadBudgets } from '../budgets'
import { Budgets } from './Budgets'
import { statementKinds, statementState, useStatementLoad } from '../statements'
import type { StatementFile, StatementPage, StatementSummary } from '../statements'
import { displayDate } from '../maintenance'
import { StatementUpload } from './StatementUpload'
import { StatementPublication } from './StatementPublication'
import { StatementDetail } from './StatementDetail'
import { FilterSelect } from './FilterSelect'
import { PageControls } from './Maintenance'
import { Icon } from './Icon'

const hashStatement=()=>new URLSearchParams(window.location.hash.split('?')[1]??'').get('statement')
function StatementArt(){return <svg className="statement-art" viewBox="0 0 250 205" fill="none" aria-hidden="true"><ellipse cx="126" cy="178" rx="107" ry="13" fill="#e2e7d7"/><rect x="83" y="27" width="111" height="145" rx="9" transform="rotate(9 83 27)" fill="#d0dac1"/><rect x="48" y="21" width="117" height="151" rx="9" transform="rotate(-7 48 21)" fill="#fffef8" stroke="#b9c6a7" strokeWidth="2"/><path d="M65 48h60M61 66h78M57 109h83M55 127h83" stroke="#c3cbb5" strokeWidth="3" strokeLinecap="round"/><path d="M56 146h25m14 0h43" stroke="#8a9d70" strokeWidth="3" strokeLinecap="round"/><circle cx="166" cy="132" r="32" fill="#edf0dd" stroke="#b6c5a2" strokeWidth="2"/><path d="m151 132 11 11 22-25" stroke="#71835a" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><path d="M188 179v-35m0 16-12-11m12 2 11-14" stroke="#7a8c61" strokeWidth="2" strokeLinecap="round"/><ellipse cx="194" cy="129" rx="11" ry="16" transform="rotate(29 194 129)" fill="#b6c59b"/></svg>}
export function Statements({user}:{user:User}) {
 const allowed=canReadBudgets(user),[panel,setPanel]=useState(()=>new URLSearchParams(window.location.hash.split('?')[1]??'').get('panel')==='budgets'?'budgets':'statements')
 useFragmentSync(()=>{const change=()=>setPanel(new URLSearchParams(window.location.hash.split('?')[1]??'').get('panel')==='budgets'?'budgets':'statements');change()},[])
 const choose=(next:string)=>{setPanel(next);window.history.replaceState(null,'',next==='budgets'?'#statements?panel=budgets':'#statements')}
 return <>{allowed&&<nav className="financial-views" aria-label="Financial views"><button type="button" aria-current={panel!=='budgets'?'page':undefined} onClick={()=>choose('statements')}>Prepared statements</button><button type="button" aria-current={panel==='budgets'?'page':undefined} onClick={()=>choose('budgets')}>Budget & expenses<Icon name="arrow"/></button></nav>}{allowed&&panel==='budgets'?<Budgets user={user}/>:<StatementRegister user={user}/>}</>
}
function StatementRegister({user}:{user:User}) {
 const [selected,setSelected]=useState<string|null>(hashStatement),[upload,setUpload]=useState<StatementFile|'new'|null>(null),[publication,setPublication]=useState<StatementFile|null>(null),[query,setQuery]=useState(''),[kind,setKind]=useState(''),[state,setState]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0)
 const load=useStatementLoad<StatementPage>('/api/financial-statements?'+new URLSearchParams({q:query,kind,state,page:String(page),refresh:String(revision)})),summary=useStatementLoad<StatementSummary>('/api/overview/statements?refresh='+revision),visible=!load.loading&&!load.error?load.data:null,counts=!summary.loading&&!summary.error?summary.data?.counts:null,staff=user.can_manage_records
 const open=(id:string)=>{setUpload(null);setPublication(null);setSelected(id);window.history.replaceState(null,'','#statements?statement='+encodeURIComponent(id))},close=()=>{setUpload(null);setPublication(null);setSelected(null);window.history.replaceState(null,'','#statements')},refresh=()=>setRevision(v=>v+1)
 useFragmentSync(()=>{const change=()=>{setSelected(hashStatement());setUpload(null);setPublication(null)};change()},[])
 const attention=staff?[['Originals checking','originals_checking','Checks before a separate review'],['For your review','pending_review','Supplied originals from another person'],['Publication reviews','publication_review','Separate audience decisions'],['Published','published','Deliberately shared originals']]:[['Available to you','published','Current permitted publications']]
 return <div className="page-enter statements-page"><section className="maintenance-hero statement-hero"><div><span className="eyebrow">THE COMMUNITY’S ACCOUNTS, CONSIDERED</span><h1>A clear record.<br/><em>A shared understanding.</em></h1><p>{staff?'Keep prepared statements, independent decisions and deliberate sharing in one thoughtful place.':'Read the originals deliberately shared with your current community audience.'}</p>{staff&&<button className="button button-dark" disabled={load.loading||!!load.error||!visible?.can_prepare} onClick={()=>setUpload('new')}>Add prepared statement<Icon name="arrow"/></button>}</div><StatementArt/></section>
 <section className={'statement-attention '+(!staff?'statement-attention-resident':'')} aria-label="Statement attention">{attention.map(([label,key,hint])=><div key={key}><span>{label}</span><strong>{counts?counts[key]??0:'—'}</strong><small>{hint}</small></div>)}</section>{summary.error&&<div className="connection-error" role="alert"><p>Statement attention counts are unavailable. The register remains usable.</p><button onClick={summary.reload}>Retry statement counts<Icon name="refresh"/></button></div>}
 <section className="statement-register"><div className="section-heading"><div><h2>{staff?'The statement register':'Shared with you'}</h2><p>{staff?'Open an original to review its context, retained versions and publication decisions.':'Your access follows the chosen audience and your current relationships.'}</p></div><span className="result-count">{visible?visible.total+' statements in this view':'Checking statements…'}</span></div><div className="statement-filters"><label className="search-control"><Icon name="search"/><input aria-label="Search statements" placeholder="Find a statement or preparer…" maxLength={100} value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><FilterSelect label="Filter statement type" value={kind} options={[{value:'',label:'All statement types'},...Object.entries(statementKinds).map(([value,label])=>({value,label}))]} onChange={value=>{setKind(value);setPage(1)}}/>{staff&&<FilterSelect label="Filter statement decision" value={state} options={[{value:'',label:'All decisions'},{value:'PENDING',label:'Awaiting internal decision'},{value:'APPROVED',label:'Approved internally'},{value:'DECLINED',label:'Declined'},{value:'WITHDRAWN',label:'Withdrawn'}]} onChange={value=>{setState(value);setPage(1)}}/>}{(query||kind||state)&&<button className="clear-button" onClick={()=>{setQuery('');setKind('');setState('');setPage(1)}}>Clear<Icon name="close"/></button>}</div>
 {load.loading?<p className="empty-state" role="status">Opening current statements…</p>:load.error?<div className="empty-state" role="alert"><h3>Statements could not be opened.</h3><p>{load.error}</p><button className="button button-dark" onClick={load.reload}>Try again<Icon name="refresh"/></button></div>:visible&&<>{visible.items.length?<div className="statement-cards">{visible.items.map(x=><button className="statement-card" key={x.id} aria-label={'Open statement '+x.title} onClick={()=>open(x.id)}><span className="statement-card-top"><span>{statementKinds[x.kind]}</span><Icon name="arrow"/></span><h3>{x.title}</h3><span className="contact-state">{statementState(x)}</span><p>{displayDate(x.period_start)} – {displayDate(x.period_end)}</p><small>Prepared by {x.prepared_by}</small><span className="statement-card-original"><Icon name="document"/>{x.filename}</span></button>)}</div>:<div className="empty-state"><Icon name="document"/><h3>{query||kind||state?'No statements match these choices.':staff?'The accounts start with an original.':'Nothing shared with this audience yet.'}</h3><p>{staff?'Add a prepared original, record its period and source, then ask a separate finance reviewer.':'An independently approved publication will appear when your current relationship belongs to its chosen audience.'}</p></div>}{visible.total>12&&<PageControls label="statements" page={page} total={visible.total} size={12} onPage={setPage}/>}</>}
 </section><p className="records-footnote"><Icon name="shield"/>Prepared outside the portal. Original files and publication decisions are preserved.</p>
 {upload&&<StatementUpload existing={upload==='new'?undefined:upload} onClose={()=>setUpload(null)} onSaved={id=>{refresh();open(id)}}/>}{publication&&<StatementPublication file={publication} onClose={()=>setPublication(null)} onSaved={()=>{refresh();setPublication(null)}}/>}{selected&&!upload&&!publication&&<StatementDetail key={selected} id={selected} onClose={close} onChanged={refresh} onUpload={setUpload} onPublish={setPublication} onOpen={open}/>}
 </div>
}
