import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import type { StatementDetail as Detail, StatementFile } from '../statements'
import { publicationStates, statementCheckErrors, statementDecisions, statementState, useStatementLoad, useStatementWrite } from '../statements'
import { messageTargetLabel } from '../messages'
import { PortalDialog } from './PortalDialog'
import { FundCheck, FundUnavailable } from './FundShared'
import { FineFeedback } from './FineShared'
import { PageControls } from './Maintenance'
import { StatementHistory, StatementPaper } from './StatementShared'
import { Icon } from './Icon'

const publicationProblems:Record<string,string>={SOURCE_CHANGED:'The current approved original changed.',AUDIENCE_CHANGED:'The current audience changed.',PROPOSER_AUTHORITY_ENDED:'The proposer’s finance appointment ended.'}
export function StatementDetail({id,onClose,onChanged,onUpload,onPublish,onOpen}:{id:string;onClose:()=>void;onChanged:()=>void;onUpload:(x:StatementFile)=>void;onPublish:(x:StatementFile)=>void;onOpen:(id:string)=>void}) {
 const [eventPage,setEventPage]=useState(1),[versionPage,setVersionPage]=useState(1),[publicationPage,setPublicationPage]=useState(1),[action,setAction]=useState(''),[publication,setPublication]=useState(''),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[success,setSuccess]=useState(''),[downloading,setDownloading]=useState(false),[downloadError,setDownloadError]=useState('')
 const load=useStatementLoad<Detail>('/api/financial-statements/'+encodeURIComponent(id)+'?'+new URLSearchParams({event_page:String(eventPage),version_page:String(versionPage),publication_page:String(publicationPage)})),x=load.data,writer=useStatementWrite(),disabled=writer.busy||writer.locked||downloading
 const pub=x?.publications.find(p=>p.id===publication),currentSignature=x?.publications.map(p=>p.id+':'+p.version+':'+p.problem).join('|')
 useEffect(()=>{setChecked(false)},[x?.version,currentSignature])
 const start=(next:string,pubID='')=>{writer.reset();setAction(next);setPublication(pubID);setReason('');setChecked(false);setSuccess('')},reload=()=>{writer.reset();setChecked(false);load.reload()}
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!x||!checked||writer.conflict||load.loading||load.error||!decisionAllowed)return;const base=publication?'/api/financial-statements/publications/'+encodeURIComponent(publication):'/api/financial-statements/'+encodeURIComponent(id);if(publication&&!pub)return;const out=await writer.send(base+'/actions',{version:pub?.version??x.version,action,reason});if(out){setAction('');setChecked(false);setSuccess(action==='PUBLISHED'?'Publication approved for its chosen current audience.':action==='REVOKED'?'Publication removed. New portal downloads are blocked; previously downloaded copies remain outside the portal.':'Decision recorded. Originals and history are retained.');load.reload();onChanged()}}
 const download=async(file:StatementFile)=>{
  if(disabled)return;setDownloading(true);setDownloadError('')
  try{const response=await fetch('/api/financial-statements/'+encodeURIComponent(file.id)+'/download',{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok){if(response.status===401)window.dispatchEvent(new Event('session-expired'));throw new Error([403,404].includes(response.status)?'Your current account cannot download this original.':'The original could not be downloaded. Try again.')};const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download=file.filename;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(err){setDownloadError((err as Error).message)}finally{setDownloading(false)}
 }
 const decisionAllowed=publication?(action==='PUBLISHED'?!!pub?.can_approve:action==='DECLINED'?!!pub?.can_decline:action==='WITHDRAWN'?!!pub?.can_withdraw:action==='REVOKED'?!!pub?.can_revoke:false):(action==='APPROVED'?!!x?.can_review&&x.validation==='AVAILABLE':action==='DECLINED'?!!x?.can_review:action==='WITHDRAWN'?!!x?.can_withdraw:action==='RETRY_VALIDATION'?!!x?.can_retry:false)
 const actionLabel=publication?({PUBLISHED:'Approve publication',DECLINED:'Decline publication',WITHDRAWN:'Withdraw publication proposal',REVOKED:'Remove this publication'} as Record<string,string>)[action]:statementDecisions[action]
 return <PortalDialog titleId="statement-detail-title" closeLabel="Close statement" onClose={onClose} busy={disabled} className="fine-dialog statement-dialog"><div className="dialog-scroll statement-detail"><span className="eyebrow">THE ACCOUNTS, KEPT TOGETHER</span><h2 id="statement-detail-title">{x?.title??'Opening this statement…'}</h2><FundUnavailable loading={load.loading} error={load.error} onRetry={load.reload}>{x&&<>
  <span className="contact-state">{statementState(x)}</span>{success&&<p className="form-success" role="status">{success}</p>}<StatementPaper file={x}/>
  <div className="statement-original-actions">{x.can_download&&<button className="button button-dark" disabled={disabled} onClick={()=>{void download(x)}}>{downloading?'Downloading…':'Download original'}<Icon name="arrow"/></button>}{x.can_upload&&<button className="button button-light" disabled={disabled} onClick={()=>onUpload(x)}>Finish original upload<Icon name="arrow"/></button>}{x.can_replace&&<button className="button button-light" disabled={disabled} onClick={()=>onUpload(x)}>Prepare replacement</button>}{x.can_publish&&<button className="button button-light" disabled={disabled} onClick={()=>onPublish(x)}>Choose publication audience<Icon name="community"/></button>}</div>{downloadError&&<p className="form-error" role="alert">{downloadError}</p>}
  {x.validation==='REJECTED'?<p className="form-error" role="alert">{statementCheckErrors[x.validation_code]??'The original was not accepted. Export a fresh plain original and submit a new version.'}</p>:x.validation==='ABANDONED'?<p className="form-help">This unused reservation expired. Earlier approved originals remain retained.</p>:x.state==='PENDING'&&x.validation!=='AVAILABLE'?<div className="document-checking" role="status"><Icon name="shield"/><p>{x.uploaded_at?'The original is saved. Checks must finish before internal approval.':'The reserved original has not finished uploading.'}</p><button className="text-link" disabled={disabled} onClick={load.reload}>Check again<Icon name="refresh"/></button></div>:x.state==='PENDING'?<p className="form-help">The original passed its checks. A different current finance reviewer must decide on this version.</p>:x.state==='APPROVED'&&!x.publication_id?<p className="form-help">Internally approved. Residents see it only after a separate publication proposal is approved.</p>:null}
  {action?<form className="portal-form statement-form statement-action-form" onSubmit={e=>{void submit(e)}}><h3>{actionLabel}</h3>{pub&&<><StatementPaper file={pub.file}/><p className="statement-decision-audience"><strong>{messageTargetLabel(pub.target)}</strong> · {pub.target_people} current people at proposal</p></>}{action==='REVOKED'&&<p className="form-help">This blocks new portal access. Copies already downloaded cannot be recalled.</p>}<fieldset className="records-fieldset" disabled={disabled}><label>Statement decision reason<textarea required minLength={5} maxLength={300} value={reason} onChange={e=>{setReason(e.target.value);setChecked(false)}}/></label><FundCheck checked={checked} onChange={setChecked}>I reviewed this exact original, the current permissions and this decision{publication?'’s chosen audience':'’s effect'}. Internal approval and publication remain separate decisions.</FundCheck></fieldset><FineFeedback writer={writer} onReload={reload}/>{!decisionAllowed&&<p className="form-help">This decision no longer applies to the current record. Your reason is retained; return to the statement to inspect its current status.</p>}<div className="form-actions message-form-actions"><button type="button" className="button button-light" disabled={disabled} onClick={()=>{setAction('');setChecked(false)}}>Back to statement</button><button className="button button-dark" disabled={writer.busy||writer.conflict||!checked||!decisionAllowed}>{writer.busy?'Saving…':writer.locked?'Retry this decision':actionLabel}<Icon name="check"/></button></div></form>:<div className="statement-review-actions">{x.can_review&&x.validation==='AVAILABLE'&&<button className="button button-dark" disabled={disabled} onClick={()=>start('APPROVED')}>Review original for approval<Icon name="check"/></button>}{x.can_review&&<button className="button button-light" disabled={disabled} onClick={()=>start('DECLINED')}>Decline this version</button>}{x.can_withdraw&&<button className="text-link" disabled={disabled} onClick={()=>start('WITHDRAWN')}>Withdraw this original</button>}{x.can_retry&&<button className="button button-light" disabled={disabled} onClick={()=>start('RETRY_VALIDATION')}>Retry unavailable checks<Icon name="refresh"/></button>}</div>}
  {x.staff&&<><section className="statement-versions" aria-label="Retained statement versions"><h3>Every original stays.</h3><ul>{x.versions.map(v=><li key={v.id}><button className="statement-version" disabled={disabled||v.id===id} onClick={()=>onOpen(v.id)}><span><strong>{v.title}</strong><small>{statementState(v)}{v.current?' · current internal version':''}{v.revision?' · Revision '+v.revision:''}</small></span><Icon name={v.id===id?'check':'arrow'}/></button></li>)}</ul>{x.version_total>20&&<PageControls label="statement versions" page={versionPage} total={x.version_total} size={20} onPage={setVersionPage} disabled={disabled}/>}</section>
  <section className="statement-publications" aria-label="Statement publication register"><h3>Publication is a choice.</h3>{!x.publications.length&&<p className="form-help">No publication proposed. Internal review alone does not share an original.</p>}{x.publications.map(p=><article key={p.id} className="statement-publication-card"><div className="statement-publication-heading"><span className="contact-state">{publicationStates[p.state]}</span><small>{messageTargetLabel(p.target)} · {p.target_people} people at proposal</small></div><h4>{p.file.title}</h4><p>{p.file.filename}{p.file.revision?' · Revision '+p.file.revision:''}</p>{p.problem&&<p className="form-error" role="alert">{publicationProblems[p.problem]??p.problem} Withdraw or decline this proposal and prepare a fresh one.</p>}{!action&&<div className="statement-review-actions">{p.can_approve&&<button className="button button-dark" disabled={disabled} onClick={()=>start('PUBLISHED',p.id)}>Review publication<Icon name="check"/></button>}{p.can_decline&&<button className="button button-light" disabled={disabled} onClick={()=>start('DECLINED',p.id)}>Decline publication</button>}{p.can_withdraw&&<button className="button button-light" disabled={disabled} onClick={()=>start('WITHDRAWN',p.id)}>Withdraw publication proposal</button>}{p.can_revoke&&<button className="button button-light" disabled={disabled} onClick={()=>start('REVOKED',p.id)}>Remove publication</button>}</div>}<details><summary>Original and decision history</summary><StatementPaper file={p.file}/>{p.file.validation==='AVAILABLE'&&<button className="text-link" disabled={disabled} onClick={()=>{void download(p.file)}}>Download this publication’s original<Icon name="arrow"/></button>}<StatementHistory events={p.events} publication/></details></article>)}{x.publication_total>20&&<PageControls label="statement publications" page={publicationPage} total={x.publication_total} size={20} onPage={setPublicationPage} disabled={disabled}/>}</section><StatementHistory events={x.events} total={x.event_total} page={eventPage} onPage={setEventPage} disabled={disabled}/></>}
 </>}</FundUnavailable></div></PortalDialog>
}
