import { useEffect, useState } from 'react'
import { request } from '../api'
import type { User } from '../api'
import { dateToday, displayDate } from '../maintenance'
import { careCategories, linkedCare, options, workStates } from '../upkeep'
import type { Work, WorkPage } from '../upkeep'
import { FilterSelect } from './FilterSelect'
import { Icon } from './Icon'
import { PageControls } from './Maintenance'
import { NewWork, WorkDialog } from './UpkeepWork'
import { UpkeepRegister } from './UpkeepRegister'

function CareCalendar(){return <svg className="upkeep-art" aria-hidden="true" viewBox="0 0 250 200" fill="none"><ellipse cx="135" cy="176" rx="100" ry="13" fill="#dde3d0" /><g transform="rotate(-8 107 99)"><rect x="29" y="37" width="157" height="129" rx="12" fill="#fbfaf3" stroke="#a8b699"/><path d="M29 70h157" stroke="#d3dcc5"/><path d="M64 27v23M149 27v23" stroke="#718566" strokeWidth="4" strokeLinecap="round"/>{[0,1,2].map(row=>[0,1,2,3].map(col=><rect key={row*4+col} x={49+col*33} y={85+row*23} width="17" height="12" rx="4" fill={row===1&&col===2?'#2d5843':'#dfe6d4'}/>))}</g><circle cx="196" cy="141" r="36" fill="#294c3d"/><path d="m181 140 10 11 22-25" stroke="#fcfbf2" strokeWidth="3" strokeLinecap="round"/><path d="M17 160c-7-27 2-50 22-59 9 25 2 43-12 51" fill="#a6b795"/><path d="m22 176 10-47" stroke="#789168" strokeWidth="2"/></svg>}
function WorkCard({item,operator,onOpen}:{item:Work;operator:boolean;onOpen:()=>void}){
 const open=!['DONE','CANCELLED'].includes(item.state),late=open&&item.due_date<dateToday()
 return <button className={'upkeep-card '+(late?'upkeep-late':'')} onClick={onOpen} aria-label={'Open work '+item.title}><span className="upkeep-card-top"><span className={'upkeep-state upkeep-state-'+item.state.toLowerCase()}>{workStates[item.state]}</span><Icon name="arrow"/></span><span className="upkeep-category">{careCategories[item.category]} · {item.priority==='NORMAL'?'Normal priority':item.priority==='HIGH'?'High priority':'Urgent'}</span><h3>{item.title}</h3><div className="upkeep-card-due"><small>{late?'Past due':'Due date'}</small><strong>{displayDate(item.due_date)}</strong></div><span className="upkeep-card-bottom"><span>{operator?item.assigned_name?(item.assignee_eligible?item.assigned_name:'Reassignment needed'):'Awaiting assignment':'Published for '+(item.audience==='BUILDING'?'Wing '+item.building_code:'all residents')}</span>{item.visit_date&&<span>Visit {displayDate(item.visit_date)}</span>}</span></button>
}
export function Upkeep({user}:{user:User}){
 const operator=user.can_handle_complaints
 const [tab,setTab]=useState('WORK'),[query,setQuery]=useState(''),[state,setState]=useState(''),[page,setPage]=useState(1)
 const [data,setData]=useState<WorkPage|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0)
 const [selected,setSelected]=useState(()=>linkedCare('task')),[creating,setCreating]=useState(()=>operator&&!!linkedCare('case')),[repeat,setRepeat]=useState<Work|null>(null)
 const [asset,setAsset]=useState(()=>linkedCare('asset'))
 useEffect(()=>{const update=()=>{setSelected(linkedCare('task'));setAsset(linkedCare('asset'));if(linkedCare('asset'))setTab('ASSET');if(operator&&linkedCare('case'))setCreating(true)};update();window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update)},[operator])
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');const timer=window.setTimeout(()=>request<WorkPage>('/api/upkeep?'+new URLSearchParams({q:query,state,page:String(page)}),controller.signal).then(value=>{setData(value);setLoading(false)}).catch((err:Error)=>{if(!controller.signal.aborted){setError(err.message);setLoading(false)}}),query?200:0);return()=>{controller.abort();clearTimeout(timer)}},[query,state,page,revision])
 const refresh=()=>setRevision(n=>n+1),clear=()=>{setQuery('');setState('');setPage(1)},close=()=>{setSelected('');window.history.replaceState(null,'','#upkeep')}
 const counts=!loading&&!error?data?.counts:undefined
 return <div className="page-enter upkeep-page"><section className="maintenance-hero upkeep-hero"><div><span className="eyebrow">CARE FOR THE THINGS WE SHARE</span><h1>Everyday care.<br/><em>Extraordinary peace.</em></h1><p>{operator?'The work, people and visits that keep your community running beautifully.':'A little view into the care that keeps your community running.'}</p>{operator&&<button className="button button-dark" disabled={loading||!!error||!data} onClick={()=>{setRepeat(null);setCreating(true)}}>Plan work<Icon name="plus"/></button>}</div><CareCalendar/></section>
 <div className="upkeep-metrics" aria-label="Work in view">{[['Open work','open',operator?'Current operational work':'Your published updates'],['Past due','overdue','Open work past its supplied date'],[operator?'Needs assignment':'Scheduled visits',operator?'unassigned':'upcoming_visits',operator?'Unassigned or no longer eligible':'Published visits in the next 7 days'],[operator?'For your check':'Published updates',operator?'ready_for_check':'published',operator?'Submitted by a different operator':'Intentionally shared with you']].map(([label,key,hint])=><div key={key}><span>{label}</span><strong>{counts?.[key]??'—'}</strong><small>{hint}</small></div>)}</div>
 {!operator&&<p className="upkeep-scope">Each update is a published snapshot, labelled with its date. The team shares a new update when there is more to tell you.</p>}
 {operator&&<div className="upkeep-tabs" role="tablist" aria-label="Upkeep workspaces" onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const tabs=Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('[role="tab"]'));const current=tabs.indexOf(document.activeElement as HTMLButtonElement);if(current<0)return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(current+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next]?.click();tabs[next]?.focus()}}>{[['WORK','Work calendar'],['ASSET','Assets'],['VENDOR','Vendors']].map(([value,label])=><button key={value} role="tab" aria-selected={tab===value} tabIndex={tab===value?0:-1} aria-controls="upkeep-panel" onClick={()=>setTab(value)}>{label}<Icon name={value==='WORK'?'leaf':value==='ASSET'?'homes':'community'}/></button>)}</div>}
 <div id="upkeep-panel" role={operator?'tabpanel':undefined}>{tab!=='WORK'&&operator?<UpkeepRegister key={tab} kind={tab} initialID={tab==='ASSET'?asset:''} onCloseLink={()=>{setAsset('');window.history.replaceState(null,'','#upkeep')}}/>:<section className="registry-panel"><div className="registry-toolbar"><div><h2>{operator?'The care calendar':'Around your community'}</h2><p>{operator?'From a plan to a separate completion check. Every step has a place.':'Resident updates for your current homes and wings.'}</p></div><span className="result-count" role="status">{loading?'Opening work…':error?'Connection unavailable':`${data?.total??0} work items found`}</span></div>
 <div className="filter-row upkeep-filters"><label className="search-control"><span className="sr-only">Search work</span><Icon name="search"/><input type="search" maxLength={100} placeholder="Find something that needs care…" value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}}/></label><FilterSelect label="Filter work by state" value={state} onChange={value=>{setState(value);setPage(1)}} options={[{value:'',label:'All work'},...options(workStates)]}/><button className="clear-button" disabled={!query&&!state} onClick={clear}>Clear<Icon name="close"/></button></div>
 <div aria-busy={loading}>{error?<div className="empty-state" role="alert"><h3>Work unavailable.</h3><p>{error}</p><button className="button button-dark" onClick={refresh}>Try again<Icon name="refresh"/></button></div>:loading?<div className="home-skeleton skeleton" aria-hidden="true"/>:!data?.items.length?<div className="records-empty"><span className="chapter-icon"><Icon name="leaf"/></span><h3>{query||state?'No work matches.':'Room for a little care.'}</h3><p>{query||state?'Try another title or stage.':operator?'Plan the first visit, assign the work and keep a clear history.':'Published care updates for your community will appear here.'}</p>{(query||state)&&<button className="text-link" onClick={clear}>Clear filters<Icon name="close"/></button>}</div>:<div className="upkeep-grid">{data.items.map(item=><WorkCard key={item.id} item={item} operator={operator} onOpen={()=>setSelected(item.id)}/>)}</div>}</div>
 {data&&!loading&&!error&&data.total>0&&<PageControls label="work items" page={data.page} total={data.total} size={data.page_size} onPage={setPage}/>}</section>}</div>
 <p className="records-footnote"><Icon name="leaf"/>{operator?'Work records keep the care accountable. Financial entries are reviewed separately.':'Shared with care, for your community.'}</p>
 {creating&&operator&&<NewWork initial={repeat} caseID={linkedCare('case')} onClose={()=>{setCreating(false);setRepeat(null);window.history.replaceState(null,'','#upkeep')}} onCreated={id=>{setCreating(false);setRepeat(null);setSelected(id);setTab('WORK');refresh();window.history.replaceState(null,'','#upkeep')}}/>}
 {selected&&!creating&&<WorkDialog key={selected} id={selected} user={user} onClose={close} onSaved={refresh} onRepeat={item=>{setSelected('');setRepeat(item);setCreating(true)}}/>}
 </div>
}
